### ISSUE TITLE
openssl : add Clang 5.0

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#1]
### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2m@conan/stable**
* Operating System: **Linux**
* Compiler+version: **clang-5.0**
* Docker image: **lasote/conanclang50**

### Steps to reproduce (Include if Applicable)

```
OpenSSL/1.0.2m@conan/stable: WARN: Can't find a 'OpenSSL/1.0.2m@conan/stable' package for the specified options and settings:
- Settings: arch=x86, build_type=Release, compiler=clang, compiler.version=5.0, os=Linux
- Options: 386=False, no_asm=False, no_bf=False, no_cast=False, no_des=False, no_dh=False, no_dsa=False, no_hmac=False, no_md2=False, no_md5=False, no_mdc2=False, no_rc2=False, no_rc4=False, no_rc5=False, no_rsa=False, no_sha=False, no_sse2=False, no_threads=False, no_zlib=False, shared=False, zlib:shared=False
ERROR: Missing prebuilt package for 'OpenSSL/1.0.2m@conan/stable'
Try to build it from sources with "--build OpenSSL"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

/cc @lasote @memsharded

**Comment by lasote** [comment]
Would you mind to update to 1.0.2n? I've pushed to the repository, I think in the following hours it should be updated.

**Comment by SSE4** [comment]
yes, sounds good as well

**Comment by SSE4** [comment]
switched to 1.0.2n, but it misses one more package (apple clang 7.3):
```
OpenSSL/1.0.2n@conan/stable: WARN: Can't find a 'OpenSSL/1.0.2n@conan/stable' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Release, compiler=apple-clang, compiler.version=7.3, os=Macos
- Options: 386=False, no_asm=False, no_bf=False, no_cast=False, no_des=False, no_dh=False, no_dsa=False, no_hmac=False, no_md2=False, no_md5=False, no_mdc2=False, no_rc2=False, no_rc4=False, no_rc5=False, no_rsa=False, no_sha=False, no_sse2=False, no_threads=False, no_zlib=False, shared=False, zlib:shared=False
ERROR: Missing prebuilt package for 'OpenSSL/1.0.2n@conan/stable'
Try to build it from sources with "--build OpenSSL"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```
can you add it as well?

**Comment by lasote** [comment]
Sure. Running. https://travis-ci.org/conan-community/conan-openssl

**Comment by SSE4** [comment]
still no package:
```OpenSSL/1.0.2n@conan/stable: WARN: Can't find a 'OpenSSL/1.0.2n@conan/stable' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Debug, compiler=apple-clang, compiler.version=7.3, os=Macos
- Options: 386=False, no_asm=False, no_bf=False, no_cast=False, no_des=False, no_dh=False, no_dsa=False, no_hmac=False, no_md2=False, no_md5=False, no_mdc2=False, no_rc2=False, no_rc4=False, no_rc5=False, no_rsa=False, no_sha=False, no_sse2=False, no_threads=False, no_zlib=False, shared=False, zlib:shared=False```

**Comment by lasote** [comment]
Bintray failed in that specific package... Relaunching build:
https://travis-ci.org/conan-community/conan-openssl/jobs/344207121

**Comment by SSE4** [comment]
still not found
<pre>
zlib/1.2.11@conan/stable: Package installed 0b32b1c0d6b042784a6f700c4f6ccd46b647f908
OpenSSL/1.0.2n@conan/stable: WARN: Can't find a 'OpenSSL/1.0.2n@conan/stable' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Debug, compiler=apple-clang, compiler.version=7.3, os=Macos
- Options: 386=False, no_asm=False, no_bf=False, no_cast=False, no_des=False, no_dh=False, no_dsa=False, no_hmac=False, no_md2=False, no_md5=False, no_mdc2=False, no_rc2=False, no_rc4=False, no_rc5=False, no_rsa=False, no_sha=False, no_sse2=False, no_threads=False, no_zlib=False, shared=False, zlib:shared=False
ERROR: Missing prebuilt package for 'OpenSSL/1.0.2n@conan/stable'
Try to build it from sources with "--build OpenSSL"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
Error while executing:
	 conan create . cpprestsdk/2.10.1@bincrafters/testing --profile /var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/tmpXZEedXconan_package_tools_profiles/profile 
</pre>
https://travis-ci.org/bincrafters/conan-cpprestsdk/jobs/344440197

**Comment by lasote** [comment]
So weird, could you relaunch in case it was a Bintray error? For 1.1 I'm adding to the trace of "missing package for xxx" the package id, to be able to verify if the package is really there. Now it is very difficult to know what happened.

**Comment by lasote** [comment]
Any progress? or still failing?

**Comment by SSE4** [comment]
trying again, will let you know in few hours

**Comment by SSE4** [comment]
still the same problem:
```
OpenSSL/1.0.2n@conan/stable: WARN: Can't find a 'OpenSSL/1.0.2n@conan/stable' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Debug, compiler=apple-clang, compiler.version=7.3, os=Macos
- Options: 386=False, no_asm=False, no_bf=False, no_cast=False, no_des=False, no_dh=False, no_dsa=False, no_hmac=False, no_md2=False, no_md5=False, no_mdc2=False, no_rc2=False, no_rc4=False, no_rc5=False, no_rsa=False, no_sha=False, no_sse2=False, no_threads=False, no_zlib=False, shared=False, zlib:shared=False
ERROR: Missing prebuilt package for 'OpenSSL/1.0.2n@conan/stable'
Try to build it from sources with "--build OpenSSL"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```
https://travis-ci.org/bincrafters/conan-cpprestsdk/jobs/346210393

**Comment by lasote** [comment]
Finally found the problem, I was bulding the page "1" both. sorry, it's already launched:

https://travis-ci.org/conan-community/conan-openssl/builds/346357094

**Comment by SSE4** [comment]
no works, thanks a lot
