### ISSUE TITLE
Readme template file

### ISSUE THREAD

**Issue by uilianries** [conan-community/community#101]
### Description of Problem, Request, or Question

Hi!

As an organization, it would be nice to have a default template for README file.

Bincrafters has an excellent good one: https://github.com/bincrafters/conan-templates/blob/master/README.md

I updated bzip2 to include package logo: https://github.com/conan-community/conan-bzip2/blob/release/1.0.6/README.md

/cc @danimtb @SSE4 @lasote

**Comment by Croydon** [comment]
I would rather recommend to use a generator instead of the one in our templates repository and edit it manually

https://github.com/bincrafters/conan-readme-generator

**Comment by uilianries** [comment]
Excellent idea @Croydon I almost forgot !

**Comment by danimtb** [comment]
Agree with the proposal @uilianries! I would like to keep the readme simple, something similar to https://github.com/conan-community/conan-docopt but including some section referencing the issue tracker

**Comment by SSE4** [comment]
@uilianries can we just use the same template as bincrafters repository, or do we need to create new one?

**Comment by uilianries** [comment]
I think they want to include the package options. We could use the readme generator, but you know the cost to keep updated.

**Comment by Croydon** [comment]
When I have worked the last time one the readme generator I have made it much more configurable. I believe conan-community could already use it without problems.

**Comment by uilianries** [comment]
Let's try it!

**Comment by uilianries** [comment]
Hi again! I've created this PR: https://github.com/conan-community/conan-zlib/pull/69, where I apply conan-readme-generator to format zlib README and LICENSE. If all agree with those changes, I could run a script to update all Conan community projects.

**Comment by Croydon** [comment]
Would be nice if you would write the command down somewhere, as it should be the same of all conan-community repositories.

Easy copy&paste :D

**Comment by danimtb** [comment]
yeah, in the ``conan remote add``. We can do nothing with the badges in this case

**Comment by uilianries** [comment]
okay, it makes sense for me.

**Comment by uilianries** [comment]
Hi again! 

I've created a simple project to update ALL conan-community repos:

https://github.com/uilianries/conan-community-update-readme

To avoid any mistake, I only applied over zlib project:

https://github.com/conan-community/conan-zlib/pull/72

If all you agree with those changes, I'm gonna run over ALL projects.

**Comment by jgsogo** [comment]
Hi!

I like the idea, I think it is useful (it is aligned with my [conan-community-utils efforts](https://github.com/jgsogo/conan-community-utils)). I have some comments related to the implementation but it is something we can iterate on in the future if we want to improve the script. There is only one thinhg I would consider right now: do not open the PR if the README/LICENSE files haven't been modified. Great!

**Comment by danimtb** [comment]
Agree with @jgsogo. This is something very helpful

**Comment by Croydon** [comment]
>  I think it is useful (it is aligned with my [conan-community-utils efforts](https://github.com/jgsogo/conan-community-utils)).

Seems like you kinda reinvented our Bincrafters tools 😅

**Comment by jgsogo** [comment]
Mine is just a visualizer, it renders a webpage with warnings/errors: http://jgsogo.es/conan-community-web/ (need more work, right now there should be dragons there, not bugs).

**Comment by uilianries** [comment]
@jgsogo 

> There is only one thinhg I would consider right now: do not open the PR if the README/LICENSE files haven't been modified

I didn't understand, because Github only allows to open a PR if there is some difference between two branches.

**Comment by uilianries** [comment]
BTW, I see no opposition in running that script. I want to run it, but it will open a big number of PRs.

**Comment by jgsogo** [comment]
The `testing` branch could have changes that aren't in the `stable|release` one. Looking at the code it looks to me that it was creating the commit in the testing branch, pushing it and then creating a PR from the testing one to the release one. This way we would avoid some false-positive PR.

**Comment by uilianries** [comment]
Oh I see, do mean outdated commit in testing branch :thinking: 

So I could change the to use a new branch, avoiding any possible false-positive, WDYT?

**Comment by jgsogo** [comment]
Opening a new branch could be an option, but then you will have two PR: one for the `testing` branch and another one for the `stable` one. Nevertheless, there are some pros: avoid false-positives, and having a PR targeting just the README/LICENSE changes (again I'm thinking about a testing branch where you are working in a feature and you already have commits in it).

**Comment by uilianries** [comment]
that's true, another options is pushing directly to stable and testing branch, no PR for this case. Since all commits have `[skip ci]`, there is no problem related to possible new package upload.

**Comment by uilianries** [comment]
Done! The command has been executed.

The log is [here](https://gist.github.com/uilianries/df61ef0af41a7db43277eaa7492dd7b2)

I'll take some time to review if some false-positive is included.

**Comment by uilianries** [comment]
Hi!

It's done, ALL Conan Community repositories are up to date.

I checked each PR before to merge, no false-positives were merged.
