### ISSUE TITLE
[Boost] Linking with boost on Windows+MSVC fails due to missing bcrypt

### ISSUE THREAD

**Issue by liberforce** [conan-community/community#102]
### Description of Problem

Here's the error message:

```
      Creating library C:/Users/gitlab-runner/.conan/data/libqi/1.6.3/sbre/testing/build/182c30e315d973e092931be77dafc7128efbcad2/sdk/lib/qi.lib and object C:/Users/gitlab-runner/.conan/data/libqi/1.6.3/sbre/testing/build/182c30e315d973e092931be77dafc7128efbcad2/sdk/lib/qi.exp
     7>os.obj : error LNK2019: unresolved external symbol BCryptCloseAlgorithmProvider referenced in function "void __cdecl `struct boost::uuids::uuid __cdecl qi::os::detail::uuidGenerator(void)'::`2'::`dynamic atexit destructor for 'g''(void)" (??__Fg@?1??uuidGenerator@detail@os@qi@@YA?AUuuid@uuids@boost@@XZ@YAXXZ) [C:\Users\gitlab-runner\.conan\data\libqi\1.6.3\sbre\testing\build\182c30e315d973e092931be77dafc7128efbcad2\qi.vcxproj]
     7>os.obj : error LNK2019: unresolved external symbol BCryptGenRandom referenced in function "struct boost::uuids::uuid __cdecl qi::os::detail::uuidGenerator(void)" (?uuidGenerator@detail@os@qi@@YA?AUuuid@uuids@boost@@XZ) [C:\Users\gitlab-runner\.conan\data\libqi\1.6.3\sbre\testing\build\182c30e315d973e092931be77dafc7128efbcad2\qi.vcxproj]
     7>os.obj : error LNK2019: unresolved external symbol BCryptOpenAlgorithmProvider referenced in function "struct boost::uuids::uuid __cdecl qi::os::detail::uuidGenerator(void)" (?uuidGenerator@detail@os@qi@@YA?AUuuid@uuids@boost@@XZ) [C:\Users\gitlab-runner\.conan\data\libqi\1.6.3\sbre\testing\build\182c30e315d973e092931be77dafc7128efbcad2\qi.vcxproj]
     7>C:\Users\gitlab-runner\.conan\data\libqi\1.6.3\sbre\testing\build\182c30e315d973e092931be77dafc7128efbcad2\sdk\bin\qi.dll : fatal error LNK1120: 3 unresolved externals [C:\Users\gitlab-runner\.conan\data\libqi\1.6.3\sbre\testing\build\182c30e315d973e092931be77dafc7128efbcad2\qi.vcxproj]
     7>Done Building Project "C:\Users\gitlab-runner\.conan\data\libqi\1.6.3\sbre\testing\build\182c30e315d973e092931be77dafc7128efbcad2\qi.vcxproj" (default targets) -- FAILED.
     3>Done Building Project "C:\Users\gitlab-runner\.conan\data\libqi\1.6.3\sbre\testing\build\182c30e315d973e092931be77dafc7128efbcad2\tests\qi\check_machineid.vcxproj" (default targets) -- FAILED.
     1>Done Building Project "C:\Users\gitlab-runner\.conan\data\libqi\1.6.3\sbre\testing\build\182c30e315d973e092931be77dafc7128efbcad2\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.
```

Full logs at:
https://gitlab.com/sbarthelemy/conan-public-recipes/-/jobs/119854642

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.68.0**
* Operating System: **Windows 2016 Server**
* Compiler+version: **MSVC 2017**

### Steps to reproduce (Include if Applicable)

What is strange is that the recipe seem to have had a fix for this:
https://github.com/conan-community/conan-boost/commit/d6a0358719cd92c9e18f7602c158205e88e20b25

However, the commit message and the link there are pretty much useless as the issues have been migrated to this repository, so I have no way to know the exact bug this was trying to fix.

However, by replacing that line in the patch with the following, it successfuly links:
```
self.cpp_info.defines.append("BOOST_UUID_FORCE_AUTO_LINK")
```

**Comment by liberforce** [comment]
Sorry about that. Unfortunately I didn't have enough background on this because the issues have been moved around across repositories, and so git blame didn't get me anything useful on why that was being done that way, and that was breaking on my side.

This is good to know, though. Do you have an idea about how this would need to be fixed?

**Comment by nickhutchinsonfiligree** [comment]
From your build log, bcrypt wasn't appearing on your link line. Unsure if that's because you were using an older package that didn't have the `self.cpp_info.libs.append("bcrypt")` addition, or if this link dependency wasn't being consumed properly.

If you want to enable the auto link behaviour -- where including a header can inject link dependencies -- that's what the magic_autolink option is for, no?

**Comment by nickhutchinson** [comment]
From your build log, bcrypt wasn't appearing on your link line. Unsure if that's because you were using an older package that didn't have the `self.cpp_info.libs.append("bcrypt")` addition, or if this link dependency wasn't being consumed properly.

If you want to enable the auto link behaviour -- where including a header can inject link dependencies -- that's what the magic_autolink option is for, no?

**Comment by liberforce** [comment]
Right. @SSE4, could you please revert [this commit](https://github.com/conan-community/conan-boost/pull/166/commits/d410f7a5be1845df93fa2eae6be45db79e3242a7)? The problem was on my side. Sorry for the inconvience.

**Comment by SSE4** [comment]
@liberforce  okay, will do, thanks for the update
