### ISSUE TITLE
[OpenSSL] Publish 1.0.2q/1.1.0j/1.1.1a

### ISSUE THREAD

**Issue by Croydon** [conan-community/community#107]

**Comment by SSE4** [comment]
@Croydon new branches are available:
https://github.com/conan-community/conan-openssl/tree/release/1.0.2q
https://github.com/conan-community/conan-openssl/tree/release/1.1.0j
https://github.com/conan-community/conan-openssl/tree/release/1.1.1a

**Comment by Croydon** [comment]
Thanks!
