### ISSUE TITLE
[OpenSSL] mingw64 cannot find make

### ISSUE THREAD

**Issue by Linux13524** [conan-community/community#108]
### Description of Problem
When building OpenSSL on Windows with mingw64 I get an error that make is not found.
Changing the line `self.run_in_src("make depend")` to `self.run_in_src("make depend", win_bash=win_bash)` fixes this error. Is there a reason not running make in the bash?

### Package Details
* Package Name/Version: **OpenSSL/1.1.0g**
* Operating System: **Windows**
* Compiler+version: **gcc version 8.2.0 (Rev3, Built by MSYS2 project)**
* Make-version: **GNU Make 4.2.1Built for  x86_64-pc-msys**

**Comment by SSE4** [comment]
I believe, it has to use `CONAN_MAKE_PROGRAM` in general, and windows bash, I'll make required changes and let you know

**Comment by SSE4** [comment]
@Linux13524 I've applied required changes to the `release/1.1.0g` branch, could you please give an another try?

**Comment by Linux13524** [comment]
`make` is found now, but there seems to be a problem with the `mingw32-make` used, resulting in an error:
```
```
The recommendation I found online was to use the `make` from msys2 instead, but when I uninstall the mingw64 make, conan uses the `C:\Windows\system32\bash.exe` (the WSL one I guess) instead of msys2.
This all looks a bit strange in my eyes, so for now I simlpy use `mingw_installer` and `msys2_installer` for OpenSSL built. But maybe you can tell me whats going on here...

**Comment by SSE4** [comment]
@Linux13524 to be more explicit, you may set the following into your profile:
`CONAN_MAKE_PROGRAM`
`CONAN_BASH_PATH`
this ensures that right executables are in use

**Comment by Linux13524** [comment]
@SSE4 Setting `CONAN_MAKE_PROGRAM` and `CONAN_BASH_PATH` in my profile works!
Thanks a lot for your help!
