### ISSUE TITLE
[OpenBLAS] Use make install rather than copying files manually straight from source

### ISSUE THREAD

**Issue by keef-cognitiv** [conan-community/community#110]
See this issue

https://github.com/xianyi/OpenBLAS/issues/500

The conan package has this issue as well because it recreates what old CMake files used to do. Since the build uses the make file, it'd probably be best to use a PREFIX and make install the result into the package directory rather than manually copying headers (incorrectly)

**Comment by SSE4** [comment]
@keef-cognitiv necessary changes were merged, please give an another try and lemme know

**Comment by SSE4** [comment]
I am closing this one for now, as required changes were merged
