### ISSUE TITLE
[openssl] 1.1.1a does not build for Android

### ISSUE THREAD

**Issue by wshallum-kmk** [conan-community/community#113]
### Description of Problem, Request, or Question

OpenSSL 1.1.1a does not build for Android. Some changes need to be made to the `conanfile.py`.

### Package Details (Include if Applicable)
* Package Name/Version: OpenSSL/1.1.1a
* Operating System: Android armeabi-v7a (cross compile from Linux)
* Compiler+version: NDK r18b, Clang 7

### Steps to reproduce (Include if Applicable)

Profile used is standalone toolchain based on NDK r18b and API 21, special tweaks were included for building OpenSSL (remove `target_host` prefix and set `ANDROID_NDK`).

```
standalone_toolchain=/home/user/Android/toolchain-arm-21
target_host=arm-linux-androideabi
cc_compiler=clang
cxx_compiler=clang++

[settings]
compiler=clang
compiler.version=7.0
compiler.libcxx=libc++
os=Android
os.api_level=21
arch=armv7
build_type=Release

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/sysroot
PATH=[$standalone_toolchain/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
LD=$target_host-ld
STRIP=$target_host-strip
CFLAGS= -fPIE -fPIC -I$standalone_toolchain/include/c++/4.9.x
CXXFLAGS= -fPIE -fPIC -I$standalone_toolchain/include/c++/4.9.x
LDFLAGS= -pie
# used by OpenSSL build env
OpenSSL:ANDROID_NDK=$standalone_toolchain
# OpenSSL 1.1.1 build config for Android adds $CROSS_COMPILE ($target_host) as a prefix to these vars
# so remove them or they would be double prefixed.
OpenSSL:AR=ar
OpenSSL:AS=as
OpenSSL:RANLIB=ranlib
OpenSSL:CC=$cc_compiler
OpenSSL:CXX=$cxx_compiler
OpenSSL:LD=ld
OpenSSL:STRIP=strip
```

There are two things that need to be fixed: 

The `android-armeabi` passed to `./Configure` should now be `android-arm`. `android-armeabi` is a "backwards compatible" target according to OpenSSL: https://github.com/openssl/openssl/blob/OpenSSL_1_1_1-stable/Configurations/15-android.conf#L240

Actually passing `android-armeabi` would lead to the Configure failing to find the host triplet - which is always used as a prefix when using the standalone toolchain, making it search for `-$CC` (note leading `-`).

After using `android-arm`, there is no mention of `$(CROSS_SYSROOT)` in the Makefile, thus the call to `replace_in_file` fails. This probably needs to be removed or set to non strict.

**Comment by SSE4** [comment]
@wshallum-kmk I've applied required changes, please give an another try

**Comment by wshallum-kmk** [comment]
@SSE4 this now builds fine for ARM. Thanks!

**Comment by SSE4** [comment]
confirmed as fixed, closing

**Comment by BillHoo** [comment]
@wshallum-kmk could you please help me with #147 ? Thanks in advance.
