### ISSUE TITLE
[opencv] build picks up system openexr

### ISSUE THREAD

**Issue by acmeijer** [conan-community/community#114]
### Description of Problem, Request, or Question

When building OpenCV the build picks up the system version of OpenEXR instead of the conan supplied version.

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/2.4.13.5@conan/stable**
* Operating System: **Linux**
* Compiler+version: **gcc-6**

### Steps to reproduce (Include if Applicable)
I am trying to use opencv/2.4.13.5@conan/stable from conan-center. Conan informs me that no binaries are available for my system (debian x86_64), and I specify that I would like to build it from source.
During the OpenCV build, it picks up dependencies to use, as can be seen here:

```
-- Media I/O: 
-- JPEG 2000: /home/op/.conan/data/jasper/2.0.14/conan/stable/package/90449607c6010415129679c4c5c43e47d3b891b7/lib/libjasper.a (ver 2.0.14) 
-- OpenEXR: /usr/lib/x86_64-linux-gnu/libImath.so /home/op/.conan/data/openexr/2.3.0/conan/stable/package/20b1686920b6d03a71cf38ef3345805f4aa7c61f/lib/libIlmImf-2_3_s.a /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver Unknown) 
```

As you can see, for OpenEXR, it is linking against a system-installed version. It happens that the build fails due to this (I am not sure exactly why but I guess some kind of version incompatibility).
My question is why does conan use the system version, when openexr itself is available in conan and AFAICT the opencv recipe looks for it. In fact if I remove the system installed version (libilmbase-dev), and try the build again, then it correctly finds the conan version:

```
-- Media I/O:
-- JPEG 2000: /home/op/.conan/data/jasper/2.0.14/conan/stable/package/90449607c6010415129679c4c5c43e47d3b891b7/lib/libjasper.a (ver 2.0.14) 
-- OpenEXR: /home/op/.conan/data/openexr/2.3.0/conan/stable/package/20b1686920b6d03a71cf38ef3345805f4aa7c61f/lib/libImath-2_3_s.a /home/op/.conan/data/openexr/2.3.0/conan/stable/package/20b1686920b6d03a71cf38ef3345805f4aa7c61f/lib/libIlmImf-2_3_s.a /home/op/.conan/data/openexr/2.3.0/conan/stable/package/20b1686920b6d03a71cf38ef3345805f4aa7c61f/lib/libIex-2_3_s.a /home/op/.conan/data/openexr/2.3.0/conan/stable/package/20b1686920b6d03a71cf38ef3345805f4aa7c61f/lib/libHalf-2_3_s.a /home/op/.conan/data/openexr/2.3.0/conan/stable/package/20b1686920b6d03a71cf38ef3345805f4aa7c61f/lib/libIlmThread-2_3_s.a (ver Unknown) 
```

**Comment by SSE4** [comment]
@acmeijer it would be helpful if you could specify which linux distribution and version are you using

**Comment by acmeijer** [comment]
Hi,

Thanks for replying - this was happening in a docker container running Debian stretch. Can get you some more data tomorrow if needed, just let me know.

**Comment by acmeijer** [comment]
I noticed you already use the conan recipe to do a find/replace in the OpenCV cmake source:

        # allow to find conan-supplied OpenEXR
        if self.options.openexr:
            find_openexr = os.path.join(self._source_subfolder, 'cmake', 'OpenCVFindOpenEXR.cmake')
            tools.replace_in_file(find_openexr,
                                  r'SET(OPENEXR_ROOT "C:/Deploy" CACHE STRING "Path to the OpenEXR \"Deploy\" folder")',
                                  '')
            tools.replace_in_file(find_openexr, r'set(OPENEXR_ROOT "")', '')
            tools.replace_in_file(find_openexr, 'SET(OPENEXR_LIBSEARCH_SUFFIXES x64/Release x64 x64/Debug)', '')
            tools.replace_in_file(find_openexr, 'SET(OPENEXR_LIBSEARCH_SUFFIXES Win32/Release Win32 Win32/Debug)',
'')

Would you recommend a similar approach here? Alternatively I am happy to open an issue on OpenCV directly and try to get it patched there.

**Comment by SSE4** [comment]
@acmeijer  yes, opening an issue would be great. until it's fixed, we will use similar workaround.

**Comment by SSE4** [comment]
@acmeijer seems like it stuck with OpenCV issue. should we just apply patch in the recipe then? could you create such pull request?

**Comment by acmeijer** [comment]
@SSE4: If you read the issue you can see that the solution is not so straightforward. I have not had any more time to dig into it yet, and I do not urgently require a solution so I've pushed this down my priority list quite a bit.

**Comment by SSE4** [comment]
I have applied a local fix for now, as it was blocking for cross-compiling: https://github.com/conan-community/conan-opencv/commit/c4764acf130ab916bfb7f02a526611333ccc5a93

**Comment by acmeijer** [comment]
Yes I think it looks fine as a local fix for use with conan. It is important to keep in mind for future versions that there is now a link between the version of OpenEXR in the conanfile and the version that is searched for in the patch.

Are you planning on applying this fix in the branches targeting other OpenCV releases as well?

**Comment by SSE4** [comment]
I can backport, if required, on request.
I am planning to submit PR to the OpenCV itself to avoid this workaround in conan.

**Comment by acmeijer** [comment]
Yes that would be best although I am not sure how you avoid hard-coding the OpenEXR version in the file which does not seem like a great solution

**Comment by SSE4** [comment]
two thing I can try:
1. find OpenEXR header first, and try to parse version from the header file (e.g. by regex)
2. have a list of supported versions and foreach

**Comment by acmeijer** [comment]
Sounds good. Also could look at creating a symlink to the static libs in OpenEXR without the version suffix, similar to what you often get for .so files. 

Will close this issue.
