### ISSUE TITLE
[TBB] Feature request: implement workarounds of known TBB issues

### ISSUE THREAD

**Issue by dzolee** [conan-community/community#115]
Hello there,

I cannot directly use your nice TBB package, because of the following known TBB issues:
1. the proxy dll can cause crashes in Qt apps -> simply don't deploy the proxy dll (.so, .dylib ..)
https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/549929

Note: the ticket above is quite old, and is about Macos, but we observed it under Linux and Win too.

2. Linux linker error if you don't specify "-L lib folder name"
https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/280689

https://stackoverflow.com/questions/5586396/getting-thread-building-blocks-intel-tbb-running-on-linux-with-gcc

Note to 2: some workarounds suggest using "-Ltbb" **and** "-L folder name" but it can break the Debug build. In my experience, "-L folder name" is enough.

### Package Details (Include if Applicable)
* Package Name/Version: TBB 2018_U6
* Operating System: **all**
* Compiler+version: **independent**

### Steps to reproduce (Include if Applicable)
For the link issue: perform a clean build, without any TBB libraries lurking around in PATH, or somewhere else. Preferably in a clean freshly setup VM if you can.

For the app crash: you just have to believe me, you can optionally omit the proxy dll.

Thanks in advance

**Comment by uilianries** [comment]
Hi @dzolee !

We updated TBB few days ago and now is available for download.

Could you please update and try again?

`conan install -r conan-community TBB/2018_U6@conan/stable -u`

**Comment by SSE4** [comment]
@dzolee we have implemented required fixes. if you still experience some problems with TBB package, please open new issue.
