### ISSUE TITLE
[boost] Build break with recent commit to conanfile.py in release/1.68.0

### ISSUE THREAD

**Issue by cstratopoulos** [conan-community/community#119]
### Description of Problem, Request, or Question
A recent commit to the conanfile.py of `conan-community/conan-boost` appears to be responsible for an ARM cross compile build break.

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.68.0**
* Operating System: **Linux**
* Compiler+version: **gcc-8**

### Steps to reproduce (Include if Applicable)
(See below)

Please note the following commit diff:
https://github.com/conan-community/conan-boost/commit/4b81ff1e7c687a1e9843a130f2ec0d0d0d01335e#diff-2b1d42f71f22b7ea0412d7602dec166fL116

Previously, address model was deduced from the `arch` setting by 
- setting `arch` to arm if, in particular, `arch.startswith("arm")`; then
- searching for `arch` in the table `{"x86_64": "64", "armv8": "64"}`, defaulting to 32 bits if not found.

In the newly added code, in the method `_b2_address_model` looks up the address model from a hardcoded dict, with no fallback value:
https://github.com/conan-community/conan-boost/commit/4b81ff1e7c687a1e9843a130f2ec0d0d0d01335e#diff-2b1d42f71f22b7ea0412d7602dec166fR123

I suspect this could be fixed with a similar conditional equality/`startswith` check as before: there could be a single `armv7` entry in the lookup table and we check if `self.settings.arch.startswith("armv7")` or something like that.

The following conan profile used to build no problem:
```
target_host=arm-linux-gnueabihf
cc_compiler=gcc
cxx_compiler=g++

[settings]
os=Linux
arch=armv7hf
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
[options]
[build_requires]
[env]
```

note that `arch=armv7hf` so `arch.startswith("arm")` is true. But in the new implementation there is no hardcoded entry for `armv7hf`, and our builds fail with

> error: "None" is not a known value of feature <address-model>
> error: legal values: "16" "32" "64" "32_64"

**Comment by SSE4** [comment]
@cstratopoulos thanks for the reporting! I am applying fixes now, will take some time for CI to run, I'll let you know once it's done.

**Comment by SSE4** [comment]
@cstratopoulos applied fix to the 1.68.0 branch (https://github.com/conan-community/conan-boost/commit/bdeaafb5e46c5fb5fd4a102fbe90d6cc3c33d52c), building on CI
if you could try locally, would be nice

**Comment by cstratopoulos** [comment]
@SSE4 yup it's all good now!

**Comment by SSE4** [comment]
@cstratopoulos thanks for the confirmation, I'll merge to 1.69.0 and others then

**Comment by SSE4** [comment]
CI is done, closing
