### ISSUE TITLE
OpenEXR installs a broken find package

### ISSUE THREAD

**Issue by barcharcraz** [conan-community/community#120]
### Description of Problem, Request, or Question
The conan openexr/2.3.0@conan/stable installs it's own find module, this overrides find modules in downstream packages causing them to fail (because the variable names are different), additionally this find module does not work for the conan package, at least on windows
### Package Details (Include if Applicable)
* Package Name/Version: **openexr/2.3.0**
* Operating System: **Windows**
* Compiler+version: **Visual Studio+15**
* Docker image: **lasote/conangcc72**

**Comment by SSE4** [comment]
applied fix (https://github.com/conan-community/conan-openexr/commit/8cdc5d2211b75ed9162871d58538d4a6681646ec), waiting for CI

**Comment by SSE4** [comment]
@barcharcraz build is completed, could you possibly give an another try?

**Comment by barcharcraz** [comment]
that did seem to fix the issue, thank you

**Comment by SSE4** [comment]
confirmed as fixed, closing
