### ISSUE TITLE
[boost] building boost with python builds boost_numpy

### ISSUE THREAD

**Issue by barcharcraz** [conan-community/community#123]
### Description of Problem, Request, or Question
building boost with python builds boost_numpy depending on if numpy happens to be installed on the building machine.

boost/1.69.0@conan/stable

**Comment by barcharcraz** [comment]
yeah so the biggest issue is that there's no way to write a conan file that says "I need boost numpy" you have to instruct users to install numpy, then use conan install . --build boost_python.

**Comment by SSE4** [comment]
@graphikrobot I can't find how to enable/disable build of boost-numpy in b2, passing `--without-numpy` results in `error: wrong library name 'numpy' in the --with-<library> option.`. could you help me to understand how to enable/disable numpy? should I add something to the user-config.jam?

**Comment by barcharcraz** [comment]
I think https://github.com/boostorg/python/blob/b644946368311160471f84d05b550342d1769431/build/Jamfile#L108 is the relevant code in the b2 files, but I don't know b2.

**Comment by shukob** [comment]
I also need this.
--with-python will also build numpy.

**Comment by SSE4** [comment]
moved to https://github.com/conan-io/conan-center-index/issues/104
