### ISSUE TITLE
conan-zlib doesn't respect os.version on Macos

### ISSUE THREAD

**Issue by malwoden** [conan-community/community#125]
### Description of Problem, Request, or Question

conan-zlib doesn't respect the os.version flag being the minimum target SDK on mac.
For cmake based builds this will set CMAKE_OSX_DEPLOYMENT_TARGET, however this doesn't appear to be set for zlib (Automake based).

This could be done by setting `-mmacosx-version-min=10.10` on the CFLAGS, CXXFLAGS and LDFLAGS. 

### Package Details (Include if Applicable)
* Package Name/Version: **zlib/1.2.11@conan/stable**
* Operating System: **Macos**
* Operation System Version: **10.13**
* Compiler+version: **apple-clang: Apple LLVM version 10.0.0**
* Conan version: **conan 1.10.2**
* Python version: **python 3.7**

### Steps to reproduce (Include if Applicable)

Build the package
`conan create . user/channel -s os.version=10.10  -s arch_build=x86_64 -s arch_target=x86_64`

In the output for the test package build, you will see the following:

`ld: warning: object file (/Users/neil/.conan/data/zlib/1.2.11/user/channel/package/e1680809ab987509837ab71936d44fbb5d69d33b/lib/libz.a(deflate.o)) was built for newer OSX version (10.13) than being linked (10.10)
ld: warning: object file (/Users/neil/.conan/data/zlib/1.2.11/user/channel/package/e1680809ab987509837ab71936d44fbb5d69d33b/lib/libz.a(zutil.o)) was built for newer OSX version (10.13) than being linked (10.10)
ld: warning: object file (/Users/neil/.conan/data/zlib/1.2.11/user/channel/package/e1680809ab987509837ab71936d44fbb5d69d33b/lib/libz.a(trees.o)) was built for newer OSX version (10.13) than being linked (10.10)
ld: warning: object file (/Users/neil/.conan/data/zlib/1.2.11/user/channel/package/e1680809ab987509837ab71936d44fbb5d69d33b/lib/libz.a(adler32.o)) was built for newer OSX version (10.13) than being linked (10.10)
ld: warning: object file (/Users/neil/.conan/data/zlib/1.2.11/user/channel/package/e1680809ab987509837ab71936d44fbb5d69d33b/lib/libz.a(crc32.o)) was built for newer OSX version (10.13) than being linked (10.10)
`

This is because the test package is respecting the os.version setting, but the zlib build itself isn't. 

### Build logs (Include if Available)
[build_log.txt](https://github.com/conan-community/community/files/2699312/build_log.txt)

**Comment by SSE4** [comment]
@malwoden I've applied required changes, please give an another try

**Comment by malwoden** [comment]
@SSE4 
Checked release/1.2.11 at ba9875b. Warnings are now gone from the build, flags are now being passed correct.

Thanks for this fix too!

**Comment by SSE4** [comment]
confirmed as fixed, closing
