### ISSUE TITLE
[boost] asmflags cannot be customized

### ISSUE THREAD

**Issue by theodelrieu** [conan-community/community#127]
### Description of Problem, Request, or Question

Cross-building Boost.Context causes some issues, since neither `cxxflags` nor `cflags` are forwarded to the assembler compiler. Instead there is a Boost.Build property called `asmflags` that could be used for this purpose.

I propose that the Boost recipe reads `ASFLAGS` to populate `asmflags` accordingly (just like it reads from `CFLAGS` and `CXXFLAGS`).

### Steps to reproduce (Include if Applicable)

* Try to build Boost.Context with `darwin-toolchain/1.0.3@theodelrieu/stable` as a build requirement

**Comment by SSE4** [comment]
@theodelrieu I've applied required changes (https://github.com/conan-community/conan-boost/commit/125b9b632e09fb4bd4b44a83a42a4bf1b4c7d92c), please give an another try

**Comment by theodelrieu** [comment]
Building Boost.Context for `macOS` shows no special flags in the command line, here is the generated `user-config.jam`:

```
using zlib : 1.2.11 : <include>/Users/theo/.conan/data/zlib/1.2.11/conan/stable/package/2f3cd49effb2f61268bd4a3678314b8052f5816e/include <search>/Users/theo/.conan/data/zlib/1.2.11/conan/stable/package/2f3cd49effb2f61268bd4a3678314b8052f5816e/lib <name>z ;
using bzip2 : 1.0.6 : <include>/Users/theo/.conan/data/bzip2/1.0.6/conan/stable/package/2f3cd49effb2f61268bd4a3678314b8052f5816e/include <search>/Users/theo/.conan/data/bzip2/1.0.6/conan/stable/package/2f3cd49effb2f61268bd4a3678314b8052f5816e/lib <name>bz2 ;
using python : 3.6 : "/usr/local/bin/python3" ;
using "clang" : "10.0" :  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" : 
<archiver>"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar" <ranlib>"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib" <cxxflags>"-isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -arch x86_64" <cflags>"-isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -arch x86_64" <linkflags>"-isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -arch x86_64" <asmflags>"-isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -arch x86_64"  ;
```

It seems the flags are still not propagated.

**Comment by SSE4** [comment]
@theodelrieu at least `<asmflags>` are in `user-config.jam`, but why doesn't b2 pick up them? I'll take my time to debug and simplify iOS/macOS code.

**Comment by theodelrieu** [comment]
Tried again today, and flags were correctly passed. I'm closing this issue :)
