### ISSUE TITLE
[ncurses] Package not available

### ISSUE THREAD

**Issue by MathPlayer** [conan-community/community#128]
### Description of Problem, Request, or Question
The ncurses package based on the recipe available at https://github.com/conan-community/conan-ncurses is not available. I can't seem to find any of the builds on bintray, conan cannot find any package matching the `ncurses/*` pattern.

### Package Details (Include if Applicable)
* Package Name/Version: **ncurses/\***
* Operating System: **macOS**
* Operation System Version: **10.14.2**
* Conan version: **1.11.1**
* Python version: **3.7.2**

### Steps to reproduce (Include if Applicable)
```
$ conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
conan-community: https://api.bintray.com/conan/conan-community/conan [Verify SSL: True]

$ conan search 'ncurses/*' -r=all
There are no packages matching the 'ncurses/*' pattern
```

**Comment by danimtb** [comment]
Hi @MathPlayer and thanks a lot for the report,

`ncurses` recipe is still in development and the CI is still not creating packages. Conan-community is an incubator repository from Conan maintainers & community leaders so packages will be promoted to conan-center as soon as they are ready.

**Comment by uilianries** [comment]
Hi @MathPlayer !

ncurses is available for download:

https://bintray.com/conan-community/conan/ncurses%3Aconan

It's not official on Conan Center yet, but you could take a try.

**Comment by MathPlayer** [comment]
Nice 😄 I tried it now and it seems to work for my own app. From my point of view this can be closed or maybe you prefer to keep it around until this arrives in Conan Center.

**Comment by uilianries** [comment]
Let's wait for Conan center inclusion :wink:

**Comment by SSE4** [comment]
I am closing this one as ncurses are in conan-center already
