### ISSUE TITLE
WiringPi package may have wrong license specified

### ISSUE THREAD

**Issue by spiderkeys** [conan-community/community#129]
### Description of Problem, Request, or Question
The conan-wiringpi repo's conanfile.py lists the license for wiringpi as GPLv3, but the license file in the official wiringpi repo shows LGPLv3:

https://git.drogon.net/?p=wiringPi;a=blob;f=COPYING.LESSER;h=65c5ca88a67c30becee01c5a8816d964b03862f9;hb=HEAD

**Comment by danimtb** [comment]
Hi @spiderkeys, thanks a lot for the advise.

We will take a look ASAP 😄
