### ISSUE TITLE
OpenSSL has some missing windows libraries it doesn't pull into libs

### ISSUE THREAD

**Issue by vadixidav** [conan-community/community#13]
### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2l**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 2015**

I got this error while building QT with the package:

```
   Creating library ..\..\lib\Qt5Network.lib and object ..\..\lib\Qt5Network.exp
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp__GetProcessWindowStation@0 referenced in function _OPENSSL_isservice
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp__GetUserObjectInformationW@20 referenced in function _OPENSSL_isservice
libeay32.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp__MessageBoxA@16 referenced in function _OPENSSL_showfatal
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp__CreateCompatibleBitmap@12 referenced in function _readscreen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp__DeleteObject@4 referenced in function _readscreen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp__GetDeviceCaps@8 referenced in function _readscreen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp__GetDIBits@28 referenced in function _readscreen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp__GetObjectA@12 referenced in function _readscreen
libeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp__GetDC@4 referenced in function _readscreenlibeay32.lib(rand_win.obj) : error LNK2019: unresolved external symbol __imp__ReleaseDC@8 referenced in function _readscreen
..\..\lib\Qt5Network.dll : fatal error LNK1120: 10 unresolved externals
```

Based on what I see [here](https://stackoverflow.com/a/23375219) it should probably also link to those windows libraries.

**Comment by vadixidav** [comment]
I am confirming if adding those libraries to the `cpp_info.libs` fixes the issue. I will report back with the result.

**Comment by vadixidav** [comment]
Did not work, still got those errors. I am going to keep investigating why this is happening.

**Comment by vadixidav** [comment]
I figured out this happened due to QT not allowing statically linking to openssl. I don't know why I got the above errors, but the problem is solved now.

**Comment by patilakash** [comment]
> I figured out this happened due to QT not allowing statically linking to openssl. I don't know why I got the above errors, but the problem is solved now.

How did you solve this issue?..

**Comment by dunno7** [comment]
I've sent some hours to find out how to solve this problem. So I post here for the new comer.
Add these lines to solve the problem
`
#pragma comment(lib, "User32.lib")
#pragma comment(lib, "GDI32.lib")
#pragma comment(lib, "Advapi32.lib")
`
