### ISSUE TITLE
[cereal] missing cereal-config.cmake in package files

### ISSUE THREAD

**Issue by crmoore** [conan-community/community#130]
### Description of Problem, Request, or Question

The conan package should include the file generated by cereal's cmake build: [packageroot]/share/cmake/cereal/cereal-config.cmake

### Package Details (Include if Applicable)
* Package Name/Version: **cereal/1.2.2**
* Operating System: **Mac OS X**
* Operation System Version: **10.14**
* Compiler+version: **apple-clang**
* Conan version: **conan 1.11.1**
* Python version: **python 3.7.0**

### Steps to reproduce (Include if Applicable)

```
# conanfile.txt
[requires]
cereal/1.2.2@conan/stable

[generators]
cmake_paths
```

```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.10.0)
project(conan-test)

find_package(cereal REQUIRED)

add_executable( conan-test main.cpp )
target_link_libraries( conan-test cereal )
target_compile_features(conan-test PRIVATE cxx_std_11)
```

main.cpp is the example from https://github.com/USCiLab/cereal, but it doesn't get far enough to need it.

```
mkdir build;
cd build
conan install ../conanfile.txt
cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake
```
cmake fails to find cereal

**Comment by SSE4** [comment]
@uilianries are you familiar with cereal? could you take a look?

**Comment by danimtb** [comment]
Hi @crmoore!

Have you tried the `cmake_find_package` generator? https://docs.conan.io/en/latest/integrations/cmake/cmake_find_package_generator.html

I think it could come handy in this case

**Comment by uilianries** [comment]
Hi @crmoore!

As Dani said, the best option for your case is `conan_find_package`. The `conan_paths` only adds the package path to your cmake_module_path, but it doesn't provide any module to be loaded.

Also, there is an excellent blog post explaining about CMake Transparent Integration: https://blog.conan.io/2018/06/11/Transparent-CMake-Integration.html

**Comment by crmoore** [comment]
I have a strong preference to not require conan to build my software.  I want my cmakelists to work the same when dependencies are managed by conan, manually or something else.  

Upstream cereal provides the correct cereal-config.camke (not a FindCereal.cmake), the conan package just needs to package it.

**Comment by crmoore** [comment]
That "transparent cmake integration" link says otherwise, in the section titled "Wait… Is this really transparent?".  

When trying it with cereal, it requires to change "target_link_libraries(conan-test cereal)" to "target_link_libraries(conan-test cereal::cereal)", which is incompatible with building without conan. The upstream config doesn't provide a 'cereal::cereal' target.

I understand that conan will never be able to provide config for arbitrary build tools in this manner.  I only expect the conan package to contain the contents an upstream's "make install" or equivalent.

**Comment by uilianries** [comment]
we could install the original cmake from Cereal, but if Cereal distributes config-version.cmake file it will be a problem, because that file is not dynamic and we can't create a new package by config.

**Comment by uilianries** [comment]
Okay, I've updated Cereal package, please barbarians, review when possible. Also, Cereal only distribute the config.cmake, so there is no problem related to config-version.cmake

**Comment by uilianries** [comment]
Hi @crmoore!

Could you please update your recipe and try it again?

    conan install -r conan-center cereal/1.2.2@conan/stable --update

CMake config file should be available now. Regards!

**Comment by crmoore** [comment]
@uilianries  Thanks for the update.  It's working as expected.

Can you expand on the config-version issue?  I know it's not relevant here, but it might help my understanding of other packages.
