### ISSUE TITLE
[openssl] Please make the name lower case with the 3.0.0 release

### ISSUE THREAD

**Issue by Croydon** [conan-community/community#132]
It got a good convention to make package names lowercase and some recipes who are older than this convention got renamed already.

I would suggest to rename `OpenSSL` to `openssl` with the 3.0.0 release, which will be the next big release.

Also heads up: It will switch to the Apache License 2.0

https://www.openssl.org/blog/blog/2018/11/28/version/

**Comment by SSE4** [comment]
their versioning scheme is completely crazy...

**Comment by SSE4** [comment]
@lasote @danimtb how should we deal with this once 3.x comes up?

**Comment by danimtb** [comment]
I would like to have it lower-case for all recipes but I think changing the case in 3.x will probably mess up in Windows with the old casing so I am not sure if this would be a problem solver or one additional problem with the casing

**Comment by Croydon** [comment]
When in doubt I like to have a strict forward-thinking approach. So yes, for Windows it might be pain in the transfer phase, but eventually, all consumers should use openssl 3.0+ anyway. So I rather would have temporary pain instead of an inconsistency forever 😄

**Comment by Croydon** [comment]
To make the transition easier I would suggest to also re-release the last patch version from each version branch again under the lower case name + we could write some update script to mass update the reference in all bincrafters + conan-community recipes. This would also be a perfect time to make sure that the latest patch versions are used in the recipes

Boost and Qt started as uppercase names as well, but we got them (and may more) renamed, so I don't see why we could not handle the rename with OpenSSL as well 😄

**Comment by Croydon** [comment]
Effectively done with https://github.com/conan-io/conan-center-index/pull/7
