### ISSUE TITLE
[zlib] Cross-building from macOS to Android fails to build

### ISSUE THREAD

**Issue by theodelrieu** [conan-community/community#137]
### Description of Problem, Request, or Question

When building on a `macOS`, `zlib`'s `configure` script forces `AR` to be Apple's `libtool`.

When building for Android with this [build requirement](https://github.com/theodelrieu/conan-android-ndk), the defined `AR` environment variable gets overwritten, and thus fails to link.

I hacked the recipe to only keep the `cmake` build helper, and everything worked fine.

There are two solutions I see:

1. Add yet another `tools.replace_in_file` to workaround the problem
1. Remove the AutoTools cruft and keep CMake

I've talked with @SSE4 who told me that @lasote was against the latter. I understand that this would require a lot of work to replicate every AutoTools behavior.

However, I think it is worth investigating time in it, the recipe is very messy and looks hard to maintain...
Not to mention it sets some flags that would be better set in a build requirement package (e.g. `RANLIB`, setting macOS minimum deployment target, etc...).

/cc @promgamer who IIRC had the same issue.

### Package Details (Include if Applicable)
* Package Name/Version: **zlib/1.2.11**
* Operating System: **macOS**
* Operation System Version: **Mojave 10.14**
* Conan version: **conan 1.8.4**
* Python version: **python 3.6.0**

### Steps to reproduce (Include if Applicable)

With the following `android` profile:

```ini
[settings]
os=Android
os.api_level=21
arch=armv8
os_build=Macos
arch_build=x86_64
compiler=clang
compiler.version=7.0
compiler.libcxx=None
build_type=Release

[build_requires]
android-ndk/r18@theodelrieu/testing
```

```shell
$ conan remote add theodelrieu https://api.bintray.com/conan/theodelrieu/conan-repo
$ conan install zlib/1.2.11@conan/stable -pr android --build missing
```

**Comment by promgamer** [comment]
I do confirm that I had the same problem and unfortunately never solved it.

**Comment by SSE4** [comment]
we're planning to discuss on how to proceed with zlib recipe. I'll keep you updated.

**Comment by SSE4** [comment]
@theodelrieu I think we may limit AutoTools-usage to Linux-only, WDYT? it seems to be the least evil

**Comment by theodelrieu** [comment]
Seems like a good compromise I'd say!

**Comment by SSE4** [comment]
okay, feel free to submit PR, or I may submit it in few days otherwise

**Comment by SSE4** [comment]
@theodelrieu changes were merged, can we close this one now?

**Comment by theodelrieu** [comment]
Yep!
