### ISSUE TITLE
[Boost] Cannot bootstrap when cross-building on Windows

### ISSUE THREAD

**Issue by theodelrieu** [conan-community/community#138]
### Description of Problem, Request, or Question

Cross-building from a Windows machine to Android fails when bootstrapping.

```
Bootstrapping the build engine

Failed to bootstrap the build engine
Please consult bootstrap.log for furter diagnostics.

boost/1.68.0@conan/stable: WARN: Error 1 while executing bootstrap.bat clang
boost/1.68.0@conan/stable: WARN: ###
### "Unknown toolset: clang"
###
### You can specify the toolset as the argument, i.e.:
###     .\build.bat msvc
###
### Toolsets supported by this script are: borland, como, gcc,
###     gcc-nocygwin, intel-win32, metrowerks, mingw, msvc, vc7, vc8,
###     vc9, vc10, vc11, vc12, vc14, vc141
###
### If you have Visual Studio 2017 installed you will need either update
### the Visual Studio 2017 installer or run from VS 2017 Command Prompt
### as we where unable to detect your toolset installation.
###
```

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.68.0@conan/stable**
* Operating System: **Windows**
* Operation System Version: **10**
* Compiler+version: **clang 7.0 (Android NDK)**
* Docker image: **conanio/gcc7**
* Conan version: **conan 1.2.0**
* Python version: **python 3.7.0**

### Steps to reproduce (Include if Applicable)

Using the following profile **android**:

```ini
[settings]
os=Android
os.api_level=21
arch=armv8
os_build=Windows
arch_build=x86_64
compiler=clang
compiler.version=7.0
compiler.libcxx=None
cppstd=14
build_type=Release

[build_requires]
android-ndk/r18@theodelrieu/testing
```

1. conan remote add theodelrieu https://api.bintray.com/conan/theodelrieu/conan-repo
1. conan install boost/1.68.0@conan/stable -pr android --build missing -o boost:without_iostreams=True

### Build logs (Include if Available)
[first_fail.log](https://github.com/conan-community/community/files/2778779/first_fail.log)

**Comment by theodelrieu** [comment]
iostreams cannot be built since they rely on #zlibandr, and this issue makes it impossible to build at the moment

**Comment by theodelrieu** [comment]
Missclicked, did not mean to close

**Comment by SSE4** [comment]
@theodelrieu I've applied a fix : https://github.com/conan-community/conan-boost/commit/305b48d022ec136664a581cd4e1f3085db58e08a
could you possible give an another try?

**Comment by theodelrieu** [comment]
It works! (I first tried on 1.68.0 which does not have the fix btw).

**Comment by SSE4** [comment]
confirmed as fixed, closing
