### ISSUE TITLE
[Boost] asmflags are not propagated when cross-building to Android

### ISSUE THREAD

**Issue by theodelrieu** [conan-community/community#139]
### Description of Problem, Request, or Question

This is related to #127.

Boost.Context cannot be built for Android.

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.68.0**
* Operating System: **Windows**
* Operation System Version: **10**
* Compiler+version: **clang 7.0 (Android NDK)**

### Steps to reproduce (Include if Applicable)

1. Workaround issue #138 (remove `self._get_bootstrap_toolset()` in https://github.com/conan-community/conan-boost/blob/release/1.68.0/conanfile.py#L386)
1. Perform the steps mentioned in #138

### Build logs (Include if Available)
[output.log](https://github.com/conan-community/community/files/2778826/output.log)

**Comment by SSE4** [comment]
weird, I see `<asmflags>` are in `user-config.jam`, but they aren't applied.
@grafikrobot any ideas?

**Comment by theodelrieu** [comment]
Any news on this issue?

**Comment by SSE4** [comment]
nope, need @grafikrobot inside here, as it's something closely related to b2/bjam

**Comment by SSE4** [comment]
@theodelrieu I am closing this one, as it was fixed by https://github.com/conan-community/conan-boost/commit/be2f56a9df6f61df0ae188ee7d26876e993a5545
