### ISSUE TITLE
[OpenSSL] OpenSSL Please package engine DLL files

### ISSUE THREAD

**Issue by LighthouseJ** [conan-community/community#14]
### Description of Problem, Request, or Question

Please package openssl 'engine' library files.
They are found in build\hash\binaries\lib\engines\\\*.dll on Windows or build/hash/openssl-version/engines/*.so on Linux

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2l@conan/stable**
* Operating System: **Windows and Linux**
* Compiler+version: **MSVC 2015(14.0)**
* Docker image: **None**

### Steps to reproduce (Include if Applicable)

(Linux) conan install OpenSSL/1.0.2l@conan/stable --build=OpenSSL -o shared=True
(Windows) conan install OpenSSL/1.0.2l@leidos/testing --build=OpenSSL -o shared=True

I believe this also occurs with 1.0.2o and similar versions.

Here are proposed changes to accommodate for engine library files, and fix copying libssl.so and libcrypto.so as symlinks.
https://gist.github.com/LighthouseJ/6efbad61534de29f29ebf16d2164928c

**Comment by lasote** [comment]
Could you shed some light on what are these engine libraries?

**Comment by LighthouseJ** [comment]
Sure thing, I'd be happy to.
In short, OpenSSL added a function to dynamically load additional libraries (like capi.dll or cswift.dll) which perform special functions not in the main libraries, like reading a certificate from a hardware device or specific protected operating systems.

See: https://github.com/openssl/openssl/blob/master/README.ENGINE

**Comment by SSE4** [comment]
@LighthouseJ I've applied required changes to the `release/1.0.2p` branch, could you please give an another try?

**Comment by SSE4** [comment]
@LighthouseJ I am closing this one for now, as required changes were applied. please open new issue, if you still have a problem.
