### ISSUE TITLE
[boost] compression library (i.e. bzip2) dependencies

### ISSUE THREAD

**Issue by firewave** [conan-community/community#146]
The boost recipe has hard-coded dependencies to zlib and bzip2. The first one makes obviously sense, but I wonder why the latter one is there. Boost supports a whole array of compression libraries and bzip2 seems like the most outdated one (and is no longer maintained as well) so it seems like this dependency is a legacy thing. Or is there some feature in Boost which becomes unavailable without it?

On a side note it would probably make sense to have these compressions configurable to leverage the more modern methods (although I am not sure where/how Boost uses them).

**Comment by SSE4** [comment]
@firewave  boost::iostreams may use bzip2, zlib and lzma, optionally. 
is it okay if I add options for them?

**Comment by SSE4** [comment]
@firewave I've pushed changes to new branch, feel free to review and test: https://github.com/conan-community/conan-boost/commit/a5a65025e5b1cf35a57a1315da829e2f2d4f385f

**Comment by firewave** [comment]
That was fast - was just supposed to be a question :) Will take me a few days to try.

There's other compression libraries as well like `zstd` - if these are added they should be complete IMO.

I also would prefer ´lzma` to be disabled by default as it would suddenly add a dependency that was hasn't been there before. Maybe even deprecate ´bzip2` being enabled as default (as it is no longer maintained).

**Comment by SSE4** [comment]
@firewave yes, it didn't support `zstd` previously, I'll add this one as well. I think `zstd` and `lzma` will be `False` by default, not sure about `bzip2`, as it used to be enabled by default.

**Comment by uilianries** [comment]
@firewave The package it's available for Linux and Windows:

https://travis-ci.org/conan-community/conan-boost/builds/494847456

Please, try it or wait for CI jobs and give us a feedback please!
