### ISSUE TITLE
[OpenSSL] problem with cross-compiling macOS to Android (wrong PATH)

### ISSUE THREAD

**Issue by tanshihaj** [conan-community/community#149]
### Description of Problem, Request, or Question
I've found out strange behaviour of `conanfile.py` when tried to compile Android version of package under macOS host. I'm talking about these lines:
https://github.com/conan-community/conan-openssl/blob/bb5d9e4177ae55cd3ee452d168e6e74be545edf4/conanfile.py#L92-L95

Long story short wrapping `Configure` call with `bash ... ""` leads to some changes with `PATH` environment variable. More specifically if I set `PATH` from `conanfile.py` as **`/path/to/android/ndk/bin`**`:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` inside `Configure` I will get `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:`**`/path/to/android/ndk/bin`**. That is `/path/to/android/ndk/bin` was moved to the end of list.

It is an issue because now `Configure` catches `clang` from system path and complains that `clang` is not from Android NDK.

Since I'm not good with bash-voodoo, I can't understand what lines above do and I don't now how can I fix it. Does anybody have an idea how to force `bash` leave `PATH` unchanged?

### Package Details
* Package Name/Version: **OpenSSL/1.1.1a**, however all other version affected too I think
* Operating System: **macOS**

### Steps to reproduce
create following `android` profile under macOS:
```
include(default)

[settings]
os=Android
os.api_level=21
compiler=clang
compiler.version=7.0
arch=armv7

[env]
OpenSSL:ANDROID_NDK=/path/to/android/ndk/
OpenSSL:PATH=[/path/to/android/ndk/clang/toolchan/bin]
OpenSSL:AR=ar
OpenSSL:AS=as
OpenSSL:RANLIB=ranlib
OpenSSL:CC=clang
OpenSSL:CXX=clang++
OpenSSL:LD=ld
OpenSSL:STRIP=strip
```

run `conan install OpenSSL/1.1.1a@conan/stable --profile android --build OpenSSL --build zlib`

**Comment by SSE4** [comment]
not sure aboud bash voodoo that OpenSSL does, but it's recommended to specify not just `clang` but something like `armv7a-linux-android21-clang` as `CC` (and `CXX). using these wrappers ensures that `--target` and `--sysroot` compiler flags are set accordingly to your settings. see more information on NDK documention: https://developer.android.com/ndk/guides/other_build_systems.

**Comment by SSE4** [comment]
okay, closing this out for now due to the inactivity, please re-open, if needed
