### ISSUE TITLE
[OpenSSL] OpenSSL needs to provide FindOpenSSL

### ISSUE THREAD

**Issue by uilianries** [conan-community/community#15]
### Description of Problem, Request, or Question

Projects that use `find_package(OpenSSL)` and solve by Conan, the default FindOpenSSL.cmake does not solve **dl** for Linux. In other words, It's not possible to use find_package(OpenSSL) + Conan. 

IMO Conan OpenSSL must provide FindOpenSSL.cmake, including `ssl crypto dl`

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2o**
* Operating System: **Linux**
* Compiler+version: **Any**
* Docker image: **Any**

### Steps to reproduce (Include if Applicable)
```
git clone https://github.com/bincrafters/conan-libzip
cd conan-libzip
git checkout 957c5ecbd94b6475edd95abd544632076bb412a5
conan create . bincrafters/testing
```

Log on Travis CI: https://travis-ci.org/bincrafters/conan-libzip/jobs/374051230#L1410

**Comment by uilianries** [comment]
Good question. :thought_balloon:

I believe it's because the platform provides shared library.
The error only occurs when try link to static library.

I'll investigate what happens when try to build boost and opencv using static library.

**Comment by SSE4** [comment]
I am running into another issue which will require custom FindOpenSSL, see https://github.com/bincrafters/community/issues/319
in short, standard CMake-provided FindOpenSSL finds system-wide OpenSSL on appveyor (which is installed to something like **C:\OpenSSL-Win64**), as result corrupted packages are produced.

**Comment by uilianries** [comment]
I think `cmake_find_package` generator is enough now.

**Comment by SSE4** [comment]
closing as obsolete

**Comment by uilianries** [comment]
thanks!
