### ISSUE TITLE
[OpenSSL] Android: "Unsupported options: no-canonical-prefixes"

### ISSUE THREAD

**Issue by Linux13524** [conan-community/community#151]
### Description of Problem, Request, or Question

Trying to configure OpenSSL with the `-no-canonical-prefixes` flag throws an error:

```
Failure!  build file wasn't produced.
Please read INSTALL and associated NOTES files.  You may also have to look over
your available compiler tool chain or change your configuration.

***** Unsupported options: no-canonical-prefixes
```

`Configure` removes the first hyphen and then compains about not knowing the option.

I already reported an issue here: theodelrieu/conan-android-ndk#7
But since it needs changes in the OpenSSL recipe I opened this issue here to discuss what changes need to be done.

/cc @theodelrieu @maikelvdh

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.1.1a**
* Operating System: **Linux**
* Operation System Version: **Fedora 29**
* Compiler+version: **clang 7 ([android-ndk](https://github.com/theodelrieu/conan-android-ndk))**
* Conan version: **conan 1.11.2**
* Python version: **python 3.7.2**

### Steps to reproduce (Include if Applicable)

see theodelrieu/conan-android-ndk#7

**Comment by SSE4** [comment]
@Linux13524 as I understand, you need to pass options using the following way (as documented):
https://wiki.openssl.org/index.php/Compilation_and_Installation#Configure_Options
https://github.com/openssl/openssl/blob/master/Configure#L75
`# -<xxx> +<xxx> compiler options are passed through`
so it removes leading dash or plus character. using for instance `+-no-canonical-prefixes` should help.
the question I have as how do you pass additional compiler options? for instance:
- via `CFLAGS=<options>`
- via `CC=gcc <options>`
- as extra configure arguments, like `./Confgure <options>`
- something else

**Comment by Linux13524** [comment]
Changing `-no-canonical-prefixes` to `+-no-canonical-prefixes` or `--no-canonical-prefixes` results in following errors:
`clang: error: no such file or directory: '+-no-canonical-prefixes'`
`clang: error: unsupported option '--no-canonical-prefixes', did you mean '-no-canonical-prefixes'?
`

So it seems like the `+` and the `-` are not removed when `compiler options are passed through`.

I'm using @theodelrieu's [android-ndk](https://github.com/theodelrieu/conan-android-ndk) recipe, which sets the compiler options in `package_info` with: 
```
compiler_flags.extend([..., "-no-canonical-prefixes"])
...
self.cpp_info.cflags = compiler_flags
self.cpp_info.cppflags = compiler_flags
```
Then the OpenSSL recipe passes them to the `./Configure` command.

Please correct me if I got something wrong.

**Comment by SSE4** [comment]
@Linux13524  where did you apply change? in the profile? or in the recipe? can you show the diff? 
I suppose cflags should still contain `-no-canonical-prefixes`, while Configure flags should use `+-no-canonical-prefixes`

**Comment by Linux13524** [comment]
Just for testing I changed the `-no-canonical-prefixes` in the android-ndk recipe:

https://github.com/theodelrieu/conan-android-ndk/blob/709093793ab0c2bcb3a76f6510860e1c0a57592a/conanfile.py#L169

This will change cflags and Configure flags.
I will see what happens if I just change the Configure flag to `+-no-canonical-prefixes`...

**Comment by SSE4** [comment]
this appears to be more puzzled, I need to debug it

**Comment by SSE4** [comment]
@Linux13524 I've updated recipe significantly : https://github.com/conan-community/conan-openssl/commit/6f3f5b8feb8c447a4fe7a3005bdd90f2a7784786
could you possibly give a new try and lemme know if it's still an issue?

**Comment by Linux13524** [comment]
@SSE4 I gave it a quick try and it seems to work now. Thanks!
