### ISSUE TITLE
[boost] There is no package for headers only

### ISSUE THREAD

**Issue by mmatrosov** [conan-community/community#152]
### Description of Problem, Request, or Question

There is a promising option `header_only` in `boost` recipe on conan-center, but there is no package built for it:

```
>conan search -r conan-center boost/1.69.0@conan/stable -q "header_only=True"
Existing packages for recipe boost/1.69.0@conan/stable:

Existing recipe in remote 'conan-center':

There are no packages for reference 'boost/1.69.0@conan/stable' matching the query 'header_only=True'
```
It is often very convenient to get only boost headers, without any binaries, since many boost libraries are header-only. Please build and upload this package.

PS I personally think it makes more sense to create a separate header-only recipe `boost-headers`, and make `boost` recipe depend on it. That's how we did in our company, where we have all recipes hand-written. Works as a charm.

### Package Details
* Package Name/Version: **boost/1.69.0**

### Steps to reproduce

    conan search -r conan-center boost/1.69.0@conan/stable -q "header_only=True"

**Comment by SSE4** [comment]
@mmatrosov package exists, but unfortunately cannot be found by a query.
package id is `5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9`, and full search (without query) finds it:
```
    Package_ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
        Outdated from recipe: False
```
it's built and uploaded here: https://travis-ci.org/conan-community/conan-boost/jobs/499683787
problem is that header-only boost calls `self.info.header_only()`, which erases all options/settings from its package id.
@lasote @danimtb any recommendations?

**Comment by danimtb** [comment]
That's unfortunate... has this recipe has different modes, the header_only option is deleted from the package ID hash, meaning that to consume the package will be inaccessible. ``self.info.header_only()`` actually means there is only one package.


The `package_id()` should have that option then. I haven't tried but something like this should do the trick:

```
package_id():
    self.info.header_only()
    self.info.options.header_only = True
```

**Comment by SSE4** [comment]
@danimtb should I apply these changes then?

**Comment by danimtb** [comment]
Yes, I think this is the right way and the current status is broken for the header_only option, so go ahead. Thanks!

**Comment by SSE4** [comment]
@mmatrosov fixed:
```
C:\>conan search -r conan-center boost/1.69.0@conan/stable -q "header_only=True"                                                                                                                                                                                                                                                                                     1H
Existing packages for recipe boost/1.69.0@conan/stable:

Existing recipe in remote 'conan-center':

    Package_ID: 524ea35a8120baabdde02483add58d81bf541327
        [options]
            header_only: True
        Outdated from recipe: False
```

**Comment by mmatrosov** [comment]
Cool, thanks a lot!

**Comment by mmatrosov** [comment]
Hm, I have some troubles installing it, please take a look:

```
C:\Users\Mikhail>conan install -r conan-center boost/1.69.0@conan/stable -o header_only=True
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
header_only=True
[build_requires]
[env]

boost/1.69.0@conan/stable: Not found, retrieving from server 'conan-center'
boost/1.69.0@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
[==================================================] 261B/261B
Downloading conanfile.py
[==================================================] 38.0KB/38.0KB
Downloading conan_export.tgz
[==================================================] 1.7KB/1.7KB
Decompressing conan_export.tgz: 100%|██████████| 1.67k/1.67k [00:00<00:00, 81.6kB/s]
ERROR: e:\packages\boost\1.69.0\conan\stable\export\conanfile.py: Error while initializing settings. 'settings.cppstd' doesn't exist
'settings' possible configurations are ['arch', 'arch_build', 'arch_target', 'build_type', 'compiler', 'os', 'os_build', 'os_target']

C:\Users\Mikhail>conan --version
Conan version 1.12.3
```

**Comment by SSE4** [comment]
@mmatrosov I think you need to update your `settings.yml` file, by adding (at very bottom):
```
cppstd: [None, 98, gnu98, 11, gnu11, 14, gnu14, 17, gnu17, 20, gnu20]
```
(or by just renaming `settings.yml.new`)

**Comment by mmatrosov** [comment]
Shouldn't it be updated automatically? I have conan of the latest versin!

**Comment by SSE4** [comment]
@mmatrosov I wish it does, but unfortunately it doesn't update `settings.yml`, not sure why. so, please add this line manually for now.

**Comment by mmatrosov** [comment]
> I wish it does, but unfortunately it doesn't update settings.yml, not sure why

@lasote @danimtb Could you please comment on this?

> so, please add this line manually for now.

It helped to resolve the problem, thanks! I renamed `settings.yml.new`. Installed package looks good.

The only thing, I have a warning upon installation (see at the bottom):

```
C:\Users\Mikhail>conan install -r conan-center boost/1.69.0@conan/stable -o header_only=True
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
header_only=True
[build_requires]
[env]

Installing package: boost/1.69.0@conan/stable
Requirements
    boost/1.69.0@conan/stable from 'conan-center' - Cache
Packages
    boost/1.69.0@conan/stable:524ea35a8120baabdde02483add58d81bf541327 - Download

boost/1.69.0@conan/stable: Retrieving package 524ea35a8120baabdde02483add58d81bf541327 from remote 'conan-center'
Downloading conanmanifest.txt
[==================================================] 1.1MB/1.1MB
Downloading conaninfo.txt
[==================================================] 1.4KB/1.4KB
Downloading conan_package.tgz
[==================================================] 12.7MB/12.7MB
Decompressing conan_package.tgz: 100%|██████████| 12.1M/12.1M [01:04<00:00, 197kB/s]
boost/1.69.0@conan/stable: Package installed 524ea35a8120baabdde02483add58d81bf541327
boost/1.69.0@conan/stable: WARN: Lib folder doesn't exist, can't collect libraries: e:\.conan\80db47\1\lib
boost/1.69.0@conan/stable: LIBRARIES: []
boost/1.69.0@conan/stable: Package folder: e:\.conan\80db47\1
```

Can we fix this?

**Comment by SSE4** [comment]
fixed: https://github.com/conan-community/conan-boost/commit/6566f107a29cce0edc80883654bfa2b32f7ff229
the warning is harmless, it doesn't affect package at all

**Comment by danimtb** [comment]
@mmatrosov the *settings.yaml.new* is created instead of replaced if we detect at the time of upgrading Conan with a new *settings.yaml* that the one you are using has been modified. That way we avoid messing up with the user-defined settings.

It seems this is not documented so I have opened an issue in the docs repo https://github.com/conan-io/docs/issues/1104

**Comment by mmatrosov** [comment]
@danimtb ok, makes sense, thanks!

@SSE4 I can confirm the warning is fixed, thanks a lot!

> the warning is harmless, it doesn't affect package at all

Yes, I just love living in the zero-warnings paradigm :)

**Comment by suriab** [comment]
I want to build boost headers conan package with custom namespace. Can someone list the steps please.
