### ISSUE TITLE
[zlib] FindZLIB.cmake misses ZLIB_LIBRARY

### ISSUE THREAD

**Issue by theirix** [conan-community/community#153]
### Description of Problem, Request, or Question

A cmake helper [`FindZLIB.cmake`](https://github.com/conan-community/conan-zlib/blob/release/1.2.11/FindZLIB.cmake) omits the `ZLIB_LIBRARY` variable while setting only the `ZLIB_LIBRARIES` variable.

### Package Details (Include if Applicable)
* Package Name/Version: **zlib/1.2.11**
* Operating System: **Linux**
* Operation System Version: **Debian 9**
* Compiler+version: **gcc-6.3**
* Conan version: **conan 1.12.3**
* Python version: **python 3.5.3**

### Steps to reproduce (Include if Applicable)

1. Check the exported FindZLIB.cmake

### Description

Variable was missing since a recent refactoring of cmake helper in https://github.com/conan-community/conan-zlib/pull/73 removes the `ZLIB_LIBRARY` variable while setting only the `ZLIB_LIBRARIES` variable. It breaks [dependent packages](https://github.com/bincrafters/community/issues/663) that expect a `ZLIB_LIBRARY` from the [official cmake helper](https://github.com/Kitware/CMake/blob/master/Modules/FindZLIB.cmake).

It can be fixed easily -- set a `ZLIB_LIBRARY` alongside with `ZLIB_LIBRARIES`.

**Comment by SSE4** [comment]
interesting, it's not mentioned in documentation (https://cmake.org/cmake/help/v3.0/module/FindZLIB.html). also, on your link, it's not mentioned in header comment (https://github.com/Kitware/CMake/blob/master/Modules/FindZLIB.cmake#L23), but actually set below (https://github.com/Kitware/CMake/blob/master/Modules/FindZLIB.cmake#L78). I'll add it.

**Comment by SSE4** [comment]
https://github.com/conan-community/conan-zlib/commit/8a29488e2da4714de16db4a68c1ff971f7b8ac55

**Comment by theirix** [comment]
Works perfectly now, thanks!

I agree that it is an implementation detail. It is common in cmake to use FOO_LIBRARY or FOO_LIBRARIES. Probably dependent packages should not rely on undocumented variables but it's better for us to maintain backward compatibility with the standard cmake helper.
