### ISSUE TITLE
How to tell cmake to use the static libraries conan build for OpenCV?

### ISSUE THREAD

**Issue by fgr** [conan-community/community#154]
I'm trying to build an OpenCV hello world test program to try Conan with OpenCV for Linux (GCC).

When I build OpenCV (using Conan) with static linkage (default in Conan), then no symbol from OpenCV can be found by the linker. E.g., `cv::imread("test.jpg")` will result in an ld error:

> undefined reference to `cv::imread'

The `imread` symbol is however present in `libopencv_core.a`, but this static library file is not taken into account by the linker since `conan_add_target_link_libraries` uses dynamic linkage `(-L/home/user/.conan/data/opencv/... -lopencv_core -lopencv_...).`

On the other hand, my hello world OpenCV test compiles and links fine when compiling OpenCV with dynamic linkage (conan option `opencv:shared=True`). However, the program does not start because it cannot find the dynamically linked OpenCV libraries -- and I'm reluctant to add to  `LD_LIBRARY_PATH` theses libraries from the conan cache (`~/.conan/data/opencv...`).

Is there a way to tell `conan_add_target_link_libraries` (or similar) to use static linking?

### Package Details (Include if Applicable)
* Package Name/Version: `opencv/3.4.5@conan/stable` with option `opencv:shared=True`
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**
* Compiler+version: **gcc-8**
* Conan version: **conan 1.12.2**
* Python version: **python 3.7.0**

**Comment by fgr** [comment]
Found the problem (and solution): In my `CMakeLists.txt ` the call to `conan_basic_setup()` was wrong. With `conan_basic_setup(TARGETS)` (instead of `conan_basic_setup()`) static linking works fine out of the box (with `conan_add_target_link_libraries()`).

**Comment by SSE4** [comment]
calling `conan_basic_setup` twice definitely doesn't sound right. I believe `conan_basic_setup(TARGETS)` shall define both targets and CMake variables, right?

**Comment by uilianries** [comment]
@fgr Are you using `CONAN_PKG::Catch2` and `CONAN_PKG::opencv` + `conan_basic_setup(TARGETS)` ?

**Comment by fgr** [comment]
@uilianries I tried again with `conan_basic_setup(TARGETS)` plus `CONAN_PKG::opencv` and `CONAN_PKG::Catch2`. The hello world program now compiles and links fine, including statically linking opencv.

I don't know what changed since February, but everything appears to work as expected. Thanks for looking into this.

**Comment by uilianries** [comment]
Nice! Closing this issue now.
