### ISSUE TITLE
[OpenCV] Is it planned to include stereo and other components?

### ISSUE THREAD

**Issue by Jochen0x90h** [conan-community/community#159]
### Description of Problem, Request, or Question
I'd like to use stereo and ximgproc. Is it possible to include them or is there a separate package for them?

These are my includes, but stereo.hpp and ximgproc.hpp are missing

```
#include <opencv2/stereo.hpp>
#include <opencv2/ximgproc.hpp>
```

**Comment by SSE4** [comment]
@Jochen0x90h we may include these components, I need to check how to enable them with CMake options first.

**Comment by SSE4** [comment]
okay, these two modules (`stereo` and `ximgproc`) are parts of [contrib](https://github.com/opencv/opencv_contrib) modules. 
they are not built by default, due to long build times and license issues, but you may easily enable them by passing the following option: `-o opencv:contrib=True` into your command line, or your conan profile.

**Comment by Jochen0x90h** [comment]
setting contrib=True does not seem to have any effect. I do

`conan install -o opencv:contrib=True --build=missing opencv/3.4.2@bincrafters/stable`

The contrib sources are not downloaded, also the contrib option is not used in ~/.conan/data/opencv/3.4.2/bincrafters/stable/export/conanfile.py
i.e. no other code line cares about the contrib opion

**Comment by SSE4** [comment]
@Jochen0x90h could you try on 4.0.x branch?

**Comment by SSE4** [comment]
@Jochen0x90h with this command line:
```
conan install -o opencv:contrib=True --build=missing opencv/3.4.5@conan/stable
```
I get `xfeatures2d` and `stereo` components installed.
so I am closing this one. please re-open if needed.
