### ISSUE TITLE
BZip2 is not found by CMake when build Clang 5.0

### ISSUE THREAD

**Issue by uilianries** [conan-community/community#16]
### Description of Problem, Request, or Question
When I try to execute `find_package(BZip2 REQUIRED)` to build any project based on clang 5.0, my cmake aborts.

I discovered this problem during my last update on conan-libzip, the recipe is under review to be included on Conan center, but it fails when try to build using clang 5.0

I checked the docker images, but both clang 4.0 and 5.0 uses artful as base, so I believe that is not the image.

I made a little [project](https://github.com/uilianries/conan-bzip2-example) example to validate this issue. Also, the logs are [here](https://travis-ci.org/uilianries/conan-bzip2-example/builds/375738635)

### Package Details (Include if Applicable)
* Package Name/Version: **bzip2/1.0.6**
* Operating System: **Linux**
* Compiler+version: **clang-5.0**
* Docker image: **lasote/conanclang50**

### Steps to reproduce (Include if Applicable)
```
git clone https://github.com/uilianries/conan-bzip2-example
cd conan-bzip2-example
docker run --rm -ti -v ${PWD}:/home/conan/project lasote/conanclang50
sudo pip install -U conan
cd project
conan create . uilianries/testing
```

**Comment by lasote** [comment]
Looks like the package is empty, checking why:
`conan get bzip2/1.0.6@conan/stable . -r conan-center -p 83dba0d44de5df94ef51020e3074d358fcc3da47`

**Comment by lasote** [comment]
No, the package is ok. I would try to reproduce it locally.

**Comment by lasote** [comment]
Yes, I confirmed that something weird is happening in bintray with that package. Reporting to JFrog Bintray team.

**Comment by uilianries** [comment]
Thanks for investigate this problem.

I'm curious if Conan server checks the package checksum by the manifest. Maybe this problem is related to others involving corrupted file after to upload on Bintray. Or just maybe, the package is corrupted after to be stored on Bintray.

**Comment by lasote** [comment]
There is an internal bug with the indexing being investigated. Please, check again, the issues with bzip2 should be solved now.

**Comment by uilianries** [comment]
It Worked!

The follow steps are fine now:

```
git clone https://github.com/uilianries/conan-bzip2-example
cd conan-bzip2-example
docker run --rm -ti -v ${PWD}:/home/conan/project lasote/conanclang50
sudo pip install -U conan
cd project
conan create . uilianries/testing
```

**Comment by uilianries** [comment]
Thanks again!
