### ISSUE TITLE
[boost] request: link boost with given python libs for a target system

### ISSUE THREAD

**Issue by Johnnyxy** [conan-community/community#162]
hi there,
I have a problem with the boost recipe. The recipe executes python scripts to detect the current version and other stuff. But for cross-compiling I need to specify the python libs which boost should be linked with by myself. I cannot rely on any autodetection the boost recipe does.

You can test this easily by "cross-building" boost on Windows from e.g. x86_64 to x86.
```python
os_build = "Windows"
os_arch = "x86_64"
os = "Windows"
arch = "x86"
```

When I am executing a Python x86_64 (64 bit) then the boost recipe would try to link against the wrong libs which it detects in the executing Python (x86_64) path.

The same applies to the Python version. If I want to link against Python 3.6 (target machine) but running Conan (build machine) with Python 3.7. Again the boost recipe tries to link against 3.7 (detected for the build machine) not 3.6 for the target machine.

Did I overlook something or is this not possible with the current boost recipe?

Best regards

**Comment by SSE4** [comment]
@Johnnyxy I think you may specify path to the custom python interpreter via `python_executable` option. e.g. `conan install . -o boost:python_executable=C:\my_custom_32bit_python\python.exe` should work if you specify 32-bit python executable. 
but probably, if python executable cannot be executed on build machine, then it will not be possible to auto-detect these things. it means we have to add additional options to manually specify path to python headers and libraries.

**Comment by Johnnyxy** [comment]
Ok. This means there is no way with the current recipe for this. The background is that I need for a library that I build to provide wrappers / binding for serval languages. Python is one of those. Think about using Python on QNX :). Since QNX 7.0 there is a Python implementation delivered with the QNX SDP. But you cannot execute this on the build machine.

In the end I cannot use the boost recipe for that. I will see if I find time to look into the boost recipe to help. But this will not happen in the next couple of weeks I think.

**Comment by SSE4** [comment]
@Johnnyxy I think it should be relatively easy to add corresponding options to the recipe to override detection. actually, it just needs 3 options: include path, library path and python version. feel free to submit such PR, or I may implement it myself, but a bit later.

**Comment by Johnnyxy** [comment]
I was re-thinking about this.
Generally you are right. Adding 2 additonal parameters (python_include_path, python_library) would suffice.

But ... for the moment I will have to replan my toolchain.

If I want the python libs to link boost with to be automatically deduced through Conan even with additional options this will not work as I wanted it to work :). I have created a packages for serval Python version (2.7, 3.5, 3.6, ...) for the libs ```python/version@user/channel``` and runtime ```python_installer/version@user/channel```. At the moment the difference between those is that they specify different ```package_info(self)``` settings.

So I can use Conan's package system to specify the python version I need/want.

But as already asked in the conan repository isses forum this cannot work at the moment (see here https://github.com/conan-io/conan/issues/4450).

Just adding new options for paths will not be enough as those path values should depend on the location of the build_dependency ```self.build_requires("python/...@.../...")```. And there is no way of retrieving this or any informations about the python package before ```self.build_requires("boost/...@.../...")```.

**Comment by SSE4** [comment]
moved to https://github.com/conan-io/conan-center-index/issues/106
