### ISSUE TITLE
[boost] Visual Studio 64-bit build uses 32-bit address-model

### ISSUE THREAD

**Issue by firewave** [conan-community/community#164]
### Description of Problem, Request, or Question

When build on Windows with a 64-bit Visual Studio compiler it will generate working 64-bit libraries, but somehow just use a 32-bit address-model:
```
    - default address-model    : 32-bit
    - default architecture     : x86
```

Using a compiler on Linux will show:
```
        - default address-model    : 64-bit
        - default architecture     : x86
```

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.69**
* Operating System: **Windows 10**
* Operation System Version: **Version 1809 (OS Build 17763.348)**
* Compiler+version: **MSVC 19.0.24215.1**
* Conan version: **conan 1.13.0**
* Python version: **python 3.6.4**

**Comment by SSE4** [comment]
it's weird, as we explicitly pass `address-model=64`, and I see the same in build log here: https://ci.appveyor.com/project/ConanCIintegration/conan-boost/build/job/uyekmndeufjkadjt?fullLog=true

**Comment by SSE4** [comment]
@firewave does issue persist with 1.70.0 (and conan 1.16)?

**Comment by firewave** [comment]
I am not able to update to Boost 1.70 yet because of a bug in the build system. I will check if that is fixed.

**Comment by firewave** [comment]
When compiling 1.69 with 64-bit MinGW (via `build_requires` in the profile) I am seeing the following:

```
warning: No toolsets are configured.
warning: Configuring default toolset "msvc".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
Performing configuration checks

    - default address-model    : 32-bit (cached)
    - default architecture     : x86 (cached)
    - has_icu builds           : no  (cached)
```

It does compile and link successfully though.

**Comment by SSE4** [comment]
but does it produce 32-bit or 64-bit libraries in that case?

**Comment by firewave** [comment]
I think it does produce 64-bit libraries in both cases as they are not interchangeable and I was able to use the MSVC ones successfully in the past.

**Comment by SSE4** [comment]
okay, so probably there is no issue on our side, you may try to open an issue against boost build for incorrect address-model report

**Comment by firewave** [comment]
That's what I thought as well - I will look into this soon.

**Comment by firewave** [comment]
It seems like this message was from the bootstrap part of the build. I just saw in the Jam execution part that it looks like this

```
Performing configuration checks

    - default address-model    : 64-bit
    - default architecture     : x86
```

I will do another Visual Studio build in the next few days and check if it is also correct after all.

**Comment by SSE4** [comment]
@firewave do you have an update on this one?

**Comment by firewave** [comment]
I just did a Visual Studio build and it uses the 32-bit address model for the actual build.

**Comment by SSE4** [comment]
@firewave so, does it mean everything works as expected?

**Comment by firewave** [comment]
It means the issue is still the same as initially reported.

Everything else were red herrings :(

**Comment by SSE4** [comment]
moved to https://github.com/conan-io/conan-center-index/issues/107
