### ISSUE TITLE
[boost] Debug recipes on Windows do not include .pdb files

### ISSUE THREAD

**Issue by michaelmaguire** [conan-community/community#165]
### Description of Problem, Request, or Question

.pdb files do not appear in the package generated even for build_type=Debug 

Guessing: Perhaps this is because on Linux debug info is included in the library file itself?

### Package Details (Include if Applicable)
* Package Name/Version: **conan-boost/1.69.0**
* Operating System: **Windows**
* Operation System Version: **Windows 2012 R2 Standard**
* Conan version: **Conan version 1.10.1**
Architecture: | x86_64
Build Type: | Debug
Compiler: | Visual Studio
Compiler Version: | 14
Compiler Runtime: | MDd
compiler.toolset: | v140_xp

### Steps to reproduce (Include if Applicable)

Use conan recipe https://github.com/conan-community/conan-boost/blob/5a6db0dee55870a09432452cb6598bc6ce044a77/conanfile.py to build with settings:

Architecture: | x86_64
Build Type: | Debug
Compiler: | Visual Studio
Compiler Version: | 14
Compiler Runtime: | MDd
compiler.toolset: | v140_xp

**Comment by SSE4** [comment]
@michaelmaguire 
- on Linux, debug info might be included into the binary (`-g` option), or stripped out to the separated .debug file (via `objcopy`).
- on Windows, it's not different, you may use `/Zi` to generate separated `.pdb` files, or use `/Z7` to embed debug information into binary
we currently don't upload debug information for binaries, as they take significant space, and we have storage limits on bintray.

**Comment by SSE4** [comment]
we're not going to add PDB files to recipes at this point.
