### ISSUE TITLE
cannot install OpenSSL/1.0.2p@conan/stable in mingw-64

### ISSUE THREAD

**Issue by wumo** [conan-community/community#166]
### Description of Problem, Request, or Question
Cannot install OpenSSL/1.0.2p@conan/stable in mingw-64
### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2p@conan/stable**
* Operating System: **Windows**
* Operation System Version: **Windows 10**
* Compiler+version: **gcc-8.1**
* Docker image: ****
* Conan version: **conan 1.3.0**
* Python version: **python 3.7.2**

### Steps to reproduce (Include if Applicable)
`conan install OpenSSL/1.0.2p@conan/stable`
### Build logs (Include if Available)
```
OpenSSL/1.0.2p@conan/stable: WARN: Build folder is dirty, removing it: C:\Users\WuMo\.conan\data\OpenSSL\1.0.2p\conan\stable\build\e393111ba38dd85fcdf785ee91a62c480dbb33b8
OpenSSL/1.0.2p@conan/stable: Building your package in C:\Users\WuMo\.conan\data\OpenSSL\1.0.2p\conan\stable\build\e393111ba38dd85fcdf785ee91a62c480dbb33b8
OpenSSL/1.0.2p@conan/stable: Copying sources to build folder
OpenSSL/1.0.2p@conan/stable: Generator txt created conanbuildinfo.txt
OpenSSL/1.0.2p@conan/stable: Calling build()
OpenSSL/1.0.2p@conan/stable: =====> Options:  --with-zlib-include="C:\Users\WuMo\.conan\data\zlib\1.2.11\conan\stable\package\2e90c2fe2f69846019f521f2004427fb191035af\include" --with-zlib-lib="C:\Users\WuMo\.conan\data\zlib\1.2.11\conan\stable\package\2e90c2fe2f69846019f521f2004427fb191035af\lib/zlib.lib"
OpenSSL/1.0.2p@conan/stable: WARN: ./Configure mingw64 -g  --with-zlib-include="/c/users/wumo/.conan/data/zlib/1.2.11/conan/stable/package/2e90c2fe2f69846019f521f2004427fb191035af/include" --with-zlib-lib="/c/users/wumo/.conan/data/zlib/1.2.11/conan/stable/package/2e90c2fe2f69846019f521f2004427fb191035af/lib/zlib.lib"
OpenSSL/1.0.2p@conan/stable: 
OpenSSL/1.0.2p@conan/stable: ERROR: Package 'e393111ba38dd85fcdf785ee91a62c480dbb33b8' build failed
OpenSSL/1.0.2p@conan/stable: WARN: Build folder C:\Users\WuMo\.conan\data\OpenSSL\1.0.2p\conan\stable\build\e393111ba38dd85fcdf785ee91a62c480dbb33b8
ERROR: OpenSSL/1.0.2p@conan/stable: Error in build() method, line 120
	self.mingw_build(config_options_string)
while calling 'mingw_build', line 323
	tools.run_in_windows_bash(self, config_line)
	ConanException: Cannot recognize the Windows subsystem, install MSYS2/cygwin or specify a build_require to apply it.
```

**Comment by SSE4** [comment]
@wumo 
`MinGW` is compiler (GCC port to Windows), but running `configure` scripts requires other *nix tools (e.g. `sed`, `grep`, etc.) to be provided, and `bash` as well.
you may solve it in different ways:

- add `CONAN_BASH_PATH` environment variable, either in your conan profile, or define it globally, and specify location of existing `bash` installation (e.g. one from cygwin, MSYS2, Git for Windows, WSL, etc)
- add build requirements to your profile, such as `msys2_installer/latest@bincrafters/stable` or `cygwin_installer/2.9.0@bincrafters/stable`.
- just add location of existing `bash` installation to the `PATH`

whatever you prefer, it should work out of the box

**Comment by wumo** [comment]
@SSE4  It works. I removed my own installed msys2 from `PATH` and added `msys2_installer/latest@bincrafters/stable` to the profile, then It compiled successfully.
