### ISSUE TITLE
[TBB] shared option deleted on Windows

### ISSUE THREAD

**Issue by Lawrencemm** [conan-community/community#168]
Could we have the combination of `False` for "shared" option and `Windows` os setting just throw an error instead of deleting the "shared" option on Windows? 

I want to use shared on Linux and Windows in my project but right now I can't because setting the option throws an error on Windows.

TBB/2019_U3
Fedora 29/Windows 10

**Comment by uilianries** [comment]
Hi @Lawrencemm It's because there is no option on Windows. TBB is only able to be built as shared library on Windows, it's a TBB feature.

We don't distribute multiple options, when we can't change it. It's like having a button that you can push, but it only works when unpressed.

How do you do to build? Are you using Conan Package Tools? If yes, you could set shared_option_name to False:

https://github.com/conan-community/conan-tbb/blob/stable/2019_U4/build.py#L10

**Comment by Lawrencemm** [comment]
This is my package:
https://github.com/Lawrencemm/lmlib

I build and develop it on Linux and Windows.

I run Conan install to get the deps and have my IDE turn on all the necessary lightbulbs.

I believe this process should be easy and as I tried to get this package working in this way I couldn't see how I could do it without forking and making this change: 
https://github.com/Lawrencemm/conan-tbb/commit/0a30a1126169b14b7c50fc52f46bc92f827850be

Because then a simple `conan install` just works on both platforms.

Without the change I get an error on install under Windows because I set the TBB:shared option in my conanfile which just fails because you delete it.

I tried conditionally adding this option but I couldn't figure out how to do so for an option specified to one of my requirements rather than my own package's options.

I'm not sure how Conan package tools helps me in this case, as I understand it's more for packaging not development of your package, but maybe I'm wrong.

**Comment by uilianries** [comment]
> Without the change I get an error on install under Windows because I set the TBB:shared option in my conanfile which just fails because you delete it.

Forcing your dependencies option in the recipe is not a good approach. You could add a profile or even passing to Conan Package Tools when building.

If you really need to set in your recipe, I would recommend the method `config_options`, where you can check the current settings, including the OS and set the desired option.

**Comment by Lawrencemm** [comment]
> Forcing your dependencies option in the recipe is not a good approach. You could add a profile

Oh. TIL. Thanks.

**Comment by Lawrencemm** [comment]
Actually, some qualms with that;

I don't really want users of my library to have to worry about setting a TBB option in their own profiles. I want TBB to be used as a shared library by default on all platforms.

I tried to set a TBB option in config_options but as far as I can tell it's for adding/subtracting options, not setting options of your requires, I tried to access TBB options and set them in these methods but couldn't find any information on how to do so.

Having the default behaviour of this package different on Linux/Windows seems not so good, where if left untouched it's a shared library on Windows, but a static library on Linux. Seems surprising.

**Comment by uilianries** [comment]
> I don't really want users of my library to have to worry about setting a TBB option in their own profiles. I want TBB to be used as a shared library by default on all platforms.

So why not:

    default_options = {"shared": True, "*:shared": True}

> I tried to set a TBB option in config_options but as far as I can tell it's for adding/subtracting options, not setting options of your requires, I tried to access TBB options and set them in these methods but couldn't find any information on how to do so.

Indeed the only way set the default options in the recipe is by attributes.

> Having the default behaviour of this package different on Linux/Windows seems not so good, where if left untouched it's a shared library on Windows, but a static library on Linux. Seems surprising.

By default all of our libraries are configured to be built as static, but we distribute shared too. The TBB project doesn't support static library on Windows, that's why we only support as shared on Windows.

**Comment by Lawrencemm** [comment]
> By default all of our libraries are configured to be built as static, but we distribute shared too. The TBB project doesn't support static library on Windows, that's why we only support as shared on Windows.

That to me indicates it's more logical to raise an error in that case, instead of just "the option doesn't exist" you can tell the user explicitly what is happening "TBB doesn't support static linking on Windows".

> So why not:
> 
> `default_options = {"shared": True, "*:shared": True}`

I haven't seen this used before, but it would appear it's defaulting to shared = True for all of my dependencies. Would I then have to add 

`"<dep>:shared": False`

For all the deps I still want to link statically against?

**Comment by uilianries** [comment]
> I haven't seen this used before, but it would appear it's defaulting to shared = True for all of my dependencies. Would I then have to add
>
> "<dep>:shared": False
>
> For all the deps I still want to link statically against?

Yes. Explicit `name:option` will override the wildcard.

https://docs.conan.io/en/latest/reference/commands/consumer/install.html#options

**Comment by Lawrencemm** [comment]
OK, well I don't really want to change several other options so that I can work around this issue.

I agree that the idea of not giving the option on a platform that can't be built as static is more coherent conceptually, however in practice I believe it would be best for usability to go with raising the error.

I'm happy for you to close the issue now if you decide to leave it as-is, I'll just have to maintain my fork.

**Comment by danimtb** [comment]
Hi!

I think this is mostly a UX/usability problem that could be solved by changing the output message to the user.

I am not sure if this can be done, but maybe if Conan detects that the option exists but it was deleted in config_options() method, it could raise a ConanInvalidConfiguration with a generic message like "Option <option_name> not supported".

I am not sure if this is feasible but it would be something very useful. WDYT?

**Comment by danimtb** [comment]
I have been thinking about this and this is my rationale:

- The shared option exists: The library can be built in at least one OS as shared and static
- The user sees the option available to be set
- There is no incompatibility of shared with other existing options
- The option affects the package ID

Evaluating the above options I think the scenario describes an invalid configuration because shared is not supported although user could initially think it was possible.

My points for deleting an option:

- It is incompatible with any other option value.
- It does not affect the package ID in a specific scenario (shared being excluded by a header_only=True option, for example).

WDYT @uilianries ?

**Comment by uilianries** [comment]
It's a design flaw to expose something that does not represent what it should do. In this case, `option` has no value on Windows, but it could be accessed by command arguments, or even in the recipe, changing the package id.

If it does not work, do not expose. It's the same idea from fPIC. BTW This discussion is not new.

**Comment by Lawrencemm** [comment]
Ok, I've found a place to take up the issue with Conan itself, thanks for your patience.

**Comment by danimtb** [comment]
@uilianries in the case of "fPIC", I think it is ok deleteing the option in windows as such concept doesn't exist for that OS. However, "shared" is a valid concept in Windows although it is not possible in this case
