### ISSUE TITLE
Build openssl for android

### ISSUE THREAD

**Issue by deekshith-elear** [conan-community/community#169]
Hi,
I am trying to build openssl form ```https://github.com/conan-community/conan-openssl``` for android and it giving error of zlib package is not avilable.
```
Requirements
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    zlib/1.2.11@conan/stable:f4ae56f9abb3606afd5dcdd9ff14d672c83b121f - Missing

Cross-build from 'Linux:x86_64' to 'Android:armv7'
zlib/1.2.11@conan/stable: WARN: Can't find a 'zlib/1.2.11@conan/stable' package for the specified settings, options and dependencies:
- Settings: arch=armv7, build_type=Release, compiler=clang, compiler.version=8, os=Android, os.api_level=19
- Options: fPIC=True, minizip=False, shared=False
- Dependencies: 
- Package ID: f4ae56f9abb3606afd5dcdd9ff14d672c83b121f
```
The cross compilation process build requires are same as like for basic compilation or I have to add any other packages?

**Comment by SSE4** [comment]
@deekshith-elear we don't upload prebuilt Android packages yet.
so you have to invoke conan with `--build missing` in order to get `zlib` and other dependencies built locally.

**Comment by SSE4** [comment]
I think question was answered. I am closing the issue for now. please open new issue(s) if you have any further question(s).
