### ISSUE TITLE
Issue while creating package with header files 

### ISSUE THREAD

**Issue by deekshith-elear** [conan-community/community#173]
Hi,
I am creating packages using conan  after building code and creating package we use 
```
self.copy("*.h", dst="include/common", src=".")
 self.copy("*.a, dst="lib", src="lib", keep_path=False)
```
my files are in below hierarchy 
```
|- main.c
|- hello.h
|-test/
   |-test.c
   |-test.h
```
when I copy my header files into package they are copying `hello.h` , `test.h` into the package 
but how can I restrict only package with headers `hello.h` only

**Comment by uilianries** [comment]
Hi @deekshith-elear 

Use the explicit header name:

```python
self.copy("hello.h", dst="include/common", src=".")
self.copy("*.a, dst="lib", src="lib", keep_path=False)
```

**Comment by deekshith-elear** [comment]
Thank you @uilianries , But If there are `20 .h` files then also I have to mention explicit names only.

**Comment by uilianries** [comment]
I see 3 options:

1) Copy everything and remove what you need:

```python
def package(self):
	self.copy("*.h", dst="include/common", src=".")
	for file in ["foo.h", "bar.h", "qux.h"]:
		tools.remove(os.path.join(self.package_folder, "include", "common", file))
```

2) Copy only what you need:

```python
def package(self):
	for file in ["foo.h", "bar.h", "qux.h"]:
		self.copy(file, dst="include/common", src=".")
```

3) Install using [CMake install](https://cmake.org/cmake/help/v3.13/command/install.html)

```python
def package(self):
	cmake = CMake(self)
	cmake.install()
```

There is not smart way to do this, it's better to keep explicit than implicit. I prefer the option 3, since you could distribute your project without Conan.

**Comment by SSE4** [comment]
@deekshith-elear if you know that API headers are in root folder, and test headers are in `test` sub-folder, you may always use `exclude` parameter of `self.copy` method, for instance:
```
self.copy("*.h", dst="include/common", src=".", exclude="*test/*.h")
```

**Comment by SSE4** [comment]
I think questions is answered, so I am closing this issue for now
