### ISSUE TITLE
[question] hooks: Eat your own dog food

### ISSUE THREAD

**Issue by uilianries** [conan-community/community#176]
### Description of Problem, Request, or Question

Hi @conan-community/barbarians 

Since Conan offers some nice hooks, I think we could add them to our CI jobs.

Some possible hooks to be included:

- [Conan Center Reviewer](https://github.com/conan-io/hooks/blob/master/hooks/conan-center_reviewer.py)
- [Attribute Checker](https://github.com/conan-io/hooks/blob/master/hooks/attribute_checker.py)
- [Binary Linter](https://github.com/conan-io/hooks/blob/master/hooks/binary_linter.py)
- [Github Updater](https://github.com/conan-io/hooks/blob/master/hooks/github_updater.py)
- [SPDX Checker](https://github.com/conan-io/hooks/blob/master/hooks/spdx_checker.py)

Should we include those hooks?
If yes, should we consider any warning as error?

related issue: https://github.com/bincrafters/community/issues/716

Regards!

**Comment by danimtb** [comment]
I am fine with this if we avoid the connection issues. But we could give them a go in some packages just to try them. At least the conan center reviewer, attribute checker and binary linter

**Comment by uilianries** [comment]
Since it's not possible to run a hook without Conan commands, I'll need to patch Conan Package Tools to install the hooks inside to the Docker container.

**Comment by danimtb** [comment]
Don't need to do the patch. conan config install with the hooks repository and the hooks activated in the conf should be enough

**Comment by uilianries** [comment]
Yeah, DOCKER_ENTRY_SCRIPT should be enough.

**Comment by jgsogo** [comment]
Sure! Let's consume our own hooks 💯

**Comment by uilianries** [comment]
First try:

https://github.com/conan-community/conan-zlib/tree/feature/hooks
https://travis-ci.org/conan-community/conan-zlib/jobs/515918538

**Comment by SSE4** [comment]
@uilianries zlib is failing after your changes. problem is that `LIEF` doesn't have wheels for python 3.7.

**Comment by SSE4** [comment]
@uilianries seems like no longer relevant, as we're moving everything to conan-index now?

**Comment by uilianries** [comment]
@SSE4 thanks for closing this one!
