### ISSUE TITLE
OpenCV package CMake options

### ISSUE THREAD

**Issue by vadixidav** [conan-community/community#177]
[OpenCV](https://github.com/conan-community/conan-opencv) currently builds python bindings in the Conan package. The relevant CMake options are:

- BUILD_opencv_python2
- BUILD_opencv_python3

I currently get a build error on python3, but it shouldn't be necessary to build.

```
LINK : fatal error LNK1104: cannot open file 'python37_d.lib' [C:\.conan\0802ca\1\build_subfolder\source_subfolder\modules\python3\opencv_python3.vcxproj]
```

These python modules should be set to `False`.

Also, you should allow configuring the `WITH_CUDA` option.

**Comment by vadixidav** [comment]
If this hasn't been tackled already, can I submit a PR for this?

**Comment by vadixidav** [comment]
I have been trying to make the additions, but I am having trouble building on my system due to this issue: <https://stackoverflow.com/questions/54995172/issue-compiling-with-cvstd-wrapper-hpp-opencv4-0-1>. I don't entirely know how to fix it, but I am going to try building with the `/std:c++17` flag passed to the compiler.

**Comment by vadixidav** [comment]
I am just going to add my changes against the OpenCV 3 release package since I have successfully built that before. Moving to that now.

**Comment by uilianries** [comment]
Hi @vadixidav ! Feel free to open an PR :smiley:

**Comment by vadixidav** [comment]
I opened a PR here conan-community/conan-opencv#17. This doesn't solve the issue for OpenCV 4.0.1 which I cannot build on my computer. I went ahead and just backported the 4.0.1 package to 3.4.5. If you like, you can just not accept it, but the changes might be valuable to apply to 4.0.1 if it is working for you on your computer.

I will test on Debian now.

**Comment by vadixidav** [comment]
I am testing on Debian now and trying to build 4.0.1. If it works I may also try to add `text` and `tesseract` as features. Currently those are not exposed in the Conan package. I am sure there are tons of other things buried in OpenCV CMake code that I don't know about, but I am trying to do what I can.

**Comment by SSE4** [comment]
fixed in https://github.com/conan-community/conan-opencv/pull/18

**Comment by vadixidav** [comment]
Eventually someone should properly backport some of the changes to 3.4.5, but this is good for now.
