### ISSUE TITLE
Missing source for OpenSSL package 1.0.2x

### ISSUE THREAD

**Issue by mattgodbolt** [conan-community/community#178]
### Description of Problem, Request, or Question

OpenSSL/1.0.2x is published to conan but has no tag or source in this repository.

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2x**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.10**

### Steps to reproduce (Include if Applicable)

* Go to https://bintray.com/conan-community/conan/OpenSSL%3Aconan/latest_1.0.2x%3Astable and see there's a version 1.0.2x (required by upstream package `libcurl`)
* Visit https://github.com/conan-community/conan-openssl and note there's no mention of 1.0.2x anywhere

**Comment by Croydon** [comment]
Both in conan-community and in Bincrafters we do work with separated git branches for every single version.

For every single OpenSSL/1.0.2x release you will find an own branch: https://github.com/conan-community/conan-openssl/branches

**Comment by SSE4** [comment]
`1.0.2x_latest` is an alias, it's just a virtual symbolic list to the latest branch, for instance it might be `1.0.2r` today, but tomorrow it may change to `1.0.2s`

**Comment by mattgodbolt** [comment]
I see, thanks @SSE4
