### ISSUE TITLE
OpenCV 4.0.1 freetype didn't build

### ISSUE THREAD

**Issue by vadixidav** [conan-community/community#179]
When I build OpenCV 4.0.1 (`opencv/4.0.1@conan/stable`) from source, specifically using the options: `opencv:nonfree=True` and `opencv:contrib=True`, it seems I don't have an opencv_freetype lib produced.

```
LINK : fatal error LNK1181: cannot open input file 'opencv_freetype401.lib' [C:\Users\vax\code\hello_opencv\build\hello.vcxpr
oj]
ERROR: conanfile.py (hello_opencv/0.1.0@None/None): Error in build() method, line 22
        cmake.build()
        ConanException: Error 1 while executing cmake --build C:\Users\vax\code\hello_opencv\build --config Release -- /m:8 /verbosity:minimal
```

I don't believe this is due to my set options (though it could be related to default options like `shared=False`). When I remove "freetype" from the libs list it works as expected. We should probably make the building of opencv_freetype an option in the package so it can be controlled.

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.0.1**
* Operating System: **Windows**
* Operation System Version: **Windows 10**
* Compiler+version: **Visual Studio 2017**
* Conan version: **conan 1.14.1**
* Python version: **python 3.7.2**

### Steps to reproduce (Include if Applicable)
Just consume opencv downstream.

**Comment by SSE4** [comment]
I guess we have to add dependencies to `freetype` and `harfbuzz` libraries: https://github.com/opencv/opencv_contrib/blob/master/modules/freetype/CMakeLists.txt#L6

**Comment by SSE4** [comment]
applied: https://github.com/conan-community/conan-opencv/commit/fa958d911acdfdf0298ec747297d7baa488f9bac

**Comment by vadixidav** [comment]
@SSE4 I will give it a try now.

**Comment by vadixidav** [comment]
@SSE4 Looks like it worked:

```
opencv/4.0.1@vadix/testing (test package): Running test()
success! open "out.jpg" to see the resulting image.
```
