### ISSUE TITLE
conan-opencv 4.0.1 with contrib=True does not build contrib dnn module

### ISSUE THREAD

**Issue by bvnp43** [conan-community/community#180]
### Description of Problem, Request, or Question
conan-opencv with contrib=True does not build dnn module

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.0.1**
* Operating System: **Macos**
* Operation System Version: **10.14.4**
* Compiler+version: **Apple LLVM version 10.0.1 (clang-1001.0.46.3)**
* Conan version: **conan 1.14.1**

### Steps to reproduce (Include if Applicable)
```
conan_cmake_run(REQUIRES opencv/4.0.1@conan/stable
                OPTIONS opencv:contrib=True
                BASIC_SETUP NO_OUTPUT_DIRS
                BUILD missing)
```
### Build logs (Include if Available)

Headers and libs for dnn module can't be found in resulting package

**Comment by SSE4** [comment]
@bvnp43 do you have a build logs available?

**Comment by bvnp43** [comment]
@SSE4 
[log.txt](https://github.com/conan-community/community/files/3079884/log.txt)

**Comment by SSE4** [comment]
message is `Module opencv_dnn_objdetect disabled because opencv_dnn dependency can't be resolved!`
I need to check OpenCV cmake files to understand which checks does it run

**Comment by bvnp43** [comment]
@SSE4 

opencv/modules/dnn/CMakeLists.txt
```
if(NOT HAVE_PROTOBUF)
    ocv_module_disable(opencv_dnn)
endif()
```

does conan have protobuf?

**Comment by SSE4** [comment]
conan has protubuf, probably it's not referenced in OCV recipe, we need to link it then

**Comment by SSE4** [comment]
fixed at https://github.com/conan-community/conan-opencv/commit/52c47e1996777b99942be2b187ba2f4c66897f49
checked locally, it builds dnn modules

**Comment by bvnp43** [comment]
thanks
