### ISSUE TITLE
[eigen] add `Eigen3_DIR` to eigen package `env_info` variable.

### ISSUE THREAD

**Issue by CD3** [conan-community/community#183]
### Description of Problem, Request, or Question
Eigen supports the modern `cmake` target-based build process, and generates an `Eigen3Config.cmake` that can be detected by `cmake` when clients look for Eigen with the `find_package` command.

When `find_package(PackageName)` is called, `cmake` will search for a `PackageNameConfig.cmake` file to load. Several directories are searched (https://cmake.org/cmake/help/v3.14/command/find_package.html#search-procedure), but the user can specify the directory to use with an environment variable named `PackageName_DIR`.

Eigen installes `Eigen3Config.cmake` in `<package_folder>/share/eigen3/cmake`. So, if the `package_info` method added the line 
```
self.env_info.Eigen3_DIR = os.path.join(self.package_folder,"share","eigen3","cmake")
```
then consumers could find the package with the normal `find_package(Eigen3)` in a virtualenv.

### Package Details
* Package Name/Version: **eigen/3.3.x**
* Operating System: **Linux and Windows**
* Build System: **cmake**
* Generator: **virtualenv**

### Steps to reproduce (Include if Applicable)

Create `main.cpp`
```
#include <iostream>
#include <Eigen/Core>

int main(void)
{
    int const N = 5;
    Eigen::MatrixXi A(N, N);
    A.setRandom();

    std::cout << "A =\n" << A << '\n' <<std::endl;
    std::cout << "A(2..3,:) =\n" << A.middleRows(2, 2) << std::endl;
    
    return 0;
}
```

Create `CMakeLists.txt`
```
cmake_minimum_required(VERSION 3.10)

find_package( Eigen3 )

add_executable( main main.cpp )
target_link_libraries( main Eigen3::Eigen )
```

This works without conan. If the user installs `eigen3` with thier distro's package manager for example, cmake will
detect Eigen's `Eigen3Config.cmake` file.

Create `conanfile.txt`
```
[requires]
eigen/3.3.5@conan/stable

[generators]
virtualenv
```

Now try to build
```
$ mkdir build
$ cd build
$ conan install ..
$ source activate.sh
$ cmake ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:3 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring done
CMake Error at CMakeLists.txt:5 (add_executable):
  Target "main" links to target "Eigen3::Eigen" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/cclark/Code/sync/projects/conan/eigen/client/build

```

**Comment by SSE4** [comment]
@CD3 I've pushed required changes: https://github.com/conan-community/conan-eigen/commit/17bd0868a6e8745938636dea208b56750cf87834
please give a try and lemme know

**Comment by CD3** [comment]
Yes, it works. Thanks you.

**Comment by Morwenn** [comment]
I see that these changes have been rolled back somehow and I'm experience this issue again when compiling ITK with a dedicated Conan recipe (which tries to use the "system" Eigen when passing `ITK_USE_SYSTEM_EIGEN` to its CMake configuration). Apparently it just uses `find_package(Eigen3 REQUIRED CONFIG)` so it doesn't seem like an issue on the ITK side but more like one on the conan-eigen one.

On the other hand there is no `share/eigen3/cmake` directory in the files exported in the Eigen recipe so keeping a `Eigen3_DIR` variable pointing there didn't really make sense. I'm not not how to solve the issue.

**Comment by CD3** [comment]
I haven't done testing, but it looks like this commit

https://github.com/conan-community/conan-eigen/commit/2acc6acd3259af6fc7c76beada087e5f2fc52579

would cause the problem. The source headers are just being copied to the package directory now instead of using cmake to do the install, so the `Eigen3Config.cmake` file will not get installed this way.

**Comment by Morwenn** [comment]
I tried to use the `cmake_find_package` generator but it doesn't work: my guess is that `find_package(Eigen3)` is looking for a file named `Eigen3Config.cmake` but the generator only produces one called `eigenConfig.cmake` instead.

**Comment by SSE4** [comment]
this should be fixed in eigen recipe - by adding `self.cpp_info.name = "Eigen3"`

**Comment by Morwenn** [comment]
@SSE4 Thanks for the tip! I cloned conan-eigen and applied that changed and the resulting Conan package was found when using the generator `cmake_find_package_multi`. However it seems that this generator doesn't forward the version information, so I get an error along these lines (despite fetching version 3.3.7 of Eigen):

```
CMake Error at source_subfolder/Modules/ThirdParty/Eigen3/CMakeLists.txt:56 (find_package):
  Could not find a configuration file for package "Eigen3" that is compatible
  with requested version "3.3".

  The following configuration files were considered but not accepted:

    ~/.conan/data/itk/5.0.1/latim/stable/build/a9e815bf664154117de467f08af021beb20b7cc4/Eigen3Config.cmake, version: unknown
```

Is this a limitation of the `cmake_find_package_multi` generator?

**Comment by SSE4** [comment]
@Morwenn I think so. seems like it has to be fixed in conan, could you create an issue in [conan](https://github.com/conan-io/conan/issues) repository?
