### ISSUE TITLE
[OpenSSL] broken on Windows with clang-cl

### ISSUE THREAD

**Issue by acgetchell** [conan-community/community#188]
### Description of Problem, Request, or Question

OpenSSL broken on Windows:

~~~
C:\Users\appveyor\.conan\data\OpenSSL\1.0.2n\conan\stable\build\14214d5db1813d4f84ab3faaf7d4140f4f8f5c3b
ERROR: OpenSSL/1.0.2n@conan/stable: Error in build() method, line 120
	raise Exception("Unsupported operating system: %s" % self.settings.os)
	Exception: Unsupported operating system: Windows
~~~

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2n**
* Operating System: **Windows**
* Compiler+version: **clang-cl**
* Conan version: **conan 1.14.5**
* Python version: **python 2.7.0**

### Steps to reproduce (Include if Applicable)

On AppVeyor with:

https://github.com/acgetchell/CDT-plusplus/blob/develop/.appveyor.yml
https://github.com/acgetchell/CDT-plusplus/blob/develop/CMakeLists.txt

### Build logs (Include if Available)

Visual Studio 15:
https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/5yyxv5y6q370oo8f#L4828

Visual Studio 17:
https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/lssasvd7rdjg92t1#L4840

**Comment by acgetchell** [comment]
Note: I'm not specifying the version of OpenSSL explicitly, some other package that has it as a dependency is.

**Comment by SSE4** [comment]
we have to add `clang-cl` support for the OpenSSL. @acgetchell do you know if there are an instructions on how to build it with this compiler?

**Comment by acgetchell** [comment]
As far as I know, `clang-cl` is just a Window's driver for clang.

http://llvm.org/devmtg/2014-04/PDFs/Talks/clang-cl.pdf

This is what I've found for building OpenSSL with clang:

https://wiki.openssl.org/index.php/Compilation_and_Installation#Modifying_Build_Settings

Conan has worked with my linux/clang Travis-CI images, so presumably that's mostly solved.

I'd be interested in tracking this issue, I'll setup an instance of Visual Studio to test separately.

**Comment by SSE4** [comment]
@acgetchell applied: https://github.com/conan-community/conan-openssl/commit/653058bd56eec626b69c91a58940a8d6988264fb

**Comment by SSE4** [comment]
I am closing this one as changes were applied.

**Comment by acgetchell** [comment]
Yes, I can verify that this is resolved.

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/07v9b44r8uhc99o3#L8381

**Comment by acgetchell** [comment]
Whoops, spoke too soon. Fails on VS 2017:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/srvpsl65subcg7no#L6644

**Comment by SSE4** [comment]
@acgetchell seems like it's curl problem , right?

**Comment by SSE4** [comment]
never mind, we have https://github.com/conan-community/community/issues/222 to track it
