### ISSUE TITLE
[pybind11] Windows build failing with following errors

### ISSUE THREAD

**Issue by Prasaddiwalkar** [conan-community/community#189]
### Description of Problem, Request, or Question
I am trying to build pybind11 python module out of my c++ code. I am getting following error while build.

 example.obj : error LNK2019: unresolved external symbol __imp_strdup referenced in function "protected: void __cdecl pybind11::cpp_function::initialize_generic(struct pybind11::detail::function_record 
*,char const *,class type_info const * const *,unsigned __int64)" (?initialize_generic@cpp_function@pybind11@@IEAAXPEAUfunction_record@detail@2@PEBDPEBQEBVtype_info@@_K@Z) [D:\temp\pybind11\build\libexam
plepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyType_IsSubtype referenced in function "public: bool __cdecl pybind11::detail::type_caster<unsigned int,void>::load(class pybind11::handle
,bool)" (?load@?$type_caster@IX@detail@pybind11@@QEAA_NVhandle@3@_N@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyType_Ready referenced in function "struct _typeobject * __cdecl pybind11::detail::make_default_metaclass(void)" (?make_default_metaclass@
detail@pybind11@@YAPEAU_typeobject@@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp__PyType_Lookup referenced in function pybind11_meta_getattro [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyObject_Repr referenced in function "class pybind11::str __cdecl pybind11::repr(class pybind11::handle)" (?repr@pybind11@@YA?AVstr@1@Vhand
le@1@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyObject_Str referenced in function "public: __cdecl pybind11::str::str(class pybind11::object &&)" (??0str@pybind11@@QEAA@$$QEAVobject@1@@
Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyObject_GetAttrString referenced in function "class pybind11::object __cdecl pybind11::getattr(class pybind11::handle,char const *,class p
ybind11::handle)" (?getattr@pybind11@@YA?AVobject@1@Vhandle@1@PEBD0@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyObject_SetAttrString referenced in function "struct _typeobject * __cdecl pybind11::detail::make_default_metaclass(void)" (?make_default_
metaclass@detail@pybind11@@YAPEAU_typeobject@@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyObject_HasAttrString referenced in function "public: void __cdecl pybind11::module::add_object(char const *,class pybind11::handle,bool)"
 (?add_object@module@pybind11@@QEAAXPEBDVhandle@2@_N@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp__PyObject_GetDictPtr referenced in function "void __cdecl pybind11::detail::clear_instance(struct _object *)" (?clear_instance@detail@pybin
d11@@YAXPEAU_object@@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyObject_ClearWeakRefs referenced in function "void __cdecl pybind11::detail::clear_instance(struct _object *)" (?clear_instance@detail@pyb
ind11@@YAXPEAU_object@@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyMem_Calloc referenced in function "public: void __cdecl pybind11::detail::instance::allocate_layout(void)" (?allocate_layout@instance@det
ail@pybind11@@QEAAXXZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyMem_Free referenced in function "public: void __cdecl pybind11::detail::instance::deallocate_layout(void)" (?deallocate_layout@instance@d
etail@pybind11@@QEAAXXZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyBytes_Size referenced in function "private: bool __cdecl pybind11::detail::string_caster<class std::basic_string<char,struct std::char_tr
aits<char>,class std::allocator<char> >,0>::load_bytes<char>(class pybind11::handle)" (??$load_bytes@D@?$string_caster@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$0A@@detail@pybind11@@
AEAA_NVhandle@2@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyBytes_AsString referenced in function "private: bool __cdecl pybind11::detail::string_caster<class std::basic_string<char,struct std::cha
r_traits<char>,class std::allocator<char> >,0>::load_bytes<char>(class pybind11::handle)" (??$load_bytes@D@?$string_caster@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$0A@@detail@pybind
11@@AEAA_NVhandle@2@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyBytes_AsStringAndSize referenced in function "public: __cdecl pybind11::str::operator class std::basic_string<char,struct std::char_trait
s<char>,class std::allocator<char> >(void)const " (??Bstr@pybind11@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyUnicode_FromString referenced in function "public: class pybind11::detail::accessor<struct pybind11::detail::accessor_policies::generic_i
tem> __cdecl pybind11::detail::object_api<class pybind11::handle>::operator[](char const *)const " (??A?$object_api@Vhandle@pybind11@@@detail@pybind11@@QEBA?AV?$accessor@Ugeneric_item@accessor_policies@d
etail@pybind11@@@12@PEBD@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyUnicode_AsEncodedString referenced in function "public: bool __cdecl pybind11::detail::string_caster<class std::basic_string<char,struct 
std::char_traits<char>,class std::allocator<char> >,0>::load(class pybind11::handle,bool)" (?load@?$string_caster@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$0A@@detail@pybind11@@QEAA_
NVhandle@3@_N@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyUnicode_DecodeUTF8 referenced in function "public: static class pybind11::handle __cdecl pybind11::detail::type_caster<char,void>::cast(c
har const *,enum pybind11::return_value_policy,class pybind11::handle)" (?cast@?$type_caster@DX@detail@pybind11@@SA?AVhandle@3@PEBDW4return_value_policy@3@V43@@Z) [D:\temp\pybind11\build\libexamplepybind
11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyUnicode_AsUTF8String referenced in function "public: __cdecl pybind11::str::operator class std::basic_string<char,struct std::char_traits
<char>,class std::allocator<char> >(void)const " (??Bstr@pybind11@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyLong_FromLong referenced in function "public: class pybind11::handle __cdecl <lambda_4315c648a4d8fc31f7222a9e0db18228>::operator()(struct
 pybind11::detail::function_call &)const " (??R<lambda_4315c648a4d8fc31f7222a9e0db18228>@@QEBA?AVhandle@pybind11@@AEAUfunction_call@detail@2@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyLong_AsUnsignedLong referenced in function "unsigned long __cdecl pybind11::detail::as_unsigned<unsigned long>(struct _object *)" (??$as_
unsigned@K@detail@pybind11@@YAKPEAU_object@@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyTuple_New referenced in function "class pybind11::tuple __cdecl pybind11::make_tuple<1>(void)" (??$make_tuple@$00@pybind11@@YA?AVtuple@0@
XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyTuple_Size referenced in function "protected: static struct _object * __cdecl pybind11::cpp_function::dispatcher(struct _object *,struct 
_object *,struct _object *)" (?dispatcher@cpp_function@pybind11@@KAPEAU_object@@PEAU3@00@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyTuple_GetItem referenced in function "public: static class pybind11::object __cdecl pybind11::detail::accessor_policies::tuple_item::get(
class pybind11::handle,unsigned __int64)" (?get@tuple_item@accessor_policies@detail@pybind11@@SA?AVobject@4@Vhandle@4@_K@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyTuple_SetItem referenced in function "protected: static struct _object * __cdecl pybind11::cpp_function::dispatcher(struct _object *,stru
ct _object *,struct _object *)" (?dispatcher@cpp_function@pybind11@@KAPEAU_object@@PEAU3@00@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2001: unresolved external symbol __imp_PyList_New [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2001: unresolved external symbol __imp_PyList_Append [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyDict_New referenced in function "protected: static struct _object * __cdecl pybind11::cpp_function::dispatcher(struct _object *,struct _o
bject *,struct _object *)" (?dispatcher@cpp_function@pybind11@@KAPEAU_object@@PEAU3@00@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyDict_Next referenced in function "protected: static struct _object * __cdecl pybind11::cpp_function::dispatcher(struct _object *,struct _
object *,struct _object *)" (?dispatcher@cpp_function@pybind11@@KAPEAU_object@@PEAU3@00@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyDict_Size referenced in function "protected: static struct _object * __cdecl pybind11::cpp_function::dispatcher(struct _object *,struct _
object *,struct _object *)" (?dispatcher@cpp_function@pybind11@@KAPEAU_object@@PEAU3@00@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyDict_Copy referenced in function "protected: static struct _object * __cdecl pybind11::cpp_function::dispatcher(struct _object *,struct _
object *,struct _object *)" (?dispatcher@cpp_function@pybind11@@KAPEAU_object@@PEAU3@00@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyDict_GetItemString referenced in function "protected: static struct _object * __cdecl pybind11::cpp_function::dispatcher(struct _object *
,struct _object *,struct _object *)" (?dispatcher@cpp_function@pybind11@@KAPEAU_object@@PEAU3@00@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyDict_DelItemString referenced in function "protected: static struct _object * __cdecl pybind11::cpp_function::dispatcher(struct _object *
,struct _object *,struct _object *)" (?dispatcher@cpp_function@pybind11@@KAPEAU_object@@PEAU3@00@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyCFunction_NewEx referenced in function "protected: void __cdecl pybind11::cpp_function::initialize_generic(struct pybind11::detail::funct
ion_record *,char const *,class type_info const * const *,unsigned __int64)" (?initialize_generic@cpp_function@pybind11@@IEAAXPEAUfunction_record@detail@2@PEBDPEBQEBVtype_info@@_K@Z) [D:\temp\pybind11\bu
ild\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyInstanceMethod_New referenced in function "protected: void __cdecl pybind11::cpp_function::initialize_generic(struct pybind11::detail::fu
nction_record *,char const *,class type_info const * const *,unsigned __int64)" (?initialize_generic@cpp_function@pybind11@@IEAAXPEAUfunction_record@detail@2@PEBDPEBQEBVtype_info@@_K@Z) [D:\temp\pybind11
\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyCapsule_New referenced in function "public: __cdecl pybind11::capsule::capsule(void const *,void (__cdecl*)(void *))" (??0capsule@pybind1
1@@QEAA@PEBXP6AXPEAX@Z@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyCapsule_GetPointer referenced in function "private: static void __cdecl <lambda_57bff18ff75e63c44eefc978be789c02>::<lambda_invoker_cdecl>
(struct _object *)" (?<lambda_invoker_cdecl>@<lambda_57bff18ff75e63c44eefc978be789c02>@@CAXPEAU_object@@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyCapsule_GetName referenced in function "struct pybind11::detail::internals & __cdecl pybind11::detail::get_internals(void)" (?get_interna
ls@detail@pybind11@@YAAEAUinternals@12@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyCapsule_GetContext referenced in function "private: static void __cdecl <lambda_57bff18ff75e63c44eefc978be789c02>::<lambda_invoker_cdecl>
(struct _object *)" (?<lambda_invoker_cdecl>@<lambda_57bff18ff75e63c44eefc978be789c02>@@CAXPEAU_object@@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyCapsule_SetContext referenced in function "public: __cdecl pybind11::capsule::capsule(void const *,void (__cdecl*)(void *))" (??0capsule@
pybind11@@QEAA@PEBXP6AXPEAX@Z@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyThread_create_key referenced in function "struct pybind11::detail::internals & __cdecl pybind11::detail::get_internals(void)" (?get_inter
nals@detail@pybind11@@YAAEAUinternals@12@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyThread_set_key_value referenced in function "public: __cdecl pybind11::gil_scoped_acquire::gil_scoped_acquire(void)" (??0gil_scoped_acqui
re@pybind11@@QEAA@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyThread_get_key_value referenced in function "public: __cdecl pybind11::gil_scoped_acquire::gil_scoped_acquire(void)" (??0gil_scoped_acqui
re@pybind11@@QEAA@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyThread_delete_key_value referenced in function "public: void __cdecl pybind11::gil_scoped_acquire::dec_ref(void)" (?dec_ref@gil_scoped_ac
quire@pybind11@@QEAAXXZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyThreadState_New referenced in function "public: __cdecl pybind11::gil_scoped_acquire::gil_scoped_acquire(void)" (??0gil_scoped_acquire@py
bind11@@QEAA@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyThreadState_Clear referenced in function "public: void __cdecl pybind11::gil_scoped_acquire::dec_ref(void)" (?dec_ref@gil_scoped_acquire@
pybind11@@QEAAXXZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyThreadState_DeleteCurrent referenced in function "public: void __cdecl pybind11::gil_scoped_acquire::dec_ref(void)" (?dec_ref@gil_scoped_
acquire@pybind11@@QEAAXXZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyThreadState_Get referenced in function "struct pybind11::detail::internals & __cdecl pybind11::detail::get_internals(void)" (?get_interna
ls@detail@pybind11@@YAAEAUinternals@12@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp__PyThreadState_UncheckedGet referenced in function "public: __cdecl pybind11::gil_scoped_acquire::gil_scoped_acquire(void)" (??0gil_scoped_
acquire@pybind11@@QEAA@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyWeakref_NewRef referenced in function "struct std::pair<class std::_List_iterator<class std::_List_val<struct std::_List_simple_types<str
uct std::pair<struct _typeobject * const,class std::vector<struct pybind11::detail::type_info *,class std::allocator<struct pybind11::detail::type_info *> > > > > >,bool> __cdecl pybind11::detail::all_ty
pe_info_get_cache(struct _typeobject *)" (?all_type_info_get_cache@detail@pybind11@@YA?AU?$pair@V?$_List_iterator@V?$_List_val@U?$_List_simple_types@U?$pair@QEAU_typeobject@@V?$vector@PEAUtype_info@detai
l@pybind11@@V?$allocator@PEAUtype_info@detail@pybind11@@@std@@@std@@@std@@@std@@@std@@@std@@_N@std@@PEAU_typeobject@@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyErr_SetString referenced in function __catch$?<lambda_invoker_cdecl>@<lambda_f5310e0d6bb5037e25e9ee4092a6a9e0>@@CAXVexception_ptr@std@@@Z
$2 [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyErr_Occurred referenced in function "unsigned long __cdecl pybind11::detail::as_unsigned<unsigned long>(struct _object *)" (??$as_unsigne
d@K@detail@pybind11@@YAKPEAU_object@@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyErr_Clear referenced in function "class pybind11::object __cdecl pybind11::getattr(class pybind11::handle,char const *,class pybind11::ha
ndle)" (?getattr@pybind11@@YA?AVobject@1@Vhandle@1@PEBD0@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyErr_Fetch referenced in function "public: __cdecl pybind11::error_already_set::error_already_set(void)" (??0error_already_set@pybind11@@Q
EAA@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyErr_Restore referenced in function __catch$?<lambda_invoker_cdecl>@<lambda_09ac1fb5269c32188e6c5e1d31e1b871>@@CAXVexception_ptr@std@@@Z$0
 [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyErr_ExceptionMatches referenced in function "public: bool __cdecl pybind11::detail::type_caster<unsigned int,void>::load(class pybind11::
handle,bool)" (?load@?$type_caster@IX@detail@pybind11@@QEAA_NVhandle@3@_N@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyErr_NormalizeException referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __
cdecl pybind11::detail::error_string(void)" (?error_string@detail@pybind11@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyException_SetTraceback referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __
cdecl pybind11::detail::error_string(void)" (?error_string@detail@pybind11@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyErr_Format referenced in function PyInit_example [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyModule_AddObject referenced in function "public: void __cdecl pybind11::module::add_object(char const *,class pybind11::handle,bool)" (?a
dd_object@module@pybind11@@QEAAXPEBDVhandle@2@_N@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyModule_Create2 referenced in function "public: __cdecl pybind11::module::module(char const *,char const *)" (??0module@pybind11@@QEAA@PEB
D0@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_Py_GetVersion referenced in function PyInit_example [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyEval_GetBuiltins referenced in function "struct pybind11::detail::internals & __cdecl pybind11::detail::get_internals(void)" (?get_intern
als@detail@pybind11@@YAAEAUinternals@12@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyEval_SaveThread referenced in function "public: __cdecl pybind11::gil_scoped_acquire::~gil_scoped_acquire(void)" (??1gil_scoped_acquire@p
ybind11@@QEAA@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyEval_InitThreads referenced in function "struct pybind11::detail::internals & __cdecl pybind11::detail::get_internals(void)" (?get_intern
als@detail@pybind11@@YAAEAUinternals@12@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyEval_AcquireThread referenced in function "public: __cdecl pybind11::gil_scoped_acquire::gil_scoped_acquire(void)" (??0gil_scoped_acquire
@pybind11@@QEAA@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyObject_CallObject referenced in function "public: class pybind11::object __cdecl pybind11::detail::simple_collector<1>::call(struct _obje
ct *)const " (?call@?$simple_collector@$00@detail@pybind11@@QEBA?AVobject@3@PEAU_object@@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyObject_GetItem referenced in function "public: static class pybind11::object __cdecl pybind11::detail::accessor_policies::generic_item::g
et(class pybind11::handle,class pybind11::handle)" (?get@generic_item@accessor_policies@detail@pybind11@@SA?AVobject@4@Vhandle@4@0@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyObject_SetItem referenced in function "struct pybind11::detail::internals & __cdecl pybind11::detail::get_internals(void)" (?get_internal
s@detail@pybind11@@YAAEAUinternals@12@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyNumber_Check referenced in function "public: bool __cdecl pybind11::detail::type_caster<unsigned int,void>::load(class pybind11::handle,b
ool)" (?load@?$type_caster@IX@detail@pybind11@@QEAA_NVhandle@3@_N@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyNumber_Long referenced in function "public: bool __cdecl pybind11::detail::type_caster<unsigned int,void>::load(class pybind11::handle,bo
ol)" (?load@?$type_caster@IX@detail@pybind11@@QEAA_NVhandle@3@_N@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyObject_IsInstance referenced in function pybind11_meta_setattro [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyFrame_GetLineNumber referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cde
cl pybind11::detail::error_string(void)" (?error_string@detail@pybind11@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyType_Type referenced in function "struct _typeobject * __cdecl pybind11::detail::make_default_metaclass(void)" (?make_default_metaclass@d
etail@pybind11@@YAPEAU_typeobject@@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyBaseObject_Type referenced in function "struct _object * __cdecl pybind11::detail::make_object_base_type(struct _typeobject *)" (?make_ob
ject_base_type@detail@pybind11@@YAPEAU_object@@PEAU_typeobject@@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp__Py_NoneStruct referenced in function "bool __cdecl pybind11::cast<bool,0>(class pybind11::handle const &)" (??$cast@_N$0A@@pybind11@@YA_NA
EBVhandle@0@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp__Py_NotImplementedStruct referenced in function "protected: static struct _object * __cdecl pybind11::cpp_function::dispatcher(struct _obje
ct *,struct _object *,struct _object *)" (?dispatcher@cpp_function@pybind11@@KAPEAU_object@@PEAU3@00@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp__Py_FalseStruct referenced in function "bool __cdecl pybind11::cast<bool,0>(class pybind11::handle const &)" (??$cast@_N$0A@@pybind11@@YA_N
AEBVhandle@0@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp__Py_TrueStruct referenced in function "bool __cdecl pybind11::cast<bool,0>(class pybind11::handle const &)" (??$cast@_N$0A@@pybind11@@YA_NA
EBVhandle@0@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyFloat_Type referenced in function "public: bool __cdecl pybind11::detail::type_caster<unsigned int,void>::load(class pybind11::handle,boo
l)" (?load@?$type_caster@IX@detail@pybind11@@QEAA_NVhandle@3@_N@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyCFunction_Type referenced in function "protected: void __cdecl pybind11::cpp_function::initialize_generic(struct pybind11::detail::functi
on_record *,char const *,class type_info const * const *,unsigned __int64)" (?initialize_generic@cpp_function@pybind11@@IEAAXPEAUfunction_record@detail@2@PEBDPEBQEBVtype_info@@_K@Z) [D:\temp\pybind11\bui
ld\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyInstanceMethod_Type referenced in function "protected: void __cdecl pybind11::cpp_function::initialize_generic(struct pybind11::detail::f
unction_record *,char const *,class type_info const * const *,unsigned __int64)" (?initialize_generic@cpp_function@pybind11@@IEAAXPEAUfunction_record@detail@2@PEBDPEBQEBVtype_info@@_K@Z) [D:\temp\pybind1
1\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyCapsule_Type referenced in function "bool __cdecl pybind11::isinstance<class pybind11::capsule,0>(class pybind11::handle)" (??$isinstance
@Vcapsule@pybind11@@$0A@@pybind11@@YA_NVhandle@0@@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyProperty_Type referenced in function "struct _typeobject * __cdecl pybind11::detail::make_static_property_type(void)" (?make_static_prope
rty_type@detail@pybind11@@YAPEAU_typeobject@@XZ) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyExc_ImportError referenced in function PyInit_example [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyExc_IndexError referenced in function __catch$?<lambda_invoker_cdecl>@<lambda_f5310e0d6bb5037e25e9ee4092a6a9e0>@@CAXVexception_ptr@std@@@
Z$6 [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyExc_MemoryError referenced in function __catch$?<lambda_invoker_cdecl>@<lambda_f5310e0d6bb5037e25e9ee4092a6a9e0>@@CAXVexception_ptr@std@@
@Z$2 [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyExc_RuntimeError referenced in function __catch$?<lambda_invoker_cdecl>@<lambda_f5310e0d6bb5037e25e9ee4092a6a9e0>@@CAXVexception_ptr@std@
@@Z$8 [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyExc_SystemError referenced in function __catch$?dispatcher@cpp_function@pybind11@@KAPEAU_object@@PEAU3@00@Z$5 [D:\temp\pybind11\build\lib
examplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyExc_TypeError referenced in function "protected: static struct _object * __cdecl pybind11::cpp_function::dispatcher(struct _object *,stru
ct _object *,struct _object *)" (?dispatcher@cpp_function@pybind11@@KAPEAU_object@@PEAU3@00@Z) [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  example.obj : error LNK2019: unresolved external symbol __imp_PyExc_ValueError referenced in function __catch$?<lambda_invoker_cdecl>@<lambda_f5310e0d6bb5037e25e9ee4092a6a9e0>@@CAXVexception_ptr@std@@@
Z$3 [D:\temp\pybind11\build\libexamplepybind11.vcxproj]
  D:\temp\pybind11\build\bin\libexamplepybind11.dll : fatal error LNK1120: 92 unresolved externals [D:\temp\pybind11\build\libexamplepybind11.vcxproj]

### Package Details (Include if Applicable)
* Package Name/Version: **zstd/1.3.3**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Compiler+version: **gcc-5.4**
* Docker image: **conanio/gcc7**
* Conan version: **conan 1.2.0**
* Python version: **python 3.7.0**

### Steps to reproduce (Include if Applicable)
conan install ..
cmake .. -G "Visual Studio 15 Win64"
cmake --build . --config Release

**Comment by SSE4** [comment]
from the linker errors, I think you have to link not just with `pybind11`, but with python libraries as well (something like `python.lib` which should be shipped with python installation itself)

**Comment by danimtb** [comment]
This recipe has been included in [conan-io/conan-center-index](https://github.com/conan-io/conan-center-index) as ``pybind11/2.4.3``. The recipe in the conan-community organization has been archived and it will no longer be maintained. Please try the new recipe and report any issue there. Thank you!
