### ISSUE TITLE
cmake_installer is broken for Linux build_arch=x86

### ISSUE THREAD

**Issue by db4** [conan-community/community#195]
Some time ago in commit https://github.com/conan-community/conan-cmake-installer/commit/5715e036453ff1d2f5c684c27f73c454b093c3c3  I made Linux x86 supported by cmake_installer (via building from sources, as x86 binary was not available on cmake.org website). That time cmake_installers' `package_id()` depended on `arch_build`:
```
    Package_ID: 445cf80f611c1d1eda08bde2ebc5066218ca9701
        [settings]
            arch_build: x86
            os_build: Linux
        Outdated from recipe: False
```
But the current recipe (probably after massive changes by @uilianries) does not:
```
    Package_ID: be241241e9d4718e5bab4eb33935bbb69606bb0c
        [settings]
            os_build: Linux
        Outdated from recipe: True
```
That means the same package (that contains x86_64 cmake executable) will be used for any Linux build architecture. For Linux x86 (or e.g. arm64) it will obviously fail.

**Comment by db4** [comment]
> That means the same package (that contains x86_64 cmake executable)

Actually, conan-center Linux package contains i386 cmake executable  but missing `arch_build` in `package_id()` is nevertheless a problem. I believe https://github.com/conan-community/community/issues/194 is related to it as well.

**Comment by uilianries** [comment]
Hi @db4 !

Thanks for reporting about this, I'm going to investigate this problem.

**Comment by SSE4** [comment]
@db4 should be fixed now, please give an another try

**Comment by db4** [comment]
Yes, now it works for me
