### ISSUE TITLE
Visual Studio 2019 builds

### ISSUE THREAD

**Issue by thedacheng** [conan-community/community#198]
### Description of Problem, Request, or Question
Any plan to create VS 2019 builds for all native libraries?

**Comment by SSE4** [comment]
waiting on appveyor (they currently only provide VS 2019 preview): https://github.com/appveyor/ci/issues/2907

**Comment by SSE4** [comment]
@thedacheng okay, this is now available
please specify which projects do you need

**Comment by SSE4** [comment]
so far added: zlib, bzip2, OpenSSL, boost

**Comment by SSE4** [comment]
closing out as we're adding builds one by one, as needed
