### ISSUE TITLE
[OpenSSL] parallel build

### ISSUE THREAD

**Issue by vaind** [conan-community/community#199]
### Description of Problem, Request, or Question
currently, the package calls `make`. I suggest changing that to `make -j` to speed up the build using multiple executors. 
I've been using that (actually `make -j build_libs`) with OpenSSL in the past, even in CI with hundreds of executions and never had issues.

### Package Details (Include if Applicable)
* Operating System: **Linux**

**Comment by SSE4** [comment]
applied, thanks: https://github.com/conan-community/conan-openssl/commit/c9e3e40298f486d66c89c990546a77c3dc2441c8

**Comment by SSE4** [comment]
changes we applied, closing
