### ISSUE TITLE
OpenSSL build using clang

### ISSUE THREAD

**Issue by alexxxgu** [conan-community/community#2]
Hi, I'm trying to use boosts with open ssl, but OpenSSL can't be compiled for Android using clang:
ERROR: OpenSSL/1.0.2n@conan/stable: Error in configure() method, line 69
        "how to build it: %s" % self.url)
        Exception: Not supported Android + Clang, please submit a patch if you know how to build it: http://github.com/lasote/conan-openssl

and boost can't be compiled using gcc:
In file included from ./boost/config/compiler/gcc.hpp:165:0,
                 from ./boost/config.hpp:39,
                 from ./boost/wave/wave_config.hpp:16,
                 from libs/wave/src/cpplexer/re2clex/cpp_re.cpp:28:
/mnt/c/Android/arm_21_toolchain15/include/c++/4.9.x/cstddef:43:25: fatal error: stddef.h: No such file or directory
(GCC bug according to Google)? toolchain was generated from android-ndk-r15c with --deprecated-headers

**Comment by lasote** [comment]
Looks like currently there is no still official support for that. We should check in a while if there is some progress

**Comment by alexxxgu** [comment]
Can I specify different toochains\compillers for different libraries for one conan project?

**Comment by lasote** [comment]
Yes, you can do settings by package: `-s OpenSSL:compiler=clang` and in the profiles you can specify env vars for an specific package: 
```
[env]
OpenSSL:specific_stuff=2
```
But, great power comes great responsibility, it should cover only corner cases.

**Comment by alexxxgu** [comment]
[requires]
boost/1.66.0@conan/stable
OpenSSL/1.1.0g@conan/stable

compiled once, but now i'm getting 
[100%] Built target bzip2
bzip2/1.0.6@conan/stable: Package '9b5efed8fbf1cba00152d97f255eab56c82b3ef9' built
bzip2/1.0.6@conan/stable: Build folder /root/.conan/data/bzip2/1.0.6/conan/stable/build/9b5efed8fbf1cba00152d97f255eab56c82b3ef9
bzip2/1.0.6@conan/stable: Generated conaninfo.txt
bzip2/1.0.6@conan/stable: Generated conanbuildinfo.txt
bzip2/1.0.6@conan/stable: Generating the package
bzip2/1.0.6@conan/stable: Package folder /root/.conan/data/bzip2/1.0.6/conan/stable/package/9b5efed8fbf1cba00152d97f255eab56c82b3ef9
bzip2/1.0.6@conan/stable: Calling package()
bzip2/1.0.6@conan/stable package(): Copied 2 '.h' files: bzlib.h, bzlib_private.h
bzip2/1.0.6@conan/stable package(): Copied 1 '' files: bzip2
bzip2/1.0.6@conan/stable package(): Copied 1 '.a' files: libbz2.a
bzip2/1.0.6@conan/stable: Package '9b5efed8fbf1cba00152d97f255eab56c82b3ef9' created
Downloading conan_sources.tgz
[==================================================] 281B/281B
zlib/1.2.11@conan/stable: Building your package in /root/.conan/data/zlib/1.2.11/conan/stable/build/39a53587004d75943e385925ca011baeab537de0
zlib/1.2.11@conan/stable: Configuring sources in /root/.conan/data/zlib/1.2.11/conan/stable/source
[==================================================] 652B/652B
zlib/1.2.11@conan/stable: WARN: Trying to remove dirty source folder
zlib/1.2.11@conan/stable: WARN: This can take a while for big packages
ERROR: zlib/1.2.11@conan/stable: Error in source() method, line 27
        tools.unzip(z_name)
        ReadError: file could not be opened successfully

**Comment by Bjoe** [comment]
Hi. I create a pull request [Android build with clang](https://github.com/conan-community/conan-openssl/pull/51) on conan-openssl. Unfortunately its not ready yet. Test package step fails and I'm not yet an conan package profi. Maybe somebody have an idea.

**Comment by alexxxgu** [comment]
@Bjoe Have not you get any issues while connecting using ssl on Android?

**Comment by Bjoe** [comment]
@alexxxgu No. I have openssl 1.0.2 compiled with NDK16, clang and libc++ for android API level 19 and I didn't have any issues. Also not with Boost. But I cross compiled boost and openssl with my own cmake cross compile environment. I will share my knowledge and try to contribute conan to build packages for android.
@lasote I see you have a conan docker file repo with some build environment ... I can create a pull request for a docker with android sdk environment to build android packages :-)

**Comment by Croydon** [comment]
This seems to be fixed?

**Comment by alexxxgu** [comment]
yes, now it works for me too, thanks

**Comment by alexxxgu** [comment]
@Bjoe  have you tried OpenSSL/1.1.0g@conan/stable ? It gives me  
  crypto/ui/ui_openssl.c:424: error: undefined reference to 'tcgetattr'
  crypto/ui/ui_openssl.c:631: error: undefined reference to 'signal'
  crypto/ui/ui_openssl.c:489: error: undefined reference to 'tcsetattr'
  crypto/ui/ui_openssl.c:531: error: undefined reference to 'tcsetattr'

on api other than 21

**Comment by Linux13524** [comment]
I get an error with standalone toolchain from NDK r16b:
```
sha256-armv4.S:2638:2: error: invalid instruction
 adrl r3,K256
```
Profile is the one from the docs:
```
standalone_toolchain=/path/to/toolchain
target_host=arm-linux-androideabi
cc_compiler=clang
cxx_compiler=clang++

[settings]
compiler=clang
compiler.version=5.0
compiler.libcxx=libc++
os=Android
os.api_level=21
arch=armv7
build_type=Release

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/sysroot
PATH=[$standalone_toolchain/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
LD=$target_host-ld
STRIP=$target_host-strip
CFLAGS= -fPIC  -I$standalone_toolchain/include/c++/4.9.x
CXXFLAGS= -fPIC  -I$standalone_toolchain/include/c++/4.9.x
LDFLAGS=
```
