### ISSUE TITLE
[OpenSSL] OpenSSL Windows CAPI OPENSSL_CAPIENG_DIALOG

### ISSUE THREAD

**Issue by vadixidav** [conan-community/community#20]
* Package Name/Version: all OpenSSL
* Operating System: Windows
* Compiler+version: Visual Studio 2015

It seems there needs to be some compilation option to add -DOPENSSL_CAPIENG_DIALOG on Windows specifically to get a chooser dialog for security tokens. `capieng_dialog` or `no_capieng_dialog` seem like potentially good names. This is also related to #14 because capieng is an engine and isn't currently packaged. When it is packaged, this option should also be added.

**Comment by SSE4** [comment]
@vadixidav I've applied required changes: https://github.com/conan-community/conan-openssl/commit/fa28d72eb5a0b19553859cda6fbd427fb3a94bbc
please give a try and lemme know

**Comment by SSE4** [comment]
changes were applied, closing
