### ISSUE TITLE
[OpenSSL] armv6 support for 1.1.1

### ISSUE THREAD

**Issue by vaind** [conan-community/community#200]
### Description of Problem, Request, or Question
Could you please bring ARMv6 support. I've manually tested that adding 
```
"armv6": "linux-armv4",
```
before [conanfile.py:L158](https://github.com/conan-community/conan-openssl/blob/release/1.1.1b/conanfile.py#L158) does the trick.

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.1.1b**
* Operating System: **Linux**
* Docker image: **dockcross/linux-armv6**

**Comment by SSE4** [comment]
applied, thanks: https://github.com/conan-community/conan-openssl/commit/9164c62bf4cc2d87d0537d38b2f0ae87c4ffb106#diff-2b1d42f71f22b7ea0412d7602dec166f

**Comment by SSE4** [comment]
changes were applied, closing
