### ISSUE TITLE
Boost 1.70.0 recipe fails with GCC 5 based profile

### ISSUE THREAD

**Issue by planetmarshall** [conan-community/community#203]
### Description of Problem, Request, or Question
Installation of Boost 1.70.0 dependency fails.

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.70.0@conan/stable**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Compiler+version: **gcc-5.4**
* Conan version: **conan 1.14.3**
* Python version: **python 3.5.2**

### Steps to reproduce (Include if Applicable)

``` 
> git clone git@github.com:conan-community/conan-boost.git --branch release/1.70.0
> cd conan-boost
> conan source . -sf tmp/source
> conan install . -if tmp/build
> conan build . -sf tmp/source -bf tmp/build 

With the following profile:

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=5.4
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
```

### Build logs (Include if Available)


```
boost/1.70.0@conan/stable: WARN: Patching user-config.jam
boost/1.70.0@conan/stable:
boost/1.70.0@conan/stable: ERROR: Package 'cc1448c669e49456a1024d0e5ecefde070e0bfe1' build failed
boost/1.70.0@conan/stable: WARN: Build folder /home/andrew/.conan/data/boost/1.70.0/conan/stable/build/cc1448c669e49456a1024d0e5ecefde070e0bfe1
ERROR: boost/1.70.0@conan/stable: Error in build() method, line 398
        self.create_user_config_jam(self._boost_build_dir)
while calling 'create_user_config_jam', line 681
        contents += ' "%s"' % exe.replace("\\", "/")
        AttributeError: 'tuple' object has no attribute 'replace'
```

**Comment by planetmarshall** [comment]
This is caused by the `self.get_toolset_version_and_exe` method returning a tuple for the `executable` return value in the case of gcc and a string in other cases.

**Comment by SSE4** [comment]
yeah, seems like I've broken it yesterday... sorry about it. I've reverted this commit, as it was completely wrong. please give an another try and lemme know.

**Comment by planetmarshall** [comment]
Working for me now, cheers.
