### ISSUE TITLE
[boost] Request: BOOST_ALL_DYN_LINK defined when SHARED option is selected.

### ISSUE THREAD

**Issue by kwilliamszaf** [conan-community/community#205]
### Description of Problem, Request, or Question
How do I get Conan to cause the BOOST_ALL_DYN_LINK variable to be defined for later use when I specify a requirement of a shared version of the BOOST libraries?

Thanks!

**Comment by SSE4** [comment]
it should be defined automatically
check this out: https://github.com/conan-community/conan-boost/blob/release/1.70.0/conanfile.py#L830

**Comment by kwilliamszaf** [comment]
Ah nice.
I had lurker defines in source and CMakeLists.
Thanks!
