### ISSUE TITLE
[zlib] Package does not build with custom source folder

### ISSUE THREAD

**Issue by planetmarshall** [conan-community/community#208]
### Package Details (Include if Applicable)
* Package Name/Version: **zlib/1.2.11**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Compiler+version: **gcc-5.4**
* Conan version: **conan 1.15.0**
* Python version: **python 3.5.2**

### Steps to reproduce (Include if Applicable)

```
conan source . -sf tmp/source
conan install . -if tmp/build
conan build . -bf tmp/build -sf tmp/source
```

### Build logs (Include if Available)

```
conanfile.py (zlib/1.2.11@None/None): Running build()
ERROR: conanfile.py (zlib/1.2.11@None/None): Error in build() method, line 49
        self._build_zlib()
while calling '_build_zlib', line 81
        with tools.chdir(self._source_subfolder):
        FileNotFoundError: [Errno 2] No such file or directory: 'source_subfolder'
```

**Comment by planetmarshall** [comment]
Also reproducible on Windows.

**Comment by SSE4** [comment]
moving discussion to the conan issue: https://github.com/conan-io/conan/issues/5165

**Comment by kaptenhonek** [comment]
Hey @planetmarshall, I had this issue myself. I made a fork of conan-zlib here: https://github.com/kaptenhonek/conan-zlib
It supports source and build in different folders (mainly due to me removing the autotools build and restructuring the package function)

**Comment by SSE4** [comment]
moved to https://github.com/conan-io/conan-center-index/issues/92
