### ISSUE TITLE
[boost] _GLIBCXX_USE_CXX11_ABI setting is not stored in Conan's output CFLAGS

### ISSUE THREAD

**Issue by Expander** [conan-community/community#209]
### Description of Problem, Request, or Question

In a C++ project I'm using the boost package recipe from the conan-center. My `conanfile.txt` reads
~~~
[requires]
boost/[>=1.37.0]@conan/stable

[options]
boost:bzip2=False
boost:error_code_header_only=False
boost:fPIC=True
boost:filesystem_no_deprecated=False
boost:header_only=False
boost:layout=system
boost:lzma=False
boost:magic_autolink=False
boost:namespace=boost
boost:namespace_alias=False
boost:python_executable=None
boost:python_version=None
boost:shared=True
boost:system_no_deprecated=False
boost:without_atomic=True
boost:without_chrono=True
boost:without_container=True
boost:without_context=True
boost:without_contract=True
boost:without_coroutine=True
boost:without_date_time=True
boost:without_exception=True
boost:without_fiber=True
boost:without_filesystem=True
boost:without_graph=True
boost:without_graph_parallel=True
boost:without_iostreams=True
boost:without_locale=True
boost:without_log=True
boost:without_math=True
boost:without_mpi=True
boost:without_program_options=True
boost:without_python=True
boost:without_random=True
boost:without_regex=True
boost:without_serialization=True
boost:without_stacktrace=True
boost:without_system=True
boost:without_test=False
boost:without_thread=True
boost:without_timer=True
boost:without_type_erasure=True
boost:without_wave=True
boost:zlib=False
boost:zstd=False

[generators]
make
pkg_config
~~~
I'm running

    conan install . --build=missing

which downloads `boost/1.70.0@conan/stable` from the conan-center. The build output contains
~~~
    "g++-6"   -fvisibility-inlines-hidden -fPIC -m64 -pthread -O3 -finline-functions -Wno-inline -Wall -fvisibility=hidden -Wno-variadic-macros -fPIC -DBOOST_ALL_NO_LIB=1 -DBOOST_TEST_DYN_LINK=1 -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0  -I"." -c -o "<home>/.conan/data/boost/1.70.0/conan/stable/build/685479e0084de2de97e40201a3bc9bade33bcf83/boost/bin.v2/libs/test/build/gcc-6/rls/thrd-mlt/vsblt-hdn/cpp_main.o" "libs/test/src/cpp_main.cpp"
~~~
I.e. the package recipe chose to set `-D_GLIBCXX_USE_CXX11_ABI=0`. After the build has finished the following `boost.pc` has been generated:
~~~
prefix=<home>/.conan/data/boost/1.70.0/conan/stable/package/685479e0084de2de97e40201a3bc9bade33bcf83
libdir=${prefix}/lib
includedir=${prefix}/include

Name: boost
Description: Boost provides free peer-reviewed portable C++ source libraries
Version: 1.70.0
Libs: -L${libdir} -lboost_unit_test_framework  -lpthread  -Wl,-rpath="${libdir}"
Cflags: -I${includedir} -DBOOST_ALL_DYN_LINK
~~~
As you can see, the `Cflags` entry contains `-DBOOST_ALL_DYN_LINK`, but not the used `-D_GLIBCXX_USE_CXX11_ABI=0`.

When I build my project with `g++-6.3.0` using the output of `pkg-config --cflags` and `pkg-config --libs` I get the following linking error:
~~~
.../test_cast_model.o: In function `_GLOBAL__sub_I_test_cast_model.cpp':
test_cast_model.cpp:(.text.startup+0xc5): undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name[abi:cxx11](boost::unit_test::basic_cstring<char const>)'
collect2: error: ld returned 1 exit status
~~~
When I manually add `-D_GLIBCXX_USE_CXX11_ABI=0` to the `CPPFLAGS` every links fine.

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.70.0**
* Operating System: **Linux**
* Operation System Version: **Debian 9**
* Compiler+version: **gcc-6.3.0**
* Conan version: **conan 1.14.4**
* Python version: **python 3.5.3**

### Proposed fix

To fix this problem I'd propose to add the definition of `_GLIBCXX_USE_CXX11_ABI` to the CFLAGS or CPPFLAGS in the Conan package recipe.

**Comment by Expander** [comment]
Just for reference, the following quick hack fixed the issue for me:
~~~
diff --git a/conanfile.py b/conanfile.py
index 0faa79a..5a63448 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -841,6 +841,11 @@ class BoostConan(ConanFile):
         if self.options.filesystem_no_deprecated:
             self.cpp_info.defines.append("BOOST_FILESYSTEM_NO_DEPRECATED")
 
+        if str(self.settings.compiler.libcxx) == "libstdc++":
+            self.cpp_info.defines.append("_GLIBCXX_USE_CXX11_ABI=0")
+        elif str(self.settings.compiler.libcxx) == "libstdc++11":
+            self.cpp_info.defines.append("_GLIBCXX_USE_CXX11_ABI=1")
+
         if not self.options.header_only:
             if self.options.error_code_header_only:
                 self.cpp_info.defines.append("BOOST_ERROR_CODE_HEADER_ONLY")

~~~
I think this patch could be improved, but at least it is a prove of concept for a fix.

Best regards,
Alex

**Comment by Expander** [comment]
I've now understood, that the boost package recipe uses `_GLIBCXX_USE_CXX11_ABI=0` to build boost on my machine, because my conan default profile reads
~~~
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=6
compiler.libcxx=libstdc++
build_type=Release
[options]
[build_requires]
[env]
~~~

So, I can workaround the issue by building boost via

    conan install . --build=missing -s compiler.libcxx=libstdc++11

However, I don't think this is optimal in the long run, because it requires the conan/boost user to know about the ABI issue of gcc and to know how to tweak conan create a compatible boost build. It would be much better if the boost package recipe would simply pass the used `CFLAGS` to the generator output (`boost.pc`, `conanbuildinfo.mak`, etc.).

If you prefer, I can prepare a refined patch/pull request.

**Comment by SSE4** [comment]
@Expander  yes please, PRs are always welcomed

**Comment by Expander** [comment]
I've refined the patch and created the pull request #183.
Since I'm not a conan expert, please carefully review my proposed change. :)
