### ISSUE TITLE
zlib: add GCC 8 & Clang 6

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#21]
### Package Details (Include if Applicable)
* Package Name/Version: **zlib/1.2.11@conan/stable**
* Operating System: **Linux**
* Compiler+version: **gcc-8.1, clang-6.0**
* Docker image: **lasote/conangcc8, lasote/conanclang60**

### Steps to reproduce (Include if Applicable)

please add GCC 8 & Clang 6 packages for zlib:

```
zlib/1.2.11@conan/stable: WARN: Can't find a 'zlib/1.2.11@conan/stable' package for the specified options and settings:
- Settings: arch=x86, build_type=Release, compiler=gcc, compiler.version=8, os=Linux
- Options: shared=False
- Package ID: c8223c48cc12489c105032ef6d1b3023532d22bd
```
```
zlib/1.2.11@conan/stable: WARN: Can't find a 'zlib/1.2.11@conan/stable' package for the specified options and settings:
- Settings: arch=x86, build_type=Release, compiler=clang, compiler.version=6.0, os=Linux
- Options: shared=False
- Package ID: 53bfe98e7c9ebae022aa252c74a10f09cc4898b0
```

/cc @lasote @danimtb

**Comment by lasote** [comment]
Pushed to testing branch: 
https://travis-ci.org/conan-community/conan-zlib
https://ci.appveyor.com/project/lasote/conan-zlib-7h7rb

If everything is ok I will push to release.
Please, ping me if I forgot about it 😖

**Comment by lasote** [comment]
Pushed to release, the new packages should appear in the following minutes.

**Comment by lasote** [comment]
Done!
