### ISSUE TITLE
[OpenCV] Unable to use sfm due to undefined reference errors.

### ISSUE THREAD

**Issue by arkjedrz** [conan-community/community#210]
Hello,
I would like to report that it is impossible to use sfm module due to undefined references (for example on cv::sfm::triangulatePoints). I have no issues with e.g. xfeatures2d. I tried to manually modify conanfile.py and add missing "sfm" to "opencv_libs", that changed undefined function from cv::sfm::triangulatePoints to 
`/home/arek/.conan/data/opencv/4.0.1/conan/stable/package/48c2c4d59e17b38982cf76475dbbdad3bfb31010/lib/libopencv_sfm.a(projection.cpp.o): In function cv::sfm::KRtFromProjection(cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::_OutputArray const&)':
projection.cpp:(.text._ZN2cv3sfm17KRtFromProjectionERKNS_11_InputArrayERKNS_12_OutputArrayES6_S6_+0x98a): undefined reference to libmv::KRt_From_P(Eigen::Matrix<double, 3, 4, 0, 3, 4> const&, Eigen::Matrix<double, 3, 3, 0, 3, 3>*, Eigen::Matrix<double, 3, 3, 0, 3, 3>*, Eigen::Matrix<double, 3, 1, 0, 3, 1>*)'
projection.cpp:(.text._ZN2cv3sfm17KRtFromProjectionERKNS_11_InputArrayERKNS_12_OutputArrayES6_S6_+0x148e): undefined reference to libmv::KRt_From_P(Eigen::Matrix<double, 3, 4, 0, 3, 4> const&, Eigen::Matrix<double, 3, 3, 0, 3, 3>*, Eigen::Matrix<double, 3, 3, 0, 3, 3>*, Eigen::Matrix<double, 3, 1, 0, 3, 1>*)'
collect2: error: ld returned 1 exit status`

Of course, I have enabled contrib and nonfree flags. Everything is compiled successfully. I checked compilation logs for broken dependencies, but there are no issues. Also, I modified conanfile.py to enforce example compilation - examples are working.

* Package Name/Version: **opencv/4.0.1@conan/stable**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04 LTS**
* Compiler+version: **gcc-7.4.0**
* Conan version: **conan 1.15.0**
* Python version: **python 3.6.7**

**Comment by SSE4** [comment]
I am getting internal compiler errors on GCC 7, trying with another compiler

**Comment by SSE4** [comment]
@arkjedrz okay, seems like I have managed to build it locally with these changes: https://github.com/conan-community/conan-opencv/commit/5b6889ba8090942b747d8654dacd48acd11931a2
please give a new try and lemme know

**Comment by arkjedrz** [comment]
What I currently get while trying to compile OpenCV 4.1.0 with contrib
```
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.3.4 in /usr/include/eigen3
-- Found required Ceres dependency: glog
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/gflags/gflags-targets.cmake:37 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: gflags_nothreads_static

  Targets not yet defined:
  gflags_shared;gflags_nothreads_shared;gflags_static

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/gflags/gflags-config.cmake:10 (include)
  /usr/local/lib/cmake/Ceres/FindGflags.cmake:348 (find_package)
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:252 (find_package)
  contrib/modules/sfm/CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/arek/.conan/data/opencv/4.1.0/conan/stable/build/12b74712fcc7a6d7ec9dbc443d1ae353aee67c3d/build_subfolder/CMakeFiles/CMakeOutput.log".
See also "/home/arek/.conan/data/opencv/4.1.0/conan/stable/build/12b74712fcc7a6d7ec9dbc443d1ae353aee67c3d/build_subfolder/CMakeFiles/CMakeError.log".
```

**Comment by SSE4** [comment]
okay, I think the problem is that OpenCV finds versions from the distro instead of conan packages, that might be an issue.

**Comment by SSE4** [comment]
@arkjedrz may you check version 4.1.1? I've added some changes for `gflags`: https://github.com/conan-community/conan-opencv/commit/86919ce38e778a498367b39af32e2b719d0b063b

**Comment by dab0bby** [comment]
During build with `conan-opencv v4.1.1` with nonfree and contrib enabled. Thats the error message i receive during compilation. maybe thats a possible error source: 

`Module opencv_sfm disabled because the following dependencies are not found: Glog/Gflags`

**Comment by arkjedrz** [comment]
> @arkjedrz may you check version 4.1.1? I've added some changes for `gflags`: [conan-community/conan-opencv@86919ce](https://github.com/conan-community/conan-opencv/commit/86919ce38e778a498367b39af32e2b719d0b063b)

I'm very sorry, I'm currently unable to check it, since I currently don't have an access to this machine I was working on.
I will check it in the future.

**Comment by SSE4** [comment]
@dab0bby do you have a full log? also, what is your environment?

**Comment by dab0bby** [comment]
@SSE4 
Environment:
```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
```
(Using Windows10). The same happens for Release also.

conanfile.txt:
```
[requires]
opencv/4.1.1@conan/stable
zlib/1.2.11@conan/stable

[options]
opencv:shared=True
opencv:freetype=False
opencv:openexr=False
opencv:contrib=True
opencv:nonfree=True

[generators]
cmake

[imports]
bin, *.dll -> ./bin # Copies all dll files from packages bin folder to my "bin" folder
lib, *.dylib* -> ./bin # Copies all dylib files from packages lib folder to my "bin" folder
```

**Comment by Cyberdr8gon** [comment]
Running into the same issue with opencv/4.1.1 on windows10

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
