### ISSUE TITLE
[OpenCV] Error in package_info() when installing opencv

### ISSUE THREAD

**Issue by skatzl** [conan-community/community#211]
Hello everybody,

I'm getting an error when trying to install opencv with conan from conan-center with the following settings:

Conan profile:

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

Conanfile.txt (here with opencv3.4.5., but same issue with other versions):
```
[requires]
opencv/3.4.5@conan/stable

[generators]
cmake 
```

Output from console (error only, the full output is attatched in 
[conanOpencvError_consoleOutput.log](https://github.com/conan-io/conan/files/3211904/conanOpencvError_consoleOutput.log)
):
```
opencv/3.4.5@conan/stable: Downloaded package revision 0
ERROR: opencv/3.4.5@conan/stable: Error in package_info() method, line 257
        self.add_libraries_from_pc('gtk+-3.0')
while calling 'add_libraries_from_pc', line 227
        libs = [lib[2:] for lib in pkg_config.libs_only_l]  # cut -l prefix
        ConanException: pkg-config command ['pkg-config', '--libs-only-l', 'gtk+-3.0', '--print-errors'] failed with error: Command 'pkg-config --libs-only-l gtk+-3.0 --print-errors' returned non-zero exit status 1.
```
Seems to me to be a bug. Or are there any other suggestions?

Cheers, katzl
[conanOpencvError_consoleOutput.log](https://github.com/conan-community/community/files/3212175/conanOpencvError_consoleOutput.log)

**Comment by SSE4** [comment]
yeah, you may try to add this: `-o opencv:gtk=None`

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
