### ISSUE TITLE
[OpenSSL] Unable to build on Windows

### ISSUE THREAD

**Issue by wouterbeek** [conan-community/community#212]
### Description of Problem, Request, or Question

I'm unable to build OpenSSL on Windows (MSVC).  The build does succeed on my Linux box (GCC9).  See the full logs below for the error message.

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.1.1a**
* Operating System: **Windows**
* Operation System Version: **Windows 10 1809**
* Compiler+version: **MSVC 19.21.27702.2 for x86**
* Conan version: **conan 1.15.1**
* Python version: **python 3.7.3**

# Profile

```
>conan profile show default
Configuration for profile default:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
[options]
[build_requires]
[env]
```

### Build logs (Include if Available)

```
> conan install OpenSSL/1.1.1a@conan/stable --build missing

# LOTS OF LOG LINES REMOVED TO SATISFY GITHUB'S MAX LINES REQUIREMENT.

        lib /nologo /out:libcrypto.lib @C:\Users\woute\AppData\Local\Temp\nm41F1.tmp
crypto\aes\aes_cfb.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX86\x86\lib.EXE"' : return code '0x458'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
OpenSSL/1.1.1a@conan/stable:
OpenSSL/1.1.1a@conan/stable: ERROR: Package 'd140711d95cc16a85766a8fc3a551dfafe84cf63' build failed
OpenSSL/1.1.1a@conan/stable: WARN: Build folder C:\Users\woute\.conan\data\OpenSSL\1.1.1a\conan\stable\build\d140711d95cc16a85766a8fc3a551dfafe84cf63
ERROR: OpenSSL/1.1.1a@conan/stable: Error in build() method, line 87
        self.visual_build()
while calling 'visual_build', line 305
        self.run_in_src("nmake build_libs")
while calling 'run_in_src', line 103
        self.run(command, win_bash=win_bash, output=buf)
        ConanException: Error 2 while executing nmake build_libs
```

**Comment by SSE4** [comment]
seems like something with vcvars, are you running this in Visual Studio command prompt?

**Comment by wouterbeek** [comment]
Yes, this was indeed run from the VS command prompt.  I'm not sure what vcvars are.  Is there some command that I can run that would reveal information that is useful to you?

**Comment by SSE4** [comment]
vcvars are just small batch (.bat) files within visual studio installation to setup Visual Studio environment for command line builds. Visual Studio command prompts are just shortcuts to these batch files. there are few of them, e.g. x86 native, x64 native, x86_6 cross command prompts. it seems like you're building for x86_64, but running x86 native command prompt. can you confirm that? if so, can you try running from the x64 native command prompt?

**Comment by wouterbeek** [comment]
Installing from within the "x64 Native Tools Command Prompt for VS 2019" command-line indeed works.  Thanks for suggesting the fix!
