### ISSUE TITLE
[openssl] Add 1.0.2s, 1.1.0k and 1.1.1c

### ISSUE THREAD

**Issue by Croydon** [conan-community/community#213]
https://www.openssl.org/news/openssl-1.0.2-notes.html
https://www.openssl.org/news/openssl-1.1.0-notes.html
https://www.openssl.org/news/openssl-1.1.1-notes.html

Thanks!

**Comment by SSE4** [comment]
cool!

**Comment by SSE4** [comment]
https://github.com/conan-community/conan-openssl/tree/release/1.1.1c
https://github.com/conan-community/conan-openssl/tree/release/1.1.0k
https://github.com/conan-community/conan-openssl/tree/release/1.0.2s
CI will take some time

**Comment by Croydon** [comment]
Some builds failed due to timeouts 

https://ci.appveyor.com/project/ConanCIintegration/conan-openssl/builds/24975938
https://travis-ci.org/conan-community/conan-openssl/jobs/539135155

Otherwise we already started to use some of these versions in Bincrafters, so I guess it's good to go

**Comment by SSE4** [comment]
thanks, I've restarted them

**Comment by Croydon** [comment]
https://ci.appveyor.com/project/ConanCIintegration/conan-openssl/builds/24895785

this needs restarting as well

**Comment by SSE4** [comment]
restarted as well. I am closing this issue, as branches have been added.
