### ISSUE TITLE
Is -DBOOST_USE_STATIC_LIBS needed?

### ISSUE THREAD

**Issue by sourcedelica** [conan-community/community#214]
### Description of Problem, Request, or Question
Is `-DBOOST_USE_STATIC_LIBS` needed?

### Package Details (Include if Applicable)
`boost/1.67.0@conan/stable`

The recipe currently adds
```
self.cpp_info.defines.append("BOOST_USE_STATIC_LIBS")
```

Googling around I can't find where that is used by Boost.  Am I missing something?  I also looked in all of the Boost headers from this package.

**Comment by SSE4** [comment]
it's here for 4 years: https://github.com/conan-community/conan-boost/commit/e6e8bf07487096203aabf7904afc0f984d7efbbe (added by @lasote )
it seems to be CMake's define, not compiler's one: https://cmake.org/cmake/help/v3.14/module/FindBoost.html
I believe it could be safely removed

**Comment by SSE4** [comment]
@sourcedelica applied: https://github.com/conan-community/conan-boost/commit/652800a56bb8c9b059006a30dfd77165cba86896

**Comment by sourcedelica** [comment]
Thanks!
