### ISSUE TITLE
OpenSSL issue with ./Configure call

### ISSUE THREAD

**Issue by kevswims** [conan-community/community#215]
I am trying to cross compile OpenSSL 1.1.1b using conan with a yocto generated toolchain for armv8. 

When OpenSSL runs it fails at the configure line:
```
OpenSSL/1.1.1b@conan/stable: ------RUNNING-------
bash -l -c -o pipefail "./Configure linux-aarch64 -O3 -s -fPIC --with-zlib-include=\"/home/build/.conan/data/zlib/1.2.11/conan/stable/package/8fd38d381db52e2495321ce060b9f457656f6c8f/include\" --with-zlib-lib=\"/home/build/.conan/data/zlib/1.2.11/conan/stable/package/8fd38d381db52e2495321ce060b9f457656f6c8f/lib\" no-asm | while read line; do printf \"%c\" .; done"
```
After this it gets stuck in a bash shell and I have to call exit a couple of times before conan will continue and tell me that the job has failed.
```
bash -l -c -o pipefail "make depend | while read line; do printf \"%c\" .; done"build@the-box:~/.conan/data/OpenSSL/1.1.1b/conan/stable/build/d087bb4c3c7c3f4a137522e70c08ecf812238cea/openssl-1.1.1b$ exi
t
exit
OpenSSL/1.1.1b@conan/stable:
OpenSSL/1.1.1b@conan/stable: WARN: ----------MAKE OPENSSL 1.1.1b-------------
OpenSSL/1.1.1b@conan/stable: ------RUNNING-------
make -j8make: *** No targets specified and no makefile found.  Stop.
OpenSSL/1.1.1b@conan/stable:
OpenSSL/1.1.1b@conan/stable: ERROR: Package 'd087bb4c3c7c3f4a137522e70c08ecf812238cea' build failed
OpenSSL/1.1.1b@conan/stable: WARN: Build folder /home/build/.conan/data/OpenSSL/1.1.1b/conan/stable/build/d087bb4c3c7c3f4a137522e70c08ecf812238cea
ERROR: OpenSSL/1.1.1b@conan/stable: Error in build() method, line 85
        self.unix_build()
while calling 'unix_build', line 239
        self.run_in_src("make -j%s" % tools.cpu_count(), show_output=True, win_bash=win_bash)
while calling 'run_in_src', line 105
        self.run(command, win_bash=win_bash, output=buf)
        ConanException: Error 512 while executing make -j8
```
### Package Details (Include if Applicable)
* Package Name/Version: OpenSSL/1.1.1b
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**
* Compiler+version: gcc-7.3 for cross compiling for armv8

* Conan version: **conan 1.15.1**
* Python version: **python 3.5.3**

I'm not sure if there is an actual error in the package or if I am just missing an option that is required for this to run correctly.

**Comment by kevswims** [comment]
Update:

I figured I would try and isolate this down some more. I tried building the project natively on my system and the build fails at the same step without using the cross compiler toolchain.

**Comment by SSE4** [comment]
@kevswims okay, please lemme know if you need some help

**Comment by kevswims** [comment]
I am going to close this out for now, it does not seem to be an issue with the package itself and I cannot reproduce this on any other system. If I come up with a solution I will post it.
