### ISSUE TITLE
[boost] Bootstrap should not use CC/CXX variables from environment

### ISSUE THREAD

**Issue by jasal82** [conan-community/community#218]
I'm trying to cross-compile boost with a custom toolchain (Yocto SDK) which I encapsulated into a Conan package used as `build_requires`. That package sets a lot of `env_info` variables in its `package_info()` method matching the ones exported in the environment setup script of the SDK. It also sets `CC` and `CXX` variables to point to the cross-compilers (`arm-oe-linux-gnueabi-gcc`, etc). Now when I try to build the boost package the `bootstrap.sh` script uses these compilers for bootstrapping which is wrong because the `b2` executable must be built for the host.

I think the boost package's `build()` function should clear the `CC` and `CXX` variables (and probably also `CFLAGS` and `CXXFLAGS`) for the scope of the bootstrap process, if that is possible. It would be even better if the environment from that toolchain package could be ignored altogether in that specific case.

**Comment by jasal82** [comment]
The following patch fixes the problem:

```diff
diff --git a/conanfile.py b/conanfile.py
index f821535..a678df1 100644
--- a/conanfile.py
+++ b/conanfile.py
@@ -771,7 +771,8 @@ class BoostConan(ConanFile):
                         option = "" if tools.os_info.is_windows else "-with-toolset="
                         cmd = "%s %s%s" % (bootstrap, option, self._get_boostrap_toolset())
                     self.output.info(cmd)
-                    self.run(cmd)
+                    with tools.environment_append({"CC": None, "CXX": None, "CFLAGS": None, "CXXFLAGS": None}):
+                        self.run(cmd)
 
         except Exception as exc:
             self.output.warn(str(exc))
```

**Comment by SSE4** [comment]
@jasal82 cool, could you open PR with your patch?

**Comment by jasal82** [comment]
I created a PR https://github.com/conan-community/conan-boost/pull/182

**Comment by SSE4** [comment]
I am closing as changes were merged
