### ISSUE TITLE
libalsa: add GCC 8 & Clang 6

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#22]
### Package Details (Include if Applicable)
* Package Name/Version: **libalsa/1.1.5@conan/stable**
* Operating System: **Linux**
* Compiler+version: **gcc-8.1, clang-6.0**
* Docker image: **lasote/conangcc8, lasote/conanclang60**

### Steps to reproduce (Include if Applicable)

please add GCC 8 & Clang 6 packages for libalsa

**Comment by lasote** [comment]
Pushed to testing!

**Comment by lasote** [comment]
Pushed to release, the new packages should appear in the following minutes.

**Comment by lasote** [comment]
Done!

**Comment by SSE4** [comment]
works, thank you!
