### ISSUE TITLE
[paho-cpp] Conan package is not compatible with cmake_paths generator

### ISSUE THREAD

**Issue by vogoltsov** [conan-community/community#221]
### Description of Problem, Request, or Question
Due to the nature of my project, I am not able to use Conan during target builds. Specifically, I am using YoctoProject to build an embedded OS image based on Linux.
I want to manage my dependencies in development environment using Conan to make life easier for developers.
Because of that, we are using Conan's `cmake_paths` generator. I allows us to continue using `find_package()` directives to locate all libraries thus staying compatible with compiling in target environment.
But when we use the `cmake_paths` with the `paho-cpp` library, linking a target against `PahoMqttCpp::paho-mqttpp3-static` results in error while generating a project:
```
CMake Error at CMakeLists.txt:16 (add_executable):
  Target "static-no-ssl-cmake_paths" links to target "CONAN_PKG::paho-c" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```
I started digging a bit deeper and discovered that while the Paho MQTT C library is referenced as `PahoMqttC` in `FindPahoMqttC.cmake`, this referenced is later replaced with `CONAN_PKG::paho-c` while building the Conan package (see [0001-find-paho-c.patch](https://github.com/conan-community/conan-paho-cpp/blob/stable/1.0.1/0001-find-paho-c.patch) ).
I have tried replacing `CONAN_PKG::paho-c` with `PahoMqttC` in `PahoMqttCppTargets.cmake` (in the package install directory) - and everything seems to be working find. Furthermore, the `cmake` generator is also working with this change.
Is there any reason to replace `PahoMqttC` with `CONAN_PKG::paho-c`? Maybe we could reverse this patch?

### Package Details
* Package Name/Version: **paho-cpp/1.0.1**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 19.04**
* Compiler+version: **gcc-8.3.0**
* Conan version: **conan 1.16.0**
* Python version: **python 3.7.3**

### Steps to reproduce (Include if Applicable)
I have created a couple of example project to demonstrate the issue: https://github.com/vogoltsov/paho-mqtt-cpp-conan-cmake-paths-example

**Comment by SSE4** [comment]
yes, I think it needs some rework, as `CONAN_PKG::pago-c` target depends on `cmake` generator which you aren't using right now

**Comment by vogoltsov** [comment]
Ok, I have fixed the issue and published the fix to my branch: https://github.com/vogoltsov/conan-paho-cpp/tree/fix-cmake-paths-generator
I haven't open a PR cause I am currently discussing this possibility of including them into `paho.mqtt.cpp`. I would appreciate it if you could take a look and review the fixes, thank you.

**Comment by uilianries** [comment]
The PR is here: https://github.com/conan-community/conan-paho-cpp/pull/5 

At least, we can compare what is necessary to fix it.
