### ISSUE TITLE
[boost] detect contradictory 'without_*' option usage

### ISSUE THREAD

**Issue by theodelrieu** [conan-community/community#223]
### Description of Problem, Request, or Question

Hello,

I'm having some trouble with the `without_*` options:

Let's say I want to build Boost without `boost_system`, so I run `conan install boost/1.70.0@conan/stable -o:without_system=True`.

Obviously, `boost_system` is a dependency of almost every Boost library, so it still gets built, but the `without_system=True` option is still a part of the package ID...

I'd suggest detecting this kind of incoherence, and warn that the option will be overriden with the correct value.

What do you think?

**Comment by SSE4** [comment]
I think feature is useful, however, it might be tricky to implement, probably requires boost dep to build the graph, or alternatively, parse boost b2 output
feel free to submit PR implementing this feature

**Comment by jgsogo** [comment]
Hi, @theodelrieu. I've talked about this issue with @SSE4 and some other related issues have arisen that are more related to Conan itself than to recipes.

For this concrete problem, I think that the options and the package should be congruent. I mean, the `with/without_xxxx` should match what it is in the package or what it is accessible for the user in the consumer libraries or applications.

If we have a recipe that looks like something like this:

```python
class ConanFile:

    options = "with_cmp01", "with_cmp02", "with_cmp03",
              "with_cmp11", "with_cmp12", "with_cmp13", "with_cmp14",
              "with_cmp21", "with_cmp22"
    default_options = # All options =True
```

with the following internal graph:

![image](https://user-images.githubusercontent.com/1406456/59771464-09eaf700-92aa-11e9-8b10-45edcdecbcc8.png)

Then we would need to write something like:

```python
    def configure(self):
        if not self.options.with_cmp01:
            self.options.with_cmp11 = False
            self.options.with_cmp12 = False
        if not self.options.with_cmp02:
            self.options.with_cmp14 = False
        if not self.options.with_cmp03:
            self.options.with_cmp13 = False

        if not self.options.with_cmp11:
            self.options.with_cmp21 = False
        if not self.options.with_cmp12:
            self.options.with_cmp21 = False
        if not self.options.with_cmp13:
            self.options.with_cmp21 = False
            self.options.with_cmp22 = False
        if not self.options.with_cmp14:
            self.options.with_cmp22 = False

        # Maybe inform the user too about the final libraries. 
        self.output.info("Libraries available in this package will be: ....")
```

then:

```python
    def build(self):
        # Translate the options to the proper flags to the build_system, or anything needed if
        #  we are just repackaging
```

And again, it appears the complexity of the package info:

```python
    def package_info(self):
        libs = []  # Only libs here, but probably the same for includedirs, defines,...
        if self.options.with_cmp22:
            libs.append("cmp22")
        if self.options.with_cmp21:
            libs.append("cmp21")
        if self.options.with_cmp14:
            libs.append("cmp14")
        if self.options.with_cmp13:
            libs.append("cmp13")
        if self.options.with_cmp12:
            libs.append("cmp12")
        if self.options.with_cmp11:
            libs.append("cmp11")
        if self.options.with_cmp03:
            libs.append("cmp03")
        if self.options.with_cmp02:
            libs.append("cmp02")
        if self.options.with_cmp01:
            libs.append("cmp01")
```

All of this can be somehow abstracted away into a helper file like the one you added to the `Qt`library ([qtmodules.conf](https://github.com/bincrafters/conan-qt/blob/testing/5.12.4/qtmodules.conf))... but **there are three things that will increase exponentially the complexity of the package_info method** and I'm not sure if those can be abstracted away easily:
 * different `cpp_info` depending on some settings values: `Windows`, `Mac`, `Linux`,...
 * recipes targeting several versions: some libraries (like `boost`) adds and remove libraries between versions or change the dependencies between them.
 * the new _components feature_ (https://github.com/conan-io/conan/pull/5242) that will allow (and recommend) the recipe writer to model the internal dependencies among the libraries.

Right now the `package_info` for the boost library is 80 lines long ([link](https://github.com/conan-community/conan-boost/blob/66ecfc8cd0ed70a411a3b7de3e767ff27b15c0d2/conanfile.py#L817)) and it doesn't handle any logic related to versions and nothing about _components_. I'm afraid (I know some of you too) about how this is going to scale and about maintainability.

I think this is something worth reading by everyone: @conan-community/barbarians  @uilianries

**Comment by SSE4** [comment]
moved to https://github.com/conan-io/conan-center-index/issues/97
