### ISSUE TITLE
OpenCV 4.1.0 target links to opencv_dnn but library is not built by package

### ISSUE THREAD

**Issue by planetmarshall** [conan-community/community#224]
### Description of Problem, Request, or Question

The DNN module is not built by the conan package but the generated CONAN_PKG::opencv target requests it.

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.1.0**
* Operating System: **Linux**
* Compiler+version: **clang 8**
* Docker image: **conanio/clang8:1.15.1**
* Conan version: **conan 1.15.1**

### Steps to reproduce (Include if Applicable)

Build and install the opencv package with the following non-default options:

```
'opencv:tiff': False,
'opencv:dc1394': False,
'opencv:harfbuzz': False,
'opencv:jasper': False,
'opencv:jpegturbo': False,
'opencv:nonfree': False,
'opencv:openexr': False,
'opencv:protobuf': False,
'opencv:webp': False,
'opencv:freetype': False,
'opencv:gtk': None
```

### Build logs (Include if Available)

OpenCV reports the following:
```
 OpenCV modules:
2235 --     To be built:                 calib3d core features2d flann gapi highgui imgcodecs imgproc ml objdetect photo stitching ts video videoio
2236 --     Disabled:                    java_bindings_generator python_bindings_generator world
2237 --     Disabled by dependency:      -
2238 --     Unavailable:                 dnn java js python2 python3
2239 --     Applications:                perf_tests
2240 --     Documentation:               NO
2241 --     Non-free algorithms:         NO
```

[pipelineLog-29.txt](https://github.com/conan-community/community/files/3294310/pipelineLog-29.txt)

**Comment by SSE4** [comment]
yes, dnn depends on protobuf, need to remove it from the list of modules if protobuf is disabled

**Comment by SSE4** [comment]
@planetmarshall applied: https://github.com/conan-community/conan-opencv/commit/39e373036821fb406ded34f2df69e31ff6882024#diff-2b1d42f71f22b7ea0412d7602dec166f
please give an another try and lemme know

**Comment by planetmarshall** [comment]
Yes this is working for me now - Thanks.
