### ISSUE TITLE
[boost] remove boost_asm_buildflags.patch

### ISSUE THREAD

**Issue by Johnnyxy** [conan-community/community#225]
Hi there,
I am building Boost 1.70.0 and the official source already contains the ASM patch. Thus the patch file can be removed from the conan recipe and conan-recipe-repository.

current output
---------------
>WARN: patches\boost_build_asmflags.patch: already patched  b'tools/build/src/tools/common.jam'
WARN: patches\boost_build_asmflags.patch: already patched  b'tools/build/src/tools/common.py'

**Comment by SSE4** [comment]
@Johnnyxy applied: https://github.com/conan-community/conan-boost/commit/da086e8425de65e6d1b43af55f02dafeb7877120

**Comment by Johnnyxy** [comment]
It works :)
