### ISSUE TITLE
[boost] Building with namespace fails

### ISSUE THREAD

**Issue by firewave** [conan-community/community#226]
### Description of Problem, Request, or Question

See https://github.com/boostorg/boost/issues/282

### Package Details
* Package Name/Version: **boost/1.70**

**Comment by SSE4** [comment]
@firewave applied: https://github.com/conan-community/conan-boost/commit/9a79f1ce0d12b1e9fcbde88701e4beaf8c277b5f#diff-2b1d42f71f22b7ea0412d7602dec166f
please give an another try and lemme know

**Comment by firewave** [comment]
It also requires https://github.com/boostorg/boost/commit/d0586e88122f41cd5ac9666db70c37d6f0fc7480 to be added as a patch for it to work completely.

**Comment by SSE4** [comment]
@firewave okay, lemme add this one as well

**Comment by SSE4** [comment]
@firewave also applied: https://github.com/conan-community/conan-boost/commit/66ecfc8cd0ed70a411a3b7de3e767ff27b15c0d2

**Comment by firewave** [comment]
Thanks. Looks identical to what I had to do locally. I think this can be closed.

**Comment by SSE4** [comment]
confirmed as fixed, closing

**Comment by firewave** [comment]
The library is actually called `boost_install` (mind the underscore). Sorry for not recognizing this earlier - didn't use the official recipe yet.

**Comment by SSE4** [comment]
good catch, fixed at https://github.com/conan-community/conan-boost/commit/324826ca7ac0c50fc221d51bb8bc8222f972f6e5
