### ISSUE TITLE
[OpenSSL] Cannot create OpenSSL packages for Android. (With possible fix/workaround)

### ISSUE THREAD

**Issue by xaqq** [conan-community/community#228]
### Creating OpenSSL package for Android fails

I was in the process of upgrading dependencies for our Android application.
There I am using the latest Android NDK (r20) and latest Conan OpenSSL recipe.
I was previously building with r18b and OpenSSL 1.0.2r successfully.

### Package Details (Include if Applicable)
* Package Name/Version: **openssl/1.1.1c**
* Operating System: **Linux**
* Operation System Version: **Debian 9.6 (Stretch)**
* Compiler+version: **clang 8**
* Docker image: **Custom debian image with Android NDK r20 installed.**
* Conan version: **conan 1.15.0**
* Python version: **python 2.7.0**

Running `conan create --profile my/profile . x/y` fails. The failure looked very weird and it took me a while to understand what was happening.
It seems like settings an absolute path to the compiler is not supported by the underlying OpenSSL build script. So things like `CC=/path/to/ndk/.../clang` did not work.

Therefore I went with `CC=clang` and `PATH=[/path/to/ndk/.../prebuilt/.../bin`] in the conan profile file. While running `which clang` obviously found my compiler, the `conan create` command failed when invoking OpenSSL's `Configure` script. It complained that it was not able to find clang.

### Possible solution

Looking at the recipe source code, the `Configure` is invoked through `bash -l -c ...`. Note the `-l` which means it is a login shell. In turns, this seems to mean that bash will reload some of my environment variable, including `$PATH`.
My temporary workaround is to remove `-l` from the command invocation. I don't really grasp the pros/cons of `-l` in this context.

I am also not sure at which point Conan is supposed to "inject" environment variable etc.

**Comment by SSE4** [comment]
same issue as https://github.com/conan-community/community/issues/161
Android detection is very unreliable in OpenSSL
will be fixed soon in the next iteration of OpenSSL recipe clean up.

**Comment by SSE4** [comment]
closing as duplicate, we have #161 to track
