### ISSUE TITLE
libalsa/1.1.5 for gcc 8

### ISSUE THREAD

**Issue by madebr** [conan-community/community#23]
### Description of Problem, Request, or Question
libalsa/1.1.5 has no packages for gcc 8

### Package Details (Include if Applicable)
* Package Name/Version: **libalsa/1.1.5**
* Operating System: **Fedora 28**
* Compiler+version: **gcc-8**

### Steps to reproduce (Include if Applicable)

conan install libalsa/1.1.5@bincrafters/stable

https://github.com/bincrafters/community/issues/330

**Comment by danimtb** [comment]
Already done in commit: https://github.com/conan-community/conan-libalsa/commit/1e2c8e61ed4f0beba10455129cc143b057539c9a

Thanks!
