### ISSUE TITLE
[OpenSSL] package the openssl binary

### ISSUE THREAD

**Issue by firewave** [conan-community/community#230]
### Description of Problem, Request, or Question
The `openssl` binary is built with the recipe but not packaged at all. Would be quite helpful to have it available - preferably in the `bin` folder.

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.1.1c**

**Comment by uilianries** [comment]
We keep library and executable separated, usually we don't mix two things at same package.

For instance, we have protobuf and protoc_installer, which separates protobuf libs and protoc binary

Maybe we need to create a new package for openssl_installer. WDYT @SSE4 @danimtb ?

**Comment by SSE4** [comment]
@firewave fixed in new recipe: https://github.com/conan-community/conan-openssl/commit/6f3f5b8feb8c447a4fe7a3005bdd90f2a7784786
please give a new try and lemme know

**Comment by SSE4** [comment]
I am closing as changes were applied. please open new issue, if needed.
