### ISSUE TITLE
[OpenSSL] Add ppc32 arch support

### ISSUE THREAD

**Issue by rarvidson** [conan-community/community#231]
### Description of Problem, Request, or Question
Arch ppc32 was added to settings.yml but is not supported by OpenSSL. Would like to add support for ppc32.

### Package Details (Include if Applicable)
* Package Name/Version: OpenSSL/1.1.1c
* Operating System: Linux
* Operation System Version: Ubuntu 19.04
* Compiler+version: gcc-5.3
* Conan version: conan 1.15.0
* Python version: python 2.7.16

### Steps to reproduce (Include if Applicable)
Use a profile that specifies ppc32 for arch like the following...

[settings]
os=Linux
arch=ppc32
compiler=gcc
compiler.version=5
compiler.libcxx=libstdc++11
cppstd=14
arch_build=x86_64
os_build=Linux

### Build logs (Include if Available)
OpenSSL/1.1.1c@conan/stable: ERROR: Package 'e11a4027fec8e254e8ddfb2f9ba2977fdf3b5576' build failed
OpenSSL/1.1.1c@conan/stable: WARN: Build folder /home/user/.conan/data/OpenSSL/1.1.1c/conan/stable/build/e11a4027fec8e254e8ddfb2f9ba2977fdf3b5576
ERROR: OpenSSL/1.1.1c@conan/stable: Error in build() method, line 93
	self.unix_build()
while calling 'unix_build', line 247
	target = self._get_target()
while calling '_get_target', line 194
	raise Exception("Unsupported arch '%s' for Linux" % self.arch)
	Exception: Unsupported arch 'ppc32' for Linux

**Comment by rarvidson** [comment]
I was able to build the package by adding
```"ppc32": "linux-ppc"```
as another target under _get_target

**Comment by SSE4** [comment]
yes, I am going to add this to the next version of the recipe

**Comment by SSE4** [comment]
@rarvidson fixed in new recipe: https://github.com/conan-community/conan-openssl/commit/6f3f5b8feb8c447a4fe7a3005bdd90f2a7784786
please give a new try and lemme know

**Comment by rarvidson** [comment]
@SSE4 looks like it worked, thank you

**Comment by SSE4** [comment]
confirmed as fixed, closing
