### ISSUE TITLE
[OpenSSL] remove obsolete options

### ISSUE THREAD

**Issue by firewave** [conan-community/community#234]
### Description of Problem, Request, or Question

In the latest OpenSSL 1.1.1 the following options are disabled by default and can be removed: `no_zlib`, `no_md2`, `no_rc4`, `no_rc5`

See https://github.com/openssl/openssl/blob/262c00882a2fd7cf16672bf467a86f75b4098a7c/Configure#L449

Also as zlib is no longer needed the dependency can be removed as well.
### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.1.1c**

**Comment by Croydon** [comment]
These options still exists upstream. I see no reason to remove them. Conan options should expose upstream options.

**Comment by firewave** [comment]
The problem is, that they are disabled by default in OpenSSL, but the recipe treats them like they are enabled by default and offers options to disable them. And since the options are used inside the recipe that leads to inverted logic. So you would need `zlib`, `md2`, etc. options in the recipe instead.

Example:
- `zlib` is disabled by default in OpenSSL - meaning implicitly `no-zlib` is set
- `no_zip` is `False` in the recipe so it assumes `zlib` is implicitly set
- as the option is used it thinks it needs the zlib dependency which is unnecessary for a default OpenSSL 1.1.1

**Comment by SSE4** [comment]
then it's just matter of changing defaults in conanfile, probably only for 1.1.1x

**Comment by firewave** [comment]
Then you also need to pass them as `zlib`, `md2`, etc. to the `Configure` script if they are set to `False`.

**Comment by SSE4** [comment]
okay, next thing to revamp is options:
- set default options according to the OpenSSL version
- remove outdated options which don't have any effect or don't exist completely
I'll try to update recipe and let you know

**Comment by SSE4** [comment]
moved to https://github.com/conan-io/conan-center-index/issues/108
