### ISSUE TITLE
[OpenSSL] disable building of tests

### ISSUE THREAD

**Issue by firewave** [conan-community/community#235]
### Description of Problem, Request, or Question

The tests are built by default which is totally necessary for a conan build. This can be disabled by adding `no-tests` to the built flags.

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.1.1c**

**Comment by SSE4** [comment]
@firewave fixed in new recipe: https://github.com/conan-community/conan-openssl/commit/6f3f5b8feb8c447a4fe7a3005bdd90f2a7784786
please give a try and lemme know

**Comment by SSE4** [comment]
I am closing as changes were applied. please open new issue, if needed.
