### ISSUE TITLE
[OpenSSL] Broken on Windows with Clang and MinGW

### ISSUE THREAD

**Issue by LunarWatcher** [conan-community/community#236]
### Description of Problem, Request, or Question

Very related to #188, with the main difference that I'm using Clang (**not** clang-cl) with MinGW. The stacktrace is actually identical:

```
ERROR: OpenSSL/1.0.2o@conan/stable: Error in build() method, line 124
        raise Exception("Unsupported operating system: %s" % self.settings.os)
        Exception: Unsupported operating system: Windows
```

Same issue with 1.1.1c and 1.1.1b. 

```
ERROR: OpenSSL/1.1.1c@conan/stable: Error in build() method, line 101
        raise Exception("Unsupported operating system: %s" % self.settings.os)
        Exception: Unsupported operating system: Windows
```

Other packages compile fine (off the top of my head, fmt and I think zlib) with my setup as well, including packages from conan/stable (so this seems to be specific to this package, and maybe others I haven't tried). 

### Package Details (Include if Applicable)
* Package Name/Version: OpenSSL, at least 1.0.2o and 1.1.1c, though presumably all versions
* Operating System: **Windows**
* Operation System Version: **Windows 10, 1803**
* Compiler+version: **Clang 8.0.0**
* Conan version: **conan 1.16.1**
* Python version: **Python 3.7.3**

### Steps to reproduce (Include if Applicable)

1. Install MinGW, grab the packages necessary to build (MinGW packages (some are listed [here](https://stackoverflow.com/a/38434410/6296561), as well as `pacman -Sy base-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-glew mingw-w64-x86_64-SDL2`. Not sure if I've left out any - I've installed a lot to get the environment working), Python 3, pip, and Conan)
2. Install Clang from the website, targeting Windows, add the install directory to MinGW's path
3. ```
   export CXX=clang++ -target x86_64-pc-windows-gnu
   export CC=clang -target x86_64-pc-windows-gnu
   ```
4. From the MinGW terminal: `conan install OpenSSL/1.1.1c@conan/stable --build missing`

**Comment by SSE4** [comment]
similar issue: https://github.com/bincrafters/community/issues/680
we need a reliable way to distinguish `clang` vs `clang-cl` in conan.

**Comment by SSE4** [comment]
moved to https://github.com/conan-io/conan-center-index/issues/96
