### ISSUE TITLE
[QNX] support building Boost for QNX

### ISSUE THREAD

**Issue by Johnnyxy** [conan-community/community#238]
Hi,
as Conan does support QNX Neutrino and its compiler QCC the conan-boost recipe could add support for QNX too. This thread should be the discussion for problems with the intercorporation between Conan, Boost and QNX.

I already have a fully working recipe locally (based on the official Conan-Boost-recipe) for QNX SDP 6.5 and QNX SDP 7.0 but to make those changes public I would like to hear opinions on how to approach certain problems to solve them in a more generic way.

obstacle - architecture
-----------------------
One obstacle is the architecture strings that Conan supplies and what QNX expects.
For example:

| Conan | maps to | QNX       |
|-------|:-------:|-----------|
| armv7 | ->      | armv7le   |
| armv8 | ->      | aarch64le |

The [Conan docs](https://docs.conan.io/en/latest/reference/config_files/settings.yml.html#architectures) define ```armv8``` as
> armv8: The ARM 64 bit and 32 bit compatible version 8 architecture. It covers only the aarch64 instruction set.

Now one could use this as concrete mapping from ```armv8``` to ```aarch64``` but this still is missing the ```little endian``` notation.

As QNX 6.5 and 7.0 do not specify a different endianess setting except ```little endian``` (le) the mapping could be hardcoded to always postfix a ```le```-specifier ```armv7le```.
Now what tickles me is that the [ARM architecture](https://en.wikipedia.org/wiki/ARM_architecture) supports both endians as ```bi-endianess```. Thus this allows to run software with different endianess-specifications.
This would make it difficult to map only to one endianess (e.g. armv7 -> armv7le) as maybe this could change in the future.

I am not that expert for ARM programming. Maybe someone with more insights could answer the following:
Based on ARM's ```bi-endianess```:
1. Where is the border where one can switch the endianess? E.g. one endianess per process? I read that the endianess can be changed on the fly, even though this is not supported by all controllers or common at all.
2.  Can one compile a library for one endianess and link it with another library or binary which was compiled with an other endianess?

solution - architecture
-----------------------
1. Ignore any endianess and hardcode the architecture mapping like in the table shown above.
2. Introduce changes to the architecture settings in the Conan ```settings.yml```.
This would imply a change for all Boost-recipe users to provide the QNX architectures in their ```settings.yml```. Such a topic has been discussed in the Conan issue tracker ([see here](https://github.com/conan-io/conan/issues/5359)). 
Adding the architectures is possible but this would introduce confusion about the usage of e.g. ```armv8``` until now.
And changing the string was reasonable declined after all because of breaking changes.

...

**Comment by SSE4** [comment]
@Johnnyxy I think this one is outdated then: https://github.com/conan-community/community/issues/78. should I close older issue?

**Comment by Johnnyxy** [comment]
The old one is outdated anyway as the original source of the "bug" is the behaviour of CMake. It got bloated by additional discussions not really related to the initial problem it has been opened for :).
From my point of view the https://github.com/conan-community/community/issues/78 has been *solved* by the workaround specified there.

**Comment by danimtb** [comment]
I think the simplest solution is to map the current armv8 and armv7 architectures in Conan to the corresponding ones in QNX (just one endianess supported as @Johnnyxy reported). As exposed in https://github.com/conan-io/conan/issues/5359, this is a problem due to the lack of standardization in the naming and the impossibility of the general settings in Conan to model every single configuration for open source packages.

@Johnnyxy If you feel we should document the QNX support in the documentation giving specific advice regarding this issue, please open an issue there and we could open a new section in te integrations

**Comment by Johnnyxy** [comment]
@SSE4 
I have opened a topic at the Conan issue tracker. This will influence the amount of changes to the boost recipe. Maybe you could head over there and revise/review it.

**Comment by SSE4** [comment]
the topic: https://github.com/conan-io/conan/issues/5463

**Comment by SSE4** [comment]
moved to https://github.com/conan-io/conan-center-index/issues/98
