### ISSUE TITLE
[OpenSSL] "Shared" option has no effect

### ISSUE THREAD

**Issue by firewave** [conan-community/community#239]
### Description of Problem, Request, or Question

The `Shared` option is not applied and no `shared` or `no-shared` are being used.

The code that handles this is only in the Windows case in `_get_flags()` which is probably an intendation issue. This issue was already present in 1.0.2 recipes -  see https://github.com/conan-community/conan-openssl/blob/5dc24b0706e1cb653bdc96be8de443dbf802e24e/conanfile.py#L163

A side effect of this is, that the produced `openssl` binary requires a shared object although it should not.

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.1.1c**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Compiler+version: **gcc-5.4**
* Conan version: **conan 1.6.1**
* Python version: **python 3.5.2**

**Comment by uilianries** [comment]
hi @firewave ! Could you update the **package details** section? It's important to reproduce your scenario.

**Comment by firewave** [comment]
What information are missing (beside a typo I just fixed)?

**Comment by uilianries** [comment]
Are you running Conan 1.6.1 ?

**Comment by firewave** [comment]
That's the version on the sys I looked it up. It will also happen with the latest version.

The error is in the recipe though - it's quite obvious if you just look at the code I referenced.

**Comment by uilianries** [comment]
> A side effect of this is, that the produced openssl binary requires a shared object although it should not.

Which openssl binary? The OpenSSL package only exports libraries.

**Comment by firewave** [comment]
Doing this exposes another problem when building on MacOS:

```
ERROR: OpenSSL/1.1.1c@local/testing: Error in build() method, line 106
	self.unix_build()
while calling 'unix_build', line 298
	self._patch_makefile()
while calling '_patch_makefile', line 266
	self._patch_install_name()
while calling '_patch_install_name', line 340
	strict=self.in_local_cache)
	ConanException: replace_in_file didn't find pattern '-install_name $(INSTALLTOP)/$(LIBDIR)/' in 'openssl-1.1.1c/Makefile' file.
```

The problem is, that `-install_name` only exists in the Makefile when `darwin-shared` is being used, but the recipe does not check that (as it was always using shared before).

**Comment by SSE4** [comment]
@firewave fixed in new recipe: https://github.com/conan-community/conan-openssl/commit/6f3f5b8feb8c447a4fe7a3005bdd90f2a7784786
please give a try and lemme know

**Comment by SSE4** [comment]
I am closing as changes were applied. please open new issue, if needed.
