### ISSUE TITLE
boost/1.67.0 for gcc 8.1

### ISSUE THREAD

**Issue by madebr** [conan-community/community#24]
### Description of Problem, Request, or Question
No conan packages for gcc 8.1 are available.

`conan install boost/1.67.0@conan/stable` fails

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.67.0**
* Operating System: **Fedora Linux 28**
* Compiler+version: **gcc-8.1.1**

**Comment by lasote** [comment]
gcc 8 builds support has been merged and will be ready in the following hours when the CI ends.

- https://ci.appveyor.com/project/lasote/conan-boost-su63s/build/1.0.68
- https://travis-ci.org/conan-community/conan-boost

Feel free to write with any issue.
