### ISSUE TITLE
[OpenSSL] Build fails with VS 2019

### ISSUE THREAD

**Issue by cstratopoulos** [conan-community/community#243]
### Description of Problem, Request, or Question
Building OpenSSL from source fails on VS2019, seemingly due to issues with the perl version.

These issues may point to a solution:
https://github.com/openssl/openssl/issues/264
https://github.com/microsoft/vcpkg/issues/1573

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2n@conan/stable**
* Operating System: **Windows**
* Operation System Version: **Windows Server 2019**
* Compiler+version: **Visual Studio 2019 (16.1.3+29009.5*)*
* Conan version: **conan 1.17.0**
* Python version: **python 3.6.8**

### Build logs (Include if Available)
See the failing step on https://dev.azure.com/ossiaco/ossiaco/_build/results?buildId=3519&view=logs

The OpenSSL build begins around line 600.

Note in particular:
> This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-msys-thread-multi

and (line numbers)
>687: Can't open perl script "ms../crypto/perlasm/x86_64-xlate.pl": No such file or directory

> 1056: Can't open perl script "cryptoperlasm/x86_64-xlate.pl": No such file or directory

The `crypto/perlasm` vs `cryptoperlasm` appears to be just as alluded to in the linked issues.

Comparing from the same build for VS2017, it appears that a cached binary of OpenSSL is available, i.e., this is only occurring with VS2019 and `--build missing`.

**Comment by cstratopoulos** [comment]
It turns out the machine above has multiple versions of perl in path: one from the git install and one from StrawberryPerl. I was able to workaround the issue by manually altering `PATH` so that the StrawberryPerl version was preferred. 

Before, `Get-Command perl` would return `C:\Program Files\Git\usr\bin\perl.exe`
> This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-msys-thread-multi

After:
> This is perl 5, version 30, subversion 0 (v5.30.0) built for MSWin32-x64-multi-thread

**Comment by SSE4** [comment]
@cstratopoulos I've updated recipe significantly: https://github.com/conan-community/conan-openssl/commit/6f3f5b8feb8c447a4fe7a3005bdd90f2a7784786
 could you possibly give a new try and lemme know if it still happens?

**Comment by cstratopoulos** [comment]
@SSE4 so, yes and no. I tried removing my StrawberryPerl workaround and queuing a build and things went totally fine. However I looked in the logs and found that OpenSSL didn't seem to be built. I'm fuzzy on Conan specifics, but maybe there's now a binary package that matched my recipe?

Anyway I added `--build OpenSSL/*` to the invocation and the recipe failed, albeit with a more helpful error message:
```
Configuring OpenSSL version 1.1.1c (0x1010103fL) for VC-conan-Debug-Windows-x86_64-Visual Studio-16
Using os-specific seed configuration

******************************************************************************
This perl implementation doesn't produce Windows like paths (with backward
slash directory separators).  Please use an implementation that matches your
building platform.

This Perl version: 5.26.2 for x86_64-msys-thread-multi
******************************************************************************
OpenSSL/1.1.1c@conan/stable: 
OpenSSL/1.1.1c@conan/stable: ERROR: Package '6acf24cd4adf2df742e006cc0e5f0329e3b6e60b' build failed
```

Failed build [here](https://dev.azure.com/ossiaco/ossiaco/_build/results?buildId=3575), successful build (with OpenSSL not actually being built) [here](https://dev.azure.com/ossiaco/ossiaco/_build/results?buildId=3573).

**Comment by SSE4** [comment]
@cstratopoulos I've added changes to enforce strawberry perl usage: https://github.com/conan-community/conan-openssl/commit/9d7ff89d245fcb263ace26b1f525537fe098c70b
could you possibly try to update and build one more time?

**Comment by cstratopoulos** [comment]
@SSE4 lgtm! https://dev.azure.com/ossiaco/ossiaco/_build/results?buildId=3577

**Comment by SSE4** [comment]
confirmed as fixed, closing
