### ISSUE TITLE
[OpenSSL] Use only one recipe

### ISSUE THREAD

**Issue by uilianries** [conan-community/community#244]
### Description of Problem, Request, or Question

Since [OpenSSL/1.1.1c](https://github.com/conan-community/conan-openssl/blob/release/1.1.1c/conanfile.py) is able to be re-used for 1.1.0 and 1.0.2, I would say we could remove some branches and keep only 1.1.1c, renaming it to another name like 1.x.x

/cc @SSE4 

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.1.1c**

**Comment by SSE4** [comment]
I'd keep them for a while, just in case if I missed some changes during the merge

**Comment by uilianries** [comment]
Yeah, but need to freeze/archive them. Otherwise we will receive PRs to the wrong target. I mean, we can keep both cases, but it will be duplicated work.

**Comment by SSE4** [comment]
I've just archived all of them. they could be easily restored, if needed.

**Comment by uilianries** [comment]
nice! Thanks!
