### ISSUE TITLE
[OpenSSL] OS incorrectly identified as Emscripten for OpenSSL/1.0.2r

### ISSUE THREAD

**Issue by EricFalkenberg** [conan-community/community#247]
### Description of Problem, Request, or Question
Building OpenSSL/1.0.2r on MacOS High Sierra, Mojave and RHEL7 produces an error stating:
```
     [exec] ERROR: OpenSSL/1.0.2r@conan/stable: Error in build() method, line 492
     [exec] 	self._make()
     [exec] while calling '_make', line 461
     [exec] 	args = " ".join(self._configure_args)
     [exec] while calling '_configure_args', line 340
     [exec] 	if self.settings.os == "Emscripten":
     [exec] 	ConanException: Invalid setting 'Emscripten' is not a valid 'settings.os' value.
     [exec] Possible values are ['Android', 'Arduino', 'FreeBSD', 'Linux', 'Macos', 'SunOS', 'Windows', 'WindowsStore', 'iOS', 'tvOS', 'watchOS']
     [exec] Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
     [exec] CMake Error at CMake/Components/CommonComponent/conan.cmake:399 (message):
     [exec]   Conan install failed='1'
     [exec] Call Stack (most recent call first):
     [exec]   CMake/Components/CommonComponent/conan.cmake:485 (conan_cmake_install)
     [exec]   CMake/Components/CommonComponent/CMakeLists.txt:262 (conan_cmake_run)
     [exec]
     [exec]
     [exec] -- Configuring incomplete, errors occurred!
     [exec] See also "/Users/***/build/CMakeFiles/CMakeOutput.log".
```
My problem is not that 1.0.2r doesnt support Emscripten but rather that I am not on Emscripten to start.
```
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=9.1
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
```
These are my settings.

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2r**
* Operating System: **MacOS & RHEL**
* Operation System Version: **10.13 & 10.14**
* Compiler+version: **apple-clang 9.1 & gcc5.3**
* Docker image: **n/a**
* Conan version: **conan 1.14.0**
* Python version: **python 3.7.3**

### Steps to reproduce (Include if Applicable)
Building on multiple MacOS machines has begun to fail starting today.

**Comment by SSE4** [comment]
@EricFalkenberg you need to update your `settings.yml` as [documented](http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting). please add `Emscripten` to the `settings.yml` and give an another try.

**Comment by EricFalkenberg** [comment]
That did not solve the issue. After adding that setting I got the same error. It seems to be the case that that version of OpenSSL doesn't support Emscripten. Further, I'm not trying to target that OS so I don't know why its happening.

**Comment by EricFalkenberg** [comment]
That got me further in the build process but it still seems to be building for `Emscripten` and fails due to that
```
     [exec] ERROR: OpenSSL/1.0.2r@conan/stable: Error in build() method, line 492
     [exec] 	self._make()
     [exec] while calling '_make', line 484
     [exec] 	self._run_make()
     [exec] while calling '_run_make', line 447
     [exec] 	self.run(" ".join(command), win_bash=self._win_bash)
     [exec] 	ConanException: Error 512 while executing /usr/bin/make -j1
     [exec] CMake Error at CMake/Components/CommonComponent/conan.cmake:399 (message):
     [exec]   Conan install failed='1'
     [exec] Call Stack (most recent call first):
     [exec]   CMake/Components/CommonComponent/conan.cmake:485 (conan_cmake_install)
     [exec]   CMake/Components/CommonComponent/CMakeLists.txt:262 (conan_cmake_run)
     [exec]
     [exec]
     [exec] -- Configuring incomplete, errors occurred!
```

**Comment by SSE4** [comment]
I don't see anything related to the Emscripten in the last log. could you possibly provide a full build log?

**Comment by SSE4** [comment]
@EricFalkenberg this shouldn't happen any longer, I've fixed condition for the Emscripten: https://github.com/conan-community/conan-openssl/commit/6f10a90f45580830a242d56d55e9ed2a68f25fca
