### ISSUE TITLE
[openssl] Rename default branch

### ISSUE THREAD

**Issue by uilianries** [conan-community/community#249]
### Description of Problem, Request, or Question

Since OpenSSL package is using only one branch for all versions, users may be confused about the branch name, which is "release/1.1.1c".

We could rename it to "release/1.x.x" or "master". However, some projects like Conan are using OpenSSL for testing. We need to check if there is some side-effect when renaming that branch.

/cc @SSE4

**Comment by SSE4** [comment]
I've created `master` branch which is default now
`release/1.1.1c` is still alive just in case someone uses it

**Comment by uilianries** [comment]
thanks so much!
