### ISSUE TITLE
Package LibSodium

### ISSUE THREAD

**Issue by luminitadaraban** [conan-community/community#25]
### Description of Problem, Request, or Question
Can you please package LibSodium?
https://github.com/jedisct1/libsodium

### Package Details (Include if Applicable)
* Package Name/Version: **libsodium/1.0.3** or higher
* Operating System: **Linux** and **Windows**
* Compiler+version: **gcc-7** and **VS14** and **VS15**

**Comment by danimtb** [comment]
Hi @luminitadaraban,

Thanks a lot for your request. I have searched an there is already a good recipe for libsodium from binrafters: https://github.com/bincrafters/conan-libsodium

The recipe is updated to latest version 1.0.16. There are even packages for the configurations you need here: https://bintray.com/bincrafters/public-conan/libsodium%3Abincrafters/1.0.16%3Astable

I f you want to try it, these are the steps:

1. COnfigure bincrafters remote in your conan client
```
$ conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
```
2. Install the reference of libsodium and conan will search in all remotes and install it from bincrafters':
```
$ conan install libsodium/1.0.16@bincrafters/stable
```

For library requests, please open an issue in https://github.com/conan-io/wishlist as this issue tracker is only intended for conan-community repos. Thanks a lot and hope it helps!
