### ISSUE TITLE
[Boost] Running `build` step separately fails

### ISSUE THREAD

**Issue by vector-of-bool** [conan-community/community#250]
### Description of Problem, Request, or Question

The `build()` method subscripts `self.requires` to obtain the full ref to the required packages. This only works if the `install` step is run in the same process (as with `conan create`), as the `install` step will populate the `self.requires` dict with the necessary keys.

Work-around: Call `self.requirements()` within `build()`, and it "just works" (maybe by accident?)

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.70.0**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Python version: **python 3.6.2**
* Conan version: 1.19.0-dev (occurs as far back as I bothered to try: 1.16.0, probably further.)

### Steps to reproduce (Include if Applicable)

Run the `install`, `source`, and `build` steps separately. The `build` step will raise a `KeyError` as the `zlib` key is not present in `self.requires` (the `self.requires` dict is empty).

### Build logs (Include if Available)

No build logs available where I write this, but the issue occurs in `create_user_config_jam()` as part of `build()` with `reference = str(self.requires[name])`.

**Comment by SSE4** [comment]
thanks for the report, I've just pushed the fix: https://github.com/conan-community/conan-boost/commit/4624bd96cd0635efdbefd9b147dc6bde8eb212c7

**Comment by SSE4** [comment]
I am closing as changes were applied. please open new issue, if needed.
