### ISSUE TITLE
[OpenCV] Contrib default value used for deleting options

### ISSUE THREAD

**Issue by henriauer** [conan-community/community#251]
### Description of Problem, Request, or Question
OpenCV (file: conanfile.py) option configuration does not work when Contrib is set to True. Freetype option is always deleted because Contrib option value is still using default (False)

Problem was likely introduced in:
commit 72b92f6503f6b6f7bff26dd02ed7436a2c155b34

### Steps to reproduce (Include if Applicable)
set conan:contrib=True in conanfile

### Build logs (Include if Available)
opencv/4.1.0@conan/stable: Downloaded recipe revision 0
ERROR: opencv/4.1.0@conan/stable: Error in requirements() method, line 164
	if self.options.freetype:
	ConanException: 'options.freetype' doesn't exist
Possible options are ['shared', 'fPIC', 'contrib', 'jpeg', 'jpegturbo', 'tiff', 'webp', 'png', 'jasper', 'openexr', 'gtk', 'nonfree', 'dc1394', 'carotene', 'cuda', 'protobuf', 'eigen', 'gstreamer']

**Comment by omaralvarez** [comment]
I have exactly the same problem. But it did not happen before the update to 4.1.1 I think.

**Comment by henriauer** [comment]
> I have exactly the same problem. But it did not happen before the update to 4.1.1 I think.

Yes can bypass the problem by changing the default value of Contrib to True in conanfile.py file. Then freetype option etc are not deleted.

**Comment by SSE4** [comment]
@henriauer @omaralvarez thanks for the report, I've applied a fix: https://github.com/conan-community/conan-opencv/commit/8ec16812e34cca0178b9f0846660e620d198b16f
please give a new try and lemme know

**Comment by henriauer** [comment]
@SSE4 fix is working for me with 4.1.1 version.

**Comment by SSE4** [comment]
confirmed as fixed, closing

**Comment by omaralvarez** [comment]
Confirmed, everything ok now!
