### ISSUE TITLE
[paho-c] Problem with cpp_info.libs in SSL-enabled package

### ISSUE THREAD

**Issue by detwiler** [conan-community/community#252]
### Problem with cpp_info.libs in SSL-enabled paho-c package 
When installing the Conan package for paho-c using the option `-o paho-c:SSL=True`, two libraries are installed, an SSL-enabled version (e.g. `paho-mqtt3as`), along with the normal non-SSL library (e.g. `paho-mqtt3a`). [This line](https://github.com/conan-community/conan-paho-c/blob/stable/1.3.0/conanfile.py#L75) in the recipe adds **_both_** libraries to the `cpp_info.libs` for the package. This causes our application to link against the **_non-SSL_** version of the library, even when specifying `-o paho-c:SSL=True`, and therefore it fails at runtime. It seems like only one of the libraries should be included in `cpp_info.libs`, depending on the `paho-c:SSL` selection.

FWIW, [this fixed it for us](https://github.com/detwiler/conan-paho-c/commit/e4f5538888d27ac4234f111a96e328cf1a26fee2) on Linux. We don't have the resources to test on other platforms, but thought we'd share in case it helps.

### Package Details (Include if Applicable)
* Package Name/Version: **paho-c/1.3.0**
* Operating System: **Linux**
* Operation System Version: **Fedora 30**
* Compiler+version: **gcc-9**
* Docker image: **N/A**
* Conan version: **conan 1.18.0**
* Python version: **python 3.7.4**

### Steps to reproduce
```
$ conan install -o paho-c:shared=True -o paho-c:SSL=True --build missing --json >(jq '.installed[] | select(.recipe.id == "paho-c/1.3.0@conan/stable") | .packages[].cpp_info.libs') paho-c/1.3.0@conan/stable >/dev/null
[
  "paho-mqtt3a",
  "paho-mqtt3as",
  "c",
  "dl",
  "pthread"
]
```

**Comment by danimtb** [comment]
Thanks a lot for reporting. Yes, this seems to be an issue in the recipe. We will try to fix it soon.

**Comment by uilianries** [comment]
Actually it's caused by upstream behavior, they install both libraries when SSL is enable. We can patch and install according that option, but I would say we need to open an issue to the author too.

**Comment by uilianries** [comment]
Hi @detwiler !

We merged a new patch with separated install according SSL option. Please, update your local copy and try again

**Comment by detwiler** [comment]
Thanks @uilianries! The new version of the package is working for us.
