### ISSUE TITLE
[boost] Not able to cross compile for Linux/arm

### ISSUE THREAD

**Issue by kwinsch** [conan-community/community#253]
### Description of Problem, Request, or Question
Tried to cross compile the boost package for arm and failed. The compilation aborts with:

```
ERROR: boost/1.70.0@demo/testing: Error in build() method, line 421
	self.run(full_command)
	ConanException: Error 1 while executing /home/user/.conan/data/boost/1.70.0/demo/testing/source/boost_1_70_0/tools/build/b2 -mfloat-abi=hard target-os=linux architecture=arm address-model=32 binary-format=elf abi=aapcs --layout=system -sBOOST_BUILD_PATH=/home/user/.conan/data/boost/1.70.0/demo/testing/source/boost_1_70_0/tools/build -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 threading=multi link=static variant=release --without-python toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=1 cxxflags="-fPIC -mcpu=cortex-a5 -mfpu=neon-vfpv4 --mfloat-abi=hard" -j4 --abbreviate-paths -d2 --debug-configuration --build-dir="/home/user/.conan/data/boost/1.70.0/annax/testing/build/6d53ac5f4723d1ff68e9cc7a543dd2401412be50"
```

After some investigation, I don't exaclty found the root cause. It could be upstream or in the way the conanfile configures the build system. At least there is an error in the build of the context module, which is written in assembler. (Upstream ticket referenced). During compilation of the context module, the buildsystem does not include all required CXXFLAGS to get the file compiled. The required assembler commands are only valid in the context of a defined vfp implementation. In my case, the flag -mfpu=neon-vfpv4 MUST be included to sucessfully build the files. The required flags are specified and exposed in conan profile.

Cross compiling for other architectures are working as expected.

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.70.0**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**
* Compiler+version: **gcc-8.3.0**
* Conan version: **conan 1.18.0**
* Python version: **python 3.6.8**

### Steps to reproduce (Include if Applicable)
`conan install boost/1.70.0@conan/stable -pr=PicoCOMA5 --build boost`

### Build logs (Include if Available)

- [boost_buildlog.txt](https://github.com/conan-community/community/files/3476480/boost_buildlog.txt)
- Toolchain recipe: https://gist.github.com/kwinsch/596d0b5a7ef72a8140b47a3b556e43d6
- Conan profile: https://gist.github.com/kwinsch/58636a6258c2fdd1ab2fd97053de8824
- Upstream ticket: [boost/context issue](https://github.com/boostorg/context/issues/114)

**Comment by SSE4** [comment]
@kwinsch may you try to set `ASFLAGS=-mfpu=neon-vfpv4` in your profile?

**Comment by kwinsch** [comment]
@SSE4 You are right. With the ASFLAGS = -mfpu=neon-vfpv4, the packages compiles without a problem. This solution works for the conan boost package 1.64.0 through v1.70.0.

I finaly set the ASFLAGS to:
`ASFLAGS = -mcpu=cortex-a5 -mfpu=neon-vfpv4 -mfloat-abi=hard `

Many thanks for the quick reply and the obvious hint!
