### ISSUE TITLE
[boost] (cross compiling) cc1plus: warning: SSE instruction set disabled, using 387 arithmetics

### ISSUE THREAD

**Issue by kwinsch** [conan-community/community#254]
### Description of Problem, Request, or Question

When cross compiling for x86, conan or the boost build process is introducing the `-march=i686` flag, which disables all optimizations declared in the CXXFLAGS environment variable.

I would expect, that the global CXXFLAGS  `-march=silvermont -mtune=silvermont -mfpmath=sse`, which is declared in the conan profile, are respected.

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.70.0**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**
* Compiler+version: **gcc-8.3.0**
* Conan version: **conan 1.18.0**
* Python version: **python 3.6.8**

### Steps to reproduce (Include if Applicable)
`conan install boost/1.70.0@conan/stable -pr=custom-x86-profile --build boost`

### Build logs (Include if Available)

`
"/home/user/.conan/data/gcc-i486-linux-musl/0.1/annax/testing/package/44fcf6b9a7fb86b2586303e3db40189d3b511830/bin/i486-linux-musl-g++"   -fvisibility-inlines-hidden -g -O3 -march=silvermont -mtune=silvermont -mfpmath=sse -fstack-protector-strong -Wformat -Werror=format-security -flto -funroll-loops -m32 -pthread -O3 -finline-functions -Wno-inline -Wall -fvisibility=hidden -march=i686 -fPIC -DBOOST_ALL_NO_LIB=1 -DBOOST_DISABLE_ASSERTS -DBOOST_FIBERS_SOURCE -DBOOST_FILESYSTEM_STATIC_LINK=1 -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=1  -I"." -c -o "/home/user/.conan/data/boost/1.70.0/conan/stable/build/907549d9952c74c7de4aab5b4f1a201a01d51623/boost/bin.v2/libs/fiber/build/gcc-8/rls/lnk-sttc/thrd-mlt/vsblt-hdn/context.o" "libs/fiber/src/context.cpp"
`

**Comment by SSE4** [comment]
we never set `-match=i686` from the recipe
it's coming from https://github.com/boostorg/build/blob/9f17722e80fa2a5876f3f26bbf2315aa969f5cd5/src/tools/gcc.jam#L1190
I think it could be specified by b2 flag:
```
Also by default, when building Boost for x86 32-bit targets it will compile for i686 (Pentium Pro) and later CPUs. This can be changed by specifying the instruction-set property in b2 or bjam command line, for example:

b2 variant=release architecture=x86 instruction-set=i486 stage
```

**Comment by SSE4** [comment]
so, proposed solution to implement:
1. check CXXFLAGS for `-march=<arch>`
2. if found, add b2 argument `instruction=set=<arch>`

**Comment by SSE4** [comment]
@kwinsch unfortunately, `silvermont` is not known instruction set value for boost.build: https://github.com/boostorg/build/blob/develop/src/tools/gcc.jam#L1191. probably, it makes sense to request one?

**Comment by kwinsch** [comment]
@SSE4 I came to the same conclusion this morning. silvermont, which includes Bay Trail, is not defined. I don't know why they duplicate the list from gcc and not just add the -march supplied by CXXFLAGS. The way they do it is error prone and will automatically break from time to time. I will ask upstream about the issue. Many thanks for the input.
