### ISSUE TITLE
[OpenCV] Need add with-ffmpeg option to opencv

### ISSUE THREAD

**Issue by bvnp43** [conan-community/community#255]
### Description of Problem, Request, or Question

OpenCV support compilation with ffmpeg. It should be added to opencv conan package as well.

### Package Details (Include if Applicable)
* Package Name/Version: **zstd/1.3.3**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Compiler+version: **gcc-5.4**
* Docker image: **conanio/gcc7**
* Conan version: **conan 1.2.0**
* Python version: **python 3.7.0**

**Comment by SSE4** [comment]
@bvnp43 agree, I will add it, right now I am adding ffmpeg 4.2 conan package

**Comment by SSE4** [comment]
@bvnp43 I've added option: https://github.com/conan-community/conan-opencv/commit/a25da52e494ce9951007ab779f3346fa138ecd0b
please give a try and lemme know

**Comment by bvnp43** [comment]
@SSE4 If I set `contrib`, `ffmpeg` to `True` in defaults , I'm getting error

```
pcre/8.41@bincrafters/stable: Downloaded recipe revision 0
ERROR: Conflict in pcre/8.41@bincrafters/stable
    Requirement bzip2/1.0.6@conan/stable conflicts with already defined bzip2/1.0.8@conan/stable
    To change it, override it in your base requirements
```

during `conan create . conan/stable`

**Comment by SSE4** [comment]
@bvnp43 okay, seems like we need to update bzip2 dependencies in some projects...

**Comment by SSE4** [comment]
@bvnp43 could you check one more time? I've corrected pcre2 to use bzip2 1.0.8

**Comment by bvnp43** [comment]
@SSE4 Works fine now, tyvm.

**Comment by SSE4** [comment]
confirmed as fixed, closing
