### ISSUE TITLE
[cmake_installer] not working on conanio/clang8-x86

### ISSUE THREAD

**Issue by osechet** [conan-community/community#256]
### Package Details (Include if Applicable)
* Package Name/Version: **cmake_installer/3.15.2**
* Operating System: **Linux**
* Operation System Version: **N/A**
* Compiler+version: **N/A**
* Docker image: **conanio/clang8-x86**
* Conan version: **conan 1.18.1**
* Python version: **python 3.7.1**

### Steps to reproduce (Include if Applicable)

* Install cmake_installer as a build_require
* Run cmake build and you get the error:
```
cmake: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

### Build logs (Include if Available)

The error is visible here: https://travis-ci.org/osechet/conan-protobuf-1/jobs/569336562

A call to `ldd` gives:
```
ldd /home/conan/.conan/data/cmake_installer/3.15.2/conan/stable/package/445cf80f611c1d1eda08bde2ebc5066218ca9701/bin/cmake
	linux-gate.so.1 (0xf77ab000)
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => not found
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf7775000)
	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xf776b000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf774b000)
	libstdc++.so.6 => /lib/i386-linux-gnu/libstdc++.so.6 (0xf756e000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf746a000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf744c000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf726c000)
	/lib/ld-linux.so.2 (0xf7784000)
```

A look at the system libraries gives:
```
$ ls -l /lib/i386-linux-gnu/libssl.so*
lrwxrwxrwx. 1 root root     13 Apr 17 16:50 /lib/i386-linux-gnu/libssl.so -> libssl.so.1.1
-rw-r--r--. 1 root root 614756 Apr 17 16:50 /lib/i386-linux-gnu/libssl.so.1.1
```

So cmake depends on `libssl.so.1.0.0` when the system only provides a `libssl.so.1.1`.

**Comment by uilianries** [comment]
seems like be a docker image bug. Thanks for reporting, I'll check it.

**Comment by uilianries** [comment]
I can confirm the bug.

**Comment by uilianries** [comment]
I'll check if it's possible building CMake with static libraries, otherwise, I'll update that docker image.

**Comment by uilianries** [comment]
I can't update the docker image because Ubuntu Disco doesn't provide libssl-1.0.0. I'll need to update cmake_installer

**Comment by uilianries** [comment]
@osechet Why do you need cmake_installer if that docker image provides a native cmake ?

**Comment by osechet** [comment]
@uilianries I'm working on a package that depends on cmake_installer to ensure it's working anywhere.

**Comment by uilianries** [comment]
Hi @osechet! I think it's working now. We are using static library link when building CMake, which means it doesn't require any ssl lib from your environment.

Please, update your local copy and try again.

**Comment by osechet** [comment]
Hi @uilianres! It's now working. Thanks.
