### ISSUE TITLE
eigen/3.3.7 needs an option to specify cmake generator or header-only

### ISSUE THREAD

**Issue by alashworth** [conan-community/community#257]
### Description of Problem, Request, or Question

I did some research before submitting this issue and it may be related to https://github.com/conan-io/conan/issues/4590.

When installing Eigen with a MinGW profile, it fails to deduce settings and starts configuring with the CMake Visual Studio generator. This is wrong, since CMake internal find_package calls depend on the generator specification.

I think to work around this, we should be able to manually specify the CMake generator in package options. I guess the package_id() function might need to be updated also? I'm not an expert in Conan. 

### Package Details (Include if Applicable)
* Package Name/Version: **eigen/3.3.7@conan/stable**
* Operating System: **Windows 10 Pro**
* Operation System Version: **10.0.17763 Build 17763**
* Compiler+version: **x86_64-w64-mingw32-g++.exe**
* Conan version: **conan 1.18.1**
* Python version: **python 3.7.3**

### Build logs (Include if Available)
```
eigen/3.3.7@conan/stable: Building your package in C:\Users\andre\.conan\data\eigen\3.3.7\conan\stable\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
eigen/3.3.7@conan/stable: Generator txt created conanbuildinfo.txt
eigen/3.3.7@conan/stable: Calling build()
eigen/3.3.7@conan/stable: WARN: This conanfile has no build step
eigen/3.3.7@conan/stable: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' built
eigen/3.3.7@conan/stable: Build folder C:\Users\andre\.conan\data\eigen\3.3.7\conan\stable\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
eigen/3.3.7@conan/stable: Generated conaninfo.txt
eigen/3.3.7@conan/stable: Generated conanbuildinfo.txt
eigen/3.3.7@conan/stable: Generating the package
eigen/3.3.7@conan/stable: Package folder C:\Users\andre\.conan\data\eigen\3.3.7\conan\stable\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
eigen/3.3.7@conan/stable: Calling package()
eigen/3.3.7@conan/stable: WARN: CMake generator could not be deduced from settings
-- Building for: Visual Studio 15 2017
<omitted>
```

**Comment by uilianries** [comment]
Hi @alashworth !

Could print your current profile?

`conan profile show <profile-name>`

Also, are you installing or building the package? I can't reproduce your error, it's working for me when running with Mingw

My current profile for GCC on Windows is:

```
Configuration for profile gcc7:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.exception=seh
compiler.version=7
compiler.libcxx=libstdc++
compiler.threads=posix
build_type=Release
[options]
[build_requires]
*: mingw_installer/1.0@conan/stable
[env]
```

**Comment by alashworth** [comment]
This is part of an install during a larger conan-orchestrated build.
```
[build_requires]

[settings]
os_build=Windows
os=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=4.9
build_type=Release

[env]
CC="D:/apps/rtools/mingw_64/bin/x86_64-w64-mingw32-gcc-4.9.3.exe"
CXX="D:/apps/rtools/mingw_64/bin/x86_64-w64-mingw32-g++.exe"
```

**Comment by uilianries** [comment]
Can't you use `mingw_installer/1.0@conan/stable` as build_requirement?

**Comment by alashworth** [comment]
No, because I must use a specific collection of tools that are externally provided.

https://cran.r-project.org/bin/windows/Rtools/

**Comment by alashworth** [comment]
Since Eigen is header-only, I am not sure why CMake.configure is being called in the conan script to begin with. All I really need from the package at the most basic level is for it to emulate wget -> tar -xvf -> export include directory path.

**Comment by uilianries** [comment]
I could copy directly all headers from the source folder. But the CMake modules won't be generated. Although, Conan offers cmake_find_package which is able to generate a Findxxx.cmake

**Comment by alashworth** [comment]
The Conan boost package when used with the header only option doesn't do anything but copy sources.  You could have a header-only / no-configuration option as well that you fall back to if the build environment can't be determined or CMake is not present.

I think it is important to support using a header-only library... as a header-only library...

**Comment by uilianries** [comment]
checking again is too simple. Eigen uses cmake to customize its header folders.

**Comment by alashworth** [comment]
CMake is an optional dependency for Eigen. It will work for end-users if they just -I (eigen-include-dir)

See: https://eigen.tuxfamily.org/dox/GettingStarted.html

**Comment by uilianries** [comment]
You could set `CONAN_CMAKE_GENERATOR_PLATFORM=MinGW Makefiles`

https://docs.conan.io/en/latest/reference/env_vars.html#cmake-related-variables

**Comment by uilianries** [comment]
> 
> 
> CMake is an optional dependency for Eigen. It will work for end-users if they just -I (eigen-include-dir)
> 
> See: https://eigen.tuxfamily.org/dox/GettingStarted.html
> 
> I know you want some way to propagate dependencies like BLAS etc, and then you can require a build environment since yes, Eigen does need this to generate the cmake modules. But this should be optional.

I see, I'll try to reproduce the same header structure and avoid cmake

**Comment by alashworth** [comment]
Thanks!

PS: there is a typo here -> https://github.com/conan-community/conan-eigen/blob/6486c14a9ac033067eec6ddd34b35846d189d385/conanfile.py#L16

**Comment by uilianries** [comment]
Thanks for reviewing! 👍

**Comment by uilianries** [comment]
@alashworth I've released a new revision, please, update your local copy and try again. I excluded CMake from the recipe

**Comment by alashworth** [comment]
This fixes my problem, but you deleted CMake generation of FindEigen3.cmake. I think now you will get other users who will raise an issue and complain about not being able to call find_package. The core of the problem is FindEigen3.cmake is a platform specific generated file, so your conanfile.py must define settings(arch, os, ...). 

I still think the best solution is to be like Conan boost and define a header-only option. 

If I get some time in the next week I will write a patch implementing this feature.

**Comment by alashworth** [comment]
I spent some time thinking about how to do this, and it seems I would need to rely on `patch_config_paths` which is an experimental feature in order to correctly export the EigenConfig.cmake  file. I do not want to write code that depends on beta features. In my client project the current configuration where I get an include folder is really all I need.

I guess I only have one other comment but it isn't important. The Conan docs say for header only, you call `self.info.header_only()` which deletes `settings`, `options`, and `requires`. Maybe you could consider doing that to? There is not much point in declaring the Eigen options in Conan unless Conan also installs and builds the dependencies, which the conanfile doesn't currently do. As a header-only library, it is always up to the client to correctly define the header definitions. Eigen also has a lot more options than you currently allow in the package, and I'm sure you don't want to maintain them.

Again, thanks for the prompt fix.
