### ISSUE TITLE
Package Tcl/Tk

### ISSUE THREAD

**Issue by luminitadaraban** [conan-community/community#26]
### Description of Problem, Request, or Question
Can you please package Tcl/Tk?
http://tcl.tk/

### Package Details (Include if Applicable)
* Package Name/Version: **tcl_tk/8.6.8**
* Operating System: **Linux** and **Windows**
* Compiler+version: **gcc-7** and **VS14** and **VS15**

**Comment by danimtb** [comment]
For library requests, please open an issue in https://github.com/conan-io/wishlist as this issue tracker is only intended for conan-community repos. Thanks!
