### ISSUE TITLE
[OpenSSL] 1.0.2r and s build tries to install into /etc/ssl/

### ISSUE THREAD

**Issue by tastytea** [conan-community/community#260]
### Description of Problem, Request, or Question

I need a different openssldir than the default one (#229), so I tried to build OpenSSL with `openssldir=/etc/ssl`. This fails with 1.0.2r and 1.0.2s.

```
installing CA.sh
cp: cannot create regular file '/etc/ssl/misc/CA.sh.new': Permission denied
```

OpenSSL/1.1.0k@conan/stable compiled, but I need 1.0.2*.

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2s**, **OpenSSL/1.0.2r**
* Operating System: **Linux**
* Operation System Version: **Gentoo 2.6**
* Compiler+version: **gcc-8.3**
* Conan version: **conan 1.18.1**
* Python version: **python 3.6.5**

### Steps to reproduce (Include if Applicable)

```
git clone https://schlomp.space/tastytea/conan-openssl_minimal-example.git
cd conan-openssl_minimal-example
mkdir build && cd build
conan install .. --build OpenSSL
```

### Build logs (Include if Available)

[conan-openssl-build.log](https://github.com/conan-community/community/files/3489244/conan-openssl-build.log)

**Comment by SSE4** [comment]
@tastytea but `/etc/ssl` is not world-writable, to install into this one you have to run as root

**Comment by tastytea** [comment]
I don't want to install into `/etc/ssl`, I want OpenSSL to read root certificates from it. If I understand #229 correctly, I have to build OpenSSL with the option `openssldir=/etc/ssl` to achieve that.

This is my first time using Conan so I may be misunderstanding it. But shouldn't Conan prevent packages from writing things outside the Conan path?

**Comment by SSE4** [comment]
conan just invokes the build system, and invokes any commands that underlying build system does. if build system tries to write into some locations, conan will not prevent that (it doesn't sandbox things).
as I understand, `--openssldir` is directory where OpenSSL files are installed (such as certificates)
see also https://wiki.openssl.org/index.php/Compilation_and_Installation#PREFIX_and_OPENSSLDIR

**Comment by tastytea** [comment]
Ah, seems like I thoroughly misunderstood, thank you.

If anyone else comes across this issue looking for a way to set the certificate dir, use the environment variables `SSL_CERT_DIR` or `SSL_CERT_FILE`.
