### ISSUE TITLE
Eigen3 package is missing include directory

### ISSUE THREAD

**Issue by alashworth** [conan-community/community#261]
The Eigen3 package exports the Eigen subdirectory headers, but not the unsupported experimental features. 

See https://bitbucket.org/eigen/eigen/src/default/unsupported/Eigen/.

The exported directory structure should be:

"include/eigen3/Eigen"
"include/eigen3/unsupported"
"incldue/eigen3/signature_of_eigen3_matrix_library" 

And the root include directory should be "include/eigen3"

so that inside a project we can do things like:
#include <unsupported/Eigen/FFT>
#include <Eigen/Dense>

**Comment by alashworth** [comment]
@uilianries

**Comment by alashworth** [comment]
In general all source folders should probably get copied.  This includes the LAPACK and BLAS libraries.

**Comment by alashworth** [comment]
Please consider exporting the whole Eigen source tree. Many legacy programs use "useless" files like signature_of_eigen3_matrix_library in their FindEigen3.cmake files.

**Comment by uilianries** [comment]
Hi @alashworth, thanks for reporting it. I'll take a look on this!

**Comment by uilianries** [comment]
> I just ran make install on a plain Eigen vanilla config. It exports Eigen, signature_of_eigen3_matrix_library, and unsupported.

I only need to update *signature_of_eigen3_matrix_library*.

> Also, consider deleting the Eigen options and setting self.info.header_only(). I've thought about it more and it's just confusing to new people to Conan when they set the option but the package doesn't install the dependencies for them as well. There are also a lot more preprocessor defines that need to be set to fully configure Eigen, and I am sure you don't want to maintain that. At least if it is really header only then users know they are responsible for setting the correct preprocessor defines and linking against the correct libraries.

About the options: I would like removing it, but it could break some users which are using the current revision. I understand your point of view, we have other packages (boost, Qt), which contain a long list of requirements. I can add new options if required, but we usually don't remove options after having them in stable branch.

> I know this is demanding but I am trying to insert Conan into a "legacy" system with the cmake_paths generator. I have to get it to work just like existing system packages since otherwise it will break our FindEigen3.cmake find module. Alternatively don't emulate the CMake install logic, and just copy everything, since Eigen guarantees the folder structure will be identical.

I think the problem is because you are looking for Eigen3, but Conan generates Findeigen.cmake. Conan has a feature under development which will be able to customize the module name.

**Comment by uilianries** [comment]
@alashworth the commit https://github.com/conan-community/conan-eigen/commit/71b008c0d1283b5a7875565660051db2f0e6413b should have fixed all problems.

The CI job https://travis-ci.org/conan-community/conan-eigen/builds/570857509 will upload the new version on Bintray. Let's some minutes.

**Comment by alashworth** [comment]
`cmake_paths` is the Conan generator that doesn't do anything but give you a directory in CMake. E.g. here is my hand-written FindEigen3.cmake:

```
# first check to see if the system has an Eigen3 config available
find_package(Eigen3 3.3 QUIET CONFIG)
if(TARGET Eigen3::Eigen)
    return()
endif()

# else check pkgconfig and conan
find_package(PkgConfig QUIET)
pkg_check_modules(PC_Eigen3 QUIET Eigen3)

find_path(Eigen3_INCLUDE_DIR
        NAMES "signature_of_eigen3_matrix_library"
        HINTS
            ${Eigen3_DIR}
            ${Eigen3_ROOT_DIR}
        PATHS
            ${CONAN_EIGEN_ROOT}
            ${PC_eigen3_INCLUDE_DIRS}
        PATH_SUFFIXES eigen3)

find_file(Eigen3_version_file
        NAME "Eigen/src/Core/util/Macros.h"
        PATHS ${Eigen3_INCLUDE_DIR})

file(STRINGS ${Eigen3_version_file} version_vars
        REGEX "EIGEN_WORLD_VERSION [0-9]|EIGEN_MAJOR_VERSION [0-9]|EIGEN_MINOR_VERSION [0-9]")

list(TRANSFORM version_vars REPLACE "#define EIGEN_(WORLD|MAJOR|MINOR)_VERSION ([0-9])" "\\2")
list(JOIN version_vars "." Eigen3_VERSION)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Eigen3
        REQUIRED_VARS Eigen3_INCLUDE_DIR
        VERSION_VAR Eigen3_VERSION)

if(Eigen3_FOUND)
    set(Eigen3_INCLUDE_DIRS ${Eigen3_INCLUDE_DIR})
    add_library(Eigen3::Eigen INTERFACE IMPORTED)
    target_include_directories(Eigen3::Eigen INTERFACE ${Eigen3_INCLUDE_DIR})
endif()
```

**Comment by uilianries** [comment]
I'll provide a custom FindEigen3.cmake for this recipe.

**Comment by uilianries** [comment]
@alashworth I've added your CMake file: https://github.com/conan-community/conan-eigen/commit/08f3f4e39fa61f20dff8a3bc5dd174049ea87580

**Comment by alashworth** [comment]
!! Shouldn't you copy the official Eigen FindEigen3.cmake?

https://bitbucket.org/eigen/eigen/raw/8071cda5714d7f454205b60b2f851986d53e8f33/cmake/FindEigen3.cmake

**Comment by uilianries** [comment]
Good idea, but I'll need to patch with Conan include path, WDYT ?

**Comment by alashworth** [comment]
I am only familiar with the `cmake_paths` generator; I don't know how the other ones work. If it is `cmake_paths`, the generator already patches `CMAKE_PREFIX_PATH` for us. 

Also, again, you will also need to patch the exported target to reflect the Conan options. (Which is why I think you should make a breaking change and drop support for them). You see in the Eigen cmake directory actually how complicated determining all the dependencies are.

**Comment by uilianries** [comment]
> I am only familiar with the cmake_paths generator; I don't know how the other ones work. If it is cmake_paths, the generator already patches CMAKE_PREFIX_PATH for us.

It will work :)

> Also, again, you will also need to patch the exported target to reflect the Conan options. (Which is why I think you should make a breaking change and drop support for them). You see in the Eigen cmake directory actually how complicated determining all the dependencies are.

Using cmake_paths won't because it's limited. To export all definitions you will need to use cmake generator only. Anyway, I gonna remove ALL options.

**Comment by uilianries** [comment]
@alashworth I think it's okay now: https://github.com/conan-community/conan-eigen/commit/131e04130d898b2960c9d8815cae5e5be7263c3f

**Comment by alashworth** [comment]
Yup, is fixed. Thanks!
