### ISSUE TITLE
[OpenCV] Not building with GTK 3 option

### ISSUE THREAD

**Issue by omaralvarez** [conan-community/community#262]
### Description of Problem, Request, or Question

When I try to build OpenCV with GTK support, it builds but with no GTK.

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.1.1**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**
* Compiler+version: **gcc-7.4.0**
* Conan version: **conan 1.18.1**
* Python version: **python 3.6.8**

### Steps to reproduce

_conanfile.txt_

```ini
[requires]
opencv/4.1.1@conan/stable

[generators]
cmake

[options]
opencv:contrib=True
opencv:nonfree=True
opencv:gtk=3
opencv:glog=False
opencv:gflags=False
opencv:gstreamer=False
```

When OpenCV is compiled:

```
conan install .. --build opencv -s compiler.libcxx=libstdc++11
```

### Build logs

```
-- Checking for module 'gtk+-3.0'
--   Package 'libselinux', required by 'gio-2.0', not found
-- Checking for module 'gtk+-2.0'
--   Package 'libselinux', required by 'gio-2.0', not found
-- Checking for module 'gthread-2.0'
--   Found gthread-2.0, version 2.58.3
```

```
--   GUI: 
--     GTK+:                        NO
--     VTK support:                 NO
```

**Comment by omaralvarez** [comment]
I have also noticed that with the current Eigen recipe sometimes OpenCV does not compile, but I already have added a pull request to fix that in `eigen/3.3.7`. It failed with:

```
/home/mads/gplaza/.conan/data/opencv/4.1.1/conan/stable/build/57186bf17ddd3392314d0ec5cb6c813157525c8c/contrib/modules/rgbd/src/odometry.cpp:21:12: fatal error: unsupported/Eigen/MatrixFunctions: does not exist
#  include <unsupported/Eigen/MatrixFunctions>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
source_subfolder/modules/rgbd/CMakeFiles/opencv_rgbd.dir/build.make:173: recipe for target 'source_subfolder/modules/rgbd/CMakeFiles/opencv_rgbd.dir/src/odometry.cpp.o' failed
```

**Comment by bmanga** [comment]
I managed to get that working in #233, it's not a proper fix but maybe it can be useful to you :)

**Comment by omaralvarez** [comment]
In my case it does not have problems with freetype, it seems that a lib is missing, which is also compiled as a dependency `libselinux`. So not sure if the same fix as in your case is applicable...

**Comment by omaralvarez** [comment]
Any new developments on this? Is it a problem on my end?

**Comment by omaralvarez** [comment]
I have found the problem, a package is missing that glib needs `libselinux-dev`.

**Comment by SSE4** [comment]
was fixed by https://github.com/conan-community/conan-opencv/pull/40
