### ISSUE TITLE
[Boost] Build with segmented-stack option

### ISSUE THREAD

**Issue by Kap1bara** [conan-community/community#264]
Tried to find a way to build boost with segmented-stack support, which is usefull for me in case of usage boost.fiber and boost.coroutine, but couldn't find an easy way to do it, e.g. switching an option in conanfile. I wonder could you add this option feature?

**Comment by SSE4** [comment]
@Kap1bara I've added new option `segmented_stacks`: https://github.com/conan-community/conan-boost/commit/6af8c8b8e263b688c9f8861f1fabfefdd5b8b407

**Comment by Kap1bara** [comment]
@SSE4, Thanks for such a fast decision. So, I've just tried to conan install with new flag. BOOST_USE_SEGMENTED_STACKS became 1, and this is fine. But this simple code fails on linking:
```
#include <boost/fiber/all.hpp>
#include <boost/thread.hpp>

int main()
{
    static_assert(BOOST_USE_SEGMENTED_STACKS);
    boost::thread([]() {
        boost::this_fiber::yield();
    }).join();

    return 0;
}
```
with .conan/data/boost/1.70.0/conan/stable/package/a68c7edf70353018c7f74f29c8118e0608077b25/lib/libboost_fiber.a(context.o): In function `std::_Function_handler<boost::context::detail::fiber_activation_record* (boost::context::detail::fiber_activation_record*&), boost::context::detail::fiber_activation_record::resume_with<boost::context::fiber, boost::fibers::context::suspend_with_cc()::{lambda(boost::context::fiber&&)#1}>(boost::fibers::context::suspend_with_cc()::{lambda(boost::context::fiber&&)#1}&&)::{lambda(boost::context::detail::fiber_activation_record*&)#1}>::_M_invoke(std::_Any_data const&, boost::context::detail::fiber_activation_record*&)':
context.cpp:(.text+0x1a2):` **undefined reference to `boost::context::detail::fiber_activation_record::current()'**
am I doing smth wrong?

**Comment by SSE4** [comment]
sorry, I have no idea. I recommend to ask on boost mail list or boost channel in slack.

**Comment by SSE4** [comment]
I am closing as required changes were applied. for the linker error, please ask on boost dev mail list or boost slack, I have no experience in such option at all.
