### ISSUE TITLE
[OpenCV] Linking to LAPACK

### ISSUE THREAD

**Issue by bmanga** [conan-community/community#265]
### Description of Problem, Request, or Question
When building the package from scratch, opencv's cmake detects the availability of LAPACK on my system and implicitly adds it as a dependency. When using the package however, the linking fails because LAPACK is not added as a dependency in the project.

It would be good if the conanfile offered an option to disable the LAPACK support or used the LAPACK conan package instead.

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/3.4.5**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**
* Compiler+version: **gcc-9**
* Conan version: **conan 1.2.0**
* Python version: **python 3.7.0**

**Comment by SSE4** [comment]
@bmanga I've added `lapack` option: https://github.com/conan-community/conan-opencv/commit/b4a645a4fbf829a1ce46ec3ec0451f2fb0775e81
please give a try and lemme know

**Comment by bmanga** [comment]
@SSE4 thanks for the prompt fix! I noticed that you have added the option only for the latest opencv (4.1.1). Is there any chance this could be backported to the other releases?

**Comment by SSE4** [comment]
@bmanga sure, why not. please tell me which branch(es) do you need?

**Comment by bmanga** [comment]
@SSE4 I am currently interested in 3.4.5! It would be a bit odd to only have those two releases fixed though, maybe I can help with backporting it to the other releases when I have some spare time if you'd like :)

**Comment by SSE4** [comment]
@bmanga sure, why not :) feel free to create necessary PR(s).

**Comment by SSE4** [comment]
@bmanga I've back-ported changes to 3.4.5 as well: https://github.com/conan-community/conan-opencv/commit/c5b1f34ffd11b6433177c026f7ee3eca5258595e
