### ISSUE TITLE
openscenegraph : Add openthreads_shared option

### ISSUE THREAD

**Issue by solvingj** [conan-community/community#266]
Openscenegraph builds and depends upon "OpenThreads", and by default it is built as a shared library dll, even when building openscengraph as a static library. 

There's a CMAKE variable called `DYNAMIC_OPENTHREADS` , we just need to pass it.

https://github.com/bincrafters/conan-openscenegraph/blob/testing/3.6.3/conanfile.py

### Package Details (Include if Applicable)
* Package Name/Version: **openscenegraph/3.6.3**

**Comment by uilianries** [comment]
Hi @solvingj ! OpenScenegraph is a package from Bincrafters, but you opened to Conan Community.

I'll mark this issue as invalid, as I can't move it to Bincrafters.

**Comment by uilianries** [comment]
Anyway, I added the option there: https://github.com/bincrafters/conan-openscenegraph/commit/77bbbf72d23bd73b0a68290eb360e2f1d1f5231d
