### ISSUE TITLE
[OpenCV] does not copy import

### ISSUE THREAD

**Issue by dab0bby** [conan-community/community#268]
In conanfile.txt i have defined the imports
```
[imports]
bin, *.dll -> ./bin
lib, *.dylib* -> ./bin
```

But the libs and dll from opencv are not copied into build directory. Only `vcruntime140.dll`, `concrt140.dll` and `msvcp140.dll`.

Compilation works, but I cant execute my program as the dll cant be found.

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.1.1@conan/stable**
* Operating System: **Windows**
* Operation System Version: **Windows 10**
* Compiler+version: **msvc-16**
* Conan version: **conan 1.18.1**
* Python version: **python 3.7.4**

**Comment by SSE4** [comment]
interesting, @uilianries do you have an idea what could be wrong?

**Comment by dab0bby** [comment]
Maybe the [`imports`](https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports)-Method can help.

**Comment by uilianries** [comment]
That's weird, because *imports* only copies those files according the pattern. I gonna try to reproduce this error on my Windows environment.

**Comment by uilianries** [comment]
@dab0bby could you please the profile that you were using when building? More specifically, I would like to know if you are using Release or Debug, and also static or shared lib.

**Comment by dab0bby** [comment]
I am using both. Debug and Release. I am also using shared libs.

Debug:
```
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
```

Release:
```
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
```

**Comment by uilianries** [comment]
Thanks!

Seems like we have a bug with OpenCV recipe, I can reproduce your problem, but the fact is that OpenCV is using a abnormal folder structure on Windows:

     C:\.conan\d826ea\1\x64\vc16\bin\

But it should be:

     C:\.conan\d826ea\1\bin\

I'm using short paths BTW. I'll check the recipe and provide a fix. Thanks for reporting.

**Comment by uilianries** [comment]
Hi @dab0bby !

We provided a new patch for your case: https://github.com/conan-community/conan-opencv/commit/0900490ef647242b57855d309560e4655d4a7a54

Please, update your local copy and try again. Cheers!

**Comment by dab0bby** [comment]
I tried. Works fine 👍 
Thanks for the quick fix.
