### ISSUE TITLE
[OpenCV] docs for option defaults are wrong

### ISSUE THREAD

**Issue by peter-moran** [conan-community/community#269]
The documentation for [Conan OpenCV options](https://github.com/conan-community/conan-opencv#available-options) are wrong.

In particular:
* `gtk` defaults to `None`, but is documented as `3`
* Missing jpegturbo, dc1394, carotene, cuda, protobuf, freetype, harfbuzz, eigen, glog, gflags, gstreamer, openblas, ffmpeg, lapack

**Comment by SSE4** [comment]
@uilianries how do we generate docs for conan-community now?

**Comment by uilianries** [comment]
@SSE4 What about the README generator from Bincrafters?

**Comment by uilianries** [comment]
Hmmm, the readme generator is not able to parse OpenCV project

**Comment by uilianries** [comment]
Hi @peter-moran !

The README files are update-to-date. Thanks for reporting those errors.
