### ISSUE TITLE
Package TclLib

### ISSUE THREAD

**Issue by luminitadaraban** [conan-community/community#27]
### Description of Problem, Request, or Question
Can you please package Tcllib?
https://www.tcl.tk/software/tcllib/

### Package Details (Include if Applicable)
* Package Name/Version: **tcllib/1.18**
* Operating System: **Linux** and **Windows**
* Compiler+version: **gcc-7** and **VS14** and **VS15**

**Comment by danimtb** [comment]
For library requests, please open an issue in https://github.com/conan-io/wishlist as this issue tracker is only intended for conan-community repos. Thanks a lot and hope it helps!
