### ISSUE TITLE
[OpenCV] 4.1.1 conan stable crosscompile to iOS fails on OSX due to deprecated OpenCL

### ISSUE THREAD

**Issue by jakschewitz** [conan-community/community#270]
### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.1.1/conan/stable**
* Operating System: **OSX**
* Operation System Version: **OSX 10.14.6**
* Compiler+version: **apple-clang 10.0**
* Conan version: **conan 1.17.0**
* Python version used for build: **python 2.7**

### Steps to reproduce (Include if Applicable)
rm -rf build;mkdir build;(cd build;conan install .. -p iOS -o opencv:shared=True --build);conan create . conan/stable -p iOS -o opencv:shared=True

### Fails with:
In file included from /Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/2b60247fc812abcae396030ca552f0ee2219776e/source_subfolder/modules/core/include/opencv2/core/opencl/runtime/opencl_core.hpp:68:
/Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/2b60247fc812abcae396030ca552f0ee2219776e/source_subfolder/modules/core/include/opencv2/core/opencl/runtime/autogenerated/opencl_core.hpp:100:10: fatal error: 'OpenCL/cl.h'
      file not found
#include <OpenCL/cl.h>

### OpenCV's build_framework.py works correctly
opencv-4.1.1/platforms/ios/build_framework.py/build_framework.py uses its own 3rdParty cl.h

### Build logs (Include if Available)
[conanBuildOpenCV4.1.1.log](https://github.com/conan-community/community/files/3550496/conanBuildOpenCV4.1.1.log)

**Comment by SSE4** [comment]
@jakschewitz I've pushed the fix: https://github.com/conan-community/conan-opencv/commit/cc044dc5f306c06842ebda2bbba450785c708b6f
please give an another try and lemme know

**Comment by jakschewitz** [comment]
now it fails with:
[ 52%] Building CXX object source_subfolder/modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/ios_conversions.mm.o
/Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/094d726b328604e5c3cdf588897f99c37d1ca3c0/source_subfolder/modules/imgcodecs/src/ios_conversions.mm:43:9: fatal error: 'UIKit/UIKit.h' file not found
#import <UIKit/UIKit.h>
        ^~~~~~~~~~~~~~~

**Comment by SSE4** [comment]
strange, for me it passed
could you print the output of `conan profile show iOS`?

**Comment by jakschewitz** [comment]
Configuration for profile ios:

[settings]
os=iOS
os_build=Macos
arch=armv8
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
os.version=12.1
[options]
opencv:openexr=False
opencv:protobuf=False
[build_requires]
[env]

**Comment by SSE4** [comment]
@jakschewitz thanks, I'll try to reproduce locally one more time with your profile

**Comment by bvnp43** [comment]
@jakschewitz @SSE4 

1. According to opencv code https://github.com/opencv/opencv/blob/master/modules/imgcodecs/CMakeLists.txt#L116, UIKit is linked only if `APPLE_FRAMEWORK` is defined

2. conan-opencv conanfile https://github.com/conan-community/conan-opencv/blob/release/4.1.1/conanfile.py#L388 does not add `APPLE_FRAMEWORK` variable to cmake

So probably you have to modify opencv sources

**Comment by jakschewitz** [comment]
@bvnp43 
thanks, adding APPLE_FRAMEWORK in conanfile.py like so
        if str(self.settings.os) in ["iOS", "watchOS", "tvOS"]:
            cmake.definitions['IOS'] = True
            cmake.definitions['APPLE_FRAMEWORK'] = True
adds '-framework UIKit' to the compile command,
but as the isysroot is defined as 
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk 
UIKit is not found, since it's only part of iPhone SDKs.

I'm puzzled about this isysroot setting for os=iOS and arch=armv8

**Comment by bvnp43** [comment]
https://github.com/conan-community/community/issues/293#issuecomment-549931371

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
