### ISSUE TITLE
[OpenCV] Invisible breaking change of default options for opencv/3.4.5

### ISSUE THREAD

**Issue by KB9** [conan-community/community#271]
### Description of Problem, Request, or Question

Conan cannot be considered a stable production environment if default options are changed beneath existing codebases. A change of the default options for opencv/3.4.5 in this [recent commit](https://github.com/conan-community/conan-opencv/commit/c5b1f34ffd11b6433177c026f7ee3eca5258595e) introduced undefined references when attempting to display images using a GTK window. I was not aware that this option had been changed and had to spend hours diagnosing a seemingly-invisible change.

Is it possible for changes to default options to be more transparent in future? Perhaps versioning the recipes themselves and notifying users of changes?

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/3.4.5**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**
* Compiler+version: **gcc-9.1.0**
* Conan version: **conan 1.18.2**
* Python version: **python 3.6.8**

**Comment by jgsogo** [comment]
Hi, @KB9 . There is a mechanism to version recipes (and packages too), have a look at [package revisions](https://docs.conan.io/en/latest/versioning/revisions.html), but for open-source and community it is not possible to save all the versions (too many binaries to store). Current CI and Bintray for conan-center doesn't use revisions (it always overrides a `0` revision).

Another mechanism you might find interesting is using `lockfiles`, these files stores not only the exact revision your are usiing, but also the options and the profile ([docs on lockfiles](https://docs.conan.io/en/latest/versioning/lockfiles.html)).

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
