### ISSUE TITLE
[OpenCV] does not include build dependency on CMake

### ISSUE THREAD

**Issue by peter-moran** [conan-community/community#274]
### Description of Problem, Request, or Question
The `opencv/4.1.1@conan/stable` conan package does not make cmake a build dependency for opencv. Without cmake on your system, you cannot build `opencv`.

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.1.1@conan/stable**

### Steps to reproduce (Include if Applicable)
Get a system without `cmake` installed and run `conan install opencv/4.1.1@conan/stable`.

One way to do this is in docker:
```
FROM ubuntu:16.04
# Install conan
RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install conan

# Install opencv
RUN conan install opencv/4.1.1@conan/stable --build opencv
```
which fails with:
```
opencv/4.1.1@conan/stable: Building your package in /root/.conan/data/opencv/4.1.1/conan/stable/build/cd50ecd06cbd831fef9e6eb699704a26b0bfefff
opencv/4.1.1@conan/stable: Generator cmake created conanbuildinfo.cmake
opencv/4.1.1@conan/stable: Calling build()
/bin/sh: 1: cmake: not found
```

### Solution
You can
```
apt-get update && apt-get install -y cmake
```

However, it seems it would be more appropriate to list opencv as a build requires, and depend on this package: https://github.com/conan-community/conan-cmake-installer. This way we can also use an exact cmake version.

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
