### ISSUE TITLE
[ffmpeg] How should I manage transtive dependency like ffmpeg?

### ISSUE THREAD

**Issue by cqjjjzr** [conan-community/community#275]
Hi. I'm writing a conan recipe that is a wrapper of FFmpeg, called "ffms2".(https://github.com/cqjjjzr/conan-ffms2-core/).

Everything seems to be OK but I found that when running the CI, it spends lots of time configuring dependencies(since the FFmpeg default config includes almost all external dependency).

So, in order to optimize the CI build speed and reduce the artifact size, should I specify ffmpeg build config in the ffms2 conanfile.py or build something like a ffmpeg-minimal repo?

Thanks.

**Comment by Croydon** [comment]
Hi @cqjjjzr! 

This repository is the wrong place for such a question. FFMPEG is a [Bincrafters package](https://github.com/bincrafters/community/issues), so either ask related questions there or if it is a more general question you can also use the [Conan repository](https://github.com/conan-io/conan)

Thanks!
