### ISSUE TITLE
[OpenCV] How to support fat library of iOS armv7 and arm64

### ISSUE THREAD

**Issue by BillHoo** [conan-community/community#278]
Hi conan team, I'm using `opencv/4.1.1@conan/stable` in an iOS project,

this generates armv7's package
```
include(default)

[settings]
os=iOS
os.version=9.0
arch=armv7
compiler=apple-clang
compiler.version=10.0

[build_requires]
darwin-toolchain/1.0.4@theodelrieu/stable
```

and this generates armv8's
```
...
arch=armv8
compiler=apple-clang
compiler.version=10.0

[build_requires]
...
```

but those are two standalone packages, the guide [With the xcode generator](https://docs.conan.io/en/latest/integrations/ide/xcode.html#with-the-xcode-generator) only refers to one package path, either armv7 or armv8. How can this way support fat library?

Thank you!

**Comment by SSE4** [comment]
@BillHoo supporting fat binaries in conan is challenging. I'd recommend you to do a `lipo` as a final post-process of the build instead.

**Comment by BillHoo** [comment]
@SSE4 thank you! I've already did so as you said. But the fat library will let me use conan with XCode more effectively without any hacking. Anyway thanks for let me know, hoping it will be supported in the future!
