### ISSUE TITLE
[bzip2] bzip2/1.06@conan/stable fails as of a5875aed3fc7ae8dd0488f7e5e99acbc480d721d

### ISSUE THREAD

**Issue by thedracle** [conan-community/community#279]
### It seems like the bzip2 conan/stable package is broken as of a5875aed3fc7ae8dd0488f7e5e99acbc480d721d

when trying to build from source.

It works as of b27e2b40bcb70be2e7d6f0e0c6e43e35c530f8d3

The error it chokes on is :
`
bzip2/1.0.6@conan/stable: Configuring sources in /root/.conan/data/bzip2/1.0.6/conan/stable/source
ERROR: bzip2/1.0.6@conan/stable: Error in source() method, line 37
        tools.get(url="%s/download_file?file_path=%s" % (url, zip_name), sha256=sha256, filename=zip_name)
        AttributeError: 'NoneType' object has no attribute 'token'
`

### Package Details (Include if Applicable)

* Package Name/Version: **bzip2/1.06@conan/stable#a5875aed3fc7ae8dd0488f7e5e99acbc480d721d**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04** **Alpine 3.9.4**
* Compiler+version: **gcc-8.3.0** & **gcc 7.4.0***
* Conan version: **conan 1.18.0**
* Python version: **python 2.7.16**

### Steps to reproduce (Include if Applicable)
conanfile.txt

>[requires]
boost/1.65.1@conan/stable
OpenSSL/1.0.2@conan/stable
[options]
boost:shared=False
[generators]
make

And build with

> conan install . -s compiler.libcxx=libstdc++11 --build boost --build bzip2 --build zlib --build OpenSSL

### Build logs (Include if Available)

`Requirement already satisfied: conan in /usr/lib/python2.7/site-packages (1.18.4)
Requirement already satisfied: PyJWT<2.0.0,>=1.4.0 in /usr/lib/python2.7/site-packages (from conan) (1.7.1)
Requirement already satisfied: requests<3.0.0,>=2.8.1 in /usr/lib/python2.7/site-packages (from conan) (2.22.0)
Requirement already satisfied: colorama<0.5.0,>=0.3.3 in /usr/lib/python2.7/site-packages (from conan) (0.4.1)
Requirement already satisfied: PyYAML<6.0,>=3.11 in /usr/lib/python2.7/site-packages (from conan) (5.1.2)
Requirement already satisfied: patch==1.16 in /usr/lib/python2.7/site-packages (from conan) (1.16)
Requirement already satisfied: fasteners>=0.14.1 in /usr/lib/python2.7/site-packages (from conan) (0.15)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/site-packages (from conan) (1.12.0)
Requirement already satisfied: node-semver==0.6.1 in /usr/lib/python2.7/site-packages (from conan) (0.6.1)
Requirement already satisfied: distro<1.2.0,>=1.0.2 in /usr/lib/python2.7/site-packages (from conan) (1.1.0)
Requirement already satisfied: pylint!=2.3.0,>=1.9.3 in /usr/lib/python2.7/site-packages (from conan) (1.9.5)
Requirement already satisfied: future==0.16.0 in /usr/lib/python2.7/site-packages (from conan) (0.16.0)
Requirement already satisfied: pygments<3.0,>=2.0 in /usr/lib/python2.7/site-packages (from conan) (2.4.2)
Requirement already satisfied: astroid>=1.6.5 in /usr/lib/python2.7/site-packages (from conan) (1.6.6)
Requirement already satisfied: deprecation<2.1,>=2.0 in /usr/lib/python2.7/site-packages (from conan) (2.0.7)
Requirement already satisfied: tqdm<5,>=4.28.1 in /usr/lib/python2.7/site-packages (from conan) (4.36.1)
Requirement already satisfied: Jinja2<3,>=2.3 in /usr/lib/python2.7/site-packages (from conan) (2.10.1)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/lib/python2.7/site-packages (from conan) (2.8.0)
Requirement already satisfied: bottle<0.13,>=0.12.8 in /usr/lib/python2.7/site-packages (from conan) (0.12.17)
Requirement already satisfied: pluginbase<1.0,>=0.5 in /usr/lib/python2.7/site-packages (from conan) (0.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests<3.0.0,>=2.8.1->conan) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/site-packages (from requests<3.0.0,>=2.8.1->conan) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests<3.0.0,>=2.8.1->conan) (1.25.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests<3.0.0,>=2.8.1->conan) (2019.9.11)
Requirement already satisfied: monotonic>=0.1 in /usr/lib/python2.7/site-packages (from fasteners>=0.14.1->conan) (1.5)
Requirement already satisfied: isort>=4.2.5 in /usr/lib/python2.7/site-packages (from pylint!=2.3.0,>=1.9.3->conan) (4.3.21)
Requirement already satisfied: singledispatch; python_version < "3.4" in /usr/lib/python2.7/site-packages (from pylint!=2.3.0,>=1.9.3->conan) (3.4.0.3)
Requirement already satisfied: configparser; python_version == "2.7" in /usr/lib/python2.7/site-packages (from pylint!=2.3.0,>=1.9.3->conan) (4.0.2)
Requirement already satisfied: mccabe in /usr/lib/python2.7/site-packages (from pylint!=2.3.0,>=1.9.3->conan) (0.6.1)
Requirement already satisfied: backports.functools-lru-cache; python_version == "2.7" in /usr/lib/python2.7/site-packages (from pylint!=2.3.0,>=1.9.3->conan) (1.5)
Requirement already satisfied: enum34>=1.1.3; python_version < "3.4" in /usr/lib/python2.7/site-packages (from astroid>=1.6.5->conan) (1.1.6)
Requirement already satisfied: wrapt in /usr/lib/python2.7/site-packages (from astroid>=1.6.5->conan) (1.11.2)
Requirement already satisfied: lazy-object-proxy in /usr/lib/python2.7/site-packages (from astroid>=1.6.5->conan) (1.4.2)
Requirement already satisfied: packaging in /usr/lib/python2.7/site-packages (from deprecation<2.1,>=2.0->conan) (19.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python2.7/site-packages (from Jinja2<3,>=2.3->conan) (1.1.1)
Requirement already satisfied: futures; python_version < "3.2" in /usr/lib/python2.7/site-packages (from isort>=4.2.5->pylint!=2.3.0,>=1.9.3->conan) (3.3.0)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python2.7/site-packages (from packaging->deprecation<2.1,>=2.0->conan) (2.4.2)
Auto detecting your dev setup to initialize the default profile (/root/.conan/profiles/default)
Found gcc 8.3
Found clang 5.0
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************

Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the default profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 default

Or edit '/root/.conan/profiles/default' and set compiler.libcxx=libstdc++11

************************************************************************************

Default settings
        os=Linux
        os_build=Linux
        arch=x86_64
        arch_build=x86_64
        compiler=gcc
        compiler.version=8
        compiler.libcxx=libstdc++
        build_type=Release
*** You can change them in /root/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***

WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

boost/1.65.1@conan/stable: Not found in local cache, looking in remotes...
boost/1.65.1@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 180/180 [00:00<00:00, 114kB/s]
Downloading conanfile.py: 100%|##########| 31.1k/31.1k [00:00<00:00, 464kB/s]
Downloading conan_export.tgz: 100%|##########| 1.00k/1.00k [00:00<00:00, 822kB/s]
Decompressing conan_export.tgz: 1.00kB [00:00, 518kB/s]
boost/1.65.1@conan/stable: Downloaded recipe revision 0
boost/1.65.1@conan/stable: WARN: Setting 'cppstd' is deprecated in favor of 'compiler.cppstd', please update your recipe.
bzip2/1.0.6@conan/stable: Not found in local cache, looking in remotes...
bzip2/1.0.6@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 163/163 [00:00<00:00, 154kB/s]
Downloading conanfile.py: 100%|##########| 2.21k/2.21k [00:00<00:00, 1.67MB/s]
Downloading conan_export.tgz: 100%|##########| 766/766 [00:00<00:00, 481kB/s]
Decompressing conan_export.tgz: 774B [00:00, 723kB/s]
bzip2/1.0.6@conan/stable: Downloaded recipe revision 0
zlib/1.2.11@conan/stable: Not found in local cache, looking in remotes...
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 296/296 [00:00<00:00, 225kB/s]
Downloading conanfile.py: 100%|##########| 8.74k/8.74k [00:00<00:00, 7.41MB/s]
Downloading conan_export.tgz: 100%|##########| 766/766 [00:00<00:00, 401kB/s]
Decompressing conan_export.tgz: 774B [00:00, 729kB/s]
zlib/1.2.11@conan/stable: Downloaded recipe revision 0
OpenSSL/1.0.2@conan/stable: Not found in local cache, looking in remotes...
OpenSSL/1.0.2@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 58.0/58.0 [00:00<00:00, 43.3kB/s]
Downloading conanfile.py: 100%|##########| 106/106 [00:00<00:00, 63.5kB/s]
OpenSSL/1.0.2@conan/stable: Downloaded recipe revision 0
OpenSSL/1.0.2q@conan/stable: Not found in local cache, looking in remotes...
OpenSSL/1.0.2q@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 58.0/58.0 [00:00<00:00, 41.3kB/s]
Downloading conanfile.py: 100%|##########| 28.7k/28.7k [00:00<00:00, 14.6MB/s]
OpenSSL/1.0.2q@conan/stable: Downloaded recipe revision 0
bzip2/1.0.6@conan/stable: Forced build from source
zlib/1.2.11@conan/stable: Forced build from source
OpenSSL/1.0.2q@conan/stable: Forced build from source
boost/1.65.1@conan/stable: Forced build from source
conanfile.txt: Installing package
Requirements
    OpenSSL/1.0.2q@conan/stable from 'conan-center' - Downloaded
    boost/1.65.1@conan/stable from 'conan-center' - Downloaded
    bzip2/1.0.6@conan/stable from 'conan-center' - Downloaded
    zlib/1.2.11@conan/stable from 'conan-center' - Downloaded
Packages
    OpenSSL/1.0.2q@conan/stable:4f75e4b120320a9fb6ac0012242d9ac95d18b6f6 - Build
    boost/1.65.1@conan/stable:5e8eff81f2db7ac8c8c3d41364df2f92d8c53fdb - Build
    bzip2/1.0.6@conan/stable:a5875aed3fc7ae8dd0488f7e5e99acbc480d721d - Build
    zlib/1.2.11@conan/stable:1d877a3df840030e6a8abb74c5ffb9088d08b47a - Build

Downloading conan_sources.tgz: 100%|##########| 807/807 [00:00<00:00, 504kB/s]
Decompressing conan_sources.tgz: 815B [00:00, 691kB/s]
bzip2/1.0.6@conan/stable: Configuring sources in /root/.conan/data/bzip2/1.0.6/conan/stable/source
ERROR: bzip2/1.0.6@conan/stable: Error in source() method, line 37
        tools.get(url="%s/download_file?file_path=%s" % (url, zip_name), sha256=sha256, filename=zip_name)
        AttributeError: 'NoneType' object has no attribute 'token'
`

**Comment by thedracle** [comment]
I've spent some time looking deeper into this, and the failure is happening in the conanfile.py at line 37, when it goes to use tools.get to download from https://bintray.com/conan/Sources/download_file?file_path=bzip2-1.0.6.tar.gz

It seems to go through two 302 redirects to Akamai when I just wget it via the console:
```
🐧❯ wget https://bintray.com/conan/Sources/download_file\?file_path\=bzip2-1.0.6.tar.gz--2019-09-23 08:23:43--  https://bintray.com/conan/Sources/download_file?file_path=bzip2-1.0.6.tar.gz
Resolving bintray.com (bintray.com)... 75.126.208.206
Connecting to bintray.com (bintray.com)|75.126.208.206|:443...
connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.bintray.com/conan/Sources/bzip2-1.0.6.tar.gz?expiry=1569252255574&signature=LoTH7x0Cg9qis%2B%2BLNuv4Kh2%2BPaj6%2BnsA4HpDIdOaz4jQ%2BlBTO8HD%2FVT%2B51MA4yNx0ZX9FfdNyNfbpPF3EeLYRg%3D%3D [following]
--2019-09-23 08:23:45--  https://dl.bintray.com/conan/Sources/bzip2-1.0.6.tar.gz?expiry=1569252255574&signature=LoTH7x0Cg9qis%2B%2BLNuv4Kh2%2BPaj6%2BnsA4HpDIdOaz4jQ%2BlBTO8HD%2FVT%2B51MA4yNx0ZX9FfdNyNfbpPF3EeLYRg%3D%3D
Resolving dl.bintray.com (dl.bintray.com)... 54.201.76.60, 52.35.217.225
Connecting to dl.bintray.com (dl.bintray.com)|54.201.76.60|:443... connected.
HTTP request sent, awaiting response... 302
Location: https://akamai.bintray.com/a2/a2848f34fcd5d6cf47def00461fcb528a0484d8edef8208d6d2e2909dc61d9cd?__gda__=exp=1569252947~hmac=0eac7b4576899e96e40ad76d51d3710ec90995ca224fb24eda77b02a5dc3f6d0&response-content-disposition=attachment%3Bfilename%3D%22bzip2-1.0.6.tar.gz%22&response-content-type=application%2Fgzip&requestInfo=U2FsdGVkX18PK7rvB7_QYR8sOFmBvL-XaIcFNnmjWk7pPJZM07aW2WGn-lSiGY_2U21qHVKn7KWtyOPfIYOEar4S9NBSZY-dttcXPpQzcqYlfNPWpShYTtLD84KcMh3S&response-X-Checksum-Sha1=3f89f861209ce81a6bab1fd1998c0ef311712002&response-X-Checksum-Sha2=a2848f34fcd5d6cf47def00461fcb528a0484d8edef8208d6d2e2909dc61d9cd [following]
--2019-09-23 08:23:47--  https://akamai.bintray.com/a2/a2848f34fcd5d6cf47def00461fcb528a0484d8edef8208d6d2e2909dc61d9cd?__gda__=exp=1569252947~hmac=0eac7b4576899e96e40ad76d51d3710ec90995ca224fb24eda77b02a5dc3f6d0&response-content-disposition=attachment%3Bfilename%3D%22bzip2-1.0.6.tar.gz%22&response-content-type=application%2Fgzip&requestInfo=U2FsdGVkX18PK7rvB7_QYR8sOFmBvL-XaIcFNnmjWk7pPJZM07aW2WGn-lSiGY_2U21qHVKn7KWtyOPfIYOEar4S9NBSZY-dttcXPpQzcqYlfNPWpShYTtLD84KcMh3S&response-X-Checksum-Sha1=3f89f861209ce81a6bab1fd1998c0ef311712002&response-X-Checksum-Sha2=a2848f34fcd5d6cf47def00461fcb528a0484d8edef8208d6d2e2909dc61d9cd
Resolving akamai.bintray.com (akamai.bintray.com)... 184.84.3.203
Connecting to akamai.bintray.com (akamai.bintray.com)|184.84.3.203|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 782025 (764K) [application/gzip]
Saving to: ‘download_file?file_path=bzip2-1.0.6.tar.gz’

download_file?file_path=bzip2- 100%[====================================================>] 763.70K  2.55MB/s    in 0.3s

2019-09-23 08:23:52 (2.55 MB/s) - ‘download_file?file_path=bzip2-1.0.6.tar.gz’ saved [782025/782025]
```

If I switch the code to download bzip2 from my own S3 bucket on AWS with no redirects, everything continues normally, and the packages builds/installs.

```
    def source(self):
        folder_name = "%s-%s" % (self.name, self.version)
        zip_name = "%s.tar.gz" % folder_name
        sha256 = "a2848f34fcd5d6cf47def00461fcb528a0484d8edef8208d6d2e2909dc61d9cd"
        #url = "https://bintray.com/conan/Sources"
        url = "https://fidelisdump.s3-us-west-2.amazonaws.com"
        tools.get(url="%s/%s" % (url, zip_name), filename=zip_name)
        os.rename(folder_name, self._source_subfolder)
```

**Comment by SSE4** [comment]
moved to https://github.com/conan-io/conan-center-index/issues/102
