### ISSUE TITLE
[OpenSSL] /usr/bin/sh: C:/Program: No such file or directory

### ISSUE THREAD

**Issue by LinArcX** [conan-community/community#28]
### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2o@conan/stable**
* Operating System: **Windows**
* Compiler+version: **gcc-5.3**
* Docker image: None

### Steps to reproduce (Include if Applicable)
I want to to cross-build poco library for android with android-toolchain. first i create an arm toolchain:
```
 C:\Python37\python build\tools\make_standalone_toolchain.py --api 28 --arch arm --install-dir ../androudtoolchain
```
then create a profile for it and put it in:
```
C:\Users\LENOVO\.conan\profiles\arm_android_28_gcc
```
contain:
```
 standalone_toolchain=D:\Software\Sources\IDE\Android\androudtoolchain
 target_host=arm-linux-androideabi
 cc_compiler=gcc
 cxx_compiler=g++

 [settings]
 compiler=gcc
 compiler.version=5.3
 compiler.libcxx=libstdc++
 os=Android
 os.api_level=28
 arch=armv7
 build_type=Release

 [env]
 CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/sysroot
 PATH=[$standalone_toolchain/bin]
 CHOST=$target_host
 AR=$target_host-ar
 AS=$target_host-as
 RANLIB=$target_host-ranlib
 CC=$target_host-$cc_compiler
 CXX=$target_host-$cxx_compiler
 LD=$target_host-ld
 STRIP=$target_host-strip
 CFLAGS= -fPIC  -I$standalone_toolchain/include/c++/4.9.x
 CXXFLAGS= -fPIC  -I$standalone_toolchain/include/c++/4.9.x
 LDFLAGS=
```
It fetch zlib(download and compile it perfectly!), but when arrive to openssl, complains:

> OpenSSL/1.0.2o@conan/stable: WARN: ----------MAKE OPENSSL 1.0.2o-------------
> making all in crypto...
> make[1]: Entering directory `C:/Users/LENOVO/.conan/data/OpenSSL/1.0.2o/conan/stable/build/170e22e3a42b12e8679b8a2f64eb142ac8d76655/openssl-1.0.2o/crypto'
> C:/Program Files/Git/usr/bin/perl ../util/mkbuildinf.pl "arm-linux-androideabi-gcc -I. -I.. -I../include -IC:\Users\LENOVO\.conan\data\zlib\1.2.11\conan\stable\package\a53fdb1f8e28df07f252608b0f1f2d9c1de0be57\include -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -fPIC -O3 -s -march=armv7-a -mandroid -I/include -B/lib -O3 -fomit-frame-pointer -Wall -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM" "android-armv7" >buildinf.h
> /usr/bin/sh: C:/Program: No such file or directory
> make[1]: *** [buildinf.h] Error 127
> make[1]: Leaving directory `C:/Users/LENOVO/.conan/data/OpenSSL/1.0.2o/conan/stable/build/170e22e3a42b12e8679b8a2f64eb142ac8d76655/openssl-1.0.2o/crypto'
> make: *** [build_crypto] Error 1
> OpenSSL/1.0.2o@conan/stable:
> OpenSSL/1.0.2o@conan/stable: ERROR: Package '170e22e3a42b12e8679b8a2f64eb142ac8d76655' build failed
> OpenSSL/1.0.2o@conan/stable: WARN: Build folder C:\Users\LENOVO\.conan\data\OpenSSL\1.0.2o\conan\stable\build\170e22e3a42b12e8679b8a2f64eb142ac8d76655
> ERROR: OpenSSL/1.0.2o@conan/stable: Error in build() method, line 111
>         self.unix_build(config_options_string)
> while calling 'unix_build', line 203
>         self.run_in_src("make", show_output=True)
> while calling 'run_in_src', line 131
>         self.run(command)
>         ConanException: Error 2 while executing make

**Comment by lasote** [comment]
It looks like it is not a direct Conan issue but a OpenSSL issue with the build system/support for Android.
Apparently, it is using `perl` to build and the path `C:/Program Files/Git/usr/bin/perl` is not quoted correctly. You could try to put perl in the path in another directory and see what happen.
Which NDK are you using?

**Comment by SSE4** [comment]
@uilianries @lasote  interesting, can we force it to use `strawberry_perl` installer (which I believe should use `short_paths`)?

**Comment by SSE4** [comment]
I think it should be generic for `os.name == "nt"`, for any cross-compiling use-case.
On Windows, Users might not have Git perl in PATH, or any perl in general.

**Comment by SSE4** [comment]
@uilianries I think that's one is fixed, right?

**Comment by uilianries** [comment]
Yes, but let's wait for feedback.

**Comment by SSE4** [comment]
I am closing this for now, as required changes were applied
@LinArcX please open a new issue if you still have problems with recipe
