### ISSUE TITLE
[OpenCV] iOS target arm64 is not supported

### ISSUE THREAD

**Issue by BillHoo** [conan-community/community#281]
### Description of Problem, Request, or Question
When cross-build `opencv/4.1.1@conan/stable` from Mac to iOS, there's no way to build architechture `arm64`, the only one suitable in conanfile is `armv8`, which is not support by XCode, Apple only support `arm64`. So what's the solution of this?

I'm currently manually install OpenCV from conan, and use `lipo` to build the fat library of `armv7` and `armv8`, i guess its not a good way.

Thank you.

### Package Details (Include if Applicable)
* Package Name/Version: **OpenCV/4.1.1**
* Operating System: **iOS**
* Compiler+version: **clang 10.0**
* Conan version: **conan 1.18.4**

**Comment by SSE4** [comment]
@BillHoo `arm64` is just an apple's naming for `armv8`

**Comment by BillHoo** [comment]
Thank you! The armv8 works pretty good, I'm closing the ticket.
