### ISSUE TITLE
Update pybind11 to 2.4.2 (possibly through 2.4.0 and 2.4.1 as well)

### ISSUE THREAD

**Issue by dorozhkin-stc** [conan-community/community#283]
### Description of Problem, Request, or Question

The upstream (https://github.com/pybind/pybind11) has released 2.4.0, 2.4.1 and 2.4.2. It would be great to have them available in conan.

**Comment by danimtb** [comment]
We would probably update the recipe to the latest version in https://github.com/conan-io/conan-center-index

Thanks for reporting!

**Comment by danimtb** [comment]
This recipe has been included in [conan-io/conan-center-index](https://github.com/conan-io/conan-center-index) as ``pybind11/2.4.3``. The recipe in the conan-community organization has been archived and it will no longer be maintained. Please try the new recipe and report any issue there. Thank you!
