### ISSUE TITLE
[OpenSSL] Please publish latest OpenSSL 1.1.1d

### ISSUE THREAD

**Issue by BillHoo** [conan-community/community#284]
Hi Conan Team,

The `OpenSSL 1.1.1d` has been released about 1 month, but I still can not find the official recipe of this version in `conan-center`, every time when I'm trying to install, it shows me this error:

`ERROR: Unable to find 'OpenSSL/1.1.1d@conan/stable' in remotes`

And I do find a commit in here - https://github.com/conan-io/conan-center-index/issues/48

But what does that mean? should I install from another place instead of `conan-center`?

Thank you in advance.

**Comment by BillHoo** [comment]
@SSE4 Sorry to push, my App is blocked by this issue and have to upgrade to `1.1.1d`, any idea if I can manually create an OpenSSL package? I use the recipe in conan-center-index, but its named as `openssl` not `OpenSSL`, so I'm afraid to use it. thank you.

**Comment by SSE4** [comment]
@BillHoo you need to switch to `openssl/1.1.1d`, the one you have found. it's the same recipe, we just moved it to the new repository.

**Comment by BillHoo** [comment]
So I need to use this recipe  `openssl/1.1.1d@_/_` ? it seems ... strange

**Comment by SSE4** [comment]
yes, and it could be used just as `openssl/1.1.1d` (without username/channel)

**Comment by BillHoo** [comment]
OK, can we confirm that `openssl/1.1.1d` is always means released by `conan` and is `stable`? cos' without username/channel makes me feel dangerous. don't laugh at me if its a common solution ;D

**Comment by SSE4** [comment]
yes, it's new policy going forward: https://blog.conan.io/2019/09/04/A-new-binary-building-service-for-Conan-center-packages.html

**Comment by BillHoo** [comment]
I got it, will read it right now, thank you and have a good day!

**Comment by cristianacrisan** [comment]
@BillHoo, were you able to access the openssl/1.1.1d package? I'm using conan 1.20.4 and still cannot download it. 
`ERROR: Failed requirement 'openssl/1.1.1d' from 'conanfile.py`

**Comment by danimtb** [comment]
@cristianacrisan you should be able to download packages (if available for your configuration) using the reference `openssl/1.1.1d` in the requirements of your conanfile.txt|.py

Gave it a try from my side and it is working fine:

```
$ conan search openssl/1.1.1d* -r conan-center
Existing package recipes:

openssl/1.1.1d


$ conan install openssl/1.1.1d@
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

openssl/1.1.1d: Not found in local cache, looking in remotes...
openssl/1.1.1d: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.10k]
Downloading conanfile.py completed [27.19k]
Downloading conan_export.tgz completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
openssl/1.1.1d: Downloaded recipe revision ce02452b46eac15207cddeb27033bc74
Installing package: openssl/1.1.1d
Requirements
    openssl/1.1.1d from 'conan-center' - Downloaded
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    openssl/1.1.1d:606fdb601e335c2001bdf31d478826b644747077 - Download
    zlib/1.2.11:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Cache

zlib/1.2.11: Already installed!
Downloading conanmanifest.txt completed [6.38k]
Downloading conaninfo.txt completed [1.34k]
Downloading conan_package.tgz completed [8357.26k]
Decompressing conan_package.tgz completed [0.00k]
openssl/1.1.1d: Package installed 606fdb601e335c2001bdf31d478826b644747077
openssl/1.1.1d: Downloaded package revision c1076656cfcd7d29497b58cf1283e29d
```
