### ISSUE TITLE
Failed to cross-compile Openssl Windows to Android

### ISSUE THREAD

**Issue by ArtBlnd** [conan-community/community#287]
### Description of Problem, Request, or Question
Fails to cross-compile OpenSSL to Android via Windows

tried to build with `1.0.x` version emits `make depend .` error.
and 1.1.x versions emits perl path error. which is Unix and Windows path difference.

### Package Details (Include if Applicable)
* Package Name/Version: **OpenSSL/1.0.2r@conan/stable**
* Operating System: **Windows**
* Operation System Version: **Windows 1906**
* Compiler+version: **Clang-8.0**
* Conan version: **conan 1.19.2**
* Python version: **python 3.7.0**

### Steps to reproduce (Include if Applicable)
```
include(default)

[build_requires]
android_ndk_installer/r20@bincrafters/stable
cygwin_installer/2.9.0@bincrafters/stable

[settings]
os=Android
os.api_level=21
arch=armv7
compiler=clang
compiler.libcxx=libc++
compiler.version=8

[env]
CFLAGS=-fPIC
CXXFLAGS=-fPIC -std=c++17
```

### Build logs (Include if Available)

```
debug|armeabi-v7a :*** Because of configuration changes, you MUST do the following before
debug|armeabi-v7a :*** building:
debug|armeabi-v7a :	make depend
debug|armeabi-v7a :    .
debug|armeabi-v7a :OpenSSL/1.0.2r@conan/stable: 
debug|armeabi-v7a :OpenSSL/1.0.2r@conan/stable: ERROR: Package 'e0c6f1e3216b7386835a70883a41ecc8ef6b2706' build failed
```

Full log here
C:/Users/junry/Desktop/Sniper-Android/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/

**Comment by ArtBlnd** [comment]
```
This perl implementation doesn't produce Unix like paths (with forward slash directory separators).  Please use an implementation that matches your building platform.
```
The 1.1.x version of OpenSSL should select MSYS2's perl when its building to android or linux on Windows platform. so it will be fixed.

**Comment by SSE4** [comment]
fixed by https://github.com/conan-io/conan-center-index/pull/129

**Comment by ArtBlnd** [comment]
How can I use lastest repository of openssl?

**Comment by SSE4** [comment]
the new reference is just `openssl/1.0.2t` (without username/channel)

**Comment by ArtBlnd** [comment]
```
1> [CMake] OpenSSL/1.0.2t: Not found in local cache, looking in remotes...
1> [CMake] OpenSSL/1.0.2t: Trying with 'conan-center'...
1> [CMake] OpenSSL/1.0.2t: Trying with 'bincrafters'...
1> [CMake] ERROR: Unable to find 'OpenSSL/1.0.2t' in remotes
```

Seems it does work on me.

**Comment by SSE4** [comment]
it should be the lower-case. it exists on `conan-center`:
```
conan search "openssl*"  -r conan-center
Existing package recipes:

openssl/1.0.2s
openssl/1.0.2t
openssl/1.1.0k
openssl/1.1.0l
openssl/1.1.1c
openssl/1.1.1d
```

**Comment by ArtBlnd** [comment]
```
ERROR: Requested 'openssl/1.1.1c' but found case incompatible 'OpenSSL'
```

I got this error seems something still being wrong.

**Comment by ArtBlnd** [comment]
nevermind, its just I have OpenSSL installed on my local machine.
