### ISSUE TITLE
[Box2D] Upgrade box2d:conan to master

### ISSUE THREAD

**Issue by igor-sadchenko** [conan-community/community#288]
### Description of Problem, Request, or Question
Upgrade Box2D package to the latest commit in master of https://github.com/erincatto/Box2D
Based on this message https://github.com/erincatto/Box2D/issues/478#issuecomment-392382485, master has last stable changes.

Here is the PR https://github.com/conan-community/conan-box2d/pull/5

### Package Details
* Package Name/Version: **[box2d:conan](https://bintray.com/beta/#/conan-community/conan/box2d:conan?tab=overview)**
* Package repo: https://github.com/conan-community/conan-box2d
* Source repo: https://github.com/erincatto/Box2D
* Latest commit: https://github.com/erincatto/Box2D/commit/ef96a4f17f1c5527d20993b586b400c2617d6ae1

**Comment by SSE4** [comment]
was merged
