### ISSUE TITLE
Error building opencv with contrib libraries

### ISSUE THREAD

**Issue by akshit-sharma** [conan-community/community#289]
### Description of Problem, Request, or Question
I am trying to install opencv with contrib libraries using [repo](https://github.com/conan-community/conan-opencv).
The conan says: Error: Failed requirement 'libffi/3.2.1' from 'glib/2.58.3@bincrafters/stable'.

### Package Details (Include if Applicable)
* Package Name/Version: opencv/4.1.1
* Operating System: Windows
* Operation System Version: Windows 10
* Compiler+version: Visual Studio 16
* Conan version: conan 1.18.1

### Steps to reproduce (Include if Applicable)
Install opencv with contrib set to true.

[conanfile.txt](https://gist.githubusercontent.com/akshit-sharma/5085192e8073b567b055f59558044fca/raw/d965cbc9b1ca727596162a6962de01f5f34c6e93/conanfile.txt)

[CMakeLists.txt](https://gist.githubusercontent.com/akshit-sharma/5085192e8073b567b055f59558044fca/raw/d965cbc9b1ca727596162a6962de01f5f34c6e93/CMakeLists.txt)

### Build logs (Include if Available)
[Build log](https://gist.githubusercontent.com/akshit-sharma/5085192e8073b567b055f59558044fca/raw/12ded18843ac11b2202d583920d20da3401539f5/conan%2520log)

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
