### ISSUE TITLE
[Opencv] option to build with vtk

### ISSUE THREAD

**Issue by akshit-sharma** [conan-community/community#290]
### Description of Problem, Request, or Question
Currently [conan-opencv](https://github.com/conan-community/conan-opencv) does not have an option to build with vtk library.

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
