### ISSUE TITLE
Cannot get boost/1.71.0@conan/stable built on Windows 10 with Boost Python enabled

### ISSUE THREAD

**Issue by 326623** [conan-community/community#291]
### Description of Problem, Request, or Question
Cannot get boost/1.71.0@conan/stable built on Windows 10 with Boost Python enabled. Once I disable Boost Python module, it has no issue.
Thanks.

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.71.0@conan/stable**
* Operating System: **Windows 10**
* Operation System Version: **Windows 10.0.18362**
* Compiler+version: **"msvc 14.1**
* Docker image: ****
* Conan version: **Conan version 1.19.2**
* Python version: **python 3.7.5**

### Build logs (Include if Available)
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.3.5
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
notice: found boost-build.jam at C:/.conan/76d9e3b/1/boost_1_71_0/boost-build.jam
notice: loading Boost.Build from C:/.conan/76d9e3b/1/boost_1_71_0/tools/build/src
notice: [zlib] Using pre-installed library
notice: [zlib] Condition
notice: [bzip2] Using pre-installed library
notice: [bzip2] Condition
C:/.conan/76d9e3b/1/boost_1_71_0/tools/build/src/build\toolset.jam:44: in toolset.using
*** argument error
* rule python.init ( version ? : cmd-or-prefix ? : includes * : libraries ? : condition * : extension-suffix ? )
* called with: ( 3.7 : c:/program files (x86)/microsoft visual studio/shared/python37_64/python.exe : c:/program files (x86)/microsoft visual studio/shared/python37_64/Include : c:/program files (x86)/microsoft visual studio/shared/python37_64/libs/python37.lib :  :  :  :  )
* extra argument files
C:/.conan/76d9e3b/1/boost_1_71_0/tools/build/src/tools\python.jam:104:see definition of rule 'python.init' being called
C:/.conan/76d9e3b/1/boost_1_71_0/tools/build/src/build\project.jam:1104: in using
C:\.conan\76d9e3b\1\boost_1_71_0\tools\build\user-config.jam:4: in modules.load
C:/.conan/76d9e3b/1/boost_1_71_0/tools/build/src\build-system.jam:255: in load-config
C:/.conan/76d9e3b/1/boost_1_71_0/tools/build/src\build-system.jam:453: in load-configuration-files
C:/.conan/76d9e3b/boost/1.71.0@conan/stable: 1/boost_1_71_0/tools/build/src\build-system.jam:607: in load
C:\.conan\76d9e3b\1\boost_1_71_0\tools\build\src/kernel\modules.jam:295: in import
C:\.conan\76d9e3b\1\boost_1_71_0\tools\build\src/kernel/bootstrap.jam:139: in boost-build
C:\.conan\76d9e3b\1\boost_1_71_0\boost-build.jam:17: in module scope
boost/1.71.0@conan/stable:
ERROR: Package '3edd3b9a08746c354067f603f944ea7bafe9731b' build failed
boost/1.71.0@conan/stable: WARN: Build folder C:\.conan\19a2a8f\1
ERROR: boost/1.71.0@conan/stable: Error in build() method, line 439
        self.run(full_command, run_environment=True)
        ConanException: Error 1 while executing C:\.conan\76d9e3b\1\boost_1_71_0\tools\build\b2.exe target-os=windows architecture=x86 address-model=64 binary-format=pe abi=ms --layout=system -sBOOST_BUILD_PATH=C:\.conan\76d9e3b\1\boost_1_71_0\tools\build -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=1 -sNO_ZSTD=1 runtime-link=shared threading=multi link=static variant=release toolset=msvc  boost.locale.icu=off -j8 --abbreviate-paths -d2 --debug-configuration --build-dir="C:\.conan\19a2a8f\1"
CMake Error at cmake/conan.cmake:399 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:485 (conan_cmake_install)
  CMakeLists.txt:15 (conan_cmake_run)

-- Configuring incomplete, errors occurred!

**Comment by Croydon** [comment]
This Boost recipe here is now achieved. Please close this issue

Please switch to the new Conan Center Index version of Boost (`boost/1.71.0`) and if it persists report the problem there

https://github.com/conan-io/conan-center-index/
