### ISSUE TITLE
[OpenCV] 4.1.1 conan stable crosscompile to iOS fails on OSX with UIKit.h not found

### ISSUE THREAD

**Issue by jakschewitz** [conan-community/community#293]
### Package Details
* Package Name/Version: **opencv/4.1.1/conan/stable**
* Operating System: **OSX**
* Operation System Version: **OSX 10.14.6**
* Compiler+version: **apple-clang 10.0**
* Conan version: **conan 1.17.0**
* Python version: **python 3.7.0**

### Steps to reproduce
rm -rf build;mkdir build;(cd build;conan install .. -p iOS -o opencv:shared=True --build);conan create . conan/stable -p iOS -o opencv:shared=True

### Build logs
-- General configuration for OpenCV 4.1.1 =====================================
--   Version control:               unknown
-- 
--   Platform:
--     Timestamp:                   2019-11-04T12:39:55Z
--     Host:                        Darwin 18.7.0 x86_64
--     Target:                      Darwin 12.0
--     CMake:                       3.13.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               Release
-- 
--   CPU/HW features:
--     Baseline:
--       requested:                 DETECT
-- 
--   C/C++:
--     Built as dynamic libs?:      NO
--     C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  (ver 10.0.1.10010046)
--     C++ flags (Release):         -stdlib=libc++   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG   -DNDEBUG
--     C++ flags (Debug):           -stdlib=libc++   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body  -fvisibility=hidden -fvisibility-inlines-hidden -g   -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body  -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG   -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body  -fvisibility=hidden -fvisibility-inlines-hidden -g   -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):      
--     Linker flags (Debug):        
--     ccache:                      NO
--     Precompiled headers:         NO
--     Extra dependencies:          /Users/rlj/.conan/data/libwebp/1.0.0/bincrafters/stable/package/987cb0f1279f139e4c3102a9f1583f37f6f1d612/lib/libwebp.a /Users/rlj/.conan/data/libpng/1.6.37/bincrafters/stable/package/6802f1948c0edd39382cfa1c774753ee6114725f/lib/libpng.a /Users/rlj/.conan/data/zlib/1.2.11/conan/stable/package/b251037818d02446e69a13d156e15cd201dd26d2/lib/libz.a /Users/rlj/.conan/data/libtiff/4.0.9/bincrafters/stable/package/6802f1948c0edd39382cfa1c774753ee6114725f/lib/libtiff.a /Users/rlj/.conan/data/jasper/2.0.14/conan/stable/package/d38de087db55adfbdc74a41121f26dd9d3863362/lib/libjasper.a /Users/rlj/.conan/data/libjpeg/9c/bincrafters/stable/package/b251037818d02446e69a13d156e15cd201dd26d2/lib/libjpeg.a -framework Accelerate -framework CoreGraphics -framework QuartzCore -framework AssetsLibrary
--     3rdparty dependencies:       ade
-- 
--   OpenCV modules:
--     To be built:                 calib3d core features2d flann gapi highgui imgcodecs imgproc ml objdetect photo stitching video videoio
--     Disabled:                    java_bindings_generator python_bindings_generator world
--     Disabled by dependency:      -
--     Unavailable:                 dnn java js python2 python3 ts
--     Applications:                -
--     Documentation:               NO
--     Non-free algorithms:         NO
-- 
--   GUI: 
-- 
--   Media I/O: 
--     ZLib:                        /Users/rlj/.conan/data/zlib/1.2.11/conan/stable/package/b251037818d02446e69a13d156e15cd201dd26d2/lib/libz.a (ver 1.2.11)
--     JPEG:                        /Users/rlj/.conan/data/libjpeg/9c/bincrafters/stable/package/b251037818d02446e69a13d156e15cd201dd26d2/lib/libjpeg.a (ver 90)
--     WEBP:                        /Users/rlj/.conan/data/libwebp/1.0.0/bincrafters/stable/package/987cb0f1279f139e4c3102a9f1583f37f6f1d612/lib/libwebp.a (ver encoder: 0x020e)
--     PNG:                         /Users/rlj/.conan/data/libpng/1.6.37/bincrafters/stable/package/6802f1948c0edd39382cfa1c774753ee6114725f/lib/libpng.a (ver 1.6.37)
--     TIFF:                        /Users/rlj/.conan/data/libtiff/4.0.9/bincrafters/stable/package/6802f1948c0edd39382cfa1c774753ee6114725f/lib/libtiff.a (ver 42 / 4.0.9)
--     JPEG 2000:                   /Users/rlj/.conan/data/jasper/2.0.14/conan/stable/package/d38de087db55adfbdc74a41121f26dd9d3863362/lib/libjasper.a (ver 2.0.14)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
-- 
--   Video I/O:
--     DC1394:                      NO
--     AVFoundation:                YES
--     iOS capture:                 YES
-- 
--   Parallel framework:            GCD
-- 
--   Trace:                         YES (built-in)
-- 
--   Other third-party libraries:
--     Eigen:                       YES (ver 3.3.7)
--     Custom HAL:                  NO
-- 
--   Python (for build):            NO
-- 
--   Install to:                    /Users/rlj/.conan/data/opencv/4.1.1/conan/stable/package/65a488ffa54a95fe713d6d039772c0dd16ce11b5

[ 52%] Building CXX object source_subfolder/modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/ios_conversions.mm.o
/Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/65a488ffa54a95fe713d6d039772c0dd16ce11b5/source_subfolder/modules/imgcodecs/src/ios_conversions.mm:43:9: fatal error: 'UIKit/UIKit.h' file not found
#import <UIKit/UIKit.h>

### profile used
conan-opencv-release-4.1.1-ios-fix > conan profile show iOS
Configuration for profile iOS:

[settings]
os=iOS
os_build=Macos
arch=armv8
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
os.version=12.0
[options]
opencv:openexr=False
opencv:protobuf=False
[build_requires]
[env]

###  Observations
1) -framework UIKit missing in "--     Extra dependencies: "
2) build_subfolder/CMakeVars.txt has only MacOS SDK paths (there's no UIKit on MacOS)
3) non-Conan OpenCV 4.1.1 build-arm64-iphoneos/CMakeVars.txt has the correct SDKs/iPhoneOS12.4.sdk

**Comment by jakschewitz** [comment]
the commandline for building ios_conversions.mm when using _conan create_ is:

[ 52%] Building CXX object source_subfolder/modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/ios_conversions.mm.o

cd /Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/65a488ffa54a95fe713d6d039772c0dd16ce11b5/build_subfolder/source_subfolder/modules/imgcodecs 
&& /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  
-DHAVE_IMGCODEC_HDR 
-DHAVE_IMGCODEC_PFM 
-DHAVE_IMGCODEC_PXM 
-DHAVE_IMGCODEC_SUNRASTER 
-DHAVE_WEBP 
-D_USE_MATH_DEFINES 
-D__OPENCV_BUILD=1 
-D__STDC_CONSTANT_MACROS 
-D__STDC_FORMAT_MACROS 
-D__STDC_LIMIT_MACROS 
-I/Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/65a488ffa54a95fe713d6d039772c0dd16ce11b5/source_subfolder/modules/imgcodecs/include 
-I/Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/65a488ffa54a95fe713d6d039772c0dd16ce11b5/build_subfolder/source_subfolder/modules/imgcodecs 
-I/Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/65a488ffa54a95fe713d6d039772c0dd16ce11b5/source_subfolder/modules/core/include 
-I/Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/65a488ffa54a95fe713d6d039772c0dd16ce11b5/source_subfolder/modules/imgproc/include 
-isystem /Users/rlj/.conan/data/libtiff/4.0.9/bincrafters/stable/package/6802f1948c0edd39382cfa1c774753ee6114725f/include 
-isystem /Users/rlj/.conan/data/libwebp/1.0.0/bincrafters/stable/package/987cb0f1279f139e4c3102a9f1583f37f6f1d612/include 
-isystem /Users/rlj/.conan/data/libpng/1.6.37/bincrafters/stable/package/6802f1948c0edd39382cfa1c774753ee6114725f/include 
-isystem /Users/rlj/.conan/data/jasper/2.0.14/conan/stable/package/d38de087db55adfbdc74a41121f26dd9d3863362/include 
-isystem /Users/rlj/.conan/data/eigen/3.3.7/conan/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/eigen3 
-isystem /Users/rlj/.conan/data/zlib/1.2.11/conan/stable/package/b251037818d02446e69a13d156e15cd201dd26d2/include 
-isystem /Users/rlj/.conan/data/libjpeg/9c/bincrafters/stable/package/b251037818d02446e69a13d156e15cd201dd26d2/include 
-isystem /Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/65a488ffa54a95fe713d6d039772c0dd16ce11b5/build_subfolder  
-stdlib=libc++   
-fsigned-char 
-W 
-Wall 
-Werror=return-type 
-Werror=non-virtual-dtor 
-Werror=address 
-Werror=sequence-point 
-Wformat 
-Werror=format-security 
-Wmissing-declarations 
-Wmissing-prototypes 
-Wstrict-prototypes 
-Wundef 
-Winit-self 
-Wpointer-arith 
-Wshadow 
-Wsign-promo 
-Wuninitialized 
-Winit-self 
-Winconsistent-missing-override 
-Wno-delete-non-virtual-dtor 
-Wno-unnamed-type-template-args 
-Wno-comment -fdiagnostics-show-option 
-Qunused-arguments 
-Wno-semicolon-before-method-body  
-fvisibility=hidden 
-fvisibility-inlines-hidden 
-Wno-deprecated-declarations 
-O3 
-DNDEBUG   
-DNDEBUG 
**-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk** 
-fPIC   
-std=c++11 
-o CMakeFiles/opencv_imgcodecs.dir/src/ios_conversions.mm.o 
-c /Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/65a488ffa54a95fe713d6d039772c0dd16ce11b5/source_subfolder/modules/imgcodecs/src/ios_conversions.mm

/Users/rlj/.conan/data/opencv/4.1.1/conan/stable/build/65a488ffa54a95fe713d6d039772c0dd16ce11b5/source_subfolder/modules/imgcodecs/src/ios_conversions.mm:43:9: fatal error: 'UIKit/UIKit.h' file not found

-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
with os=iOS and arch=armv8 shouldn't this be 
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk

**Comment by jakschewitz** [comment]
@bvnp43 pointed out that APPLE_FRAMEWORK is needed to include UIKit, so

adding APPLE_FRAMEWORK in conanfile.py like so
```
if str(self.settings.os) in ["iOS", "watchOS", "tvOS"]:
cmake.definitions['IOS'] = True
cmake.definitions['APPLE_FRAMEWORK'] = True
```
adds '-framework UIKit' to the compile command,

but as the isysroot is defined as
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk`
by the build system UIKit is not found, since it's only part of iPhone SDKs.

I'm puzzled about this isysroot setting for os=iOS and arch=armv8.

The MacOS path seems to be needed for the compiler tests, while the iPhone path is definitely needed for cross-compiling on MacOS for iOS.

**Comment by bvnp43** [comment]
@jakschewitz @SSE4 https://docs.conan.io/en/1.6/systems_cross_building/cross_building.html#example-darwin-toolchain
I've tried it, seems working 

```
bvnp43@toy:~/.conan/profiles$ cat iOS 
include(default)

[settings]
os=iOS
os_build=Macos
arch=armv8
arch_build=x86_64
compiler=apple-clang
compiler.version=11.0
compiler.libcxx=libc++
build_type=Release
os.version=12.1
[options]
opencv:contrib=False
opencv:ffmpeg=False
opencv:freetype=False
opencv:harfbuzz=False
opencv:tiff=False
opencv:png=False
opencv:webp=False
opencv:openexr=False
[build_requires]
darwin-toolchain/1.0.4@theodelrieu/stable
[env]
```

and your commands

```
rm -rf build;mkdir build;(cd build;conan install .. -p iOS --build);conan create . conan/stable -p iOS
```

This is not needed
```
cmake.definitions['APPLE_FRAMEWORK'] = True
```

```
bvnp43@toy:~/.conan/data/opencv/4.1.1/conan/stable/package/6e33785ed4acbfba66cbf6b74a99b666b62f11f0/lib$ ls -la
total 156096
drwxr-xr-x  19 yura  staff   608B Nov  5 19:26 ./
drwxr-xr-x  10 yura  staff   320B Nov  5 19:26 ../
-rw-r--r--   1 yura  staff   1.0M Nov  5 19:26 libade.a
-rw-r--r--   1 yura  staff   7.6M Nov  5 19:26 libopencv_calib3d.a
-rw-r--r--   1 yura  staff    11M Nov  5 19:26 libopencv_core.a
-rw-r--r--   1 yura  staff    15M Nov  5 19:26 libopencv_dnn.a
-rw-r--r--   1 yura  staff   2.4M Nov  5 19:26 libopencv_features2d.a
-rw-r--r--   1 yura  staff   1.3M Nov  5 19:26 libopencv_flann.a
-rw-r--r--   1 yura  staff    14M Nov  5 19:26 libopencv_gapi.a
-rw-r--r--   1 yura  staff   168K Nov  5 19:26 libopencv_highgui.a
-rw-r--r--   1 yura  staff   1.3M Nov  5 19:26 libopencv_imgcodecs.a
-rw-r--r--   1 yura  staff    11M Nov  5 19:26 libopencv_imgproc.a
-rw-r--r--   1 yura  staff   2.9M Nov  5 19:26 libopencv_ml.a
-rw-r--r--   1 yura  staff   1.2M Nov  5 19:26 libopencv_objdetect.a
-rw-r--r--   1 yura  staff   2.6M Nov  5 19:26 libopencv_photo.a
-rw-r--r--   1 yura  staff   2.5M Nov  5 19:26 libopencv_stitching.a
-rw-r--r--   1 yura  staff   1.2M Nov  5 19:26 libopencv_video.a
-rw-r--r--   1 yura  staff   1.4M Nov  5 19:26 libopencv_videoio.a
-rw-r--r--   1 yura  staff    64K Nov  5 19:26 libquirc.a
bvnp43@toy:~/.conan/data/opencv/4.1.1/conan/stable/package/6e33785ed4acbfba66cbf6b74a99b666b62f11f0/lib$ lipo -info libopencv_core.a
Non-fat file: libopencv_core.a is architecture: arm64
```

Also need some changes in test_package cause i'm getting 

```
[100%] Built target lena
opencv/4.1.1@conan/stable (test package): Running test()
/bin/sh: ./lena: Bad CPU type in executable
ERROR: opencv/4.1.2@conan/stable (test package): Error in test() method, line 27
	self.run('lena.exe' if self.settings.os == 'Windows' else './lena', run_environment=True)
	ConanException: Error 126 while executing DYLD_LIBRARY_PATH="/Users/yura/.conan/data/opencv/4.1.1/conan/stable/package/6e33785ed4acbfba66cbf6b74a99b666b62f11f0/lib:/Users/yura/.conan/data/zlib/1.2.11/conan/stable/package/4a15c9aedbef41d2b1c73d593b73cae8b7531f6c/lib:/Users/yura/.conan/data/jasper/2.0.14/conan/stable/package/77f7bf27dc21ff97eb59ec1cdb587b4c80dac504/lib:/Users/yura/.conan/data/protobuf/3.5.2/bincrafters/stable/package/20a28b0f6f841e8c2ed1044b8a14e69f4b66b263/lib:/Users/yura/.conan/data/libjpeg/9c/bincrafters/stable/package/4a15c9aedbef41d2b1c73d593b73cae8b7531f6c/lib" DYLD_FRAMEWORK_PATH="" ./lena
```

png support i disabled cause there were some linking errors with arm neon, others are just my custom settings

**Comment by jakschewitz** [comment]
thanks a million :)
```
[build_requires]
darwin-toolchain/1.0.4@theodelrieu/stable

```
the darwin toolchain solves it all - up to the framework creation

**Comment by SSE4** [comment]
@bvnp43 @jakschewitz if you could create PR with fix(es), would be great

**Comment by jakschewitz** [comment]
what is a PR?
in order to build static libraries no fixes were needed, just the darwin-toolchain had to be added to the profile.
For creating shared libraries there is still issue #294 open.
