### ISSUE TITLE
[fontconfig] package fails to build with conan >= 1.19.3

### ISSUE THREAD

**Issue by planetmarshall** [conan-community/community#295]
### Description of Problem, Request, or Question

fontconfig pakage build fails with the following error:
```
ERROR: fontconfig/2.13.91: Error in build() method, line 70
	self._patch_files()
while calling '_patch_files', line 66
	os.rename('ZLIB.pc', 'zlib.pc')
	FileNotFoundError: [Errno 2] No such file or directory: 'ZLIB.pc' -> 'zlib.pc'
```

### Package Details
* Package Name/Version: **fontconfig/2.13.91**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**
* Compiler+version: **gcc-7.4.0**
* Conan version: **conan 1.19.3**
* Python version: **python 3.7.4**

### Steps to reproduce
```
conan create .
```

### Build logs

Package build fails due to change in behaviour of `pkg-config` generator.
With Conan < 1.19.3
```
conanfile.py (fontconfig/2.13.91): Generator pkg_config created ZLIB.pc
```
With Conan >=1.19.3
```
conanfile.py (fontconfig/2.13.91): Generator pkg_config created zlib.pc
```

**Comment by SSE4** [comment]
fixed by https://github.com/conan-community/conan-fontconfig/pull/8
