### ISSUE TITLE
[OpenCV] 4.1.1 static visual studio fails with multiple errors

### ISSUE THREAD

**Issue by wpalfi** [conan-community/community#298]
* Package Name/Version: opencv/4.1.1@conan/stable
* Operating System: Windows
* Operation System Version: Windows 10
* Compiler+version: vs 15.9.15
* Conan version: conan 1.20.5
* Python version: python 3.6.3

Shared package works as expected. 

But with `opencv:shared=False` I get cmake and linker errors with tiff, eigen and protobuf.

I could get it running with this workaround:

```cmake
if (NOT CONAN_BIN_DIRS_OPENCV)
    set(OpenCV_STATIC ON)
    set(CONAN_LIBTIFF_ROOT ${CONAN_TIFF_ROOT})    
    find_package(Eigen3 REQUIRED)
    
    find_package(protobuf REQUIRED)
    add_library(libprotobuf INTERFACE)
    target_link_libraries(libprotobuf INTERFACE protobuf::libprotobuf)
endif()
```

**Comment by wpalfi** [comment]
This is only when using `find_package(OpenCV)`

As another workaround: Dont use `find_package()` and link to `CONAN_PKG::opencv` instead.

**Comment by SSE4** [comment]
was fixed by https://github.com/conan-community/conan-opencv/pull/50
