### ISSUE TITLE
[ncurses] Error opening terminal: xterm-256color.

### ISSUE THREAD

**Issue by jedenastka** [conan-community/community#301]
### Description of Problem, Request, or Question
My project is compiling with ncurses, but when initscr() is ran, it says `Error opening terminal: xterm-256color.`.

### Package Details (Include if Applicable)
* Package Name/Version: **ncurses/6.1**
* Operating System: **Linux**
* Operation System Version: **Debian 10**
* Compiler+version: **gcc-8.3.0**
* Conan version: **1.21.0**
* Python version: **3.7.3**

### Steps to reproduce
Maybe not steps, but simple program that should work, but doesn't.
```cpp
#include <ncurses.h>

int main() {
    initscr();
    printw("Hello world!");
    getch();
    endwin();
}
```

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
