### ISSUE TITLE
[intel_media_sdk] 2018R2_1 ERROR: Error while initializing settings. Invalid setting 'gcc' is not a valid 'settings.compiler' value. Possible values are ['Visual Studio']

### ISSUE THREAD

**Issue by leyewen** [conan-community/community#303]
### Description of Problem, Request, or Question
intel_media_sdk/2018R2_1@bincrafters/stable for the project with gcc-mingw-w64-8.1.0_x86_64 and cmake-3.15.5 in windows 10 system can't build passed.

### Package Details (Include if Applicable)
Package Name/Version: conan-opencv/4.1.1
Operating System: Windows
Operation System Version: Windows 10
Compiler+version: gcc-mingw-w64-8.1.0_x86_64
Docker image: conanio/gcc8.1
Conan version: conan 1.20.5
Python version: python 3.7.5

### Steps to reproduce (Include if Applicable)
open opencv support ffmpeg
`opencv:ffmpeg=True`

add ffmpeg dependency
`ffmpeg/4.2.1@bincrafters/stable`

cmake build and fail.

It can't build passed with gcc-mingw-w64-8.1.0_x86_64 and cmake-3.15.5 in windows 10 system.

### Fixed method
open file
`.conan\data\intel_media_sdk\2018R2_1\bincrafters\stable\export\conanfile.py`
**1 modify line 18**
src:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

from conans import ConanFile, tools
from conans.model.version import Version
import os


class IntelMediaSDKConan(ConanFile):
    name = "intel_media_sdk"
    version = "2018R2_1"
    url = "https://github.com/bincrafters/conan-intel_media_sdk"
    description = "Intel® Media SDK provides an API to access hardware-accelerated video decode, encode and " \
                  "filtering on Intel® platforms with integrated graphics."
    license = "MIT"
    exports = ["LICENSE.md"]
    settings = {"os": ["Windows"], "arch": ["x86", "x86_64"], "compiler": ["Visual Studio"]}
    _exe_name = 'MediaSDK%s.exe' % version

```
`    settings = {"os": ["Windows"], "arch": ["x86", "x86_64"], "compiler": ["Visual Studio"]}`

desc:
add 'gcc' support to it.
`    settings = {"os": ["Windows"], "arch": ["x86", "x86_64"], "compiler": ["Visual Studio", "gcc"]}`

**2 modify line 57**
src:
`            if int(str(self.settings.compiler.version)) >= 14:`
desc:
`            if self.settings.compiler == "Visual Studio" and int(str(self.settings.compiler.version)) >= 14:`

**3 modify line 67**
src:
`        if self.settings.compiler.runtime != 'MT':`
desc:
`        if self.settings.compiler == "gcc" or self.settings.compiler.runtime != 'MT':`

And then build passed.

Please fixed the bug to conan-intel_media_sdk project.
https://github.com/bincrafters/conan-intel_media_sdk

### Build logs (Include if Available)

> intel_media_sdk/2018R2_1@bincrafters/stable: Downloaded recipe revision 0
> ERROR: Error while initializing settings. Invalid setting 'gcc' is not a valid 'settings.compiler' value.
> Possible values are ['Visual Studio']
> Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

> intel_media_sdk/2018R2_1@bincrafters/stable: Calling package()
> ERROR: intel_media_sdk/2018R2_1@bincrafters/stable: Error in package() method, line 58
> 	if int(str(self.settings.compiler.version)) >= 14:
> 	ValueError: invalid literal for int() with base 10: '8.1'

> intel_media_sdk/2018R2_1@bincrafters/stable: Calling package()
> intel_media_sdk/2018R2_1@bincrafters/stable package(): Packaged 2 '.dll' files: libmfxsw32.dll, mfxplugin32_h264la_hw.dll
> intel_media_sdk/2018R2_1@bincrafters/stable package(): Packaged 21 '.h' files
> intel_media_sdk/2018R2_1@bincrafters/stable package(): Packaged 1 '.lib' file: libmfx.lib
> intel_media_sdk/2018R2_1@bincrafters/stable package(): Packaged 1 '.pdf' file: mediasdk_release_notes.pdf
> intel_media_sdk/2018R2_1@bincrafters/stable package(): Packaged 1 '.rtf' file: Media_SDK_EULA.rtf
> intel_media_sdk/2018R2_1@bincrafters/stable package(): Packaged 1 '.txt' file: redist.txt
> intel_media_sdk/2018R2_1@bincrafters/stable: Package '4576ec72bb1b80956d8fe117b9f92e0bbd7ecdcd' created
> intel_media_sdk/2018R2_1@bincrafters/stable: Created package revision f6f2ea4f43ae2429687034f96a1c8586
> ERROR: intel_media_sdk/2018R2_1@bincrafters/stable: Error in package_info() method, line 67
> 	if self.settings.compiler.runtime != 'MT':
> 	ConanException: 'settings.compiler.runtime' doesn't exist for 'gcc'
> 'settings.compiler' possible configurations are ['cppstd', 'exception', 'libcxx', 'threads', 'version']

**Comment by Croydon** [comment]
https://github.com/bincrafters/community/issues/1075 was the right place to report this problem

Conan-Community is the wrong place, please close this issue

**Comment by leyewen** [comment]
issue in https://github.com/bincrafters/community/issues/1075
