### ISSUE TITLE
[OpenCV] 4.1.1 mingw build fail in precomp.hpp.command.sh

### ISSUE THREAD

**Issue by leyewen** [conan-community/community#305]
### Description of Problem, Request, or Question
Build `opencv/4.1.1@conan/stable ` with `gcc-mingw-w64-8.1.0_x86_64` in windows 10.
It fail in execute `precomp.hpp.command.sh`.

### Package Details
* Package Name/Version: **conan-opencv/4.1.1**
* Operating System: **Windows**
* Operation System Version: **Windows 10**
* Compiler+version: **gcc-mingw-w64-8.1.0_x86_64**
* Docker image: **conanio/gcc8.1**
* Conan version: **conan 1.21.0**
* Python version: **python 3.7.6**

### Steps to reproduce
profile
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=8.1
compiler.libcxx=libstdc++11
compiler.exception=seh
compiler.threads=posix
compiler.cppstd=14
build_type=Debug

[options]

[build_requires]

[env]
CONAN_CMAKE_GENERATOR=MinGW Makefiles

```

conanfile.txt
```
[requires]
opencv/4.1.1@conan/stable
```

### fixed issues

I search and find out one solution:
see
https://github.com/opencv/opencv/issues/14723
https://github.com/opencv/opencv/pull/15225
add `ENABLE_PRECOMPILED_HEADERS` via CMake command.
And then, modify the file `.conan\data\opencv\4.1.1\conan\stable\export\conanfile.py`
in line 209 add:
```
        # mingw can't execute precomp.hpp.command.sh in Windows
        if self.settings.os == 'Windows' and self.settings.compiler == 'gcc':
            cmake.definitions['ENABLE_PRECOMPILED_HEADERS'] = False
```
After, build pretty.

or

**Another fixed method:**
replace OpenCVPCHSupport.cmake with opencv-4.2.0 `OpenCVPCHSupport.cmake`
C:\.conan\d64fea\1\source_subfolder\cmake\OpenCVPCHSupport.cmake
`https://raw.githubusercontent.com/opencv/opencv/4.2.0/cmake/OpenCVPCHSupport.cmake`
This cmake has patch pch and precomp.
build pretty too.

### Build logs

> Scanning dependencies of target pch_Generate_opencv_ml
> [ 11%] Generating precomp.hpp
> [ 11%] Generating precomp.hpp.gch/opencv_ml_Debug.gch
> 
> mingw32-make.exe[2]: *** [source_subfolder\modules\ml\CMakeFiles\pch_Generate_opencv_ml.dir\build.make:64: source_subfolder/modules/ml/precomp.hpp.gch/opencv_ml_Debug.gch] Error 1
> mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:1312: source_subfolder/modules/ml/CMakeFiles/pch_Generate_opencv_ml.dir/all] Error 2
> mingw32-make.exe[1]: *** Waiting for unfinished jobs....
> 
> mingw32-make.exe[2]: *** [source_subfolder\modules\imgproc\CMakeFiles\pch_Generate_opencv_imgproc.dir\build.make:64: source_subfolder/modules/imgproc/precomp.hpp.gch/opencv_imgproc_Debug.gch] Error 1
> mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:1199: source_subfolder/modules/imgproc/CMakeFiles/pch_Generate_opencv_imgproc.dir/all] Error 2
> 
> mingw32-make.exe[2]: *** [source_subfolder\modules\flann\CMakeFiles\pch_Generate_opencv_flann.dir\build.make:64: source_subfolder/modules/flann/precomp.hpp.gch/opencv_flann_Debug.gch] Error 1
> mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:1086: source_subfolder/modules/flann/CMakeFiles/pch_Generate_opencv_flann.dir/all] Error 2
> 
> mingw32-make.exe[2]: *** [source_subfolder\modules\core\CMakeFiles\pch_Generate_opencv_core.dir\build.make:64: source_subfolder/modules/core/precomp.hpp.gch/opencv_core_Debug.gch] Error 1
> mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:973: source_subfolder/modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all] Error 2
> mingw32-make.exe: *** [Makefile:151: all] Error 2
> opencv/4.1.1@conan/stable: 
> opencv/4.1.1@conan/stable: ERROR: Package '783cf24ea219dff5d1db85690867edd9c23b7549' build failed
> opencv/4.1.1@conan/stable: WARN: Build folder C:\.conan\df576c\1
> ERROR: opencv/4.1.1@conan/stable: Error in build() method, line 408
> 	cmake.build()
> 	ConanException: Error 2 while executing cmake --build C:\.conan\df576c\1\build_subfolder -- -j4
>

**Comment by SSE4** [comment]
I am going to add suggested fix, thanks

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
