### ISSUE TITLE
mingw_installer distribution

### ISSUE THREAD

**Issue by ericLemanissier** [conan-community/community#309]
mingw-builds project did not show sign of life for nearly 2 years.  Last version is gcc 8.1.0.
Did someone already considered using another distribution for mingw_installer ? An interesting one is @StephanTLavavej's https://nuwen.net/mingw.html : https://github.com/StephanTLavavej/mingw-distro. It already has gcc 8.2.0 and 9.2.0
I'm not sure at all that there is any sort of abi compatibility between different mingw distribution, so maybe it would be wiser to create a mingw_nuwen package

### Package Details (Include if Applicable)
* Package Name/Version: **mingw_installer/1.0**
* Operating System: **Windows**

**Comment by StephanTLavavej** [comment]
I provide no ABI compatibility guarantees, *especially* not with other distros.

**Comment by qno** [comment]
Hi,

is using this an option - http://winlibs.com ?

**Comment by uilianries** [comment]
Hi!

[MinGW Install](https://conan.io/center/mingw_installer) has been deprecated and will no longer maintained. Please, open a [issue](https://github.com/conan-io/conan-center-index/issues) for a new package request.

Regards.
