### ISSUE TITLE
[eigen] Different Cmake target name on WIndows and Linux

### ISSUE THREAD

**Issue by stefan-gavranovic** [conan-community/community#312]
### Description of Problem, Request, or Question

When using cmake targets generator, target name of Eigen on Windows is `CONAN_PKG::eigen`, while on Linux it is `CONAN_PKG::Eigen3`.

Shouldn't the name be the same across all platforms?

### Package Details (Include if Applicable)
* Package Name/Version: **eigen3:3.3.7**
* Operating System: **Linux/Windows**
* Operation System Version: **Ubuntu 18.04/ Win 10**
* Compiler+version: **gcc-8.3**
* Conan version: **conan 1.20.5**
* Python version: **python 3.7.0**

**Comment by danimtb** [comment]
HI @stefan-gavranovic, we are in the process of moving this recipe to the new central repository for ConanCenter in [conan-io/conan-center-index](https://github.com/conan-io/conan-center-index).

If you are using the recipe from this repo `conan-community` with reference `eigen/3.3.7@conan/stable`, I'd sugest you to try the new package from conan-center-index with the reference `eigen/3.3.7` (without user/channel).

That recipe will be more updated. Thanks!

**Comment by stefan-gavranovic** [comment]
@danimtb Thanks a lot, it worked out. No more issues on different platforms, now the target is defined as `CONAN_PKG::eigen`.

I would like to point out that your suggestion works only for `conanfile.txt`

* `conanfile.txt` 
```
[requires]
eigen/3.3.7
```
* Command Line Interface:
```
conan install eigen/3.3.7@
```
`@` symbol needs to be added at the end.
