### ISSUE TITLE
[ 95%] Built target opencv_dnn gmake: *** [Makefile:152: all] Error 2

### ISSUE THREAD

**Issue by mullerhai** [conan-community/community#314]
### Package Details (Include if Applicable)
* Package Name/Version: ** opencv/4.1.1@conan/stable**
* Operating System: **macos lastest **
* Operation System Version: **macos catalina 10.15.1**
* Compiler+version: **gcc-9 g++-9**

* Conan version: **conan 1.22.2**
* Python version: **conda python 3.6.8**
conan  profile 👍 
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Macos
os_build=Macos
[options]
[build_requires]
cmake_installer/3.15.5@conan/stable
[env]
CXX=g++-9
CC=gcc-9
CMAKE_C_COMPILER=gcc-9

conanfile.txt

[requires]
opencv/4.1.1@conan/stable
[options]
opencv:openexr=False
opencv:contrib=False

cmd : conan install ./conanfile.txt --build missing
### Build logs (Include if Available)
[ 95%] Building CXX object source_subfolder/modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/vulkan/vk_loader.cpp.o
cc1plus: warning: /Users/muller/.conan/data/opencv/4.1.1/conan/stable/build/0bc14574c37035aa8c5293f07b8b6f0b378a587c/build_subfolder/source_subfolder/modules/dnn/precomp.hpp.gch/opencv_dnn_Release.gch: had text segment at different address
[ 95%] Building CXX object source_subfolder/modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx.cpp.o
[ 95%] Building CXX object source_subfolder/modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx2.cpp.o
[ 95%] Building CXX object source_subfolder/modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.o
[ 95%] Linking CXX static library ../../../lib/libopencv_dnn.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../lib/libopencv_dnn.a(THGeneral.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../lib/libopencv_dnn.a(vk_functions.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../lib/libopencv_dnn.a(vk_loader.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../lib/libopencv_dnn.a(THGeneral.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../lib/libopencv_dnn.a(vk_functions.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../lib/libopencv_dnn.a(vk_loader.cpp.o) has no symbols
[ 95%] Built target opencv_dnn
gmake: *** [Makefile:152: all] Error 2
opencv/4.1.1@conan/stable:
opencv/4.1.1@conan/stable: ERROR: Package '0bc14574c37035aa8c5293f07b8b6f0b378a587c' build failed
opencv/4.1.1@conan/stable: WARN: Build folder /Users/muller/.conan/data/opencv/4.1.1/conan/stable/build/0bc14574c37035aa8c5293f07b8b6f0b378a587c
ERROR: opencv/4.1.1@conan/stable: Error in build() method, line 422
	cmake.build()
	ConanException: Error 2 while executing cmake --build '/Users/muller/.conan/data/opencv/4.1.1/conan/stable/build/0bc14574c37035aa8c5293f07b8b6f0b378a587c/build_subfolder' '--' '-j4'

**Comment by mullerhai** [comment]
gmake[2]: *** [source_subfolder/modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:180: source_subfolder/modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_avfoundation_mac.mm.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1995: source_subfolder/modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
gmake: *** [Makefile:152: all] Error 2

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
