### ISSUE TITLE
[opencv] Windows build fails due to libtiff linking errors

### ISSUE THREAD

**Issue by planetmarshall** [conan-community/community#316]
### Description of Problem, Request, or Question

OpenCV 4.1.1 fails to build on Windows platforms due to libtiff linking errors. Looks like there is a mismatch between the OpenCV libjpeg requirement and libtiff's own requirement

### Package Details (Include if Applicable)

* Package Name/Version: **opencv/4.1.1**
* Operating System: **Windows**
* Operation System Version: **Windows 2019 Server**
* Compiler+version: **MSVC 2017 and 2019**
* Conan version: **conan 1.22.2**
* Python version: **python 3.8.1**

### Steps to reproduce (Include if Applicable)

conan create . opencv/4.1.1@ -o opencv:shared=True

### Build logs (Include if Available)

[conan_opencv4_buildlog.txt](https://github.com/conan-community/community/files/4272698/conan_opencv4_buildlog.txt)

**Comment by planetmarshall** [comment]
The `libjpeg` version mismatch is a red herring. This appears to be an issue with linking to  libtiff.

### Workaround

Build OpenCV without libtiff's `jbig` and `lzma` support, eg:

```
conan create . opencv/4.1.1@ -o opencv:shared=True -o libtiff:jbig=False -o libtiff:lzma=False
```

**Comment by SSE4** [comment]
was fixed by https://github.com/conan-community/conan-opencv/pull/50
