### ISSUE TITLE
[lapack] system_requirements failure

### ISSUE THREAD

**Issue by phaile2** [conan-community/community#317]
### Package Details
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**
* Compiler+version: **gcc-8.2**
* Python version: **python 3+**

### Steps to reproduce
Building lapack with gcc > 8

### Build logs
lapack/3.7.1@conan/stable: ERROR: while executing system_requirements(): invalid literal for int() with base 10: '8.2'
ERROR: Error in system requirements

Likely failing on this line 
installer.install("libgfortran-{}-dev".format(int(versionfloat)))
because converting a string with a decimal to an int in python3+ results in an error
should maybe be 
installer.install("libgfortran-{}-dev".format(int(float(versionfloat))))

**Comment by phaile2** [comment]
https://github.com/conan-community/conan-lapack/pull/13

**Comment by uilianries** [comment]
Hi!

[Lapack](https://conan.io/center/lapack) has been deprecated and will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for a new package request.

Regards.
