### ISSUE TITLE
[restclient-cpp] Add restclient-cpp package to community index

### ISSUE THREAD

**Issue by igor-sadchenko** [conan-community/community#320]
# Description of Problem, Request, or Question

Add restclient-cpp package to the latest commit in master of https://github.com/mrtazz/restclient-cpp

Here is the repo with recipe https://github.com/igor-sadchenko/conan-restclient-cpp
# Package Details

Package Name/Version: restclient-cpp:conan
Package repo: https://github.com/igor-sadchenko/conan-restclient-cpp
Source repo: https://github.com/mrtazz/restclient-cpp
Latest commit: mrtazz/restclient-cpp@eeb00a8

**Comment by Croydon** [comment]
Hi @igor-sadchenko!

This is the wrong repository if you wish for a new Conan recipe.

Please request new packages in the issue tracker of the [Conan Center Index](https://github.com/conan-io/conan-center-index). Thanks!

**Comment by uilianries** [comment]
Moved to https://github.com/conan-io/conan-center-index/issues/1307
