### ISSUE TITLE
[OpenCV] 4.1.1 link error while building with with ffmpeg enabled

### ISSUE THREAD

**Issue by daravi** [conan-community/community#321]
### Problem
While building opencv with ffmpeg 4.2.1, build fails to locate ffmpeg dependencies (openjpeg)

I am getting undefined reference errors while building opencv_videoio target from opencv, which uses avcodec from ffmpeg, which in turn uses openjp2 from openjpeg. I see `-lavcodec` in the make invocation of opencv built but not `-lopenjp2`. I'm not sure if this is related to #272 and #273 or not.

### Package Details
* Package Name/Version: **opencv/4.1.1**
* Operating System: **Linux**
* Operation System Version: **CentOS 8**
* Compiler+version: **clang 9.0**
* Conan version: **conan 1.23.0**
* Python version: **python 3.6.8**

### Steps to reproduce
Edit ffmpeg requirement to be ffmpeg/4.2.1 instead of ffmpeg/4.2 then run:
`conan create -s build_type=Debug -o opencv:shared=True -o opencv:ffmpeg=True . opencv/4.1.1@conan/stable`

### Build logs
Attached
[output.txt](https://github.com/conan-community/community/files/4423359/output.txt)
[output_verbose.txt](https://github.com/conan-community/community/files/4423360/output_verbose.txt)

**Comment by ericLemanissier** [comment]
This seems to be caused because transitive requirements are not appended to `cmake.definitions['FFMPEG_LIBRARIES']` (and same for all `cmake.definitions['FOO_LIBRARIES']`)

A function like this could be used :
```
    def _gather_libs(self, p):
        libs = self.deps_cpp_info[p].libs + self.deps_cpp_info[p].system_libs
        for dep in self.deps_cpp_info[p].public_deps:
            libs += self._gather_libs(dep)
        return libs
...
    cmake.definitions['FFMPEG_LIBRARIES'] = ";".join(self._gather_libs('ffmpeg'))

```

**Comment by daravi** [comment]
I wouldn't mind making a PR. But shouldn't this be part of default Conan behavior? i.e. Shouldn't Conan recursively add public dependencies of a dependency to the dependency's cpp_info? The point of cpp_info variables are to allow consumers to use the requirement. If using a requirement requires other dependencies, i.e. if the requirement has a public or interface dependency on another package, shouldn't that package be added to the cpp_info variables? I am not sure if Conan has the concept of public/private/interface levels of dependency but if it doesn't then anything under the the requirement in the dependency graph should be added to the cpp_info variables. Shouldn't it?

**Comment by ericLemanissier** [comment]
a more precise approximation could be:
```
    def _gather_libs(self, p):
        libs = self.deps_cpp_info[p].libs + self.deps_cpp_info[p].system_libs
        if not getattr(self.options[p],'shared', False):
            for dep in self.deps_cpp_info[p].public_deps:
                libs += self._gather_libs(dep)
        return libs
```

**Comment by martin-schulze-vireso** [comment]
> Shouldn't Conan recursively add public dependencies of a dependency to the dependency's cpp_info?

Conan in fact does that. However, the build process for the package does rely on OpenCV's CMakeLists.txt which does not use the conan supplied targets. Instead they `find_package` the conan versions which discards the dependencies. When you build something with the OpenCV conan, all those dependencies are there. (At least thats what I saw while debugging into a similar problem with libtiff's lzma and jbig dependencies.)
