### ISSUE TITLE
import eigen according to new conan package style

### ISSUE THREAD

**Issue by resqsx** [conan-community/community#324]
* Package Name/Version: **opencv/4.1.1**

The eigen package should be included as **eigen/3.3.7** and not **eigen/3.3.7@conan/stable**.

**Comment by danimtb** [comment]
This recipe has been included in [conan-io/conan-center-index](https://github.com/conan-io/conan-center-index) as ``eigen/3.3.7``. The recipe in the conan-community organization has been archived and it will no longer be maintained. Please try the new recipe and report any issue there. Thank you!

**Comment by resqsx** [comment]
But it is still in the opencv package as `eigen/3.3.7@conan/stable`.
See https://github.com/conan-community/conan-opencv/blob/release/4.1.1/conanfile.py line 172.
My report description was a bit short.

**Comment by danimtb** [comment]
oh, sorry. I did not see the report was related to opencv. I'll reopen but please take into account that community efforts are now focused on porting recipes to conan-center-index so this will take low priority. Meanwhile, you can override the eigen dependency with the new reference 😄

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
