### ISSUE TITLE
[opencv/4.1.1] options not propagated to install requirements

### ISSUE THREAD

**Issue by sflis** [conan-community/community#326]
### Description of Problem, Request, or Question
I'm not sure if I'm doing something wrong, but I tried to do a custom build and installation of opencv/4.1.1 with tiff, jasper and openexr disabled by executing the following command:
```shell
conan create . conan/stable-partial -o opencv:tiff=False -o opencv:openexr=False -o opencv:jasper=False 
```
When I tried to use the package from my local cache in my project it still tried to pull down those dependencies that I had disabled. When I ran `conan info` on the package it gave the correct  requirements, however if I ran `conan get` the original conanfile.py was displayed.  It looks like the conaninfo.txt in the package folder was changed to reflect the reduced requirements but conanfile.py in the export folder was not changed. 

Is this working as expected? I might be doing something wrong. What is the procedure if I want to build and install a custom version of a package with reduced requirements? 

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.1.1**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 18.04**
* Compiler+version: **gcc-8.3.0**
* Conan version: **conan 1.21.0**
* Python version: **python 3.6.9**

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
