### ISSUE TITLE
To be moved to CCI

### ISSUE THREAD

**Issue by uilianries** [conan-community/community#327]
### Description of Problem, Request, or Question

Here is the list of packages which are provided by Conan Community and need to be ported:

- [x] arduinojson/5.13.0@conan/stable
- [x] box2d/2.3.1@conan/stable
- [x] fontconfig/2.13.91@conan/stable
- [x] lapack/3.7.1@conan/stable
- [x] libimagequant/2.12.2@conan/stable
- [x] ~mili/17@conan/stable~ see https://github.com/conan-community/community/issues/327#issuecomment-754153837
- [x] mingw_installer/1.0@conan/stable
- [x] muparser/2.2.6@conan/stable
- [x] ncurses/6.1@conan/stable
- [x] opencv/2.4.13.5@conan/stable
- [x] opencv/3.4.5@conan/stable
- [x] opencv/4.1.1@conan/stable
- [x] parallelstl/20181004@conan/stable
- [x] pistache/d5608a1@conan/stable
- [x] relapack/1.0@conan/stable
- [x] tiny-dnn/0.1.1@conan/stable
- [x] wiringpi/2.50@conan/stable

**Comment by Croydon** [comment]
ncruses is done via https://github.com/conan-io/conan-center-index/pull/994

And also the regular reminder to archive https://github.com/conan-community/conan-ncurses

Thanks!

**Comment by uilianries** [comment]
Thanks @Croydon I'll archive ASAP!

**Comment by uilianries** [comment]
no, thank you for this remind!

**Comment by Croydon** [comment]
https://github.com/conan-community/conan-arduinojson is done via https://github.com/conan-io/conan-center-index/pull/1878

**Comment by Croydon** [comment]
https://github.com/conan-community/conan-box2d done via https://github.com/conan-io/conan-center-index/pull/1879

**Comment by Croydon** [comment]
https://github.com/conan-community/conan-parallelstl got renamed upstream to onedpl and is done via https://github.com/conan-io/conan-center-index/pull/2072

**Comment by Croydon** [comment]
OpenCV 2 is done via https://github.com/conan-io/conan-center-index/pull/2743

**Comment by uilianries** [comment]
Thank you @Croydon

**Comment by Croydon** [comment]
OpenCV 4 done via https://github.com/conan-io/conan-center-index/pull/3409

I think this issue deserves it to be pinned :)

**Comment by Croydon** [comment]
Pistache done via https://github.com/conan-io/conan-center-index/pull/3719

https://github.com/conan-community/conan-pistache can be archived

**Comment by uilianries** [comment]
The package `mili/17@conan/stable` is complicated. The project disappeared from Bitbucket and the downloaded package it's from an old Google storage. There is a reference about that project: https://github.com/MariadeAnton/MiLi but its last commit is from 2016.

I vote for deprecating Mili without moving to CCI.

**Comment by Croydon** [comment]
Agreed. If it is desired, people can re-request it.

**Comment by danimtb** [comment]
yeah, agree

**Comment by Croydon** [comment]
Since all OpenCV versions are now done since https://github.com/conan-io/conan-center-index/pull/3465

Happy mass closing of issues and pull requests 😁  

https://github.com/conan-community/community/issues?q=is%3Aissue+is%3Aopen+opencv

https://github.com/conan-community/conan-opencv/pulls

and archiving of the repository

**Comment by Croydon** [comment]
wiringpi is done https://github.com/conan-io/conan-center-index/pull/4118

**Comment by uilianries** [comment]
MuParser: https://github.com/conan-io/conan-center-index/pull/4228

**Comment by uilianries** [comment]
All package from Conan Community has been or deprecated.

As users are not requesting those few last package we deprecated them instead for moving to CCI.

Anyone is able to open an issue to CCI requesting their port, no problem.

**Comment by danimtb** [comment]
Thanks a lot guys for the collaboration! I am finally closing this issue and continue with the next steps
