### ISSUE TITLE
[opencv] Make android build setup more explicit/canonical

### ISSUE THREAD

**Issue by martin-schulze-vireso** [conan-community/community#332]
### Description of Problem, Request, or Question

There is some history of android related changes in the conanfile.py but it seems they are geared towards different build setups.

Currently, the following setups in android might be encountered:

* standalone toolchain via make_standalone_toolchain.py ([deprecated](https://developer.android.com/ndk/guides/standalone_toolchain) since r19)
* standalone NDK usage as seen in the conanio/android-clang8* docker containers
  * these containers need considerable setup to work correctly, which is not available in local settings with `--build missing`
  * only come with NDK r19 (clang 8)
* newest NDK r21 (clang 9) for multiple platforms (the [current downloadable form](https://developer.android.com/ndk/downloads)) with platform specific tool prefix
  * the setup we might encounter on dev systems where Android builds are delivered for multiple platforms (e.g. different armv7/8 phones and some (x86) emulators)

Additionally, these might be driven via the Android NDKs toolchain file or via CMake's built in Android support.

Google discourages the use of CMake's built in Android support but has an [ongoing ticket](https://github.com/android/ndk/issues/463) about merging their efforts.

How can we avoid breaking one setup by fixing the other? Is there a standard android setup for this package that must always work?

#### Context

I am trying to get the build working on my local dev machine with `--build missing`. The CMake project that uses OpenCV is embedded in a gradle build which might be run from inside Android studio. There is no conan repository yet, as we are just testing if using conan is viable here.
I ran into following problems:

1. using the my custom toolchain file as in https://docs.conan.io/en/latest/integrations/cross_platform/android.html#using-toolchain-from-android-ndk via CONAN_CMAKE_TOOLCHAIN_FILE breaks the build: 
```
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```
2. CMake's internal android support via the environment variable CONAN_CMAKE_ANDROID_NDK fails on linking OpenCV because OpenCV internally uses the ANDROID_NDK_ABI_NAME variable which is only set in the toolchain file. This changes the output folder from staticlibs/x85 to /staticlibs which conan does not expose as libdir so libraries are not found

I can work around that by adding `cmake.definitions['ANDROID_NDK_ABI_NAME']` in conanfile.py. However, I am not sure if this interferes when using the toolchain file. I did not find another way to pass the CMake definition through conan than to patch conanfile.py since https://github.com/conan-io/conan/issues/3099 is still open.

**Comment by SSE4** [comment]
the bad thing about android that there is no canonical way - there is CMake built-in support, there is NDK provided toolchain file, and there are tons of 3rd-party toolchain files. then NDK itself maybe installed via several ways, e.g. as part of Android Studio, as standalone toolchain (via NDK script), or as 3rd-party thing (e.g. crystax ndk). some of that approaches only support certain versions of SDK. and we probably have to support all of them.

**Comment by SSE4** [comment]
for the particulal error:
```
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```
1. add `make/4.2.1@` as build requirement to conan profile
```
[build_requirements]
make/4.2.1
```
2. use ninja by adding `ninja/1.9.0` as build requirement and specifying `CONAN_CMAKE_GENERATOR=Ninja`:
```
[build_requires]
ninja/1.9.0
[env]
CONAN_CMAKE_GENERATOR=Ninja
```

**Comment by martin-schulze-vireso** [comment]
> the bad thing about android that there is no canonical way

Yes, that was what I was getting at: If we want to maintain a build recipe that works for android we will be seeing changes that come from different build setups which might conflict with each other. Just take my [current PR](https://github.com/conan-community/conan-opencv/pull/54): How do we know it does not break another workflow? 

I am proposing to nail down one specific workflow via CI and if that breaks the change is not acceptable. The conanio/android-clang build containers are an obvious candidate to nail that down. The  problem with that is that there is only one NDK version available right now and the local app builds might require other clang versions, so we can't even deliver prebuilt versions for all expected consumers with this approach.

> add make/4.2.1@  [...] adding ninja/1.9.0
While it is nice to see that delivering make or ninja via conan is possible, I don't think it was the problem here, since it is available from PATH. Somehow, specifying a toolchain file seems to break all sorts of automation inside CMake in my case.

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
