### ISSUE TITLE
OpenCV package links against system installation of Eigen3

### ISSUE THREAD

**Issue by CraigCarey** [conan-community/community#333]
### Description of Problem, Request, or Question
OpenCV package links against system installation of Eigen3 if it's present, rather than Conan Eigen3. This results in an unfound target error when trying to link against the Conan OpenCV package.

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.3.0@conan/stable**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 20.04**
* Compiler+version: **gcc-9.3**
* Conan version: **conan 1.26.1**
* Python version: **python 3.8.2**
* CMake version: **cmake 3.17.3**

#### conanfile.txt
```
[requires]
opencv/4.3.0@conan/stable

[generators]
cmake_paths
```

```bash
sudo apt install -y libeigen3-dev
conan install . --build=missing
grep -ir Eigen3_DIR  ~/.conan/data/opencv

> /home/craig/.conan/data/opencv/4.3.0/conan/stable/build/9874bf13399d88250fbbdc528696a0302fd27b51/build_subfolder/CMakeVars.txt:Eigen3_DIR=/usr/lib/cmake/eigen3
> /home/craig/.conan/data/

sudo apt purge -y libeigen3-dev
conan remove -f opencv
conan install . --build=missing
grep -ir Eigen3_DIR  ~/.conan/data/opencv

/home/craig/.conan/data/opencv/4.3.0/conan/stable/build/9874bf13399d88250fbbdc528696a0302fd27b51/build_subfolder/CMakeVars.txt:Eigen3_DIR=Eigen3_DIR-NOTFOUND
/home/craig/.conan/data/opencv/4.3.0/conan/stable/build/9874bf13399d88250fbbdc528696a0302fd27b51/build_subfolder/CMakeCache.txt:Eigen3_DIR:PATH=Eigen3_DIR-NOTFOUND
```

### Build logs (Include if Available)
```bash
The file was found at

    /home/craig/.conan/data/opencv/4.3.0/conan/stable/package/4a0115866937e82a7327e477119070e3dbae4a8b/cmake/OpenCVConfig.cmake



-- Configuring done
CMake Error at CMakeLists.txt:72 (add_executable):
  Target "skeleton_tester" links to target "Eigen3::Eigen" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
