### ISSUE TITLE
[opencv] Gtk cannot be disabled

### ISSUE THREAD

**Issue by SalDiAngelus** [conan-community/community#336]
### Description of Problem, Request, or Question
Checking for none when setting cmake.definitions['WITH_GTK'] is incorrect. 'is not None' should be '!= 'None''. See https://docs.conan.io/en/latest/reference/conanfile/attributes.html#options where it says

> Comparison using is is always equals to False because the types would be different as the option value is encapsulated inside a Conan class.

### Package Details
* Package Name/Version: **opencv/4.3.0**

### Steps to reproduce
conan install opencv/4.3.0@conan/stable -o gtk=None -b opencv

### Build logs (Include if Available)
--   GUI:
--     GTK+:                        YES (ver 3.22.30)
--       GThread :                  YES (ver 2.56.4)
--       GtkGlExt:                  NO
--     VTK support:                 NO

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
