### ISSUE TITLE
[OpenCV] Harfbuzz glib version conflicts with GTK compatibility

### ISSUE THREAD

**Issue by ryanseipp** [conan-community/community#337]
### Description of Problem, Request, or Question
When building OpenCV with GTK2/3 support and contrib modules, Harfbuzz introduces outdated glib dependency that doesn't match requirement for GTK support and overrides system version. Requires user to either disable harfbuzz option, or introduce updated dependency on glib. Appears harfbuzz conan package >= 2.6.4 updates its glib dependency to above the threshold of 2.59.2. Would submit a PR but do not have time to test the updated version.

System glib version:
```sh
pkg-config --modversion glib-2.0
2.64.4
```
[Relevant lines from current opencv harfbuzz version recipe](https://github.com/bincrafters/conan-harfbuzz/blob/stable/2.4.0/conanfile.py#L46)

I'm currently unsure why harfbuzz's glib version overrides the system glib version when building opencv, although I can understand how linking against two versions of the same library in one program gets troublesome. Unfortunately I don't have the time to investigate this further.

### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.3.0@conan/stable**
* Operating System: **Linux**
* Operation System Version: **Manjaro Linux (kernel 5.6.19-2)**
* Compiler+version: **gcc-10.1.0**
* Conan version: **conan 1.28.0**
* Python version: **python 3.8.3-1**

### Steps to reproduce (Include if Applicable)
```
[requires]
opencv/4.3.0@conan/stable

[generators]
cmake

[options]
opencv:contrib=True
opencv:gtk=3
```

### Build logs (Include if Available)
```
-- Checking for module 'gtk+-3.0'
--   Package dependency requirement 'gobject-2.0 >= 2.59.2' could not be satisfied.
Package 'gobject-2.0' has version '2.58.3', required version is '>= 2.59.2'
Package dependency requirement 'gobject-2.0 >= 2.59.2' could not be satisfied.
Package 'gobject-2.0' has version '2.58.3', required version is '>= 2.59.2'
-- Checking for module 'gtk+-2.0'
--   Package dependency requirement 'gobject-2.0 >= 2.59.2' could not be satisfied.
Package 'gobject-2.0' has version '2.58.3', required version is '>= 2.59.2'
Package dependency requirement 'gobject-2.0 >= 2.59.2' could not be satisfied.
Package 'gobject-2.0' has version '2.58.3', required version is '>= 2.59.2'
Package dependency requirement 'gobject-2.0 >= 2.59.2' could not be satisfied.
Package 'gobject-2.0' has version '2.58.3', required version is '>= 2.59.2'
-- Checking for module 'gthread-2.0'
--   Found gthread-2.0, version 2.58.3
```
```
--   GUI: 
--     GTK+:                        NO
```

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
