### ISSUE TITLE
opencv build fails if freetype is enabled on Windows (It worked on Linux)

### ISSUE THREAD

**Issue by nikhiljain217** [conan-community/community#341]
### Package Details (Include if Applicable)
Package Name/Version: opencv/4.1.1@conan/stable
Operating System: Windows
Operation System Version: Windows10
Compiler+version: Visual Studio 2019
Conan version: conan 1.18.1
Python version: python 3.7.4

### Steps to reproduce (Include if Applicable)
Building Opencv with contrib  set to True.

###Workaround
Disabling freetype fixes the issue.

### Build logs (Include if Available)

Build logs:
[build_logs.txt](https://github.com/conan-community/community/files/5220530/build_logs.txt)

https://github.com/conan-community/community/issues/272 -- This is similar issue which was fixed by changing the version of freetype in conanfile.py. My opencv conanfile.py is latest. I could see the code changes from this fix in my conanfile.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
