### ISSUE TITLE
Wrong dependency order in Findncurses.cmake for panelw library

### ISSUE THREAD

**Issue by matslil** [conan-community/community#344]
### Package Details (Include if Applicable)
* Package Name/Version: **ncurses/6.1**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Compiler+version: **gcc-5.4**
* Docker image: **N/A**
* Conan version: **conan 1.21.1**
* Python version: **python 2.7.12**

### Steps to reproduce (Include if Applicable)
conan install -g cmake_find_package nurses/6.1@conan/stable -b -o ncurses:with_widec=True

### Build logs (Include if Available)

The generated Findncurses.cmake, line 57:

> set(curses_LIBRARY_LIST formw menuw ncurses++w nurses panelw)

is incorrect, panelw is mentioned too late and causes link errors.

The following worked for me:

> set(ncurses_LIBRARY_LIST formw panelw menuw ncurses++w nursesw)

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!
