### ISSUE TITLE
[boost] building with mingw failes

### ISSUE THREAD

**Issue by Johnnyxy** [conan-community/community#347]
Hi, I am trying to build Boost 1.74.0 with MinGW from Windows.

MinGW bin-folder is in the ```PATH``` and the GCC can be executed via ```gcc``` and ```g++```.

Windows CMD
---------------
Now from a normal Windows ```cmd``` console I can build Boost successfully.

MSYS2 / MSYS2-MinGW
-------------------------
But when I am in a MSYS2 or a MSYS2-MinGW environment then Boost cannot be built because Boost cannot execute the detected gcc/g++-path.
In the Boost recipe the path to the compiler is deduced by checking the environment variable ```CXX``` and if not successful by using the following path detection:
```python
    def _cxx(self):
        ...
        if self.settings.compiler == "gcc":
            return tools.which("g++-%s" % compiler_version) or tools.which("g++-%s" % major) or tools.which("g++") or ""
        ...
```
In MSYS2/MSYS2-MinGW-console this results in ```/mingw64/bin/g++```. Boost is not able to use this path as it needs a Windows-formatted path and stops execution with the following error:
```
warning: toolset gcc initialization:
warning: can not find user-provided command '/mingw64/bin/g++'
```

Problem
--------
Conan uses the ```which``` command as this is the native way to find files in ```PATH``` in a Unix(-like) shell. But in this (maybe special) case the function ```where``` from Windows has to be employed as this would return a Windows-path like this:
```c:\msys64\mingw64\bin\gcc.exe```.

Workaround
-------------
One could set the ```CXX``` environment variable to the full g++-path. Then Boost would use this path and build without problems.
But I would like to avoid that as everything is already known at the point of the Boost-build invocation to detect the correct path automatically.

Question
---------
Is there a quick fix that I did not think of until now?
Otherwise I would just modify the recipe to execute ```where``` when a MSYS2 environment is detected.

Related
--------
A similar problem has been discussed here which led to the ```tools.which``` implementation, I think: https://github.com/conan-community/community/issues/75

**Comment by danimtb** [comment]
boost recipe has been moved to [conan-io/conan-center-index](https://github.com/conan-io/conan-center-index) so please report the issues in that repo and I am sure we can look into the issue. Thanks!

**Comment by Johnnyxy** [comment]
Ouh, yes you are right. I mistook the repos :).
I will open an issue there.
