### ISSUE TITLE
Eigen is out of date

### ISSUE THREAD

**Issue by james-atkins** [conan-community/community#38]
Eigen 3.3.5 was released on the July 23, 2018.

http://eigen.tuxfamily.org/index.php?title=News:Eigen_3.3.5_released!

**Comment by danimtb** [comment]
Merged to `testing/3.3.5` and will be in the stable branch soon

**Comment by danimtb** [comment]
New 3.3.5 stable release: https://bintray.com/conan-community/conan/eigen%3Aconan/3.3.5%3Astable

Use it with the reference: ``eigen/3.3.5@conan/stable``

Thanks for the advice and PR @james-atkins!
