### ISSUE TITLE
docopt does not link

### ISSUE THREAD

**Issue by acgetchell** [conan-community/community#39]
### Package Details (Include if Applicable)
* Package Name/Version: **docopt/0.6.2@conan/stable**
* Operating System: **MacOS**
* Compiler+version: **AppleClang 9.1.0.9020039**

### Steps to reproduce (Include if Applicable)

Without using the docopt package, my CMakefile.txt looks like:

~~~
include_directories (BEFORE ${PROJECT_SOURCE_DIR}/include ${PROJECT_SOURCE_DIR}/src/date/include ${Boost_INCLUDE_DIRS} ${CURL_INCLUDE_DIR})
add_executable(cdt src/cdt.cpp src/docopt/docopt.cpp src/date/src/tz.cpp)
target_link_libraries(cdt PRIVATE ${CGAL_LIBRARIES} ${CGAL_3RD_PARTY_LIBRARIES} ${Boost_LIBRARIES} ${CURL_LIBRARIES})
~~~

Going to Conan, I have:

~~~
include_directories (BEFORE ${PROJECT_SOURCE_DIR}/include ${PROJECT_SOURCE_DIR}/src/date/include ${CURL_INCLUDE_DIR})
add_executable(cdt src/cdt.cpp src/date/src/tz.cpp)
target_link_libraries(cdt PRIVATE ${CGAL_LIBRARIES} ${CGAL_3RD_PARTY_LIBRARIES} CONAN_PKG::boost CONAN_PKG::libcurl CONAN_PKG::TBB CONAN_PKG:docopt)
~~~

But the linker does not find docopt:

/usr/local/bin/cmake --build /Users/adam/CDT-plusplus/build --target cdt -- -j 4
Scanning dependencies of target cdt
[ 66%] Building CXX object CMakeFiles/cdt.dir/src/cdt.cpp.o
[ 66%] Building CXX object CMakeFiles/cdt.dir/src/date/src/tz.cpp.o
[100%] Linking CXX executable bin/cdt
ld: library not found for -lCONAN_PKG:docopt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bin/cdt] Error 1
make[2]: *** [CMakeFiles/cdt.dir/all] Error 2
make[1]: *** [CMakeFiles/cdt.dir/rule] Error 2
make: *** [cdt] Error 2
...`

There seems to be missing the equivalent of `add_executable(cdt src/cdt.app src/docopt/docopt.cpp 
Full diff here:

https://github.com/acgetchell/CDT-plusplus/compare/feature/conan

**Comment by danimtb** [comment]
There is a mistake in your code snippet:

`CONAN_PKG:docopt` should be `CONAN_PKG::docopt`

Give it a try and let me know

**Comment by acgetchell** [comment]
🤦‍♂️ 

So there is, and it works now.

Thanks!
