### ISSUE TITLE
[conan-stb] add GCC 8 & Clang 6 & Apple Clang 9.1

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#42]
### Package Details (Include if Applicable)
* Package Name/Version: **stb/20180214@conan/stable**
* Operating System: **Linux**
* Compiler+version: **gcc-8.2**
* Docker image: **lasote/conangcc8**

### Steps to reproduce (Include if Applicable)

https://github.com/conan-community/conan-stb/pull/1

**Comment by danimtb** [comment]
PR was merged! thanks @SSE4
