### ISSUE TITLE
`conan install zlib/1.2.11@conan/stable` fails

### ISSUE THREAD

**Issue by madebr** [conan-community/community#44]
### Description of Problem, Request, or Question
The command `conan install zlib/1.2.11@conan/stable` fails.
### Package Details (Include if Applicable)
* Package Name/Version: **zlib/1.2.11**
* Operating System: **Windows**
* Compiler+version: **Visual Studio 15 2017**

### Steps to reproduce (Include if Applicable)
```
conan install zlib/1.2.11@conan/stable
```
Output is:
```
zlib/1.2.11@conan/stable: Retrieving from predefined remote 'conan-center'
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt

Downloading conanfile.py

ERROR: C:\Users\maarten\.conan\data\zlib\1.2.11\conan\stable\export\conanfile.py: Error while initializing options. 'tuple' object has no attribute 'split'
```

**Comment by madebr** [comment]
The problem was my system.
- Upgraded to python 3.7, removed the python3.6 folder and force reinstalled conan on python 3.7.

Sorry and thanks for your work..

**Comment by madebr** [comment]
I had a similar problem on my linux system.
```
python3 -m pip install --upgrade --user --force-reinstall conan
```
fixed it.

**Comment by lasote** [comment]
Thanks for the feedback!
