### ISSUE TITLE
[TBB] TBB/2018_U5@conan/stable fails to build on Travis-CI macOS/gcc-8

### ISSUE THREAD

**Issue by acgetchell** [conan-community/community#48]
### Package Details (Include if Applicable)
* Package Name/Version: **TBB/2018_U5**
* Operating System: **macOS 10.13**
* Compiler+version: **gcc-8**

### Steps to reproduce (Include if Applicable)

My .travis.yml file is here:

https://github.com/acgetchell/CDT-plusplus/blob/develop/.travis.yml

Conan:

https://github.com/acgetchell/CDT-plusplus/blob/develop/conanfile.py

CMake:

https://github.com/acgetchell/CDT-plusplus/blob/develop/CMakeLists.txt

It works on Linux/clang, Linux/gcc, and macOS/clang with Travis-CI:

https://travis-ci.org/acgetchell/CDT-plusplus

The failing line for macOS/gcc is `g++-8: error: unrecognized command line option `-stdlib=libc++`:

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/429272545#L1708

Which is odd as I'm setting  `settings.compiler.libcxx=libstdc++11` here:

https://github.com/acgetchell/CDT-plusplus/blob/develop/.travis.yml#L230

**Comment by SSE4** [comment]
@acgetchell this was fixed by https://github.com/conan-community/conan-tbb/pull/9

**Comment by acgetchell** [comment]
This generates a new error:

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/452545060#L1174

**Comment by acgetchell** [comment]
Reverting back to TBB/2018_U5@conan/stable makes the new issue go away.

https://travis-ci.org/acgetchell/CDT-plusplus/builds/452555345

**Comment by SSE4** [comment]
interesting, TBB says `Invalid configuration: Intel-TBB is not supported by clang`, need to check if it's really unsupported configuration

**Comment by acgetchell** [comment]
TBB/2018_U5 at least is supported by clang, as I've been compiling it for months.

**Comment by SSE4** [comment]
@acgetchell okay, I've re-enabled Clang support, please give an another try

**Comment by acgetchell** [comment]
Yes, that error is fixed.

https://travis-ci.org/acgetchell/CDT-plusplus/builds/453740652

It's back to https://github.com/travis-ci/travis-ci/issues/9640

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/453740662#L2184
