### ISSUE TITLE
conan-tweetnacl inclusion review

### ISSUE THREAD

**Issue by danimtb** [conan-community/community#5]
## Inclusion Request Review

This is a review for [conan-tweetnacl](https://github.com/conan-community/conan-tweetnacl) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries]
(http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).
 
### Package
tweetnacl/20140427@conan/stable
 
#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [x] Linter
- [x] Updated
- [x] Clean
- [ ] test_package: **Not working in windows, see PR open** conan-community/conan-tweetnacl#1
- [x] Raise errors on invalid configurations
- [ ] LICENSE of the recipe: **No license in the repo of recipe. Use MIT (Same as Conan)**
- [ ] LICENSE of the library: **No license in the package (Maybe generate file with PUBLIC DOMAIN?)**
- [x] Manages correctly the 'pure_c' parameter and removes libcxx when a C lib
 
#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [x] (If not header only) CI configurations for Linux/MacOSX/Windows
 
#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [ ] Issue tracker **Set issue tracker to conan-community**
- [x] Version control
- [x] GitHub repo (user/repo)
 
### Additional comments
 
I think it would be better to use `source()` to download files from original website

**Comment by pvicente** [comment]
@danimtb addressed requested changes. Please kindly review.

**Comment by danimtb** [comment]
Everything done here and tweetnacl is already in conan-center! 🎉
