### ISSUE TITLE
[boost] Boost 1.68.0 - Wrong linking order

### ISSUE THREAD

**Issue by uilianries** [conan-community/community#51]
### Description of Problem, Request, or Question

Hi!

I'm trying to build Facebook Folly package, but during linkage stage I get the follow error:

```
/home/conan/.conan/data/folly/2018.10.15.00/bincrafters/testing/package/a2b5bbc27f5f32aaf3f11506fa66f3c83eca270f/lib/libfolly.so: undefined reference to `boost::system::detail::generic_category_instance'
/home/conan/.conan/data/folly/2018.10.15.00/bincrafters/testing/package/a2b5bbc27f5f32aaf3f11506fa66f3c83eca270f/lib/libfolly.so: undefined reference to `boost::system::detail::system_category_instance'
```

@vdeurzen reported the same problem on Slack channel Conan:

> I'm having some trouble linking with boost from conan center, I'm missing some of the multithreading symbols it seems, any ideas what I might be doing wrong?
> for example: `boost::system::generic_category()`
> well, that's the first that's missing, I'm considering it may simply be the linking order
or `undefined reference to` > boost::log::v2s_mt_posix::aux::futex_based_event::wait()`

#### Logs:
* Travis: https://travis-ci.org/bincrafters/conan-folly/jobs/444214034#L2201

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.68.0@conan/stable**
* Operating System: **Linux**
* Compiler+version: **gcc-8**
* Docker image: **conanio/gcc8**
* Options: shared=False

### Steps to reproduce (Include if Applicable)

    git clone https://github.com/bincrafters/conan-folly.git
    cd conan-folly
    git checkout testing/2018.10.15.00
    conan create . bincrafters/testing -s build_type=Release -s arch=x86_64 -o folly:shared=True

**Comment by uilianries** [comment]
Up!

**Comment by danimtb** [comment]
This kind of question may deserve a feature in Conan. If it is not possible now, consumers should be able to override link order. Although maybe if you are using CMake you could always use targets and link them in your desired order. Am I wrong?

**Comment by lasote** [comment]
Yes please @SSE4 take a look, thanks

**Comment by SSE4** [comment]
I am not sure targets helps much here - we now have 1 target per recipe, so consumer links with just `CONAN_PKG::boost`

**Comment by uilianries** [comment]
Hi guys! Thanks for helping me!

I could specify all boost libraries needed, but as @SSE4 said, when our consumer links folly by CONAN_PKG::folly or ${CONAN_LIBS}, all Boost libraries will be liked together.

I see no way changing boost libraries from Folly's recipe.

**Comment by danimtb** [comment]
You are right, link order has to be fixed in boost recipe

**Comment by SSE4** [comment]
I have found solution using `boostdep` tool, but it requires to use sources from git. I'll try to find out if there is something different between tarball and git sources, which prevents boostdep work

**Comment by lasote** [comment]
Just in case you are thinking about calling `boostdep` dynamically, we don't want to introduce runtime dependencies to calculate the package_info. 
This issue should be mitigated with https://github.com/conan-io/conan/issues/5090 but it will take time.
In the meantime, I think there should be a right order of specifying the libraries for all cases, right? do we know the right order? does the `boostdep` tool knows?

**Comment by SSE4** [comment]
`boostdep` is part of boost sources. it knows the order, that's right, but it's different for different boost versions. the best thing is to pre-calculate it for each version via simple script, and use hard-coded output of script within the recipe.

**Comment by SSE4** [comment]
wait for components feature and another round of recipe cleanup...

**Comment by SSE4** [comment]
moved to https://github.com/conan-io/conan-center-index/issues/103
