### ISSUE TITLE
[zlib] Feature Request : Minizip support

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#52]
_From @franknarf8 on October 15, 2018 9:2_

Actual :
- The contrib folder is ignored
- Minizip headers and libraries are not packaged

Expected : 
- Zlib `conanfile.py` has a Minizip option that defaults to `false`.

Some guys are already doing it : https://github.com/odant/conan-zlib

Thanks!

_Copied from original issue: conan-community/conan-zlib#53_

**Comment by SSE4** [comment]
@franknarf8 I've added minizip option to the zlib, please give a try

**Comment by franknarf8** [comment]
Hello @SSE4 ,

Everything seems to work, thanks a lot!

Everything works fine (patches applied, code compiled and linked). The following are only very minor things I thought you might like brought up to your attention. I am seeing the following warnings when building on getting the following errors on windows during the source command : 
```
zlib/1.2.11@conan/stable: Configuring sources in C:\Users\MyUser\.conan\data\zlib\1.2.11\conan\stable\source
[==================================================] 607.7KB/607.7KB
WARN: minizip.patch: error: absolute paths are not allowed - file no.1
WARN: minizip.patch: stripping absolute path from source name 'b'/dev/null''
WARN: minizip.patch: error: absolute paths are not allowed - file no.2
WARN: minizip.patch: stripping absolute path from source name 'b'/dev/null''
```

There are also a couple warnings generated by minizip, but it is expected as it is C code. (e.g. `'size_t' to 'unsigned int', possible loss of data`)

With the following profile : 
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
```

Thanks again!

- Frank

**Comment by SSE4** [comment]
@franknarf8  these patch warnings are safe to ignore, they are harmless

**Comment by SSE4** [comment]
confirmed as fixed, closing
