### ISSUE TITLE
[zlib] Building Android version of lib on Windows, can't find stderr, sdtout

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#57]
_From @tanshihaj on July 2, 2018 11:59_

I want to build Android version of zlib on windows.

Step by step:
1. I've downloaded Android NDK r17b and created standalone toolchain:

`C:/path/to/ndk/build/tools/make_standalone_toolchain.py --arch=arm --api=21 --stl=libc++ --install-dir=C:/path/to/toolchain`

2. Created profile:

```
standalone_toolchain=C:/path/to/toolchain
target_host=arm-linux-androideabi
cc_compiler=gcc
cxx_compiler=g++

[build_requires]
cmake_installer/[>2.8.11]@conan/stable

[settings]
os_build=Windows
arch_build=x86_64
os=Android
os.api_level=21
arch=armv7
compiler=gcc
compiler.version=4.9
compiler.libcxx=libstdc++

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain/sysroot
CONAN_CMAKE_GENERATOR="Unix Makefiles"
PATH=[$standalone_toolchain/bin]
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
LD=$target_host-ld
STRIP=$target_host-strip
CFLAGS= -fPIC  -I$standalone_toolchain/include/c++/4.9.x
CXXFLAGS= -fPIC  -I$standalone_toolchain/include/c++/4.9.x
LDFLAGS=
```

3. And tried to build `zlib`:

`conan install "zlib/[>1.0.0]@conan/stable" --build=missing --profile=C:/path/to/profile`

CMake configures, but during linking minigzip I get following error:

```
[ 45%] Linking C executable ../bin/minigzip64
C:/Users/.../.conan/data/zlib/1.2.11/conan/stable/build/9b9c1e032a0e146ebb45b64a243464699bf83fa2/zlib-1.2.11/test/minigzip.c:355: error: undefined reference to 'stderr'
C:/Users/.../.conan/data/zlib/1.2.11/conan/stable/build/9b9c1e032a0e146ebb45b64a243464699bf83fa2/zlib-1.2.11/test/minigzip.c:490: error: undefined reference to 'stderr'
C:/Users/.../.conan/data/zlib/1.2.11/conan/stable/build/9b9c1e032a0e146ebb45b64a243464699bf83fa2/zlib-1.2.11/test/minigzip.c:543: error: undefined reference to 'stderr'
C:/Users/.../.conan/data/zlib/1.2.11/conan/stable/build/9b9c1e032a0e146ebb45b64a243464699bf83fa2/zlib-1.2.11/test/minigzip.c:651: error: undefined reference to 'stdin'
C:/Users/.../.conan/data/zlib/1.2.11/conan/stable/build/9b9c1e032a0e146ebb45b64a243464699bf83fa2/zlib-1.2.11/test/minigzip.c:651: error: undefined reference to 'stdout'
C:/Users/.../.conan/data/zlib/1.2.11/conan/stable/build/9b9c1e032a0e146ebb45b64a243464699bf83fa2/zlib-1.2.11/test/minigzip.c:651: error: undefined reference to 'stderr'
collect2.exe: error: ld returned 1 exit status
make.exe[2]: *** [bin/minigzip64] Error 1
make.exe[1]: *** [zlib-1.2.11/CMakeFiles/minigzip64.dir/all] Error 2
make.exe: *** [all] Error 2
```
I'm actually don't know what should I do now.

_Copied from original issue: conan-community/conan-zlib#39_

**Comment by SSE4** [comment]
_From @lasote on July 4, 2018 6:52_

Hi! I'm not sure if conan has something to do with it. I've found a similar issue googling:

https://github.com/openssl/openssl/issues/3826

They suggest to pass `--deprecated-headers` to the toolchain creation:

> When creating Android NDK toolchain using make_standalone_toolchain.py, pass --deprecated-headers as an argument. Found it reading NDK's changelog.

Let me know if it works please!

**Comment by SSE4** [comment]
@tanshihaj have you tried suggestion about `--deprecated-headers`? if so, did it work for you?

**Comment by tanshihaj** [comment]
Sorry for late reply. I've already find that openssl project issue, however new ndk (I think after version 16) doesn't support --deprecated-headers.

**Comment by SSE4** [comment]
@tanshihaj do you know is there patch or another workaround available?

**Comment by tanshihaj** [comment]
Well, currently I'm trying to solve it, it seems it is possible to solve problem building it with clang rather than gcc. I will reply here if I solve the issue.

**Comment by SSE4** [comment]
@tanshihaj I don't see any way to disable programs from the build when calling configure
however, calling `make libz.a` instead of just `make`, and probably `make install-libs` instead of `make install` may do the trick, see:
https://github.com/madler/zlib/blob/master/Makefile.in#L130
https://github.com/madler/zlib/blob/master/Makefile.in#L306

**Comment by tanshihaj** [comment]
Yes, it seems it works. I've successfully build android version of zlib from macOS and Windows. macOS and Windows versions also builds ok. I can send pull request I think if you need it.

**Comment by SSE4** [comment]
@tanshihaj yep, please send, as other people may suffer from the same problem

**Comment by SSE4** [comment]
@tanshihaj I think now it is fixed, as your changes were merged, can you confirm?

**Comment by tanshihaj** [comment]
Yes, I've checked, it builds for Android from repo.

**Comment by SSE4** [comment]
confirmed as fixed, closing
