### ISSUE TITLE
[zlib] Package not updated

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#59]
_From @TheJare on December 7, 2017 22:37_

I'm not sure where's the right place to file this issue, but the version of this package in bintray (conan-transit) fails to build for me. Win10Pro x64, VS 2017 15.5, CMake 3.10, conan 0.29.2 installed via pip on python 2.7.14.

```
zlib/1.2.11@lasote/stable: WARN: Build folder d:\Soft\conan-home\data\zlib\1.2.11\lasote\stable\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
ERROR: zlib/1.2.11@lasote/stable: Error in build() method, line 59
        cmake = CMake(self.settings)
        ConanException: First argument of CMake() has to be ConanFile. Use CMake(self)
```

I see that line was fixed in https://github.com/lasote/conan-zlib/commit/2a1965eb6070e92a6c2c4bd59bae4ff053391815#diff-2b1d42f71f22b7ea0412d7602dec166fL53 but it does not seem to be in the released package. How can I use this package?

_Copied from original issue: conan-community/conan-zlib#23_

**Comment by SSE4** [comment]
_From @kaidokert on December 10, 2017 22:51_

I just ran into the same issue and reported at conan-io/conan/issues/2136
Is there an Appveyor build set up or can i PR the config for it ?

**Comment by SSE4** [comment]
_From @lasote on December 11, 2017 10:8_

Try to use zlib/1.2.11@conan/stable from conan-center: https://bintray.com/conan-community/conan/zlib%3Aconan

@kaidokert about the related issue you pointed, let us review the docs and get it right.

**Comment by SSE4** [comment]
@TheJare @kaidokert is it still an issue?

**Comment by kaidokert** [comment]
Not sure , i just tried to follow and walk through instructions here : https://docs.conan.io/en/latest/integrations/clion.html

Doesnt work because conan ends up using MSVC toolset and Clion uses Mingw. Forcing -g -g "MinGW Makefiles" doesnt have an effect either. Not sure if i have time to dig through this again

**Comment by SSE4** [comment]
@kaidokert sorry, missed your earlier response
from your command line:
```
conan install . -g "CodeBlocks - MinGW Makefiles"
```
I think it's not quite appropriate usage, as `-g` option here states for conan generator, not CMake generator (see https://docs.conan.io/en/latest/reference/generators.html). so, e.g. you may pass `conan install . -g visual_studio` or `conan install . -g cmake`).

however, there is a way to specify CMake generator to use, there is `CONAN_CMAKE_ENVIRONMENT` variable - see https://docs.conan.io/en/latest/reference/env_vars.html?highlight=conan_cmake_generator

such variable may be specified in profiles, see https://docs.conan.io/en/latest/reference/profiles.html

in general, I recommend you to create a profile for MinGW builds, as in example https://docs.conan.io/en/latest/systems_cross_building/windows_subsystems.html?highlight=mingw

**Comment by SSE4** [comment]
@kaidokert I am closing an issue for now, since question was answered. please open new issue you if still have any problems or questions.
