### ISSUE TITLE
[bzip2] md5 hash check on source tar is broken

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#64]
_From @jeb2239 on October 14, 2018 2:38_

```
bzip2/1.0.6@conan/stable: Building your package in /home/barriosj/.conan/data/bzip2/1.0.6/conan/stable/build/b09bec465fef58dc59f15f359cb57c2007336987
bzip2/1.0.6@conan/stable: WARN: Trying to remove corrupted source folder
bzip2/1.0.6@conan/stable: WARN: This can take a while for big packages
bzip2/1.0.6@conan/stable: Configuring sources in /home/barriosj/.conan/data/bzip2/1.0.6/conan/stable/source
[==================================================] 17.5KB/17.5KB    
bzip2/1.0.6@conan/stable: WARN: Trying to remove corrupted source folder
bzip2/1.0.6@conan/stable: WARN: This can take a while for big packages
ERROR: bzip2/1.0.6@conan/stable: Error in source() method, line 34
	tools.check_md5(zip_name, "00b516f4704d4a7cb50a1d97e6e8e15b")
	ConanException: md5 signature failed for 'bzip2-1.0.6.tar.gz' file. 
 Provided signature: 00b516f4704d4a7cb50a1d97e6e8e15b  
 Computed signature: bb6639fad5666cfe31b46330395a3352
```
this seems like it might be an error

_Copied from original issue: conan-community/conan-bzip2#21_

**Comment by SSE4** [comment]
_From @lasote on October 15, 2018 10:50_

It is working properly here. Are you downloading the recipe from `conan-center`? Could be possible that you have some network/proxy issue and the downloaded file is not the correct one?

**Comment by SSE4** [comment]
_From @hpanderson on October 18, 2018 22:27_

I got the same error with the same computed md5. It's downloading an html page from bzip.org, not the archive itself. It turned out I had an old version of the bzip conanfile in ~/.conan, prior to the url change to bintray.com in dba00bfc. Running `conan remove bzip2` then running the conan install again solved the error for me.

**Comment by SSE4** [comment]
this is well-known problem with bzip2 and source-forge in general, that it frequently becomes temporarily inaccessibly.
other package manager use mirrors, e.g. https://github.com/Homebrew/homebrew-core/blob/master/Formula/bzip2.rb#L5
I think we can add similar mirror handling.

**Comment by danimtb** [comment]
bzip2 sources are actually mirrored and used in recipe https://github.com/conan-community/conan-bzip2/blob/659cbe1040ef1ece1e2c7e08648a000baffa8558/conanfile.py#L36

As the bzip2 domain expired some months ago (can't find the issue right now)

**Comment by SSE4** [comment]
then I believe it's already fixed and can be closed

**Comment by SSE4** [comment]
closing as already fixed
