### ISSUE TITLE
[bzip2] bzip2 fails on macOS 10.14

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#65]
_From @acgetchell on September 27, 2018 4:12_

Description of Problem, Request, or Question

bzip2/1.0.6@conan/stable fails to build on macOS 10.14:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/gni54v03r5vs68a5#L5610

Package Details (Include if Applicable)

Package Name/Version: bzip2/1.0.6@conan/stable
Operating System: macOS 10.14
Compiler+version: apple-clang 10.0
Steps to reproduce (Include if Applicable)

Run build script locally:

https://github.com/acgetchell/CDT-plusplus/blob/develop/build.sh

Results:

┌─[adam][hapkido][±][feature/refactor-simplicial-manifold ?:1 ✗][~/CDT-plusplus]
└─▪ ./build.sh 
Downloading conaninfo.txt
[==================================================] 150B/150B        
Downloading conaninfo.txt
[==================================================] 150B/150B        
Downloading conaninfo.txt
[==================================================] 324B/324B        
bzip2/1.0.6@conan/stable: WARN: Package is corrupted, removing folder: /Users/adam/.conan/data/bzip2/1.0.6/conan/stable/package/534dcc368c999e07e81f146b3466b8f656ef1f55
Downloading conaninfo.txt
[==================================================] 230B/230B        
PROJECT: Installing /Users/adam/CDT-plusplus/conanfile.py
Requirements
    TBB/2018_U5@conan/stable from 'conan-center' - Cache
    boost/1.68.0@conan/stable from 'conan-center' - Cache
    bzip2/1.0.6@conan/stable from 'conan-center' - Cache
    catch2/2.4.0@bincrafters/stable from 'conan-center' - Cache
    date/2.4@bincrafters/stable from 'bincrafters' - Cache
    docopt/0.6.2@conan/stable from 'conan-center' - Cache
    eigen/3.3.5@conan/stable from 'conan-center' - Cache
    gsl_microsoft/1.0.0@bincrafters/stable from 'bincrafters' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    TBB/2018_U5@conan/stable:03db91a62823ebc2b1df6e5cf549c2f674116656 - Cache
    boost/1.68.0@conan/stable:411d816e9b8d6cb0bb1ef6e5be8b2a94b8b17c04 - Build
    bzip2/1.0.6@conan/stable:534dcc368c999e07e81f146b3466b8f656ef1f55 - Build
    catch2/2.4.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    date/2.4@bincrafters/stable:cce31ad1c9344304d9adb841bfd3adef175a5b20 - Build
    docopt/0.6.2@conan/stable:f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2 - Build
    eigen/3.3.5@conan/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    gsl_microsoft/1.0.0@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    zlib/1.2.11@conan/stable:bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583 - Build
Build requirements
    cmake_installer/3.11.3@conan/stable from 'conan-center' - Cache
Build requirements packages
    cmake_installer/3.11.3@conan/stable:743cf0321be3152777da4d05247a66d1552e70a2 - Download

TBB/2018_U5@conan/stable: Already installed!
bzip2/1.0.6@conan/stable: Building your package in /Users/adam/.conan/data/bzip2/1.0.6/conan/stable/build/534dcc368c999e07e81f146b3466b8f656ef1f55
bzip2/1.0.6@conan/stable: Copying sources to build folder
bzip2/1.0.6@conan/stable: Generator cmake created conanbuildinfo.cmake
bzip2/1.0.6@conan/stable: Calling build()
sh: cmake: command not found
bzip2/1.0.6@conan/stable: 
bzip2/1.0.6@conan/stable: ERROR: Package '534dcc368c999e07e81f146b3466b8f656ef1f55' build failed
bzip2/1.0.6@conan/stable: WARN: Build folder /Users/adam/.conan/data/bzip2/1.0.6/conan/stable/build/534dcc368c999e07e81f146b3466b8f656ef1f55
ERROR: bzip2/1.0.6@conan/stable: Error in build() method, line 50
	cmake.configure(build_dir=".", source_dir="..")
	ConanException: Error 32512 while executing cd '.' && cmake -G "Ninja" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_COMPILER="apple-clang" -DCONAN_COMPILER_VERSION="10.0" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="/Users/adam/.conan/data/bzip2/1.0.6/conan/stable/package/534dcc368c999e07e81f146b3466b8f656ef1f55" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DFPIC="ON" -Wno-dev '..'
ERROR: conanbuildinfo.txt file not found in /Users/adam/CDT-plusplus/build
It is required for this command
You can generate it using 'conan install'

_Copied from original issue: conan-community/conan-bzip2#20_

**Comment by SSE4** [comment]
_From @acgetchell on September 27, 2018 4:24_

Here's the trace log:
```
┌─[adam][hapkido][~]
└─▪ cat conan_trace.log
{"_action": "COMMAND", "name": "install", "parameters": {"build": ["missing"], "env": null, "generators": null, "install_folder": null, "manifests": null, "manifests_interactive": null, "no_imports": false, "options": null, "path": "..", "profile_name": "cdt", "remote_name": null, "settings": null, "update": false, "verify": null}, "time": 1538022133.728381}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "boost/1.68.0@conan/stable", "time": 1538022133.75566}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "bzip2/1.0.6@conan/stable", "time": 1538022133.7625248}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "zlib/1.2.11@conan/stable", "time": 1538022133.767026}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "catch2/2.4.0@bincrafters/stable", "time": 1538022133.77169}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "TBB/2018_U5@conan/stable", "time": 1538022133.776154}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "eigen/3.3.5@conan/stable", "time": 1538022133.781068}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "docopt/0.6.2@conan/stable", "time": 1538022133.7865658}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "date/2.4@bincrafters/stable", "time": 1538022133.791123}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "gsl_microsoft/1.0.0@bincrafters/stable", "time": 1538022133.795522}
{"_action": "REST_API_CALL", "duration": 0.556879997253418, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.7.3 (Python 3.7.0) python-requests/2.19.1", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "", "X-Conan-Client-Version": "1.7.3"}, "method": "GET", "time": 1538022136.3078778, "url": "https://conan.bintray.com/v1/conans/eigen/3.3.5/conan/stable/packages/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/download_urls"}
{"_action": "DOWNLOAD", "duration": 6.332798957824707, "time": 1538022142.641851, "url": "https://api.bintray.com/conan/conan/conan-center/v1/files/conan/eigen/3.3.5/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/conaninfo.txt"}
{"_action": "REST_API_CALL", "duration": 0.44116902351379395, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.7.3 (Python 3.7.0) python-requests/2.19.1", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "", "X-Conan-Client-Version": "1.7.3"}, "method": "GET", "time": 1538022143.084971, "url": "https://conan.bintray.com/v1/conans/bzip2/1.0.6/conan/stable/packages/534dcc368c999e07e81f146b3466b8f656ef1f55/download_urls"}
{"_action": "REST_API_CALL", "duration": 0.42850208282470703, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.7.3 (Python 3.7.0) python-requests/2.19.1", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "", "X-Conan-Client-Version": "1.7.3"}, "method": "GET", "time": 1538022143.515357, "url": "https://conan.bintray.com/v1/conans/boost/1.68.0/conan/stable/packages/411d816e9b8d6cb0bb1ef6e5be8b2a94b8b17c04/download_urls"}
{"_action": "REST_API_CALL", "duration": 0.4722301959991455, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.7.3 (Python 3.7.0) python-requests/2.19.1", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "", "X-Conan-Client-Version": "1.7.3"}, "method": "GET", "time": 1538022143.989411, "url": "https://conan.bintray.com/v1/conans/docopt/0.6.2/conan/stable/packages/f8bda7f0751e4bc3beaa6c3b2eb02d455291c8a2/download_urls"}
{"_action": "REST_API_CALL", "duration": 0.570519208908081, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.7.3 (Python 3.7.0) python-requests/2.19.1", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "", "X-Conan-Client-Version": "1.7.3"}, "method": "GET", "time": 1538022144.5637639, "url": "https://conan.bintray.com/v1/conans/zlib/1.2.11/conan/stable/packages/bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583/download_urls"}
{"_action": "REST_API_CALL", "duration": 0.3973979949951172, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.7.3 (Python 3.7.0) python-requests/2.19.1", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "", "X-Conan-Client-Version": "1.7.3"}, "method": "GET", "time": 1538022145.491582, "url": "https://api.bintray.com/conan/bincrafters/public-conan/v1/conans/gsl_microsoft/1.0.0/bincrafters/stable/packages/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/download_urls"}
{"_action": "DOWNLOAD", "duration": 1.1620538234710693, "time": 1538022146.654774, "url": "https://api.bintray.com/conan/bincrafters/public-conan/v1/files/bincrafters/gsl_microsoft/1.0.0/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/conaninfo.txt"}
{"_action": "REST_API_CALL", "duration": 0.32395315170288086, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.7.3 (Python 3.7.0) python-requests/2.19.1", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "", "X-Conan-Client-Version": "1.7.3"}, "method": "GET", "time": 1538022146.979906, "url": "https://conan.bintray.com/v1/conans/catch2/2.4.0/bincrafters/stable/packages/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/download_urls"}
{"_action": "DOWNLOAD", "duration": 1.0982089042663574, "time": 1538022148.0791879, "url": "https://api.bintray.com/conan/conan/conan-center/v1/files/bincrafters/catch2/2.4.0/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/conaninfo.txt"}
{"_action": "REST_API_CALL", "duration": 0.2825460433959961, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.7.3 (Python 3.7.0) python-requests/2.19.1", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "", "X-Conan-Client-Version": "1.7.3"}, "method": "GET", "time": 1538022148.363543, "url": "https://api.bintray.com/conan/bincrafters/public-conan/v1/conans/date/2.4/bincrafters/stable/packages/cce31ad1c9344304d9adb841bfd3adef175a5b20/download_urls"}
{"_action": "GOT_RECIPE_FROM_LOCAL_CACHE", "_id": "cmake_installer/3.11.3@conan/stable", "time": 1538022148.370744}
{"_action": "REST_API_CALL", "duration": 0.43105006217956543, "headers": {"Authorization": "**********", "User-Agent": "Conan/1.7.3 (Python 3.7.0) python-requests/2.19.1", "X-Client-Anonymous-Id": "**********", "X-Client-Id": "", "X-Conan-Client-Version": "1.7.3"}, "method": "GET", "time": 1538022148.808962, "url": "https://conan.bintray.com/v1/conans/cmake_installer/3.11.3/conan/stable/packages/743cf0321be3152777da4d05247a66d1552e70a2/download_urls"}
{"_action": "DOWNLOAD", "duration": 1.434664011001587, "time": 1538022150.244769, "url": "https://api.bintray.com/conan/conan/conan-center/v1/files/conan/cmake_installer/3.11.3/stable/package/743cf0321be3152777da4d05247a66d1552e70a2/conaninfo.txt"}
{"_action": "GOT_PACKAGE_FROM_LOCAL_CACHE", "_id": "TBB/2018_U5@conan/stable:03db91a62823ebc2b1df6e5cf549c2f674116656", "time": 1538022150.247375}
{"_action": "EXCEPTION", "class": "ConanExceptionInUserConanfileMethod", "message": "bzip2/1.0.6@conan/stable: Error in build() method, line 50\n\tcmake.configure(build_dir=\".\", source_dir=\"..\")\n\tConanException: Error 32512 while executing cd '.' && cmake -G \"Ninja\" -DCMAKE_BUILD_TYPE=\"Release\" -DCONAN_EXPORTED=\"1\" -DCONAN_COMPILER=\"apple-clang\" -DCONAN_COMPILER_VERSION=\"10.0\" -DCONAN_CXX_FLAGS=\"-m64\" -DCONAN_SHARED_LINKER_FLAGS=\"-m64\" -DCONAN_C_FLAGS=\"-m64\" -DBUILD_SHARED_LIBS=\"OFF\" -DCMAKE_INSTALL_PREFIX=\"/Users/adam/.conan/data/bzip2/1.0.6/conan/stable/package/534dcc368c999e07e81f146b3466b8f656ef1f55\" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE=\"ON\" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=\"ON\" -DFPIC=\"ON\" -Wno-dev '..'", "time": 1538022150.300261}
{"_action": "COMMAND", "name": "build", "parameters": {"build_folder": null, "conanfile_path": "..", "install_folder": null, "package_folder": null, "should_build": true, "should_configure": true, "should_install": true, "should_test": true, "source_folder": null}, "time": 1538022150.697929}
{"_action": "EXCEPTION", "class": "ConanException", "message": "conanbuildinfo.txt file not found in /Users/adam/CDT-plusplus/build\nIt is required for this command\nYou can generate it using 'conan install'", "time": 1538022150.7203789}
```

**Comment by SSE4** [comment]
_From @memsharded on September 27, 2018 7:27_

It seems related to cmake not being found in the path:

> sh: cmake: command not found

Which is weird, because the cmake build_requires is there. Might be a bug in conan, not the bzip2 package.

**Comment by SSE4** [comment]
_From @lasote on September 27, 2018 9:38_

Could you paste here the applied profile? I can't find it.

**Comment by SSE4** [comment]
_From @acgetchell on September 27, 2018 16:37_

```
┌─[adam][hapkido][±][feature/refactor-simplicial-manifold ✓][~/CDT-plusplus]
└─▪ conan profile show cdt
Configuration for profile cdt:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Ninja
```

**Comment by SSE4** [comment]
_From @acgetchell on September 27, 2018 16:55_

@memsharded Should I be setting `[build_requires]` in the profile also?

I hadn't before, but ...

**Comment by SSE4** [comment]
_From @acgetchell on September 27, 2018 20:11_

Ah, interesting. If I `brew install cmake` then it works.

So, other packages build with `cmake_build_requires`, but oddly not bzip2.

**Comment by SSE4** [comment]
@acgetchell so, I think there is no issue, as you either need to install `cmake`, or add `cmake_installer` to your profile, right?

**Comment by acgetchell** [comment]
I don’t have this problem anymore, please feel free to close this issue.

**Comment by SSE4** [comment]
closing as fixed

**Comment by mrlizzard** [comment]
Hello teams,

I have the same problem but I can't solve this problem.
I've installed cmake too with the command listed above.

`ERROR: bzip2/1.0.6@conan/stable: Error in build() method, line 51
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 46
	cmake.configure()
	ConanException: Error 1 while executing cd '/Users/cyrilcolinet/.conan/data/bzip2/1.0.6/conan/stable/build/ee2131c66d6ea00f9f848d51fa8a2ee24fd80146' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="9" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DBUILD_SHARED_LIBS="ON" -DCMAKE_INSTALL_PREFIX="/Users/cyrilcolinet/.conan/data/bzip2/1.0.6/conan/stable/package/ee2131c66d6ea00f9f848d51fa8a2ee24fd80146" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DBZ2_VERSION_STRING="1.0.6" -DBZ2_VERSION_MAJOR="1" -DBZ2_BUILD_EXE="ON" -Wno-dev '/Users/cyrilcolinet/.conan/data/bzip2/1.0.6/conan/stable/build/ee2131c66d6ea00f9f848d51fa8a2ee24fd80146'`

Can you please steer me for the resolution (and the victory)...
Thanks a lot
