### ISSUE TITLE
[strawberryperl] Change order of arch_build/arch_os and arch/os

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#69]
_From @helmesjo on July 6, 2018 9:26_

I got the exception `"Only windows supported for strawberry perl"`, and having to manually specify `-s arch_build="x86" -s os_build="Windows"` etc. when I already have `-s arch="x86" -s os="Windows"` seems kind of redundant.

It is my understanding that most of the time, `arch_build`/`os_build` will not be altered, and perhaps `arch`/`os` are more reliable defaults, right?

So consider changing:
```
@property
    def arch(self):
        return self.settings.get_safe("arch_build") or self.settings.get_safe("arch")
@property
    def os(self):
        return self.settings.get_safe("os_build") or self.settings.get_safe("os")
```
To:
```
@property
    def arch(self):
        return self.settings.get_safe("arch") or self.settings.get_safe("arch_build")
@property
    def os(self):
        return self.settings.get_safe("os") or self.settings.get_safe("os_build")
```

_Copied from original issue: conan-community/conan-strawberryperl#3_

**Comment by SSE4** [comment]
@uilianries @lasote do we need to do something with this one? I have no idea, honestly.

**Comment by uilianries** [comment]
Seems like his profile doesn't have `os_build` configured. I think we are good to close it.

**Comment by SSE4** [comment]
okay, closing then. @helmesjo please open a new issue, if you still have a problem.

**Comment by uilianries** [comment]
Thanks!
