### ISSUE TITLE
conan-tiny-dnn inclusion request into conan-center

### ISSUE THREAD

**Issue by pvicente** [conan-community/community#7]
## Inclusion Request Review

This is a review for [tiny-dnn/0.1.1@conan/stable (conan-community/conan)](https://github.com/conan-community/conan-tiny-dnn) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
tiny-dnn/0.1.1@conan/stable

#### Recipe quality
- [x] Git public repository
- [x] Recipe fields
- [] Linter
- [x] Updated
- [x] Clean
- [x] test_package
- [] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments

See linter warning:

![screenshot 2018-03-14 19 51 19](https://user-images.githubusercontent.com/471109/37427422-5606d8ca-27c1-11e8-93f6-0dd5d4556821.png)

**Comment by danimtb** [comment]
should be good to go too! 🐸

**Comment by pvicente** [comment]
@danimtb please see PR above. After that it should be ready.

**Comment by pvicente** [comment]
All done!!! https://bintray.com/conan/conan-center?filterByPkgName=tiny-dnn%3Aconan

![screenshot 2018-03-15 16 53 11](https://user-images.githubusercontent.com/471109/37478300-bbd09898-2871-11e8-8e62-205ded08bb0e.png)
