### ISSUE TITLE
[OpenCV] Add android/ios

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#71]
_From @LinArcX on July 8, 2018 7:35_

Hi. and thanks for this great job.
it will very amazing if we try opencv with android-toolchain(arm)or use it in ios development.

_Copied from original issue: conan-community/conan-opencv#5_

**Comment by CAMOBAP795** [comment]
I'm successfully compiled `opencv/4.0.1@conan/stable` for Android with next options:

```
opencv:tiff=False
opencv:openexr=False
opencv:jpegturbo=True
```

**Comment by SSE4** [comment]
builds fine for Android and iOS locally. at this point, we're not uploading iOS/Android to bintray, but support local builds.
