### ISSUE TITLE
[OpenCV] Update from https://github.com/db4/conan-opencv

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#72]
_From @memsharded on February 6, 2018 11:28_

This repo https://github.com/db4/conan-opencv has an advanced recipe, worth checking and collaborating. 

cc/ @db4

_Copied from original issue: conan-community/conan-opencv#3_

**Comment by hosaka** [comment]
Also interested in this, need more granular options for my project, is there anything I can help with?

**Comment by hosaka** [comment]
To be a bit more specific, I'm building openc/4.0.1@conan/stable with options:
```
opencv:gtk=None
opencv:jasper=False
opencv:jpeg=False
opencv:openexr=False
opencv:png=False
opencv:tiff=False
opencv:webp=False
```
However linking fails with not finding the dc1394 lib. Passing WITH_1394=OFF to the opencv fixes this problem.

**Comment by SSE4** [comment]
@hosaka if you have time, feel free to submit pull requests adding new options, e.g. one for dc1394, or any others you may need.

**Comment by uilianries** [comment]
Hi!

[OpenCV](https://conan.io/center/opencv) has been moved to [Conan Center Index](https://github.com/conan-io/conan-center-index), and this version will no longer maintained. Please, open a new [issue](https://github.com/conan-io/conan-center-index/issues) for bugs and improvements.

Regards.
