### ISSUE TITLE
[OpenCV] Why is this not published on conan.io?

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#73]
_From @Brunni on March 7, 2017 22:8_

Hi,
I just wanted to know why this is not published on conan.io.

Could we make it work with opencv 3.1 and 3.2?

_Copied from original issue: conan-community/conan-opencv#2_

**Comment by Croydon** [comment]
Should be closed imo, OpenCV is now in the conan-community repository.

**Comment by lasote** [comment]
Not yet in conan-center. but I hope very soon!

**Comment by SSE4** [comment]
finally, in conan-centre: https://bintray.com/conan-community/conan/opencv%3Aconan

**Comment by Croydon** [comment]
cross referencing: https://github.com/conan-io/wishlist/issues/4

**Comment by SSE4** [comment]
cross referencing: https://github.com/conan-io/conan/issues/3289
