### ISSUE TITLE
[SFML] Visual 14 not working

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#74]
_From @memsharded on December 10, 2015 16:52_

As is, it fails to build VS 14 packages:
 jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol __iob_func referenced in function out put_message [C:\Users\memsharded\conanws\packages\conan-sfml\build\8c8ae8d42b389a80fb84b2245c14354ca1d0f793\ client.vcxproj]
  jpeg.lib(jerror.obj) : error LNK2019: unresolved external symbol sprintf referenced in function format _message [C:\Users\memsharded\conanws\packages\conan-sfml\build\8c8ae8d42b389a80fb84b2245c14354ca1d0f793\cli ent.vcxproj]
  jpeg.lib(jmemmgr.obj) : error LNK2019: unresolved external symbol sscanf referenced in function jinit_ memory_mgr [C:\Users\memsharded\conanws\packages\conan-sfml\build\8c8ae8d42b389a80fb84b2245c14354ca1d0f793\c lient.vcxproj]

_Copied from original issue: conan-community/conan-sfml#1_

**Comment by SSE4** [comment]
@memsharded I doubt we are going to support SFML going forward, as there is bincrafters package. I am going to close this one, any objections?

**Comment by danimtb** [comment]
I think is fine and we should close the sfml repo too
