### ISSUE TITLE
[boost] Boost fails to build for iOS with wrong archiver

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#76]
_From @zhuhaow on September 12, 2018 14:17_

Related issue: https://github.com/conan-io/conan/issues/3514

boost expect libtool as the archiver instead of ar when building for iOS.

In cross compiling profile, such as https://github.com/theodelrieu/conan-darwin-toolchain/blob/release/1.0/conanfile.py, the env variable AR is set to ar and later the boost package will pick that up https://github.com/conan-community/conan-boost/blob/6b6a3c9bc8f07824ec3932422c9ba14311707c48/conanfile.py#L252 which will set the archiver to ar where the build will fail as the building script expect libtool.

A reasonable workaround is simply do not use AR/RANLIB env if we are building boost for iOS, which is odd but should always work. Other way is to use some env variable defining the libtool to use, this requires conan defines a new env variable for libtool at least in conan community I think.

_Copied from original issue: conan-community/conan-boost#156_

**Comment by theodelrieu** [comment]
@zhuhaow Could you provide a reproducible use-case so that I can understand the issue? I'm able to build Boost for iOS, but I've forked the monolithic Boost recipe months ago.

**Comment by zhuhaow** [comment]
Sorry for the late reply.

I just tried with the latest conan-boost 1.69 branch (https://github.com/conan-community/conan-boost), with command 
`conan create --profile path_to_ios_profile --build -o boost:without_iostreams=True . test/test`

And the profile file I used is from 
https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#example-darwin-toolchain

You will notice a lot of error about ar parameters such as 

```
ar: only one of -a and -[bi] options allowed
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
...failed darwin.archive /Users/zhuhao/.conan/data/boost/1.69.0/test/test/build/f8644327f89dfae557cd86bf909a89c97cb6a034/boost/bin.v2/libs/test/build/drwn-12.1~/rls/lnk-sttc/mcsx-vrsn-iphn-12.1/trgt-os-iphn/thrd-mlt/vsblt-hdn/libboost_unit_test_framework.a...
...skipped <pstage/lib>libboost_unit_test_framework.a for lack of <p/Users/zhuhao/.conan/data/boost/1.69.0/test/test/build/f8644327f89dfae557cd86bf909a89c97cb6a034/boost/bin.v2/libs/test/build/drwn-12.1~/rls/lnk-sttc/mcsx-vrsn-iphn-12.1/trgt-os-iphn/thrd-mlt/vsblt-hdn>libboost_unit_test_framework.a...
darwin.compile.c++ /Users/zhuhao/.conan/data/boost/1.69.0/test/test/build/f8644327f89dfae557cd86bf909a89c97cb6a034/boost/bin.v2/libs/wave/build/drwn-12.1~/rls/lnk-sttc/mcsx-vrsn-iphn-12.1/trgt-os-iphn/thrd-mlt/vsblt-hdn/instantiate_re2c_lexer.o
```

I have a dirty fix here https://github.com/zhuhaow/conan-boost/blob/darwin_fix/conanfile.py

**Comment by theodelrieu** [comment]
Could you try using `darwin-toolchain/1.0.3@theodelrieu/stable` instead?

**Comment by zhuhaow** [comment]
No luck. Same error.

**Comment by theodelrieu** [comment]
I'll take a look tomorrow

**Comment by theodelrieu** [comment]
Ok, I did set `libtool` as archiver and this fixed your issue. I'll try to use it as `RANLIB` too, since the man page says it is meant to be a replacement of both `ar` and `ranlib`.

However I could not build Boost even with this fix, `Boost.Context` fails to build the assembly files.
The problem is that `CFLAGS` are not passed to the compiler when building `.s` files. The workaround I use in my `Boost` recipe is to write them in the "compiler invocation" part of `user-config.jam`.

I hope there is a better way

**Comment by theodelrieu** [comment]
Unfortunately, setting `libtool` as archiver breaks some Autotools-based libraries (e.g. `libsodium`). I'm afraid I cannot make the change in `darwin-toolchain`.

It would be easier to fix the problem in Boost directly to support both `libtool` and `ar`.

**Comment by zhuhaow** [comment]
Maybe.

`libtool` is not a drop-in replacement for `ar`.

**Comment by SSE4** [comment]
I wonder why `darwin` toolset in in use, I was thinking `clang-darwin` should be used instead now? my understanding that `darwin` was designed for old GCC 4.x, before XCode switched to Clang, while `clang-darwin` is recommended one for the modern installations?
@theodelrieu can you confirm that?

**Comment by theodelrieu** [comment]
I'm not well versed into Boost.Build, but I'm quite sure that you're right on this one.

**Comment by SSE4** [comment]
okay, if you guys can try to change the following lines locally to use `clang` or `clang-darwin` and test would be nice:
https://github.com/conan-community/conan-boost/blob/release/1.69.0/conanfile.py#L358
https://github.com/conan-community/conan-boost/blob/release/1.69.0/conanfile.py#L372

**Comment by theodelrieu** [comment]
I get the following error:

>/Users/theo/.conan/data/boost/1.69.0/conan/stable/build/899b66155515f48d7b9399a1e2b096d975711bb0/boost_1_69_0/tools/build/src/build/feature.jam:327: in validate-feature from module feature
error: unknown feature "<macosx-version>"
/Users/theo/.conan/data/boost/1.69.0/conan/stable/build/899b66155515f48d7b9399a1e2b096d975711bb0/boost_1_69_0/tools/build/src/build/feature.jam:361: in expand-subfeatures-aux from module feature
/Users/theo/.conan/data/boost/1.69.0/conan/stable/build/899b66155515f48d7b9399a1e2b096d975711bb0/boost_1_69_0/tools/build/src/build/feature.jam:422: in feature.expand-subfeatures from module feature
/Users/theo/.conan/data/boost/1.69.0/conan/stable/build/899b66155515f48d7b9399a1e2b096d975711bb0/boost_1_69_0/tools/build/src/build/build-request.jam:20: in apply-to-property-set from module build-request
(builtin): -1: in sequence.transform from module sequence
/Users/theo/.conan/data/boost/1.69.0/conan/stable/build/899b66155515f48d7b9399a1e2b096d975711bb0/boost_1_69_0/tools/build/src/build/build-request.jam:32: in build-request.expand-no-defaults from module build-request
/Users/theo/.conan/data/boost/1.69.0/conan/stable/build/899b66155515f48d7b9399a1e2b096d975711bb0/boost_1_69_0/tools/build/src/build-system.jam:775: in load from module build-system
/Users/theo/.conan/data/boost/1.69.0/conan/stable/build/899b66155515f48d7b9399a1e2b096d975711bb0/boost_1_69_0/tools/build/src/kernel/modules.jam:295: in import from module modules
/Users/theo/.conan/data/boost/1.69.0/conan/stable/build/899b66155515f48d7b9399a1e2b096d975711bb0/boost_1_69_0/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
/Users/theo/.conan/data/boost/1.69.0/conan/stable/build/899b66155515f48d7b9399a1e2b096d975711bb0/boost_1_69_0/boost-build.jam:17: in module scope from module

**Comment by theodelrieu** [comment]
Forgot to mention I'm building for iOS

**Comment by theodelrieu** [comment]
It works on macOS, one funny thing is that the generated `user-config.jam` is not used when building for iOS...

For example, `zlib` and `bzip2` are not found, whereas they are when building for macOS... Is it a toolset name problem?

**Comment by SSE4** [comment]
@theodelrieu @zhuhaow I've applied changes to use toolset `clang-darwin` (Apple Clang) instead of just `darwin` (which is supposed to be GCC 4.x) - https://github.com/conan-community/conan-boost/commit/ad35f8afa2a33ff569f308b31626c71a8e287206.
at least, it builds locally for me with the following profile:
```
sse4_macbookpro% conan profile show ios
Configuration for profile ios:

[settings]
os=iOS
os.version=10.0
os_build=Macos
arch=armv8
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
[options]
[build_requires]
[env]
```
I didn't test another architectures (like armv7 or armv7s or x86 for simulators) or watchOS/tvOS
so, please give an another try and lemme know.

**Comment by theodelrieu** [comment]
I was able to build as well, I'm going to release a new version of `darwin-toolchain`. So @zhuhaow can test again

**Comment by theodelrieu** [comment]
@zhuhaow I just released `darwin-toolchain/1.0.4@theodelrieu/testing`, let me know if it works out for you. If so, I'll push it to `stable`.

**Comment by zhuhaow** [comment]
Sorry for the late reply. Everything works fine now. 🎉

**Comment by theodelrieu** [comment]
Great, I'm releasing it to stable then 👍

**Comment by SSE4** [comment]
great news! I am closing the issue then.
