### ISSUE TITLE
[boost] No packages available for 1.68.0 for Linux

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#79]
_From @LauraBogdan on August 17, 2018 9:28_

Yet all the packages for windows are available.

_Copied from original issue: conan-community/conan-boost#143_

**Comment by SSE4** [comment]
_From @Croydon on September 1, 2018 3:58_

There still seems to be no package for (at least) Clang 5

**Comment by SSE4** [comment]
_From @lasote on September 3, 2018 9:9_

Please, specify the complete trace for the missing package, for example this one for clang 5 is present: 

`conan get boost/1.68.0@conan/stable -p 1cc2206afa37cd09efc31c5913e054039089f7c8 -r conan-center`

**Comment by SSE4** [comment]
_From @Croydon on September 4, 2018 15:48_

I'm not sure if this is all information you need, let me know if you need more:

>	os=Linux
	os_build=Linux
	arch=x86_64
	arch_build=x86_64
	compiler=clang
	compiler.version=5.0
	compiler.libcxx=libstdc++
	build_type=Release

https://travis-ci.org/inexorgame/inexor-core/jobs/423269281#L570
https://travis-ci.org/inexorgame/inexor-core/jobs/423269281#L792

**Comment by SSE4** [comment]
_From @lasote on September 5, 2018 9:1_

These specific settings resolves to the package `boost/1.68.0@conan/stable:66ea23538750d0ff55320a0f64616b0b6ba3d9cb` that is present indeed. Probably you or one of your dependencies are changing some option?

**Comment by SSE4** [comment]
_From @Croydon on September 5, 2018 9:4_

We are setting shared explicit to False, but that is all I'm aware about

https://github.com/inexorgame/inexor-core/blob/e2aa17cb224b09aa4a73b423802db7bf2edb6ccf/dependencies.py#L21 (this files says boost 1.66 but the same was true for 1.68)

**Comment by SSE4** [comment]
_From @lasote on September 5, 2018 9:6_

The `shared=False` is the default and resolves to `66ea23538750d0ff55320a0f64616b0b6ba3d9cb`. It has to be some more change maybe in an intermediate dep, let me check.

**Comment by SSE4** [comment]
_From @lasote on September 5, 2018 9:29_

Now I see, from the command line you are appending `-s compiler.libcxx=libstdc++11` so the id is the missing one, but that is because conan package tools never generated `libstdc++11` packages for linux clang so far.

**Comment by SSE4** [comment]
_From @lasote on September 5, 2018 9:33_

Actually the 1.66.0 has the same issue: boost/1.66.0@conan/stable:7e07acc0e70d88aaa1ddb206f621d8a2f03b7ba1 - Missing

**Comment by SSE4** [comment]
@lasote could you check if we still missed packages?

**Comment by danimtb** [comment]
boost package for this configuration are still missing:

```
(conan) λ conan install boost/1.68.0@conan/stable -pr croydon
Configuration:
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=5.0
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

boost/1.68.0@conan/stable: Installing package
Requirements
    boost/1.68.0@conan/stable from 'conan-center' - Cache
    bzip2/1.0.6@conan/stable from local cache - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    boost/1.68.0@conan/stable:7e07acc0e70d88aaa1ddb206f621d8a2f03b7ba1 - Missing
    bzip2/1.0.6@conan/stable:0bb6f9a537a76b4aa6af7fb4dbef0aa6dddcabf4 - Cache
    zlib/1.2.11@conan/stable:0bb6f9a537a76b4aa6af7fb4dbef0aa6dddcabf4 - Cache

bzip2/1.0.6@conan/stable: Already installed!
zlib/1.2.11@conan/stable: Already installed!
boost/1.68.0@conan/stable: WARN: Can't find a 'boost/1.68.0@conan/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=clang, compiler.libcxx=libstdc++11, compiler.version=5.0, os=Linux
- Options: fPIC=True, header_only=False, magic_autolink=False, shared=False, skip_lib_rename=False, without_atomic=False, without_chrono=False, without_container=False, without_context=False, without_contract=False, without_coroutine=False, without_date_time=False, without_exception=False, without_fiber=False, without_filesystem=False, without_graph=False, without_graph_parallel=False, without_iostreams=False, without_locale=False, without_log=False, without_math=False, without_mpi=False, without_program_options=False, without_python=True, without_random=False, without_regex=False, without_serialization=False, without_signals=False, without_stacktrace=False, without_system=False, without_test=False, without_thread=False, without_timer=False, without_type_erasure=False, without_wave=False, bzip2:fPIC=True, bzip2:shared=False, zlib:fPIC=True, zlib:minizip=False, zlib:shared=False
- Dependencies: bzip2/1.0.6@conan/stable, zlib/1.2.11@conan/stable
- Package ID: 7e07acc0e70d88aaa1ddb206f621d8a2f03b7ba1

ERROR: Missing prebuilt package for 'boost/1.68.0@conan/stable'
Try to build it from sources with "--build boost"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

If this configuration if built by default in conan-docker-tools (I think it is) we should investigate what is happening there.

**Comment by SSE4** [comment]
@Croydon I think I've added missing packages to build. they aren't build by default by CPT, but for boost they are available now: https://bintray.com/conan-community/conan/boost%3Aconan#files/conan%2Fboost%2F1.68.0%2Fstable%2Fpackage%2F7e07acc0e70d88aaa1ddb206f621d8a2f03b7ba1

**Comment by Croydon** [comment]
I can't make any real world test run as we are still using 1.66.0 and I can't easily update this for now, but it looks good to me, thanks!

**Comment by SSE4** [comment]
@Croydon thank you very much! what do you think we should do now with this issue?

**Comment by Croydon** [comment]
My use case should be good to go and the original author pushed this: https://github.com/conan-community/conan-boost/commit/40358a3938dc8c4e750690fb13c6cbf8b2dd782f

So I guess it can be closed.

**Comment by SSE4** [comment]
confirmed as fixed, closing
