### ISSUE TITLE
ArduinoJson inclusion-request to conan-center

### ISSUE THREAD

**Issue by danimtb** [conan-community/community#9]
Moved from personal repo to conan-community.
cc/ @pvicente

## Inclusion Request Review

This is a review for [arduinojson/5.13.0@conan/stable (conan-community/conan)](https://github.com/danimtb/conan-arduinojson) inclusion request to conan-center.
This review follows the [inclusion guidelines or third party libraries](http://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#inclusion-guidelines-for-third-party-libraries).

### Package
arduinojson/5.13.0@conan/stable

#### Recipe quality
- [x] Git public repository
- [ ] Recipe fields
- [ ] Linter
- [x] Updated
- [x] Clean
- [x] test_package
- [ ] Raise errors on invalid configurations
- [x] LICENSE of the recipe
- [x] LICENSE of the library

**Recipe Fields**: 

#### CI Integration
- [x] Provide at least one CI configuration (header only)
- [ ] (If not header only) CI configurations for Linux/MacOSX/Windows

#### Bintray Package Information
- [x] Description
- [x] Licenses
- [x] Tags
- [x] Maturity
- [x] Website (if any)
- [x] Issue tracker
- [x] Version control

### Additional comments
[url field](https://github.com/danimtb/conan-arduinojson/blob/stable/5.13.0/conanfile.py#L10) should point to this repo.

Header only library, missing method:

```
    def package_id(self):
        self.info.header_only()
```

See linter warning:

![screenshot 2018-03-14 19 46 29](https://user-images.githubusercontent.com/471109/37427210-8da76e1c-27c0-11e8-935a-468ae8f47d20.png)

**Comment by danimtb** [comment]
Addressed all issues above.

Note this change
```
def package_id(self):
        self.info.header_only()
```
is not needed as the recipe does not declare `settings`.

cc/ @pvicente

**Comment by pvicente** [comment]
@danimtb ACK, yes I forgot it, I've checked again the [docs about it](http://docs.conan.io/en/latest/howtos/header_only.html?highlight=header%20only) sorry about it. only changes are linter and url field now pointing to ```conan-community``` and ready to go.

**Comment by danimtb** [comment]
It should be good to go now! 😉

**Comment by pvicente** [comment]
All done!!! https://bintray.com/conan/conan-center?filterByPkgName=arduinojson%3Aconan

![screenshot 2018-03-15 15 12 41](https://user-images.githubusercontent.com/471109/37472182-5cee496e-2863-11e8-954a-13ff30f8cdd6.png)
