### ISSUE TITLE
[boost] Should other boost defines be handled via options?

### ISSUE THREAD

**Issue by SSE4** [conan-community/community#90]
_From @KalleDK on January 22, 2018 15:41_

The three I know of (and use)

I think this only is needed in cpp_info and might not change how boost itself is compiled.
BOOST_ERROR_CODE_HEADER_ONLY (Is needed if system is not available)

I think these actually changes how the build ends up, and should also be in cpp_info
BOOST_SYSTEM_NO_DEPRECATED (Error if deprecated calls are used)
BOOST_ASIO_NO_DEPRECATED (Error if deprecated calls are used)

_Copied from original issue: conan-community/conan-boost#73_

**Comment by SSE4** [comment]
_From @simon-bourne on March 16, 2018 7:52_

There's also `BOOST_USE_VALGRIND` and `BOOST_USE_ASAN` in Boost Context. I don't know of any way to get a definitive list though.

**Comment by SSE4** [comment]
_From @trivigy on May 15, 2018 21:27_

Is there a work around of how to set these for now?
I need to build boost with BOOST_ASIO_NO_DEPRECATED because it actually changes how the functionality works to make boost asio rely only on new classes rather than older ones. mutable_buffer vs mutable_buffers_1

**Comment by SSE4** [comment]
_From @lasote on May 23, 2018 7:39_

I think some of them if they affect how is boost built, should be modeled as options in the recipe. I think there is no possible workaround but introduce the options. I would try to do it in the following days. Please write again if no news in a couple of days. Thanks

**Comment by SSE4** [comment]
let's limit the scope for the following definitions for now:
- BOOST_ERROR_CODE_HEADER_ONLY 
- BOOST_SYSTEM_NO_DEPRECATED 
- BOOST_ASIO_NO_DEPRECATED 
I am going to add options for them
for other definitions, please open new issue(s)

**Comment by SSE4** [comment]
@KalleDK I've applied required changes, please give a try: https://github.com/conan-community/conan-boost/commit/a5f953d572216109e9a30dbda035e7e146619e8b

**Comment by firewave** [comment]
There's also `BOOST_FILESYSTEM_NO_DEPRECATED`.

**Comment by SSE4** [comment]
@firewave okay, I'll add this one as well

**Comment by SSE4** [comment]
https://github.com/conan-community/conan-boost/commit/856523d409cfd1bef338f7d1045693c8f5e21fd2

**Comment by SSE4** [comment]
I am closing this one as all requested defines were added as options. for other defines please open new issue(s).
