### ISSUE TITLE
gcc armv7hf builds for bzip2

### ISSUE THREAD

**Issue by mbeach** [conan-community/community#96]
### Description of Problem, Request, or Question

Hi, I'd like to contribute some armv7hf with gcc builds for conan-bzip2. Please see conan-community/conan-bzip2#23.

**Comment by danimtb** [comment]
As explained in https://github.com/conan-community/conan-zlib/pull/55 we are not adding binaries for ARM archs to our current CI matrix. However, PRs for cross-building support or support fo other architectures in the recipe will be always welcome.

Thanks!
